### ISSUE TITLE
Exceptionless locally installed is not logging any exception

### ISSUE THREAD

**Issue by fduverger** [exceptionless/Exceptionless#100]
Hi,
Great tool! It is very handy. I have Exceptionless up and running locally as a special requirement from my company. 
The problem is that doesn't seam to be logging Exceptions. I am using the generated key for the project but no luck.
I created a trial account on https://exceptionless.com/, follow the same steps and worked perfectly. What Am I missing?
Regards

**Comment by niemyjski** [comment]
Are you setting the ServerUrl and enableSSL to false as shown here: http://docs.exceptionless.com/contents/configuration/ ?

```
Self hosted options

The Exceptionless client can also be configured to send data to your self hosted instance. This is configured by setting the serverUrl setting to point to your Exceptionless instance. Please note that if you do not have SSL configured you must set the enableSSL setting to false.
```

**Comment by fduverger** [comment]
Yes. Here is my config:
<exceptionless apiKey="Bx7JgglstPG544R34Tw9T7RlCed3OIwtYXVeyhT2" serverUrl="http://localhost:50000" enableSSL="false"  />
 ...
  <appSettings>
   ...
    <add key="EnableSSL" value="false" />
...
<appSettings>

**Comment by niemyjski** [comment]
Can you access http://localhost:50000/api/v2/status ? What does it say? Have you tried to enable logging: http://docs.exceptionless.com/contents/troubleshooting/ ?

**Comment by fduverger** [comment]
It says:
{
  "message": "All Systems Check",
  "version": "2.0.0"
}

**Comment by niemyjski** [comment]
Can you try troubleshooting the client and see what the logs say.

**Comment by fduverger** [comment]
Update your client: I just added Exceptionless.Web from nuget.
Ensure that the queue has time to process: Do not apply (I think)
How to locate the default isolated storage queue folder:
I located the following path 'C:\ProgramData\IsolatedStorage\. This is exceptionless.log file content:
ExceptionlessClient: Processing queue...
QueueManager: Cleaning up files older than: 4/13/2015 9:03:28 PM
QueueManager: Getting Manifests
exceptionless.com
ExceptionlessClient: Client startup.
ExceptionlessClient: Triggering configuration update and queue processing...
ExceptionlessClient: Done triggering configuration update and queue processing.
LocalConfigurationDictionary: Saving local configuration.
LocalConfigurationDictionary: Done saving local configuration.
ExceptionlessClient: Startup done.
ExceptionlessClient: Updating configuration settings.
LocalConfigurationDictionary: Saving local configuration.
LocalConfigurationDictionary: Done saving local configuration.
ExceptionlessClient: Updated configuration to version 4.
ExceptionlessClient: Processing queue...
QueueManager: Cleaning up files older than: 4/13/2015 9:00:59 PM
QueueManager: Getting Manifests
Firewall / Proxy: Do not apply
Enable client logging: Done. Do not create the file in the given path

**Comment by niemyjski** [comment]
What happens if you call ExceptionlessClient.Default.SubmitLog("test"); does this show up in your dashboard. It appears everything is running but I don't see anywhere it's catching an exception.

**Comment by fduverger** [comment]
No, it doesn't.

**Comment by niemyjski** [comment]
Could you please join our chat room so we can talk about this some more: https://gitter.im/exceptionless/Discuss

**Comment by fduverger** [comment]
I am on meeting right now. Give me half an hour please

**Comment by niemyjski** [comment]
I might be a round, I need to eat and head to the gym (it's 5:14 currently). If you could join that room, I'll message you when I'm back. Or we could always meet up there tomorrow as well.

**Comment by fduverger** [comment]
Ok. I will let you know when I finish. Either way sounds good to me.
Thanks

**Comment by niemyjski** [comment]
I'm on the chat now and will be for the rest of the day. If I don't respond right away give me a few as I might be on a break / coding

**Comment by fduverger** [comment]
Whenever you are ready!

On Wed, Apr 29, 2015 at 8:21 AM, Blake Niemyjski <notifications@github.com>
wrote:

> I'm on the chat now and will be for the rest of the day. If I don't
> respond right away give me a few as I might be on a break / coding
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exceptionless/Exceptionless/issues/100#issuecomment-97406650>
> .
>



-- 
****************************************************
**      Ing. Frank Gonzalez Duverger  **
**                                                           **
****************************************************

**Comment by niemyjski** [comment]
This was caused by two things (for others reading).

* The projects configuration section didn't set the `serverUrl="http://localhost:50000" enableSSL="false"`
* Dynamic scripting wasn't enabled in the [elasticsearch.yml](https://github.com/exceptionless/Exceptionless/blob/master/Libraries/elasticsearch.yml#L12) file. I've updated the readme to mention this.
