### ISSUE TITLE
I use the lastest image at hub.docker.com  but doesn't work 

### ISSUE THREAD

**Issue by DUWENINK** [exceptionless/Exceptionless#1005]
`https://hub.docker.com/layers/exceptionless/exceptionless/7.2.0/images/sha256-5c72e3686d26ee57c4ba78a5b5de3129368ba920de838b3a55e723efba5452bb?context=explore`
 i use the command ` docker run -d  --restart=always  --name=exceptionless   -it -p 5005:80 exceptionless/exceptionless:7.2.0` to deploy  but the logs shows  `  ==> /var/log/supervisor/exceptionless.log <==
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0-rc.2.21480.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=centos.8-x64

==> /var/log/supervisor/elasticsearch.log <== 
`
and the webuis shows 
![image](https://user-images.githubusercontent.com/16337239/141715776-91ae721f-4a9c-40b3-be54-fee2d853501b.png)

**Comment by ejsmith** [comment]
Sorry about that. I just pushed 7.2.1 and this issue should be resolved now.
