### ISSUE TITLE
Swagger docs url input doesn't update properly

### ISSUE THREAD

**Issue by fduverger** [exceptionless/Exceptionless#101]
When a new virtual directory on IIS is created (like http://localhost/exceptionless) the url input on the api documentation page does not update properly. It should show this http://localhost/exceptionless/docs/index but instead is showing this http://localhost:80/docs/index.

**Comment by niemyjski** [comment]
This doesn't work due to a possible bug in swagger. You can see in our configuration that we are not specifying the root url: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/AppBuilder.cs#L148 But swagger is trying to load it from the root.

**Comment by niemyjski** [comment]
I'm waiting on a reply from the swashbuckle issue I created. I believe this could be a bug with the library we use.

**Comment by fduverger** [comment]
Ok

**Comment by niemyjski** [comment]
@fduverger, I'm still waiting on a fix for this issue: https://github.com/domaindrivendev/Swashbuckle/issues/305

**Comment by niemyjski** [comment]
Still waiting on a fix :(

**Comment by niemyjski** [comment]
I'm going to close this as a known issue. I've sent out another update on that swashbuckle issue and will update to it when a fix is available.

**Comment by vikpai** [comment]
did we ever find a resolution for this? I was using the swagger nuget package and when we deploy this to our dev boxes, it misses the VD and fails.

**Comment by niemyjski** [comment]
@vikpai , they still haven't fixed it in swashbuckle. https://github.com/domaindrivendev/Swashbuckle/issues/305

**Comment by vikpai** [comment]
Thanks! @niemyjski

**Comment by vikpai** [comment]
are there any workarounds?

**Comment by niemyjski** [comment]
You could try the one they posted in the issue. I don't want to apply it as it's pretty specific to owin.
