### ISSUE TITLE
Why are logs lost

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#1017]
On the UI, you can see that the log is written in, and then after a while, the log suddenly retreats and disappears. It is accidental, but the event counter is still accumulated

**Comment by ysq5202121** [comment]
Very strange

**Comment by niemyjski** [comment]
Do you have a retention policy? Are the events still in Elasticsearch? I'd start by checking the Elasticsearch and cleanup logs.

**Comment by niemyjski** [comment]
I'm closing this until more information is available.
