### ISSUE TITLE
Create a plugin that retrieve the versions of the .NET Framework installed

### ISSUE THREAD

**Issue by matteomigliore** [exceptionless/Exceptionless#102]
Especially for Windows package should be useful to have more details of the .NET Framework versions installed.

In our case know if the 4.6 is installed is important because is an in-place-update of the previous versions and the RC has an issue with WCF proxy creation.

**Comment by niemyjski** [comment]
I don't see us adding a plugin for this as the EnvironmentInfo already contains the runtime version: https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Extras/Services/EnvironmentInfoCollector.cs#L112 . Also adding a change like this to look at registry... wouldn't run cross platform.

You could always create a plugin that adds this info to EnvironmentInfo's extended data. You can get a list of installed versions by doing something like this: https://msdn.microsoft.com/en-us/library/hh925568%28v=vs.110%29.aspx
