### ISSUE TITLE
UI unauthorised error reaching API under IIS8 due to CORS

### ISSUE THREAD

**Issue by greg-williams-tcg** [exceptionless/Exceptionless#103]
IIS8 and ASP.NET will deny cross-origin-resource-sharing if WebDav is enabled as it does not know how to handle 'OPTIONS' HTTP action.

The distributed web.config contains sections to remove WebDav and the handler mappings for IIS7.5, but for IIS8, the verb was changed to simply 'OPTIONS'.

The following configuration now works for me (YMMV) under system.webserver:

```XML
<httpProtocol>
      <customHeaders>
       <remove name="Server" />
        <remove name="X-Powered-By" />
        <remove name="X-AspNet-Version" />        
        <remove name="Access-Control-Allow-Headers"/>
		
        <add    name="Access-Control-Allow-Headers" value="Origin, X-Requested-With, Content-Type, Accept" />
		<add 	name="Access-Control-Expose-Headers" value="ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-Exceptionless-Client" />
        <remove name="Access-Control-Allow-Origin"/>
                
      </customHeaders>
    </httpProtocol>
    <handlers>
      <remove name="OPTIONS"/>
      <remove name="WebDAV" />
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />      
      
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
```

**Comment by niemyjski** [comment]
So you were seeing issues with the Isapi extensionless url handlers? Is there any chance you can use our default config and narrow down one by one which makes it work and which one breaks it..

We were already specifying the Options handler.. but you say this has been renamed to just options??

```
<remove name="OPTIONSVerbHandler" />
```

Why did you need to remove the access control * headers? I'm not feeling comfortable making those changes like that as we already have cors working.

Do I just need to install the web dav module on iis8 to reproduce?

**Comment by niemyjski** [comment]
Were you able to narrow down the list of specific changes required for this?

**Comment by greg-williams-tcg** [comment]
Hi, yes, and there were few things going on so I've stripped it back again and only the following was required (phew):
```
<remove name="OPTIONS"/>
```
see: [http://thoughtfulpractices.blogspot.com.au/2013/12/enabling-cross-origin-requests-cors-in.html]

The rest of the handlers/access-control headers seem to be fine.

**Comment by Phyxion** [comment]
I can indeed confirm that adding the above line works.

**Comment by niemyjski** [comment]
@greg-williams-tcg @Phyxion  I've fixed this in the following commit: https://github.com/exceptionless/Exceptionless/commit/7bbd59773f7e17e9e846f54c1704bf2df578ad4e

**Comment by niemyjski** [comment]
We'll make sure this gets deployed a new release soon!
