### ISSUE TITLE
ES Error

### ISSUE THREAD

**Issue by NPUlrk** [exceptionless/Exceptionless#1049]
I use exceptionless with self-hosted docker image. Elasticsearch uses another SaaS service. I have set the correct link address in the environment variable EX_ConnectionStrings__Elasticsearch of Docker. However, after the system runs for a period of time, the latest event/log cannot be received. Check the Docker run logs. The following information is displayed:

> {"type": "server", "timestamp": "2022-03-02T09:02:02,771Z", "level": "ERROR", "component": "o.e.m.f.FsHealthService", "cluster.name": "docker-cluster", "node.name": "ex01-78bb46988f-lrgvx", "message": "health check of [/usr/share/elasticsearch/data/nodes/0] failed", "cluster.uuid": "Ew2TWic_Qn6UB1dmy-fIPQ", "node.id": "fkLt_wUWS5SF6dZmKSCNhg" ,
> "stacktrace": ["java.nio.file.FileSystemException: /usr/share/elasticsearch/data/nodes/0/.es_temp_file: No space left on device",
> "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]",
> "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]",
> "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
> "at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]",
> "at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]",
> "at java.nio.file.Files.newOutputStream(Files.java:224) ~[?:?]",
> "at org.elasticsearch.monitor.fs.FsHealthService$FsHealthMonitor.monitorFSHealth(FsHealthService.java:171) [elasticsearch-7.10.0.jar:7.10.0]",
> "at org.elasticsearch.monitor.fs.FsHealthService$FsHealthMonitor.run(FsHealthService.java:146) [elasticsearch-7.10.0.jar:7.10.0]",
> "at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:213) [elasticsearch-7.10.0.jar:7.10.0]",
> "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.10.0.jar:7.10.0]",
> "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.10.0.jar:7.10.0]",
> "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
> "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
> "at java.lang.Thread.run(Thread.java:832) [?:?]"] }

The ES version in the log is 7.10.0, which is not the version used by the ES server: 8.9.0. This exception may occurs because the storage space of the ES in the container is insufficient. I doubt that even if I set the external Elasticsearch, the container will still start an ES instance. How do I disable the internal ES instance? Or how to fix the above error?

Thank you.

Environment Info:
Exceptionless version:7.0.9
Docker Environment:
![image](https://user-images.githubusercontent.com/21106497/156333970-94de6233-6428-4ddd-91b9-06e8689ec2b3.png)

**Comment by niemyjski** [comment]
What image are you using? I personally wouldn't use the `exceptionless` image in this case because you are using elasticsearch service externally and that would remove Elasticsearch from running inside your container completely. The health check will fail if Elasticsearch doesn't respond to a ping. @ejsmith could we make it so if the connection string env is set and doesn't contain localhost we don't start up elastic?

**Comment by NPUlrk** [comment]
> What image are you using? I personally wouldn't use the `exceptionless` image in this case because you are using elasticsearch service externally and that would remove Elasticsearch from running inside your container completely. The health check will fail if Elasticsearch doesn't respond to a ping. @ejsmith could we make it so if the connection string env is set and doesn't contain localhost we don't start up elastic?

I use docker image exceptionless:7.0.9, which include exceptionless(7.0.9), Web(3.0.9), and Elasticsearch(7.10.0).

**Comment by niemyjski** [comment]
I'd recommend changing your base image so you aren't running elasticsearch or giving it just enough space so you don't have this error. If you'd like to submit a pr that fixes this behavior as described in my previous reply that would be greatly appreciated.

**Comment by NPUlrk** [comment]
> 

Thanks for your reply, it seems that the problem can be solved by providing more storage space.
I have tried what you said by judging whether there is ES connection string environment variable settings and then no longer starting ES. As far as I know it doesn't seem possible, because the configuration of ES is in the container construction stage(docker image build), and the setting of environment variables is in the container startup. take effect after that.
