### ISSUE TITLE
Zapier retrieving Tasks from multiple Exceptionless Projects when only one Exceptionless Project had an error

### ISSUE THREAD

**Issue by SyraChad** [exceptionless/Exceptionless#105]

**Comment by niemyjski** [comment]
I found the root cause of this issue and am talking with the team on a fix.. This issue is caused by the fact that when a webhook is created the organization and project ids are set.. then in our pipeline was are getting all of the hooks by an organization or project id. Which there is multiple.

**Comment by niemyjski** [comment]
@ejsmith Could you please review my changes.

**Comment by niemyjski** [comment]
@SyraChad, This fix has been deployed into production.
