### ISSUE TITLE
Clicking cancel on upgrade plan does not make it go away

### ISSUE THREAD

**Issue by ocbaker** [exceptionless/Exceptionless#106]
When trying to add a new organisation while on a free plan causes the message to upgrade popup. However the only way you can cancel that dialog is to click upgrade and then click close.

![Gif of the issue](http://vgy.me/eTxj25.gif)

**Comment by niemyjski** [comment]
Thanks for reporting this behavior. I'll take a look into this and try to reproduce.

**Comment by niemyjski** [comment]
This has been fixed in the following commit: https://github.com/exceptionless/Exceptionless.UI/commit/a44afc64ad41a0d4e419a055c797484172134d1e and will be deployed soon.
