### ISSUE TITLE
Extended Data is missing information

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#108]
I'm not sure if this is related to the UI or to this, so I'm just putting it here.
When you add a boolean (either through .AddObject or through .DefaultData) that is ``false``, it is not listed in the Extended Data tab in the interface.

``ExceptionlessClient.Default.Configuration.DefaultData.Add("This is not listed", false);``

**Comment by niemyjski** [comment]
@Phyxion Is this included in the event but just not shown in the ui. You can confirm this via the api / network tab.

**Comment by Phyxion** [comment]
It should be sent (I can see it in Event.Data).

**Comment by niemyjski** [comment]
I've been able to reproduce and am taking a look into it.

**Comment by Phyxion** [comment]
Great, thanks :+1:

**Comment by niemyjski** [comment]
I've fixed this issue and we will get this deployed soon.

**Comment by Phyxion** [comment]
Sounds great, looking forward to that.
