### ISSUE TITLE
How can I change the error eMail template?

### ISSUE THREAD

**Issue by strombringer** [exceptionless/Exceptionless#109]
Is there an option to change the eMail template?

I'd like to include a few more fields in the error mails, e.g. Version and Tags, to make it easier to scan mails and decide whether to take action immediately or later

**Comment by niemyjski** [comment]
Yes, this can be done by editing the [templates](https://github.com/exceptionless/Exceptionless/tree/master/Source/Core/Mail/Templates). We'd be more than happy to accept a pull request for this.

**Comment by strombringer** [comment]
Perfect. I'll take a look at them.

**Comment by niemyjski** [comment]
Were you able to modify the templates?

**Comment by strombringer** [comment]
Not yet, because I had to do stuff that had higher priority :-/

**Comment by niemyjski** [comment]
@strombringer I'm going to close this issue. Please feel free to do a pull request for any updates or let us know if you have any questions.
