### ISSUE TITLE
Frontend not rendering / blank page after logging in

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#1092]
Hello,
I'm seeing an issue after logging into Exceptionless where a blank page appears and the application is not usable. The API/backend is reachable.

If signed out, the login page shows up but I notice "NOTICE_SIGNINGUP" placeholder text in the footer, like it somehow did not get rendered.

![image](https://user-images.githubusercontent.com/11253613/167503141-01540a27-e793-41d4-8ddd-0f37a82c4c72.png)

After logging in, there is only a blank page.

Unsure if related but accessing the Swagger documentation at `/docs/index.html` shows that the swagger.json file can't be found.

![image](https://user-images.githubusercontent.com/11253613/167503753-97ba6de5-5a49-4323-9072-65c94ae192a7.png)

Any idea on what could be happening? I turned on verbose logging but I'm not seeing any logs that stand out for this issue.

**Comment by niemyjski** [comment]
What version are you using? What docker image/tag are you using? What are the network errors you are seeing in the browser console when viewing swagger and the site?

**Comment by Edreih** [comment]
My issue was resolved after I moved the application (self-hosted) to a different web server. The angular/UI is now rendering properly. I haven't found a root cause as of yet. 

Thank you.
