### ISSUE TITLE
blank page，Unable to open any pages

### ISSUE THREAD

**Issue by 18682788952** [exceptionless/Exceptionless#1104]
![image](https://user-images.githubusercontent.com/31786261/172280077-569b7b3f-6735-41b7-895a-05306c9768b7.png)

![image](https://user-images.githubusercontent.com/31786261/172280326-a7ae3be1-45b8-43f5-8c1f-fa7bce587c21.png)

docker run -p 5000:80 --restart always --name exceptionless -v /work/exceptionless/elasticsearch:/usr/share/elasticsearch/data exceptionless/exceptionless:latest

**Comment by niemyjski** [comment]
This is a duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/195 Please see the comments for more information.
