### ISSUE TITLE
Found a problem

### ISSUE THREAD

**Issue by CaiNiaoM** [exceptionless/Exceptionless#1123]
Why can't I write in today's log for the new project created yesterday? Today, I create a new project. Setting a new apikey can be written into the new project again

**Comment by niemyjski** [comment]
Hello,

I'm not sure with the limited amount of context submitted with this issue. I'd recommend following the troubleshooting guide here: https://exceptionless.com/docs/clients/javascript/troubleshooting/. I'd try submitting an event and then looking at the server and client logs.

**Comment by CaiNiaoM** [comment]
I don't think it's caused by the number of submissions. It's because I set up a service in docker yesterday, and then created a new log project. I tested it on the same day, and it can be recorded in the log. The next day, when I re wrote the log, I found that it was not written in, and then I created a new apikey for the project, so I can write the log in,

**Comment by niemyjski** [comment]
I'd recommend running through the troubleshooting guides for self-hosting as well as the client troubleshooting. We can't really help with very limited context or information to go off of.
