### ISSUE TITLE
如何连接开启了xpack的ES8.3.1

### ISSUE THREAD

**Issue by Hirsinkai** [exceptionless/Exceptionless#1139]
ES
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate

Exceptionless
      #如何使用账号密码连接？
      EX_ConnectionStrings__Elasticsearch: server= https://elasticsearch:9200

**Comment by niemyjski** [comment]
Hello, I'm not sure what you're asking. Configuring elasticsearch is outside of the scope of this project. If you need to add additional client options we would be open to a pr.
