### ISSUE TITLE
User Access

### ISSUE THREAD

**Issue by meharhay** [exceptionless/Exceptionless#117]
It would be great to restrict access to specific projects by user in an organization.  We have different teams and the global access to all projects is not ideal for security reasons.

**Comment by niemyjski** [comment]
Do you see users implemented at a organization scope and at a project level?

**Comment by meharhay** [comment]
I'd see it that you would have users at the organization scope to then select which projects in that organization the user has access to.

**Comment by niemyjski** [comment]
Do you want me to reopen this? Yeah, we would need something at the org and project level

**Comment by meharhay** [comment]
Sorry, hit the wrong button "Close and Comment" instead of just Comment.  I reopened. Thanks!

**Comment by niemyjski** [comment]
I'm closing as a duplicate to this: https://github.com/exceptionless/Exceptionless/issues/152
