### ISSUE TITLE
Server Stopps Accepting request after some time.

### ISSUE THREAD

**Issue by Crushedice** [exceptionless/Exceptionless#1183]
Greetings, 
My current Setup for Exceptionless is a Self-hosted Docker instance on a Vpn, 
together with a cloud flare Tunnel to use a Domain name owned by me.

After the initial setup for a Winforms client, it works all as intended,
Error reporting, additional data, even sessions.

But after a while, the server stops accepting requests altogether, 
when i inspected the requests with "Fiddler", I get "HTTP/1.1 401 Unauthorized" responses.
The requests from the client are the same, the whole time. 
I also tried both; using the Domain name , aswell as the IP+port.  Same result.

Some help would be appreciated .

**Comment by Crushedice** [comment]
Ok, I think I found a hint.
I tried a bunch of things, even the Api tests at "../docs/index.html",
of which ONLY one thing worked at all:
Creating a new api key,  so I already thought it probably has something todo with a rate limit.

And actually I saw this, showing up in the response headers , after creating a new key:

`HTTP/1.1 202 Accepted
Content-Length: 0
Connection: close
Date: Wed, 26 Oct 2022 21:11:56 GMT
Content-Security-Policy: default-src 'self' https://js.stripe.com http://js.stripe.com;script-src 'self' https://js.stripe.com http://js.stripe.com https://cdn.jsdelivr.net http://cdn.jsdelivr.net 'unsafe-eval' 'unsafe-inline';style-src 'self' https://fonts.googleapis.com http://fonts.googleapis.com https://cdn.jsdelivr.net http://cdn.jsdelivr.net 'unsafe-inline';font-src 'self' https://fonts.gstatic.com http://fonts.gstatic.com https://cdn.jsdelivr.net http://cdn.jsdelivr.net;img-src 'self' data: https://q.stripe.com http://q.stripe.com https://www.gravatar.com http://www.gravatar.com
Strict-Transport-Security: max-age=31536000; includeSubDomains
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Exceptionless-ConfigVersion: 4
X-RateLimit-Limit: 3500
X-RateLimit-Remaining: 3498
`

The X-RateLimit ,  did not show up on other - unauthorized 401 - attempts.

is this actually a Api-Key Rate limit? 
and if, how to disable it "easily" ...
I'm not too keen on the whole docker thing, for me its kind of unreasonably complicated.
Even though I'm a C# Developer, never used docker that much at all.

**Comment by niemyjski** [comment]
The Api Throttle limit is set to 3500 by default and if you are over the limit the Status429TooManyRequests status code will be returned. If you want to change the value, you need to set an env variable like `-e EX_ApiThrottleLimit=-1`

```cs
options.ApiThrottleLimit = config.GetValue(nameof(options.ApiThrottleLimit), options.AppMode == AppMode.Development ? Int32.MaxValue : 3500).NormalizeValue();
```

I don't think this explains the 401.

**Comment by Crushedice** [comment]
Something  that got my attention was this : 
`namespace Exceptionless.Web.Controllers;

[Produces("application/json")]
[ApiController]
public abstract class ExceptionlessApiController : Controller {
    public const string API_PREFIX = "api/v2";
    protected const int DEFAULT_LIMIT = 10;
    protected const int MAXIMUM_LIMIT = 100;
    protected const int MAXIMUM_SKIP = 1000;`

specially because, i got 3 api keys out for my users, and got ~300 reports, 
each, stopped working at around 100. 
What exactly does this max limit / how could i set the limit to a different value?

**Comment by ejsmith** [comment]
That is for paging data returned from the UI.

Can you check to see if your API keys have been disabled?

**Comment by Crushedice** [comment]
as far as i can see, they are not 
[ScreenShot](https://xbb.dmt.ovh/bOWA5/yoTinOrA59.png)

**Comment by niemyjski** [comment]
We will add a new status to the ui to show if it's suspended.

**Comment by Crushedice** [comment]
After some bit of trying around with the API calls,
i finally got some useful response that shows at least what's wrong now.
```

[
  {
    "id": "-----------------------------------------------",
    "organization_id": "635c256d8c84b3001861afbb",
    "project_id": "635c256d8c84b3001861afbc",
    "scopes": [
      "client"
    ],
    "is_disabled": false,
    "is_suspended": true,
    "created_utc": "2022-10-28T18:54:38.0639116Z",
    "updated_utc": "2022-10-28T18:54:38.0643681Z"
  },
  {
    "id": "-------------------------------------------",
    "organization_id": "635c256d8c84b3001861afbb",
    "project_id": "635c256d8c84b3001861afbc",
    "scopes": [
      "client"
    ],
    "is_disabled": false,
    "is_suspended": true,
    "created_utc": "2022-10-28T19:06:29.375407Z",
    "updated_utc": "2022-10-28T19:06:29.3754546Z"
  }
]
```

So, ya.  They seem to be suspended... 
Any way to revert them, and prevent this from happening?

**Comment by ejsmith** [comment]
Hmm... shouldn't be happening on self hosted installs. Can you check the org api call to see if it's suspended as well?

**Comment by niemyjski** [comment]
We're going to make changes to make this more visible in the UI. @ejsmith Perhaps we should log a reason on the org with why it's suspended.

**Comment by Crushedice** [comment]
I've reinstalled my vps, as I was running into some Issues, unrelated to this.
nothing much has improved, however I've managed to setup a separate elasticsearch container that is being used now.

> ( Just for FYI, it didn't work at all at first. The solution was  setting EX_ConnectionStrings__Elasticsearch to the actual IP of the server, not localhost:port ) 

But now i am kind of stuck, as of now i only get 401 or 403 responses, with fiddler or with the swaggerUI; on both: the IP:port and the tunneling domain name ...

maybe there is something wrong with my setup; as i almost never use docker really,
here's the container info;
[Exceptionless Container](https://pastebin.com/gBVHRmge)
[Elasticsearch Container](https://pastebin.com/CJ8GJDZV)

**Comment by Crushedice** [comment]
Something is definitly wierd... 

I tested out more things now, tried to switch the transport protocol of the tunnel from quic to http2 , didnt help.

but i also created 3 more api keys,
one- from the dashboard, created normally, it was suspended after working for an hour or so
one created with the API, 
and another one with the dashboard, which i disabled immediatly. 
and ALL 3 are suspended, even though i did not use the api-created one,
and even Disabled the other one beforehand.... 
it seems it has nothing even todo with any usage limits... which... really throws me off...
```

[
  {
    "id": "----------------------------------",
    "organization_id": "635c256d8c84b3001861afbb",
    "project_id": "635c256d8c84b3001861afbc",
    "scopes": [
      "client"
    ],
    "notes": "FallbackToken",
    "is_disabled": false,
    "is_suspended": true,
    "created_utc": "2022-10-28T18:54:38.0639116Z",
    "updated_utc": "2022-10-29T18:58:35.603809Z"
  },
  {
    "id": "-----------------------------------",
    "organization_id": "635c256d8c84b3001861afbb",
    "project_id": "635c256d8c84b3001861afbc",
    "scopes": [
      "user",
      "client"
    ],
    "notes": "ApiCreatedToken",
    "is_disabled": false,
    "is_suspended": true,
    "created_utc": "2022-10-29T18:57:34.3894015Z",
    "updated_utc": "2022-10-29T18:57:34.3904637Z"
  },
  {
    "id": "------------------------------------",
    "organization_id": "635c256d8c84b3001861afbb",
    "project_id": "635c256d8c84b3001861afbc",
    "scopes": [
      "client"
    ],
    "is_disabled": true,
    "is_suspended": true,
    "created_utc": "2022-10-29T18:58:57.3794739Z",
    "updated_utc": "2022-10-29T18:59:02.5639165Z"
  },
  {
    "id": "-------------------------------------------",
    "organization_id": "635c256d8c84b3001861afbb",
    "project_id": "635c256d8c84b3001861afbc",
    "scopes": [
      "client"
    ],
    "notes": "ApiTest",
    "is_disabled": false,
    "is_suspended": true,
    "created_utc": "2022-10-29T18:58:48.8288253Z",
    "updated_utc": "2022-10-29T18:59:24.8721593Z"
  }
]
```

**Comment by ejsmith** [comment]
Yeah, there has got to be some bug with code that we added for suspending tokens recently. I am going to dig into it today. Can you check to see if the org also got suspended or only the token?

**Comment by Crushedice** [comment]
Nope. the organization has not been suspended.
Here the Elasticsearch info for the org
```
{
	"_index": "prod-organizations-v2",
	"_id": "635c256d8c84b3001861afbb",
	"_version": 32,
	"_seq_no": 31,
	"_primary_term": 5,
	"found": true,
	"_source": {
		"id": "635c256d8c84b3001861afbb",
		"name": "Rusticaland",
		"plan_id": "EX_UNLIMITED",
		"plan_name": "Unlimited",
		"plan_description": "Unlimited",
		"billing_change_date": "2022-10-28T18:54:37.6901438",
		"billing_changed_by_user_id": "635c25618c84b3001861afba",
		"billing_status": 0,
		"billing_price": 0,
		"max_events_per_month": -1,
		"bonus_events_per_month": 0,
		"retention_days": 180,
		"is_suspended": false,
		"has_premium_features": true,
		"max_users": -1,
		"max_projects": -1,
		"usage_hours": [
			{
				"date": "2022-10-28T19:00:00",
				"total": 17,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-28T20:00:00",
				"total": 25,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T12:00:00",
				"total": 11,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T19:00:00",
				"total": 89,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T20:00:00",
				"total": 34,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T22:00:00",
				"total": 14,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			}
		],
		"usage": [
			{
				"date": "2022-10-01T00:00:00",
				"limit": -1,
				"total": 190,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			}
		],
		"last_event_date_utc": "2022-10-29T22:20:13.4767519Z",
		"created_utc": "2022-10-28T18:54:37.6926766",
		"updated_utc": "2022-10-29T22:20:13.4771537Z",
		"is_deleted": false
	}
}
```

and the project 

```
{
	"_index": "prod-projects-v2",
	"_id": "635c256d8c84b3001861afbc",
	"_version": 36,
	"_seq_no": 35,
	"_primary_term": 5,
	"found": true,
	"_source": {
		"id": "635c256d8c84b3001861afbc",
		"organization_id": "635c256d8c84b3001861afbb",
		"name": "Launcher",
		"is_configured": true,
		"configuration": {
			"version": 2,
			"settings": {
				"@@UserAgentBotPatterns": "*bot*,*crawler*,*spider*,*aolbuild*,*teoma*,*yahoo*",
				"@@log:*": "trace"
			}
		},
		"notification_settings": {
			"635c25618c84b3001861afba": {
				"send_daily_summary": true,
				"report_new_errors": true,
				"report_critical_errors": true,
				"report_event_regressions": true,
				"report_new_events": false,
				"report_critical_events": false
			}
		},
		"usage_hours": [
			{
				"date": "2022-10-28T19:00:00",
				"total": 17,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-28T20:00:00",
				"total": 25,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T12:00:00",
				"total": 11,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T19:00:00",
				"total": 89,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T20:00:00",
				"total": 34,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			},
			{
				"date": "2022-10-29T22:00:00",
				"total": 14,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			}
		],
		"usage": [
			{
				"date": "2022-10-01T00:00:00",
				"limit": -1,
				"total": 190,
				"blocked": 0,
				"discarded": 0,
				"too_big": 0
			}
		],
		"last_event_date_utc": "2022-10-29T22:20:13.4919481Z",
		"delete_bot_data_enabled": false,
		"next_summary_end_of_day_ticks": 638026884000000000,
		"created_utc": "2022-10-28T18:54:37.9628123",
		"updated_utc": "2022-10-29T22:20:13.4923334Z",
		"is_deleted": false
	}
}
```

in my user data is the field:
```
"roles": [
			"client",
			"user",
			"global"
		],
```

Isn't "Admin" missing there, or am i wrong?

**Comment by ejsmith** [comment]
Thank you for the info! Global is the admin role.

**Comment by Crushedice** [comment]
Oh i see, then just FYI , if "Global" is the admin role, the token creation api tells you something different;

> This is a helper action that makes it easier to create a token for a specific project. You may also specify a scope when creating a token. There are three valid scopes: client, user and admin.

Another thing, from the suspension of the tokens, even the unused ones, one can assume that its tied to some 
timer for cleanup, or some other actions, but I only found 2 instances where the exceptionless code modifies the tokens to "Is_suspended" . But as my organization is not suspended, it shouldn't be happening.

I looked into the elastic database, and got a question ;
is it normal that "organizations" and "Projects" are labeled with "V2"  where, the other ones are V1 ? 
-> [Screenshot of Database](https://xbb.dmt.ovh/bOWA5/zeVOmObO40.png)

Also, a bit of a silly question: can't I "just" modify the entries in the database, and lock them to not get modified?
Specifically the "is_suspended" field

**Comment by Crushedice** [comment]
Ok, I just now deployed the container with the app modus "Development" to get a usefull log. 

And i think this one narrows it down pretty much : 

> {"log":"[20:30:00 INF] Found 0 suspended orgs","stream":"stdout","time":"2022-10-30T20:30:00.113443623Z"}
> .....................
> .......................
> {"log":"[20:30:00 INF] Marking 7 tokens as suspended","stream":"stdout","time":"2022-10-30T20:30:00.236620284Z"}

should be this method: 
```
 private async Task MarkTokensSuspended(JobContext context) {
        var suspendedOrgs = await _organizationRepository.FindAsync(q => q.FieldEquals(o => o.IsSuspended, true).OnlyIds(), o => o.SearchAfterPaging().PageLimit(1000));
        _logger.LogInformation("Found {SuspendedOrgCount} suspended orgs", suspendedOrgs.Total);

        do {
            var updatedCount = await _tokenRepository.PatchAllAsync(q => q.Organization(suspendedOrgs.Hits.Select(o => o.Id)).FieldEquals(t => t.IsSuspended, false), new PartialPatch(new { is_suspended = true }));
            if (updatedCount > 0)
                _logger.LogInformation("Marking {SuspendedTokenCount} tokens as suspended", updatedCount);
        } while (!context.CancellationToken.IsCancellationRequested && await suspendedOrgs.NextPageAsync());
    }
```

**Comment by ejsmith** [comment]
Hmm. That's a huge help! I wonder if somehow the list of org ids being empty is causing all tokens to be returned??

**Comment by Crushedice** [comment]
I would have tried now, to create another org, suspend it, and see if a new api key gets suspended then.

But i don't think I can even make those changes with any API Call,
same with the Web UI.

For the Method-
I would "simply" put in a check for  suspendedOrgs.Count()<=0  
and if,  dont even look for tokens ?

**Comment by ejsmith** [comment]
Yeah, we can definitely add the count check. If you want, you can submit a PR since you found it. If  not, I'll get it updated and also go check the repository implementation to make sure it's handling that correctly.

**Comment by ejsmith** [comment]
This should be fixed in the lasted build. Thank you @Crushedice!
