### ISSUE TITLE
Exception while creating project or organization with the dot after the end

### ISSUE THREAD

**Issue by hmvs** [exceptionless/Exceptionless#119]
Preconditions: 
Go to 'Add project' page
Steps to reproduce: 
1. Type the project name slowly in 'Project Name' field
2. At the end of the name leave dot symbol
3. Browser will send OPTIONS request and server will return 404 response, and page will be redirected to the error page immediately

**Comment by niemyjski** [comment]
So I narrowed this down a bit more..

It appears that the server is never even hit and chrome / (and maybe firefox) never even send a request. It creates a preflight request for this but is rejected when the request ends in a period.

**Comment by hmvs** [comment]
I could be wrong, but i think chrome and firefox send it. It's just IIS server respond with 404. And as i can remember It could be fixed via web.config.

**Comment by niemyjski** [comment]
I think we may need to create a simple js sample of making a request and log a bug with chrome maybe. I don't see anyone else running into this but it's kind of crazy. I guess for now the work around would be to create it with a period and a second character and then after it's created try renaming it.

**Comment by niemyjski** [comment]
@hmvs could you look into it a bit more? I enabled EnableSystemDiagnosticsTracing and nothing was outputted (something should be written per request). I also didn't see anything in the `chrome://net-internals/#events` window.

**Comment by hmvs** [comment]
but response from the server is here:
Access-Control-Expose-Headers:ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-Exceptionless-Client, X-Exceptionless-ConfigVersion
Cache-Control:private
Content-Length:1918
Content-Type:text/html; charset=utf-8
Date:Mon, 13 Jul 2015 21:12:14 GMT
Server:Microsoft-IIS/8.0
Set-Cookie:ARRAffinity=....... ;Path=/;Domain=api.exceptionless.io
X-AspNet-Version:4.0.30319

**Comment by hmvs** [comment]
you can disable https and try to do a sniff some traffic. but i believe it's something with url parsing of IIS.

**Comment by hmvs** [comment]
Just try this link
https://api.exceptionless.io/api/v2/projects/check-name/Walle.
And this
https://api.exceptionless.io/api/v2/projects/check-name/Walle.D

**Comment by niemyjski** [comment]
Yeah, just weird that nothing is written out when doing request level tracing. Thanks for posting that, I didn't even think of checking the response headers. I'll look more into config changes that could affect this.

**Comment by niemyjski** [comment]
I found the solution however, I'm not sure we want to enable it...

The solution is to set [`RelaxedUrlToFileSystemMapping`](https://msdn.microsoft.com/en-us/library/system.web.configuration.httpruntimesection.relaxedurltofilesystemmapping.aspx) to `true` as stated [here](http://haacked.com/archive/2010/04/29/allowing-reserved-filenames-in-URLs.aspx/). However there are a few warnings that this can open up your attack surface (http://www.hanselman.com/blog/ExperimentsInWackinessAllowingPercentsAnglebracketsAndOtherNaughtyThingsInTheASPNETIISRequestURL.aspx and http://stackoverflow.com/questions/11642623/any-potential-security-risks-setting-with-turning-on-relaxedurltofilesystemmappi)

**Comment by niemyjski** [comment]
@ejsmith thoughts?

**Comment by ejsmith** [comment]
Seems like it could be a security issue and I'm really not sure why you would want a project name that ends with a period.

I think the real problem is us redirecting to the error page. We really need to fix that behaviour.

**Comment by niemyjski** [comment]
Yeah, we'll you might want `Company LLC.` which would fail. Yeah, I looked into that redirect behavior and it happens because the status is 0 and not 404 as reported in the chrome network tab.

**Comment by ejsmith** [comment]
I still say that you need to check the status before you redirect.

**Comment by niemyjski** [comment]
We do and in this case it's 0.

**Comment by niemyjski** [comment]
I think the solution is to move all of the routes that check names to move them to a query string... Then we don't have these issues...

**Comment by ejsmith** [comment]
No, that is not the core problem. What we are doing works fine and is the more RESTful approach. We have had an issue with getting thrown to the status page improperly for a long time now. I think we really need to be checking the status page for non-200 before redirecting to the status page.

**Comment by niemyjski** [comment]
We are checking the status code before redirecting.... Chrome returns status 0 even though the network window might say 404

**Comment by ejsmith** [comment]
No, the status page status code. Just because we get an error doesn't mean the site is down. We should only be sending them to the status page if the site is actually down.

**Comment by ejsmith** [comment]
How about you create an error page that says sorry an error has occurred and maybe even gives them a reference code from Exceptionless and a comment box.  That page can kick off a check on the API status asynchronously after the view is displayed and then if we think the site is down we can redirect them to the status page.

**Comment by niemyjski** [comment]
Yeah, that would work out pretty well.
