### ISSUE TITLE
Changing ownership of directory problem and framework missing

### ISSUE THREAD

**Issue by veraciousnottaken** [exceptionless/Exceptionless#1192]
I'm running defaults from docu:
`docker run --rm -it -p 5000:80 -p 5001:443 \
    -e EX_ConnectionStrings__Email=\
    -e ASPNETCORE_URLS="https://+;http://+" \
    -e ASPNETCORE_HTTPS_PORT=5001 \
    -e ASPNETCORE_Kestrel__Certificates__Default__Password="!password0" \
    -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx \
    -v ~/.aspnet/https:/https/ \
    -v /srv/exceptionless/esdata:/usr/share/elasticsearch/data \
    exceptionless/exceptionless:latest
`

And getting errors:

chown: changing ownership of '/usr/share/elasticsearch/data': Operation not permitted
Running Exceptionless Web
/app/wwwroot /app
Exceptionless UI Config
    .constant('BASE_URL', '' || window.location.origin)
    .constant('EXCEPTIONLESS_API_KEY', '')
    .constant('EXCEPTIONLESS_SERVER_URL', '')
    .constant('FACEBOOK_APPID', '')
    .constant('GITHUB_APPID', '')
    .constant('GOOGLE_APPID', '')
    .constant('INTERCOM_APPID', '')
    .constant('LIVE_APPID', '')
    .constant('SLACK_APPID', '')
    .constant('STRIPE_PUBLISHABLE_KEY', '')
    .constant('SYSTEM_NOTIFICATION_MESSAGE', '')
    .constant('USE_HTML5_MODE', true)
    .constant('USE_SSL', false)
    .constant('ENABLE_ACCOUNT_CREATION', true);
/app
==> /var/log/supervisor/elasticsearch.log <==

==> /var/log/supervisor/exceptionless.log <==
.NET location: /usr/share/elasticsearch/.dotnet/

The following frameworks were found:
  7.0.0-rc.2.22472.3 at [/usr/share/elasticsearch/.dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=ubuntu.20.04-x64
00You must install or update .NET to run this application.

App: /app/Exceptionless.Web.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: /usr/share/elasticsearch/.dotnet/

My environment:
`docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.157-1-pve
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 2GiB

**Comment by niemyjski** [comment]
Have you tried this https://stackoverflow.com/questions/67498836/docker-chown-changing-ownership-of-data-db-operation-not-permitted ?

**Comment by niemyjski** [comment]
Is there anything in the docker logs when the app runs or logs when you hit those ports?

**Comment by veraciousnottaken** [comment]
The same with simplest:
`docker run --user=root --rm -it -p 5000:80 exceptionless/exceptionless:latest`

Running continers
`docker ps`
CONTAINER ID   IMAGE                                PORTS                                                                                            
f23ea5fa0f24   exceptionless/exceptionless:latest   9200/tcp, 9300/tcp, 0.0.0.0:5000->80/tcp, :::5000->80/tcp                                        
757955301b81   mariadb:10.9                         3306/tcp                                                                                         
abd2f0f8e2db   portainer/portainer-ce:latest        0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp, 9000/tcp   

Docker logs
`docker logs brave_mcclintock`
Running Exceptionless Web
/app/wwwroot /app
Exceptionless UI Config

    .constant('BASE_URL', '' || window.location.origin)
    .constant('EXCEPTIONLESS_API_KEY', '')
    .constant('EXCEPTIONLESS_SERVER_URL', '')
    .constant('FACEBOOK_APPID', '')
    .constant('GITHUB_APPID', '')
    .constant('GOOGLE_APPID', '')
    .constant('INTERCOM_APPID', '')
    .constant('LIVE_APPID', '')
    .constant('SLACK_APPID', '')
    .constant('STRIPE_PUBLISHABLE_KEY', '')
    .constant('SYSTEM_NOTIFICATION_MESSAGE', '')
    .constant('USE_HTML5_MODE', true)
    .constant('USE_SSL', false)
    .constant('ENABLE_ACCOUNT_CREATION', true);
/app

My system
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)

  System load:                      2.4853515625
  Usage of /:                       21.2% of 123.41GB
  Memory usage:                     46%
  Swap usage:                       0%
  Processes:                        157
  Users logged in:                  1
  IPv4 address for br-b2903fab9e78: 172.18.0.1
  IPv4 address for br-b3ec9e5b3122: 172.19.0.1
  IPv4 address for docker0:         172.17.0.1
  IPv4 address for eth0:            10.80.9.153

Open ports:
`sudo lsof -i -P -n | grep LISTEN`

systemd-r   680 systemd-resolve   14u  IPv4  42207      0t0  TCP 127.0.0.53:53 (LISTEN)
sshd        748            root    3u  IPv4  42838      0t0  TCP *:22 (LISTEN)
sshd        748            root    4u  IPv6  42849      0t0  TCP *:22 (LISTEN)
docker-pr  1540            root    4u  IPv4  48672      0t0  TCP *:9443 (LISTEN)
docker-pr  1547            root    4u  IPv6  50417      0t0  TCP *:9443 (LISTEN)
docker-pr  1562            root    4u  IPv4  50425      0t0  TCP *:8000 (LISTEN)
docker-pr  1569            root    4u  IPv6  50430      0t0  TCP *:8000 (LISTEN)
sshd       5485           tomek    7u  IPv6  63629      0t0  TCP [::1]:6010 (LISTEN)
sshd       5485           tomek    9u  IPv4  63630      0t0  TCP 127.0.0.1:6010 (LISTEN)
sshd      55115           tomek    7u  IPv6 179874      0t0  TCP [::1]:6011 (LISTEN)
sshd      55115           tomek    9u  IPv4 179875      0t0  TCP 127.0.0.1:6011 (LISTEN)
docker-pr 58591            root    4u  IPv4 187676      0t0  TCP *:5000 (LISTEN)
docker-pr 58600            root    4u  IPv6 186664      0t0  TCP *:5000 (LISTEN)

Situation is the same if I use -p 80:80

**Comment by niemyjski** [comment]
I'm really not sure, I just ran that exact docker command and it brought it right up on port 5000. Are there any errors in the docker logs?

**Comment by niemyjski** [comment]
I just realized that I was running a slightly older version of Exceptionless because docker was caching the latest tag. I'm also seeing this, and I believe there is probably a bug trying to create the Exceptionless UI Config. We'll take a look into this the first chance we get. If you wanted to dig into it, there is a [update-config](https://github.com/exceptionless/Exceptionless.UI/blob/main/update-config.sh) file and that's where I'd start debugging.

cc @ejsmith

**Comment by ejsmith** [comment]
Closing this, it should be working.
