### ISSUE TITLE
Sort & Filter views by App Version

### ISSUE THREAD

**Issue by Crushedice** [exceptionless/Exceptionless#1213]
Greetings,
i would like to know, if its possible to filter the displayed exceptions by the app Version it came from? 
Currently, i have to manually lookup the app Version, to know if the latest version produced the viewed exception or some older one.

If its not currently possible, you can take this as a feature request.
Thanks.

**Comment by niemyjski** [comment]
Hello,

Yes, you can do this by filtering on version (https://exceptionless.com/docs/filtering-and-searching/#searchable-fields-and-requirements) version:1 or version:1.0 or version:1.0.0

Please let us know if you have any questions or feedback.
