### ISSUE TITLE
how-to install host-self in windows server ?

### ISSUE THREAD

**Issue by kiquenet** [exceptionless/Exceptionless#1214]
any updates for 2023 ? https://www.youtube.com/watch?v=P01v289dR10

easy guide ? step by step...

not found https://exceptionless.com/news/2020/2020-09-30-how-to-self-host-your-error-monitoring-service/

**Comment by niemyjski** [comment]
All of our self-hosting documentation is located here: https://exceptionless.com/docs/self-hosting/ We recommend using Kubernetes for production and normal docker for small instances or for testing.
