### ISSUE TITLE
Project identifier not being passed to Exceptionless Web app

### ISSUE THREAD

**Issue by promising1** [exceptionless/Exceptionless#1228]
Using the Exceptionless.AspNetCore and an example provided on your site, I set up my Web API to send events to the local Exceptionless Web app. All is working, but looking at the console logs of Exceptionless, when posting an event, I noticed the following: 
```
Project null from request doesn't match project route id 63c84998693cea2714470263
```
Is it something I am missing or is it just an information log that I shouldn't worry about?

Client set up:

appsettings.json:
```json
"Exceptionless": {
    "ApiKey": "7Rmf85EqbDksj8XAe4vSD2RBL2UYVsftmMO21goa",
    "ServerUrl": "https://localhost:7101"
}
```

**Comment by niemyjski** [comment]
How did you create your api key?

**Comment by promising1** [comment]
That's the problem, I create a project in Exceptionless and use it's key, as proposed in the examples.

**Comment by niemyjski** [comment]
Thanks for that information, I'll try and see if I can reproduce.

**Comment by niemyjski** [comment]
This was mostly just a log message that shouldn't be displayed in this case. But we also fixed some additional issues around this in the linked pr.

**Comment by niemyjski** [comment]
A nightly build is out there with a fix.

**Comment by promising1** [comment]
Cool. ty
