### ISSUE TITLE
Extending the Exceptionless language support to Java

### ISSUE THREAD

**Issue by xbelt** [exceptionless/Exceptionless#123]
I previously contacted the exceptionless developers about upcoming language support and they informed me that the next project will probably be Java.

I find this project an awesome piece of software so I wanted to contribute to the new client. 
This issue should start a conversation about the future Java client of this software. 

As a discussion starter I would like to ask the following questions:
- Since Java does not support extension methods how would you use the ExceptionLess client?
- What other parts of the current client need to be changed due to language restrictions in Java?`

I hope we'll find some people who are willing to contribute in any way!

Lukas

**Comment by niemyjski** [comment]
I think the best approach would be to do what we do for the JavaScript client for event submission if there is no extension method support (https://github.com/exceptionless/Exceptionless.JavaScript/wiki/Sending-Events). I wonder what it would take to just do a port of our .NET PCL (or JavaScript) client to Java.. I think if we could port our .NET client that would be the best but I'm not sure on all the limitations. Could you look into this?

Going forward, if you wanted to take the lead on this. Would you like me to create the repo and then you could fork it?

**Comment by niemyjski** [comment]
I'd be more than happy to meet up with you and talk it over as well.

**Comment by xbelt** [comment]
I think this would be a good approach. I will look into this but I am quite positive that we can recreate most of the functionality except the features using extension methods.

I think creating a repo would be a nice start.

**Comment by niemyjski** [comment]
I've created a repo if you want to create a fork and work on it: https://github.com/exceptionless/Exceptionless.Java I'd start by porting the C# client over and try to keep as close as you can. We really appreciate this and will help out where we can!

**Comment by niemyjski** [comment]
I'm closing this as we've created a java repo that we can create issues on :).

**Comment by niemyjski** [comment]
@xbelt I'm checking in to see if you needed any assistance getting the Java client going or if you've had any luck.

**Comment by xbelt** [comment]
@niemyjski University has kept me very busy the last few month so I could not get much work done but I hope I'll have more time to work on this project in the near future.

**Comment by niemyjski** [comment]
@xbelt Thanks for the update. I hope you do well in your studies.

**Comment by scottcate** [comment]
@niemyjski Did this ever get published?

**Comment by niemyjski** [comment]
@scottcate nope, we are still accepting pull requests for a Java client, our api is super simple to use. Would you be interested in contributing one?

**Comment by scottcate** [comment]
Probably not, a friend was asking for one. I don't have the skill set required to help.

**Comment by niemyjski** [comment]
We'd really like to have one, it just comes down to resources
