### ISSUE TITLE
Unable to connect to http://localhost:5000 using docker-compose.yml on sign-up

### ISSUE THREAD

**Issue by TheGreatSageEqualToHeaven** [exceptionless/Exceptionless#1230]
Using the [docker-compose.yml](https://github.com/exceptionless/Exceptionless/blob/main/docker-compose.yml) on the github repo, when trying to sign-up I get an error saying "unable to connect to http://localhost:5000". I was struggling to understand how to self-host so any type of help will be appreciated.

**Comment by ejsmith** [comment]
You may have to change the port if you are running on OSX because they decided to use port 5000. We need to change the default port.

**Comment by TheGreatSageEqualToHeaven** [comment]
I'm using ubuntu 22.04, I tried changing the port and still got the same issue.

**Comment by ejsmith** [comment]
You will need to look at the logs in docker to see what is going on.

**Comment by niemyjski** [comment]
@TheGreatSageEqualToHeaven What did the docker logs say?

**Comment by TheGreatSageEqualToHeaven** [comment]
> @TheGreatSageEqualToHeaven What did the docker logs say?

Hi there, I'm currently on holiday and forgot about this issue. I'll follow up in a few weeks.

**Comment by ejsmith** [comment]
Not sure if this is the issue or not, but I changed the default dev port for the app from 5000 because 5000 is used by OSX now. Need to check the docker compose files and make sure that they are using different ports as well.
