### ISSUE TITLE
v7.2.1 can not run

### ISSUE THREAD

**Issue by HscNet** [exceptionless/Exceptionless#1265]
i use latest,v7.2.1，use docker , for" docker-compose up -d", can not run. and use v6.0.0, use "docker-compose up -d " ，can run,but "api" ，port:5000, can not access.   

i know. 5000 port is not running, so,can not access;

**Comment by HscNet** [comment]
https://exceptionless.com/docs/self-hosting/docker/

Unable to find image 'exceptionless/exceptionless:latest' locally

**Comment by HscNet** [comment]
I  am OK；

All of a sudden, it is better. It seems that it is caused by the environmental problems of supervisord.

Operation steps:

1. The docker-compose mode of v6.0.0 is installed, but the api fails to start and cannot access 50000, so it cannot register and log in;

2. Continue to follow docs, docker, docker run -- rm - it - p 5000:80 exceptionless/exceptionless: latest;

3. The 5000 port can be accessed normally, and can be registered and logged in, which means that step 2 takes effect, and the original 5100 can still be accessed, but cannot be logged in, because the port 50000 has not been started successfully, which may be an internal program error;

4. Continue the test, remove all containers and images, reinstall step 2 (docker run -- rm - it - p 5000:80), or OK, and log in to register. However, during the day, I tried to press docs many times, but I still couldn't access 51005000, register and log in;


I'm not sure what the problem is for the time being. It may be caused by the problem of hypervisor, because I have encountered it in the daytime, and I can now.

The above is my operation method. I hope it will help you. If you have any problems, you can try my steps.

my email : 413408219@qq.com

**Comment by niemyjski** [comment]
Hello,

Can you please try the latest versions, we changed the default ports so they didn't conflict with other known ports. We also integrated the UI directly into this app.
