### ISSUE TITLE
Exceptionless installs with Errors (null-valued expression)

### ISSUE THREAD

**Issue by JonasDralle** [exceptionless/Exceptionless#128]
I installed Exceptionless via Package Manager Console for my WPF Program.
Console says that it got installed successfully.

I did everything as stated in [the setup tutorial](https://i.imgur.com/cS1LOv4.png) and then pressed on _Debug_.

Visual Studio compiled and launched everything but then says that an TypeInitialization-Exception got thrown inside of code that I didn't wrote. I would need to disable "Only my Code".

The Exception is gone and the programs runs fine when I uninstall Exceptionless. I don't think that anything at the project got damaged on the install/uninstall so I assume that the error is inside of Exceptionless.

I'm sorry that I don't embed these two logs in here but I seriously don't want to spam. I haven't figured out how to use spoilers in github-flavored markdown so please excuse me:

**The Package Manger Console says this on install-package**
http://pastebin.com/raw.php?i=1pJStUXy

**The Exeption Visual Studio gives me when I launch with isntalled Exceptionless**
http://pastebin.com/raw.php?i=cq1460Ui
(it's completely in german, unlocalize.com hasn't worked on this one)

My own project does not contain this kind of error. I double checked. It's a very very simple WPF Form with merely 50 lines of code behind. I can send it to you guys in a zip file if you really need it to solve the problem.

I hope that this either helps me to get this working on my machine or that this helps you to improve your software thru bugfixing.

Thanks. Have a nice day

**Comment by niemyjski** [comment]
I think your config file is/was corrupted some how. Can you verify that the following is set:

```
<configuration>
  <configSections>
    <section name="exceptionless" type="Exceptionless.ExceptionlessSection, Exceptionless.Extras" />
  </configSections>
  <exceptionless apiKey="API_KEY_HERE"  />
```

Before you check this. Is there any chance you could put together a small sample/zip yours that reproduces this? I'd like to get to the bottom of this.

**Comment by JonasDralle** [comment]
Yes my app.config looks different.

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
	  </startup>
	  <exceptionless apiKey="API_KEY_HERE" />
	</configuration>

I deleted all my custom code for the .rar File
Error still occurs :)

You can Download it here:
http://www.xup.in/dl,86849326/Exceptionless_Error_128.rar/
http://www.mediafire.com/download/5p85c5lu6eppbcp/Exceptionless_Error_128.rar
(Both have the same file but you can chose which one to download from)

I'll try your .config approach and then tell you about the results

**Comment by JonasDralle** [comment]
Yea I'm propably pretty stupid not to start the exceptionless package on runtime. I don't think that this an error on your side.

I'm sorry that I might have wasted your time. Have a nice day

**Comment by niemyjski** [comment]
After looking at the inner exceptions you can see that it didn't know how to read the app.config

```
{"Unrecognized configuration section exceptionless. (C:\\Users\\Blake\\Downloads\\Exceptionless_Error_128\\JonasDralle.Höheninterpolation\\JonasDralle.Höheninterpolation\\bin\\Debug\\JonasDralle.Höheninterpolation.vshost.exe.Config line 6)"}
```

I noticed that you installed two separate packages. I'd recommend only installing `Exceptionless.Wpf` which will install the portable dependency as well (and wpf specific error handling). After uninstalling all packages that you had and installing the wpf package I didn't get any errors as it added

```xml

  <configSections>
    <section name="exceptionless" type="Exceptionless.ExceptionlessSection, Exceptionless.Extras" />
  </configSections>
```

to the app.config.

The last step you'd need to take is this:

```
Finally, you must import the "Exceptionless" namespace and call the following line
of code to start reporting unhandled exceptions.

Exceptionless.ExceptionlessClient.Default.Register()
```
If you install the wpf package and your app.config doesn't have the config section defined, please let me know.

Also what version of the nuget package manager and vs are you using?

**Comment by niemyjski** [comment]
@JonasDralle How is everything working out?
