### ISSUE TITLE
Data Exclusion by default overridden by data inclusions.

### ISSUE THREAD

**Issue by chrisproud** [exceptionless/Exceptionless#1285]
From a data security perspective it would be better to exclude all data post data by default, specifying only which fields should be included in the log data.

I believe this could be achieved without breaking existing functionality by adding an field called "Data inclusions" that overrides the data exclusions which could be set as *.

Is this possible?

**Comment by niemyjski** [comment]
@chrisproud would you mind submitting a pr for this? I'm going to close this in the mean time, but please feel free to open a pr and reference this issue.
