### ISSUE TITLE
Promoting a tab named the same as default tabs causes it to be unselectable via UI

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#1289]
**Description**
When promoting extended data to a tab, the tab cannot be selected via the UI.

![Snag_22aba1cd](https://user-images.githubusercontent.com/11253613/94177805-c7767980-fe5f-11ea-96d3-f251a071aea0.png)

**Investigation**
Digging into the source it looks like Angular is targeting the tab by its name with `ng-click="vm.activateTab(tab.title)"`, which there is two of. The tab is not selectable because the extended data tab title is named the same as one of the default Exceptionless tabs.

**Workaround**
Find the HTML for demoting the tab that is non-selectable, assign it a CSS ID so that it is selectable by JavaScript:
```
<a ng-click="vm.demoteTab()" id="demote">Demote Tab</a>
```
Then, in the web console, execute the command to mimic a click to demote the tab.
```
console.dir(document.getElementById("demote").click());
```

Then, don't name extended data objects the same as the default ones. Would be better to have tabs selectable by id rather than title?

Hopefully this is useful to any who encounter this. Thanks.

**Comment by niemyjski** [comment]
Thanks for reporting this and sorry about taking so long to get this fixed. The latest nightly has a fix for this issue.
