### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by muhammetsahin** [exceptionless/Exceptionless#130]
I've got tihs error on my server (windows 2012)

![image](https://cloud.githubusercontent.com/assets/2045788/9197173/bda6f4a4-403a-11e5-9913-697a89b16a52.png)

**Comment by niemyjski** [comment]
It looks like you don't have PowerShell installed. Can you please verify that this is installed.

**Comment by muhammetsahin** [comment]
PowerShell is already installed . I started manuel first " Start-ElasticSearch.ps1 " and than started " Start-Website.ps1 "

I've got another 

![image](https://cloud.githubusercontent.com/assets/2045788/9198142/a7a44802-4042-11e5-95b1-947922cbcc4a.png)

**Comment by niemyjski** [comment]
Looks like you're getting that because elasticsearch is not running. Is there any chance you can join our chat room? https://gitter.im/exceptionless/Discuss

**Comment by niemyjski** [comment]
@muhammetsahin I found the issue. You opened command prompt as an administrator and executed those commands against the system32 directory where the files didn't exist. You need to run the `start.bat` file by double clicking on it to launch the website. Please let me know if you have any questions or if this did not help.

**Comment by muhammetsahin** [comment]
@niemyjski thank you for help. I solved :)
