### ISSUE TITLE
Preserve string sent with AddObject and not try to make them more readable by splitting the keys in the ui based on casing

### ISSUE THREAD

**Issue by PCAssistSoftware** [exceptionless/Exceptionless#1316]
I use AddObject quite a lot to send additional information with an error e.g. 

`ex.ToExceptionless().AddObject(SelectedBackupType, "SelectedBackupType").Submit() `

And what I enter as the name e.g. in this example SelectedBackupType is what I want to appear in the web interface, as in most cases I use the variable name so I can easily refer to it later.

So why does it insist on inserting spaces between words when I don't want them? it happens with most items I submit with .AddObject and although is only a "visual" annoyance, is still annoying.

Screenshot below shows other examples:

![image](https://user-images.githubusercontent.com/10872799/236844033-cb79324e-bd2f-433c-83d7-0a124bb7cddb.png)

**Comment by niemyjski** [comment]
@PCAssistSoftware Thanks for reporting this, I've fixed this in the latest nightly. I'm not sure when we will push a new release, but it will go out on the next git tag.

**Comment by PCAssistSoftware** [comment]
@niemyjski  - thank you
