### ISSUE TITLE
Improve handling of Exception<T> where T : struct

### ISSUE THREAD

**Issue by corneliutusnea** [exceptionless/Exceptionless#132]
We use an Exception<T> which gets rendered a bit oddly in the UI.
public class CustomException<T> : ApplicationException
where T : struct
We use this so we can use enums instead of strings for error messages that are then easy to group in "buckets" or localize.

The the EL UI they get rendered as:
My.Custom.Namespace..CustomException`1[[Some.Long.Name.Space.ErrorCategory_ErrorBucket, Long.AssemblyName., Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

EL should understand such exceptions and render them as:
CustomException<ErrorCategory_ErrorBucket>

**Comment by niemyjski** [comment]
Yeah, I agree this should use the namespace+typename and not the assembly full name.

**Comment by niemyjski** [comment]
It also looks like the grids are having issues with these type names too.

**Comment by niemyjski** [comment]
Issue moved to [exceptionless/Exceptionless.Net #83](https://github.com/exceptionless/Exceptionless.Net/issues/83) via [**ZenHub.io**](https://www.zenhub.io/)
