### ISSUE TITLE
Sort the data in the Additional Data tab

### ISSUE THREAD

**Issue by corneliutusnea** [exceptionless/Exceptionless#133]
The elements in the Additional Data tab could be sorted by name and make not have the property names wrapped on two lines.
The values there are the ones you read using reflection of the exception object so the order is the reflection order. If the would be sorted alphabetically would make it easier to read.

**Comment by niemyjski** [comment]
I'll try and get this done in the next release, or if you'd like to take a stab at it, I think all we need to do is apply a filter to the angular repeater.

**Comment by niemyjski** [comment]
This change has been deployed. Please let us know what you think.
