### ISSUE TITLE
why data in extend data will be split?

### ISSUE THREAD

**Issue by sampsonye** [exceptionless/Exceptionless#1338]
![image](https://github.com/exceptionless/Exceptionless/assets/5895634/4d508913-b269-4468-ac0f-6f7867d93ff6)

**Comment by niemyjski** [comment]
What client and client version are you using? Please make sure you are using the latest version. If you have the issue with the latest version please include a small snippet that reproduces the issue

**Comment by niemyjski** [comment]
What's the raw output of your toJsonString method?

**Comment by sampsonye** [comment]
> What's the raw output of your toJsonString method?

`ToJsonString`just a shortcut of `JsonSerializer.Serialize(obj)` (STJ)
the raw output like below:
```
["0:66c56967-4781-4cab-b8dc-3fe03a31b032","1:52496c54-ee7d-4e7c-8945-f455845342e8","2:905aaa33-d6d7-45ef-bb94-6b45a3b2f6d3","3:66071216-83a0-4324-8469-275058e2a4c4","4:b7933e03-7f82-4b51-a864-527e12a72a4e","5:7f68f344-d853-44bc-976f-f7108b59e5d3","6:9d95c258-e1a9-48eb-b74b-0ca0d8583013","7:0d53d0ad-73d2-410a-93ac-4c7916e4486d","8:2ae15c5b-8f47-489e-9723-245720127316","9:e7b295a4-89aa-445f-910d-60585a3035d3","10:af54aab5-0d70-4fd3-8825-1b5c9def36b8","11:78e48d0b-5d81-4544-b744-d15552c79fe2","12:01728b56-0a10-45bc-8aff-a397f8dd1ef6","13:642c01a2-da30-44bb-86e6-a4f4f2e80a23","14:fa665bcf-5a6d-403c-a60c-a9f8d1445ea0","15:976d5f43-9fbc-4a67-8ae9-144cce7afa56","16:83f221dc-f772-46f5-abdc-b6eed61e7367","17:4b64258d-cfc2-4a1f-b489-ba728eb1f675","18:808354d5-7d6b-4362-b5a4-5ab97cbe95fb","19:7aef0383-d886-4525-95c3-7e1a29091a08","20:8d664b6a-e4e3-4e4e-b9fb-6e245c37c8bb","21:515f683d-3481-4efe-92ff-e245787fae1c","22:18b5d150-5112-4b19-8f99-a1da4b531016","23:5fa65ebb-7a86-4c40-bda7-da15091d8d82","24:ed7db380-b62f-40d1-9444-a4cda5d37f6e","25:32c01fb2-ea06-48f5-a439-69d93c28a80c","26:c0f5e81a-738d-4632-b8e3-562281493335","27:f5359011-72b3-461a-8886-2efe907e1ad7","28:b4114e35-230f-4b22-8ef9-4ae82b2b6d45","29:9eb2ca8b-7be6-4eb4-85bf-c3f3d1f52982","30:0e3f25e7-0ea3-427f-91ad-e3a7804552f8","31:f3258c7b-2e31-40f9-8da4-8bcdad8b2dc2","32:595a5f5d-ab6b-421d-a4c1-07b0f61ca034","33:d3cd4199-e114-4c38-bbbc-740f37dc4e42","34:e06ff656-8fea-4967-abeb-31e13f10c10b","35:5e967d84-a021-48e0-90da-479e4e8bdb38","36:8af22c2f-e273-489e-b1fb-7a3f212bc4c5","37:8607ca22-3134-45b6-aff4-470f9d28e2f4","38:bdaac9d4-ab97-41ff-8206-67e2e0c37bc1","39:4cebf092-7c76-4886-9d68-f3b99bcc2e7c","40:13008651-d68a-4ba9-a97a-22b49d0f77eb","41:47fcbf5e-8c72-484e-b418-8aca1cff9b7d","42:4f3142df-832d-44ad-ae38-7e2bc4bdd045","43:36c167ed-0a67-4c66-b8a3-933d3f476aae","44:1ca9e177-0e92-4549-9d4d-79aca4b52be5","45:6369def1-117f-4b24-b87e-3bf86c2c7013","46:fc4fd912-17e4-4e65-91dd-d722b61beb56","47:21f6521b-5f8d-4fde-8eb8-b0ae...
```

**Comment by niemyjski** [comment]
Thanks for that, I can't think of anything that would be causing this. Can you please try debugging this by looking at the event being posted or post a new event via our api and put this raw json in the event data dictionary property.

**Comment by sampsonye** [comment]
![image](https://github.com/exceptionless/Exceptionless/assets/5895634/61ca88e6-f084-42c7-8613-41c70b6de20e)

I think it may frontend bug

**Comment by niemyjski** [comment]
@sampsonye nice catch, any chance you can submit a pr for this.

**Comment by niemyjski** [comment]
Are you self hosting or using our hosted service? If self hosting, what version are you using? I'm not seeing the same behavior with the snippet you provided.
![Screenshot 2023-07-07 081246](https://github.com/exceptionless/Exceptionless/assets/1020579/a067ee70-a52c-4643-b557-0619913f0532)

Any chance you can attach the complete event json snippet and just blank out any p2 information.

**Comment by niemyjski** [comment]
I see that you have an object of data instead of an array, so if you could post your entire event json as mentioned above that would be great. I've resolved the sort and naming issue in the latest nightly build.
