### ISSUE TITLE
Send Email Bug！！

### ISSUE THREAD

**Issue by MuJint** [exceptionless/Exceptionless#1358]
I found an assembly data bug in the construction of send mail.
Please see the code and the screenshot.
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/227ac01b-2501-45d3-aa9c-83aea8a713b0)
The code in the screenshot should be commented to always get the test address in the configuration.
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/f83a2952-7aff-41c5-bb9a-a7e749ac54ff)
All **QueueMessageAsync** methods do not take From and should read the sender of the configuration file.

The following fixes the code
```
return QueueMessageAsync(new MailMessage {
            From = _appOptions.EmailOptions.SmtpFrom,
            To = invite.EmailAddress,
            Subject = subject,
            Body = body
        }, template);
```

In addition, there will be problems in reading the email configuration, the general email address will be **xx@xx.com**. Converting to a Uri will fail

**Comment by MuJint** [comment]
The second picture is a mistake. It should be SmtpUser. Because in smtp authorization, the sender should be the same as the authorizer.

**Comment by MuJint** [comment]
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/0f39f8c1-43f8-48ac-8cfb-1a42999ae2b2)

**Comment by niemyjski** [comment]
@MuJint Thanks for reporting this issue. Can you please clarify the lines of code that should be changed. In the first reply and images that code only runs if you are not in production mode, of which we only send emails to test domains.

The from is always set from here: https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs#L88-L91 via app options SmtpFrom

**Comment by MuJint** [comment]
Since docker is not supported in our environment, IIS deployment is used. The production environment configuration is shown in the following figure.
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/e3b5a941-e55f-4d28-b55e-3b5d52ec2d1e)
When the `EmailOptions.ReadFromConfiguration(config, options)` method reads the configuration。the `SmtpFrom`  field is not the configured authorized party.
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/651c46a7-d98f-4a1e-adce-932bc66eddc7)

So, if there is a problem with the configuration file ?

**Comment by MuJint** [comment]
I use the Windows IIS deployer.
oh, I see. Because this is the case with the configuration file, the account is for example: smtps://yuxin.bb@qq.com:aaaaaaaaa@smtp.qq.com:465. Converting to a URI will fail

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Utility/SmtpUri.cs#L6C39-L6C43

can't set the field `SmtpFrom` .

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Configuration/EmailOptions.cs#L51

**Comment by MuJint** [comment]
for example，send OrganizationInvite .the `from` field is not set. Please see code.

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Mail/Mailer.cs#L114

Get the `notification.From` field when it is empty, but `SmtpFrom` field is NUll in the configuration file.

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs#L88-L91

**Comment by niemyjski** [comment]
@MuJint you need to escape the `@` sign in the configuration with `%40` for it to be parsible. Please note the password part probably wouldn't be escaped and I wouldn't put an email address as a password.

`smtps://test%40test.com:testpass@smtp.test.com:587`

**Comment by MuJint** [comment]
thanks,i will try it tomorrow.
&nbsp;


于心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Blake ***@***.***&gt;; 
发送时间: 2023年7月5日(星期三) 晚上8:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [exceptionless/Exceptionless] Send Email Bug！！ (Issue #1358)





 
@MuJint you need to escape the @ sign in the configuration with %40 for it to be parsible. Please note the password part probably wouldn't be escaped and I wouldn't put an email address as a password.
 
***@***.***:587

**Comment by MuJint** [comment]
hi,after trying, @ convert with %40 is right. But the above errors still occur.please see https://github.com/exceptionless/Exceptionless/issues/1358#issuecomment-1620955532

Please refer to the results below.
I restored the code here and logged it.
```
public Task SendOrganizationInviteAsync(User sender, Organization organization, Invite invite) {
        const string template = "organization-invited";
        string subject = $"{sender.FullName} invited you to join the organization \"{organization.Name}\" on Exceptionless";
        var data = new Dictionary<string, object> {
                { "Subject", subject },
                { "BaseUrl", _appOptions.BaseURL },
                { "InviteToken", invite.Token }
            };

        var body = RenderTemplate(template, data);

        var message = new MailMessage {
            To = invite.EmailAddress,
            Subject = subject,
            Body = body
        };

        _logger.LogError($"now envirment：{_appOptions.AppMode}");
        _logger.LogError($"send invite param：{JsonConvert.SerializeObject(message)}");
        _logger.LogError($"configruation ：{JsonConvert.SerializeObject(_appOptions.EmailOptions)}");
        return QueueMessageAsync(message, template);
    }
```
Source code : https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Mail/Mailer.cs#L111C91-L111C91

The picture result：
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/7e3fbc7d-b8e1-4019-922a-118bf8a2f971)
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/6ec2ac25-58f8-4faf-bf14-6b6fc57ce744)

As you can see above,the `SmtpFrom` is always NULL.But the code still read `SmptFrom`.Please see code

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Insulation/Mail/MailKitMailSender.cs#L96

**Comment by niemyjski** [comment]
We don't support IIS hosting so I'm not sure how you are configuring settings. If you could provide your exact configuration using docker compose or docker environment variables that would be a huge help to see why it's not set. Also, you could try setting it in appsettings.yml and step through the debugger why it's not set.

**Comment by MuJint** [comment]
Okay, but I don't think it's the environment.

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Configuration/EmailOptions.cs#L47C27-L47C34

I read the code and the configuration file and found the problem.

https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Web/appsettings.Production.yml
https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Web/appsettings.Development.yml
https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Web/appsettings.yml

I got the initial code from git as above. You did not configure the parameter `SmptForm` in the configuration file.
This will lead to misunderstandings.I recommend that you attach the full configuration parameters to the configuration file.

The figure below will solve the problem!
![image](https://github.com/exceptionless/Exceptionless/assets/28145880/27a0185c-d6f5-4689-9941-d2e7571aaad4)

Thank you for replying to my questions and look forward to your resolution of the profile issue.

**Comment by niemyjski** [comment]
@MuJint Thanks for the follow up. Looks like we set it as a default here: https://github.com/search?q=repo%3Aexceptionless%2FExceptionless%20smtpfrom&type=code We don't expect users to be updating the appsettings files when deploying as we are expecting environment variables to be set via docker env

**Comment by niemyjski** [comment]
Any chance you'd be willing to update the self hosting guide with any email settings that should be set. Also, can we close this?

**Comment by MuJint** [comment]
Of course, this has solved my own problem.
But there are still a lot of windows environment can not get rid of, which is very frustrating. With best wishes.
