### ISSUE TITLE
Improved Notification Emails

### ISSUE THREAD

**Issue by kaiukdevelopment** [exceptionless/Exceptionless#136]
Hello,

Could you please add extra information to the emails that get sent out as notifications for each exception? We would like to see:

All tags
User identity
User description

Thank You,

Robert Edworthy
KAI Consulting

**Comment by niemyjski** [comment]
It would be good to be able to click on the email address and prepopulate the subject with the event's message.

**Comment by ejsmith** [comment]
I would love to see more information on these emails as well. @kaiukdevelopment, would you be willing to make these changes? I believe the we currently pass in the entire event object and it would just be a matter of changing the html template.

**Comment by niemyjski** [comment]
@kaiukdevelopment would you mind submitting a pull request for this?

**Comment by niemyjski** [comment]
I'm closing this as it's now merged into 177.

**Comment by niemyjski** [comment]
@kaiukdevelopment I wanted to let you know that this is currently being implemented in #177 and rolled soon :)
