### ISSUE TITLE
Direct Migration from 2.7 to 8.0

### ISSUE THREAD

**Issue by fischer-david** [exceptionless/Exceptionless#1366]
Hey there,

I'm not sure if im right here, but I wanted to ask if there is a way to migrate directly from Ver. 2.7 to 8.0, or if I have to go through all steps written here?
https://exceptionless.com/docs/self-hosting/upgrading-self-hosted-instance/

Best regards
David

**Comment by niemyjski** [comment]
You'd need to go through all the steps there. If you wanted to go the fast route and you didn't want your existing exception data, you could just start fresh and recreate your projects and manually copy over your api keys through kibana.

**Comment by fischer-david** [comment]
okay thx 👍
