### ISSUE TITLE
Is there a way to not show "Send report" dialog?

### ISSUE THREAD

**Issue by arturdev** [exceptionless/Exceptionless#137]
Do you support silent mode or something like that? 
I want to report all crashes automatically, without user interaction

**Comment by niemyjski** [comment]
Yes, you can do this by passing `false` to the [Register extension method](https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Platforms/Wpf/ExceptionlessWpfExtensions.cs#L18). Please let me know if you have any questions or need any assistance.

**Comment by arturdev** [comment]
Thank you very much!

**Comment by niemyjski** [comment]
No problem!
