### ISSUE TITLE
Get Events via API: The parameter "after" is not working

### ISSUE THREAD

**Issue by gliden** [exceptionless/Exceptionless#1382]
When using the REST-API to get all events, the parameter "after" is not working. 
The result is always an empty array.
I use this route `/api/v2/projects/:projectId/events `

**Comment by gliden** [comment]
We're using the hosted version

**Comment by niemyjski** [comment]
What version are you self hosting?

**Comment by gliden** [comment]
We‘re using this version: https://be.exceptionless.io/

**Comment by niemyjski** [comment]
Thanks for bringing this to our attention, I'm digging into this and adding test coverage.

**Comment by niemyjski** [comment]
This has been fixed and a version has been deployed.
