### ISSUE TITLE
Delete old data automatically

### ISSUE THREAD

**Issue by adamzolotarev** [exceptionless/Exceptionless#139]
It would be nice to be able to configure Exceptionless to automatically remove old data. 
E.g., if it's been more than 2 weeks since the last exception occurrence, then remove the exception stack.

**Comment by niemyjski** [comment]
We have a retention job that runs that will automatically cleanup old data based on the plans retention period. It would take quite a bit of work to implement this tho and cause a lot of churn for little gain. Thoughts?

**Comment by adamzolotarev** [comment]
Do you by chance have a code sample of how you implemented it? Say, if we wanted to do something similar for self-hosted version.

**Comment by niemyjski** [comment]
Yes, the source is here: https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Jobs/RetentionLimitsJob.cs

**Comment by adamzolotarev** [comment]
So, if we wanted to make this job work on a self-hosted plan, we would need to add retention-days to the organization. Would it make sense to update API to allow updating retention_days for Unlimited Plan. Something like:
```C#
        protected override PermissionResult CanUpdate(Organization original, Delta<NewOrganization> changes) {
            var changed = changes.GetEntity();
            if (!IsOrganizationNameAvailableInternal(changed.Name))
                return PermissionResult.DenyWithMessage("A organization with this name already exists.");
			if(OrganizationRetentionDaysChanged(changed.RetentionDays) && !CanOrganizationRetentionDaysBeChanged(original.PlanId))
                return PermissionResult.DenyWithMessage("Your billing plan does not allow to change retention days.");
            return base.CanUpdate(original, changes);
        }
        private bool CanOrganizationRetentionDaysBeChanged(string billingPlanId)
        {
            return billingPlanId == BillingManager.UnlimitedPlan.Id;
        }
        private bool OrganizationRetentionDaysChanged(int retentionDays)
        {
            return !_repository.GetByIds(GetAssociatedOrganizationIds()).Documents.Any(o => o.RetentionDays == retentionDays);
        }
```

**Comment by niemyjski** [comment]
I wouldn't make this change. I think the proper way to fix this would be to add the functionality to post custom plans as global admin. And then you could select this plan with that retention period. But the thing now. I think our retention job never deletes stacks only old events, but empty stacks shouldn't show up in the ui. What are your thoughts?

**Comment by adamzolotarev** [comment]
Deleting just events should be fine - our main concern is maintaining ElasticSearch performance. I'll look at the code. Thank you!

**Comment by niemyjski** [comment]
No problem, You could always just update the organization in elastic with new retention limits. The jobs will run automatically and will manage this for you :).

**Comment by adamzolotarev** [comment]
I was thinking that too. Just need to figure out how to do it in ES.

**Comment by adamzolotarev** [comment]
I think we'll just do ES update. I used the query below in case someone else needs it. But it's not an issue anymore for us. Doesn't look like it's worth the effort.

PUT /organizations-v1/organization/youOrganizationId?pretty
{
  "retention_days": "21",
  "billing_change_date":"2015-09-30T15:11:16.5708671-04:00",
  "modified_utc":"2015-09-30T15:11:16.5708671-04:00"
}

Thanks again for your help!

**Comment by niemyjski** [comment]
Awesome thanks! We really appreciate this. I was thinking more on your custom code above and I think it would work but it could be confusing because we'd be adding it to the update model as an allowed property and then rejecting it on specific cases. So for consistency I don't think it would work :(.

**Comment by niemyjski** [comment]
Is it fine if I close this issue?

**Comment by adamzolotarev** [comment]
Definitely. Thank you!

**Comment by niemyjski** [comment]
There is also a setting you can do to control the retention period for all projects (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Settings.cs#L150) If you set a property called `MaximumRetentionDays` it will delete all data past this date.

**Comment by lordscarlet** [comment]
I had to do this recently, and this was the simpler way to make the update in ES:

```
POST /organizations/organization/[guid]/_update?pretty
{
    "doc" : {        
            "retention_days": 180
    }
}
```

**Comment by mariohik** [comment]
@lordscarlet I had version 5.0 installed, and that code worked perfectly.
Now in version 6.0 it returns an error.
Can you tell me if anything has changed?
```
{
  "error": {
    "root_cause": [
      {
        "type": "document_missing_exception",
        "reason": "[organization][guid]: document missing",
        "index_uuid": "QLH3U8WXR3-CfCcWa4OcZg",
        "shard": "0",
        "index": "organizations"
      }
    ],
    "type": "document_missing_exception",
    "reason": "[organization][guid]: document missing",
    "index_uuid": "QLH3U8WXR3-CfCcWa4OcZg",
    "shard": "0",
    "index": "organizations"
  },
  "status": 404
}
```

**Comment by niemyjski** [comment]
Elasticsearch 7 removed index types. Use the following command.

```
POST /organizations/_doc/[guid]/_update?pretty
{
    "doc" : {        
            "retention_days": 180
    }
}
```
