### ISSUE TITLE
Docker run is not working

### ISSUE THREAD

**Issue by cetins32** [exceptionless/Exceptionless#1455]
we user docker latest version. UI can be working but api dont works latest version.
Can you check api on docker [Exceptionless] latest version for api

**Comment by niemyjski** [comment]
Thanks for reporting this issue, can you please provide enough information that we can reproduce:

- What operation system are you using
- What version of docker are you using
- What is the exact docker command you are using
- what is the exact docker tag and version are you using?
- Are there any logs that are outputted?

**Comment by niemyjski** [comment]
@cetins32 can you please provide the above information

**Comment by niemyjski** [comment]
Closing until more information is provided.
