### ISSUE TITLE
The WPF library lacks support for unhandled exceptions AppDomain UnhandledExeption and UnobservedTaskException

### ISSUE THREAD

**Issue by mgnslndh** [exceptionless/Exceptionless#146]
The WPF library wires up two event handlers for WinForm exceptions and dispatcher exceptions. Shouldn't it also wire up event handlers for unhandled exception notifications by AppDomain.Current.UnhandledException and TaskScheduler.UnobservedTaskException?

**Comment by mgnslndh** [comment]
The WPF library wires up two event handlers for WinForm exceptions and dispatcher exceptions. Shouldn't it also wire up event handlers for unhandled exception notifications by AppDomain.Current.UnhandledException and TaskScheduler.UnobservedTaskException?

**Comment by mgnslndh** [comment]
Found the event handlers being registered in the `Startup()` method. Sorry about this.

**Comment by niemyjski** [comment]
It's all good! Please let us know if you have any questions.
