### ISSUE TITLE
When use NLog.config link to exceptionless and how to set User Identity Name in UI?

### ISSUE THREAD

**Issue by pccai** [exceptionless/Exceptionless#1461]
![image](https://github.com/exceptionless/Exceptionless/assets/2232794/de5ea0ac-24f3-4bb8-9672-bc05b1a73fa8)

Excepitonless 8.0
Net 7.0.5

**Comment by pccai** [comment]
not {aspnet-item}, HttpContext.Items["Accout"] = "aaa BBB";

**Comment by niemyjski** [comment]
You would need to make sure you set the Identity property https://github.com/exceptionless/Exceptionless.Net/blob/601692c98dd0061eeebbbb6e85930634dfaef38b/src/Platforms/Exceptionless.NLog/LogEventBuilderExtensions.cs#L60

**Comment by pccai** [comment]
tks.

It's now worked for me:

  <target type="Exceptionless, Exceptionless.NLog" name="exceptionless" apiKey="API_KEY_HERE" **userIdentity="${aspnet-user-identity}"**>
      <field name="host" layout="${machinename}" />
      <field name="process" layout="${processname}" />
    </target>

**Comment by niemyjski** [comment]
Awesome!
