### ISSUE TITLE
Add setting to allow InviteToken to override EnableAccountCreation

### ISSUE THREAD

**Issue by theit8514** [exceptionless/Exceptionless#147]
Currently, EnableAccountCreation disables all account creations, even those invited to an organization with a valid InviteToken. Was looking to see if a configuration setting could be added to allow InviteTokens to be used. In my situation, I might have several organizations for different teams in my self-hosted instance and would need to go to the web.config and modify EnableAccountCreation any time one of those organizations need to add a coworker. With this settings, they can use the current Invite system to invite people to organizations while still preventing users outside our organization from creating accounts.

Some code and tests written already: https://github.com/theit8514/Exceptionless/commit/ddb1721ed7abcd44c06a88ffa113367bdeabfb31. Existing functionality is tested as well. Both settings off result in no accounts being accepted, and accounts should be accepted when EnableAccountCreation is enabled regardless of the InviteToken setting.

**Comment by niemyjski** [comment]
This would be good to have. I can see people wanting this scenario. It should be pretty easy to validate the token inside of the controller action and bypass that check. thoughts?

**Comment by niemyjski** [comment]
@theit8514 would you mind submitting a pull request for this.

**Comment by niemyjski** [comment]
Closed via https://github.com/exceptionless/Exceptionless/pull/174
