### ISSUE TITLE
Wrong Port allocation in self-hosting docker command 

### ISSUE THREAD

**Issue by nikschen** [exceptionless/Exceptionless#1473]
In docker command from [docs](https://exceptionless.com/docs/self-hosting/docker/):
`docker run --rm -it -p 5000:80 exceptionless/exceptionless:latest `
is a wrong port allocation, should be 5000:8080 or default port in image should be changed

Output from docker container when running: 
`[09:26:23 INF] Now listening on: http://[::]:8080 <Microsoft.Hosting.Lifetime>`
No configuration changes made by me

**Comment by ejsmith** [comment]
Thanks @nikschen, this is due to the recent default port change on .NET docker containers. Would you be able to submit a quick PR to update the places you saw this?

**Comment by nikschen** [comment]
Ah I see. Yeah, no Problem. I filed a pull request at the corresponding repository: [Link](https://github.com/exceptionless/Website/pull/51)

**Comment by ejsmith** [comment]
Thank you @nikschen!

**Comment by niemyjski** [comment]
Fixed via https://github.com/exceptionless/Website/pull/51
