### ISSUE TITLE
Why can't I see the HTTP request data in the exception details?

### ISSUE THREAD

**Issue by jerseycolipot** [exceptionless/Exceptionless#1476]
I have set up my own Exceptionless service, but I can't see the data submitted by the client in the exception details. As shown in the screenshot, is it a configuration issue on the server side of Exceptionless or on the client side? The request is submitted with JSON parameters, and in theory, it should be able to log the content of the JSON body of a POST request. However, I noticed that if I submit parameters in the form of a form, it can be logged. Is this a bug, or am I using it incorrectly? Thank you for your assistance.
![Uploading exceptionlessERROR.png…]()

**Comment by niemyjski** [comment]
Can you please fix the screenshot as it was never uploaded. Also, can you please send a snippet of client code you are using to create the event / let us know how we can reproduce the behavior on our side so we can give you more information.

**Comment by jerseycolipot** [comment]
![exceptionlessERROR](https://github.com/exceptionless/Exceptionless/assets/144749354/2fc72793-2f28-471e-8720-d2b0395bccdb)

**Comment by jerseycolipot** [comment]
there is the picture

> Can you please fix the screenshot as it was never uploaded. Also, can you please send a snippet of client code you are using to create the event / let us know how we can reproduce the behavior on our side so we can give you more information.

**Comment by niemyjski** [comment]
@jerseycolipot you would need to enable buffering so the request stream can be reread. There will be a performance overhead of enabling this. I thought there was a way todo this via kestrel config but a middleware will work as well (just make sure it's a really higher priority). https://devblogs.microsoft.com/dotnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/ https://markb.uk/asp-net-core-read-raw-request-body-as-string.html
