### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by jerseycolipot** [exceptionless/Exceptionless#1479]
I am currently using Exceptionless.AspNetCore (version 6.0.0) in my web API gateway project. The project is based on Ocelot (version 18.0.0), and I use Ocelot to forward traffic downstream. For instance, if someone requests the path [www.xxx.com/goods/get](http://www.xxx.com/goods/get) (where [www.xxx.com](http://www.xxx.com/) is my gateway developed using Ocelot), I route the request to 192.168.0.222/goods/get (where 192.168.0.222 is the actual downstream interface). The request is successful, and I retrieve the correct result from the downstream interface. In other words, the path is correct, and Ocelot successfully forwards the request. However, because the /goods/get path does not exist in my gateway project, Exceptionless reports a 404 error. Could you please advise if there is an issue with my code?
here is the code 
![exceptionless](https://github.com/exceptionless/Exceptionless/assets/144749354/bf5f1c68-9cfc-4892-b05b-f591b55ae1c5)

**Comment by niemyjski** [comment]
UseExceptionless registers middleware and should be one of the first middleware added otherwise anything before it won't get caught. I think this will solve your problem too as it sounds like the api is returning 404, and Ocelot is handling and redirecting? Please comment if still an issue and we'll reopen it, please include a small repo if you can.

**Comment by jerseycolipot** [comment]
> UseExceptionless registers middleware and should be one of the first middleware added otherwise anything before it won't get caught. I think this will solve your problem too as it sounds like the api is returning 404, and Ocelot is handling and redirecting? Please comment if still an issue and we'll reopen it, please include a small repo if you can.

You're welcome! As you mentioned, I moved the line of code "app.UseExceptionless(app.Configuration)" from the image to the beginning of my custom middleware, and it started working correctly. When I have more time, I plan to delve into its code to gain a better understanding of how it works. Thank you again for your response; it has been very helpful. I appreciate your assistance and also want to express gratitude for the open-source work you have done, which has saved me a lot of time.
