### ISSUE TITLE
How can I make the ExceptionLessUI interface find the logs with specific tags that I want?

### ISSUE THREAD

**Issue by jerseycolipot** [exceptionless/Exceptionless#1481]
In my requests when entering the system, I add the 'oucRequestId' HTTP header in the http headers, and its value is a GUID. Then, for logging in my system, I use Serilog, and the project references Serilog.Sinks.Exceptionless to output logs to ExceptionLess.

When someone requests my API and an exception occurs, the exception is sent to ExceptionLess. I can see the 'oucRequestId' parameter in the 'request' of this exception log on the web of ExceptionLessUI, but when I search for this value, I cannot find the exception. How should I write logs to allow ExceptionLess to search and find these logs?

**Comment by niemyjski** [comment]
We currently do not search header values. You could write a plugin to to copy the header value to the event data property (dictionary) via SetProperty. I'd take a look at this: https://exceptionless.com/docs/clients/dotnet/plugins/ You'd want your plugin to have a higher priority (> 90) than the http plugin.

You may also be able to do this via sink configuration but I'm not sure. Please let us know if you have any questions.

**Comment by jerseycolipot** [comment]
> We currently do not search header values. You could write a plugin to to copy the header value to the event data property (dictionary) via SetProperty. I'd take a look at this: https://exceptionless.com/docs/clients/dotnet/plugins/ You'd want your plugin to have a higher priority (> 90) than the http plugin.
> 
> You may also be able to do this via sink configuration but I'm not sure. Please let us know if you have any questions.

    // 创建一个自定义事件
    var customEvent = new Event
    {
        Message = "customEvent Message",
        Type = "customEvent  Type",
        Source = "customEvent Source",
    };

    customEvent.SetProperty("oucRequestIdTest", oucRequestId);

    ExceptionlessClient.Default.SubmitEvent(customEvent);

I send log to exceptionless like this ,
![image](https://github.com/exceptionless/Exceptionless/assets/144749354/c744bc88-8ce1-4f5d-8c43-be36361d0f76)

the log like picture show  ，but I when I search the keyword"53bbfd9a1b4343a3b73e7823ccbee0ba" ,it had no resuts , It looks like "SetProperty” will not be search 。

**Comment by niemyjski** [comment]
See the search docs, you need to search using custom data data.propertyname:blah
