### ISSUE TITLE
Account creation with token

### ISSUE THREAD

**Issue by ChaosDMG** [exceptionless/Exceptionless#1516]
The "EnableAccountCreation" check should not apply for users with a valid invite token. 
If needed you can simply revoke the users invite.

Just on a side note, I found a bug where you can signup with a valid token with EnableAccountCreation set to false if you click create while email validation is in progress.
You can reproduce this by entering your name and password then copy paste you email address and immediately click the create my account button.

**Comment by niemyjski** [comment]
Hello,

We'd be willing to accept a pr for this.

**Comment by ChaosDMG** [comment]
I cant access signup
![image](https://github.com/exceptionless/Exceptionless/assets/10861785/8d92ce50-d783-4d83-b2a3-2689ed53cdf2)
![image](https://github.com/exceptionless/Exceptionless/assets/10861785/41a8b8da-8578-47a1-861e-23c50b931d46)


From looking at the code it might just be a js fix to check for EnableAccountCreation or token rather than just EnableAccountCreation. The api might already work that way but its a bit hard to tell if I cant debug because of the above.

**Comment by niemyjski** [comment]
It looks like you are running the new ui locally, can you also go to this folder `Exceptionless\src\Exceptionless.Web\ClientApp.angular\` and run `npm run serve`

**Comment by niemyjski** [comment]
Thanks again for the PR! We will cut a new beta release soon, in the mean time please use the nightly images.
