### ISSUE TITLE
Filtering by custom data range

### ISSUE THREAD

**Issue by modesto** [exceptionless/Exceptionless#153]
Hi,

Is it possible to filter by custom data range?

Something like data.age:(>18 AND <= 35)

Kind regards

**Comment by niemyjski** [comment]
Hello,

Yes you can do this today with: `data.age:(>18 AND <= 35)` as shown here https://github.com/exceptionless/Exceptionless/wiki/Filtering-Searching#ranges

Is this not working?

Please let us know if you have any questions

**Comment by modesto** [comment]
Hello,

I'm trying it but it is not working. If I write a query like `data.measuredtimeinmilliseconds:1709` it works ok and I get the only event with this value. But if I query `data.measuredtimeinmilliseconds:(>1708 AND <= 2000)` I don't get any result.

What can I do to diagnose the problem?

**Comment by niemyjski** [comment]
what kind of extended data are you submitting? This is just a number property:
```json
"data": { "measturedtimeinms":1709 }
```

Does `((data.measuredtimeinmilliseconds:>1708) AND (data.measuredtimeinmilliseconds:<= 2000))` work?

**Comment by modesto** [comment]
Yes, is just a number property like this:

` "data": { "MeasuredTimeInMilliseconds": 1709 }`

I've tried `((data.measuredtimeinmilliseconds:>1708) AND (data.measuredtimeinmilliseconds:<= 2000))` and it doesn't work

**Comment by niemyjski** [comment]
I'll try and create a sample and get back to you. On a side note please feel free to join our chat room: https://gitter.im/exceptionless/Discuss

**Comment by niemyjski** [comment]
I ran the following query which should work: `data.MeasuredTimeInMilliseconds:(>=50 AND <200)` and it didn't seem to be returning data. I'll take a closer look into this.

```json
[
    { 
      "message": 50,
      "data": { "MeasuredTimeInMilliseconds": 50 }
    },
    { 
      "message": 100,
      "data": { "MeasuredTimeInMilliseconds": 100 }
    },
    { 
      "message": 150,
      "data": { "MeasuredTimeInMilliseconds": 150 }
    }
]
```
