### ISSUE TITLE
elasticsearch connection failed

### ISSUE THREAD

**Issue by 107295472** [exceptionless/Exceptionless#1534]
docker run -d -p 5201:8080 --name el -v /home/elasticsearch/esdata:/usr/share/elasticsearch/data -e EX_Html5Mode=true exceptionless/exceptionless:8.1.6

`
["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];"

 Health check Elasticsearch with status Unhealthy completed after 214.335ms with message 'null' <Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService>

`

**Comment by 107295472** [comment]
chown: changing ownership of '/usr/share/elasticsearch/data': Operation not permitted

**Comment by niemyjski** [comment]
Are you sure you have the proper permissions on your elasticsearch share?

**Comment by 107295472** [comment]
Is elasticsearch not within docker?

**Comment by 107295472** [comment]
Do I need to install elasticsearch independently externally?

**Comment by 107295472** [comment]
Okay, esdata requires 777 permissions

**Comment by niemyjski** [comment]
If you use the all in one image it's included, otherwise a connection string needs to be specified. I'm not sure what permissions they (elasticsearch) specify.

**Comment by niemyjski** [comment]
We just extend the base elasticsearch docker image 


FROM exceptionless/elasticsearch:8.11.1 AS exceptionless

So I'd take a look at that image to see what permissions it uses.
