### ISSUE TITLE
Email verification link gives 404 is clean URLs are enabled

### ISSUE THREAD

**Issue by cmjacobs** [exceptionless/Exceptionless#154]
When i click the verify email link, i get a 404 error.

I am self hosting (full disclosure: IIS7, not 8). If I undo the settings for clean URLs, then resend the verification email, the link works again.

**Comment by niemyjski** [comment]
Do you have the clean URLS setting defined in the javascript app? If they are not set in both places this may fail. Can you please confirm this.

**Comment by cmjacobs** [comment]
I set USE_HTML5_MODE to true in app.config.*.js file and i removed the # in the js and web.config files from the base url

**Comment by ejsmith** [comment]
@cmjacobs That should be all that you need. If you want to join our gitter room, we can setup a remote meeting and I can take a look into this with you.
