### ISSUE TITLE
Filter/block events from stale application instances

### ISSUE THREAD

**Issue by stephenwelsh** [exceptionless/Exceptionless#156]
In our scenario we have 1000+ clients that install our product (typically a desktop app) and although we have an in-place upgrade capability, it's optional and user driven. Therefore after a while we have a situation with a number of old installations with issues that have been resolved submitting irrelevant exception reports.
Essentially it is out of our control to upgrade the older instances, however given the newer releases have resolved issues the submissions from older releases become less relevant.

Therefore we think it would be appropriate to control the clients submissions with a project level setting that enables/disables the client based on it’s version. For example:

Set the Project Configuration Setting: EnableVerson=4.2

In our application check the ‘EnableVersion’ setting from the Exceptionless client once registered, if the current application version is older (i.e. 4.1) then disable submissions. If the current version is the same or newer then submit.

In our situation the version number is enough for us to control which submissions are more/less relevant, however I would imagine there may be other criteria that may be of value to be able to leverage for enabling/disabling of submissions

**Comment by srijken** [comment]
Sort-of related, we also had one specific error causing a 250k+ exceptions in a month. This is an error that users/clients never see, but is unhandled. Because the error is outside of our control, we can't do much about it. It would also be good if the final solution would also make it possible to do something about this.

For us a working solution would be to control in the Project Configuration that a certain exception should be filtered by the client. I'm not sure yet how this should be configured, just exception type, or a regex match or something is probably too course.

Ideally filtering a stack would be best, but the problem with that is that the event -> stack code has to move from server to client. Problem is, this is against the decision in Exceptionless that the logic should be on the server side, so it's easier to patch.

**Comment by stephenwelsh** [comment]
I guess we would need a way to identify a particular type of submission at the client side and use server side control to block/disable. Is there anything is the server side stack grouping logic that could be replicated client side.
Failing that the ability to filter based on any one of the submission properties matching a particular value should cover most scenarios.
In our case if we could set a project level filter/block on the version property of a submission that should be all we need.

**Comment by ejsmith** [comment]
This can be done now fairly easily using [project configuration](http://blog.exceptionless.com/the-power-of-real-time-project-settings/) and wiring up to the [submitting event](http://docs.exceptionless.com/contents/sendingevents/) and cancelling the submission.

**Comment by ejsmith** [comment]
It would be nice if it was more of a 1st class feature though.

**Comment by stephenwelsh** [comment]
Another thought, as this is mostly a problem for us when a small number of application instances send a high number of duplicate submissions. Would there be merit in being able to de-prioritise certain stacks server side and respond to the client with a lower throttling limit so clients that submit low-priority stack submissions get throttled before others?

**Comment by niemyjski** [comment]
Yeah, we are deduplicating exceptions right now, it might be nice to say if an exception is still rapidly occurring over x minutes really throttle that error

**Comment by niemyjski** [comment]
Just can't think of an intelligent solution other than itelligently throttling deduplication while keeping the client dumb (no stacking info)

**Comment by ejsmith** [comment]
I suppose we could implement a client side plugin to do rudimentary stacking and let people opt into using it. Could also implement a client side throttler plugin.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless/issues/112

**Comment by niemyjski** [comment]
I think we could implement the version:latest functionality and send down the latest version down to the client in a header. Then we could get really smart and even allow you to turn off old clients. I know in one of our products we can get hammered with older errors that are no longer relevant.

**Comment by niemyjski** [comment]
Merged into https://github.com/exceptionless/Exceptionless/issues/112
