### ISSUE TITLE
Facing the issue while deploying in k8s aks.

### ISSUE THREAD

**Issue by Ranjithsyncfusion** [exceptionless/Exceptionless#1561]
PS C:\Users\888888888888\Downloads\Exceptionless-main\k8s> kubectl apply -f ex-dev-elasticsearch.yaml
Error from server (NotFound): error when creating "ex-dev-elasticsearch.yaml": namespaces "ex-dev" not found
Error from server (NotFound): error when creating "ex-dev-elasticsearch.yaml": namespaces "ex-dev" not found

**Comment by niemyjski** [comment]
You'd need to create that ex-dev namespace. I'd recommend using a production configuration and not a development one. See this https://github.com/exceptionless/Exceptionless/blob/main/k8s/ex-setup.ps1 and https://exceptionless.com/docs/self-hosting/kubernetes/

**Comment by niemyjski** [comment]
Also, any steps that you use for local would be greatly appreciated if they were documented for others, we mainly setup and run on azure.

**Comment by Ranjithsyncfusion** [comment]
Can you please mention the exact file that you recommended .

**Comment by niemyjski** [comment]
I linked to it, all of our k8s/helm files and scripts are in thisfolder https://github.com/exceptionless/Exceptionless/tree/main/k8s

**Comment by wang2024666** [comment]
> I linked to it, all of our k8s/helm files and scripts are in this folder https://github.com/exceptionless/Exceptionless/tree/main/k8s

hi niemyjsi, could we delpoy all-in-one in K8S without helm? we hope to deploy API,APP,Job all in one pod with yaml file, is there such methord?

**Comment by niemyjski** [comment]
We use helm for deployment to our cluster. I'm not sure about your question, I'm sure it's possible but not something we are actively going to work on. Please feel free to contribute back.
