### ISSUE TITLE
References to Microsoft.VisualBasic

### ISSUE THREAD

**Issue by DanubeRS** [exceptionless/Exceptionless#157]
The `Exceptionless.Extras` project has referenced Microsoft.VisualBasic, which is not compatible with Xamarin.Mac. AFAIK, this is only used in the `EnviromentInfoCollector` class for collecting information about a computer (through `ComputerInfo`).

This looks to be easily substituted (with possible exception of Memory properties).

**Comment by niemyjski** [comment]
What package are you trying to use in your app? We use this extras implementation to provide full implementations of interfaces defined in the portable library.

**Comment by niemyjski** [comment]
What package are you trying to use in your app? We use this extras implementation to provide full implementations of interfaces defined in the portable library.

**Comment by DanubeRS** [comment]
I am writing an application which uses WebAPI in a self-host scenario. I installed the Base package, and used in in combination with the NLog integration and worked great, but wanted to integrate via the WebAPI package.

The only place I could find the `Microsoft.VisualBasic` dll reference was in the Extras library, which at least in usage here, is just a wrapper around a p/invoke on `kernel32.dll`?

I had a quick look at the source, and you have a catch for Mono in there. I was just curious as to whether an alternative for the limited use of the `Microsoft.VisualBasic` could be used, thus removing that problematic reference.

**Comment by DanubeRS** [comment]
I quickly slapped together a change for my personal use, to which I will throw in an internal (private) NuGet package. Look [here](https://github.com/DanubeRS/Exceptionless.Net/commit/90c8fd337b761cc4b48ae30cffad0d526dd58723) to see my (poorly) migrated code. Basically checked to see if I could load in `System.Management` to simulate `OSName` and p/invoked for memory. Untested, so I can't be sure it works well enough for general use. Disposed of the `Microsoft.VisualBasic` reference and it works great in Xamarin.Mac

**Comment by niemyjski** [comment]
Can you please let me know how this works out for you? I know we are going to be working on a dnx client very soon and that might be the way to go.
