### ISSUE TITLE
How to enable Azure AD in docker deployment.

### ISSUE THREAD

**Issue by Ranjithsyncfusion** [exceptionless/Exceptionless#1590]

**Comment by Ranjithsyncfusion** [comment]
Hi Team, 

I have deployed in docker using docker compose, and Azure AD also created, obtained App ID. But there is no idea for configuring Azure AD auth for that docker deployment.

**Comment by niemyjski** [comment]
Looks like you need to set the LDAP connection string https://github.com/exceptionless/Exceptionless/blob/main/src/Exceptionless.Core/Configuration/AuthOptions.cs#L36-L37
