### ISSUE TITLE
InvoicePaymentSucceededAsync logs incorrect text when an organization is not found

### ISSUE THREAD

**Issue by ingeniousllc** [exceptionless/Exceptionless#162]
In the `Source\Billing\StripeEventHandler.cs` file, the method `InvoicePaymentSucceeded` logs incorrect text when the organization cannot be  found in the repository. Here are the lines in question:

```C#
private async Task InvoicePaymentSucceededAsync(StripeInvoice inv) {
    var org = await _organizationRepository.GetByStripeCustomerIdAsync(inv.CustomerId).AnyContext();
    if (org == null) {
        Logger.Error().Message("Unknown customer id in payment failed notification: {0}", inv.CustomerId).Write();
        return;
    }
    //...
}
```
It looks like the code was copy/pasted from the `InvoicePaymentFailedAsync` method just below it but that text was not changed.

**Comment by niemyjski** [comment]
@ingeniousllc would you mind submitting a pull request for this change?

**Comment by niemyjski** [comment]
Thanks!

**Comment by ingeniousllc** [comment]
@niemyjski Request created: https://github.com/exceptionless/Exceptionless/pull/163

**Comment by niemyjski** [comment]
Please let us know if you find anything else :).
