### ISSUE TITLE
How can I view the full content of a long log message?

### ISSUE THREAD

**Issue by maobiwen** [exceptionless/Exceptionless#1637]
In the ExceptionLess backend management, the complete log content cannot be displayed. I am using ExceptionLess to record logs, and when the log messages are very long, the backend management page shows part of the content followed by "..." to indicate that there is more log content. However, I don't know where to view the rest of the log information. Could you please confirm if the content is fully recorded, and if it is, what method should I use to retrieve the complete content?This log contains a key piece of information that I need to find the cause of the bug. Please help me figure out how to retrieve the complete information. Thank you.

![exceptionless](https://github.com/exceptionless/Exceptionless/assets/11902441/4e438a18-91ca-403b-8bc9-bc403feba7e1)

**Comment by niemyjski** [comment]
Hello,

We trim off long event messages and don't recommend putting long message content there. We recommend putting objects / json payload into custom properties which are fully rendered in extended data and can be promoted to their own tab. Even better if the extended property is a simple data type it will be searchable. https://exceptionless.com/docs/clients/dotnet/sending-events/#sending-additional-information
