### ISSUE TITLE
Can't create project locally

### ISSUE THREAD

**Issue by fagnercarvalho** [exceptionless/Exceptionless#167]
Hello!

I was trying to setup Exceptionless in a Azure VM running Windows Server 2012 R2 x64 but I having some strange issues. I basically create a account then a organization and a project but somehow the site keeps telling me to create a project. If I logout and try to login again I receive a **"An error occurred while logging in. Please contact support for more information."** error. If I try to reset my password I receive a **"An error occurred while trying to reset your password. Message: No user was found with this Email Address."** error.
After that I created a account in Exceptionless to log everything from my Azure Exceptionless site into Exceptionless but the only error that I got was related to the fact that the SMTP server was not configured correctly (to solve this I just replaced the Website mode from 'Production' to 'Dev' because I just testing for now).

I setup my server basically following the [tutorial for Self-hosting](https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#production).

Some relevant information:

``api/v2/status`` response:

``` json
{
  "message": "All Systems Check",
  "version": "3.1.1822 68f48d2a7e"
}
```

Elastic Search log:

```
[2015-12-08 02:26:35,139][INFO ][node                     ] [ex-es01] version[1.7.3], pid[2752], build[05d4530/2015-10-15T09:14:17Z]
[2015-12-08 02:26:35,139][INFO ][node                     ] [ex-es01] initializing ...
[2015-12-08 02:26:36,029][INFO ][plugins                  ] [ex-es01] loaded [], sites []
[2015-12-08 02:26:37,576][INFO ][env                      ] [ex-es01] using [1] data paths, mounts [[(C:)]], net usable_space [114gb], net total_space [126.6gb], types [NTFS]
[2015-12-08 02:26:56,907][WARN ][script                   ] [ex-es01] deprecated setting [script.disable_dynamic] is set, replace with fine-grained scripting settings (e.g. script.inline, script.indexed, script.file)
[2015-12-08 02:27:00,406][INFO ][node                     ] [ex-es01] initialized
[2015-12-08 02:27:00,419][INFO ][node                     ] [ex-es01] starting ...
[2015-12-08 02:27:01,940][INFO ][transport                ] [ex-es01] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/100.113.112.35:9300]}
[2015-12-08 02:27:02,032][INFO ][discovery                ] [ex-es01] exceptionless/h0jrk6jLRyepEPG5evjznw
[2015-12-08 02:27:06,743][INFO ][cluster.service          ] [ex-es01] new_master [ex-es01][h0jrk6jLRyepEPG5evjznw][exceptionless][inet[/100.113.112.35:9300]], reason: zen-disco-join (elected_as_master)
[2015-12-08 02:27:07,227][INFO ][http                     ] [ex-es01] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/100.113.112.35:9200]}
[2015-12-08 02:27:07,227][INFO ][node                     ] [ex-es01] started
[2015-12-08 02:27:07,309][INFO ][gateway                  ] [ex-es01] recovered [3] indices into cluster_state
[2015-12-08 02:29:36,269][INFO ][cluster.metadata         ] [ex-es01] [organizations-v1] update_mapping [project] (dynamic)
[2015-12-08 02:35:29,218][INFO ][cluster.metadata         ] [ex-es01] [organizations-v1] update_mapping [project] (dynamic)
```

Web.config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <add name="RedisConnectionString" connectionString="" />
    <add name="ElasticSearchConnectionString" connectionString="http://localhost:9200" />
  </connectionStrings>
  <appSettings>
    <!-- Base url for the ui used to build links in emails and other places. -->
    <add key="BaseURL" value="http://SITE.cloudapp.net/#" />
    <!-- Controls whether SSL is required. Only enable this if you have SSL configured. -->
    <add key="EnableSSL" value="false" />
    <!--
    Dev: Use this mode when debugging. (Outbound emails restricted)
    QA: Use this mode when deployed to staging.  (Outbound emails restricted)
    Production: Use this mode when deployed to production.
    -->
    <add key="WebsiteMode" value="Dev" />
    <!-- Email addresses that match this comma delimited list of domains and email addresses will be allowed to be sent out in Dev and QA mode -->
    <add key="AllowedOutboundAddresses" value="exceptionless.io,codesmithtools.com" />
    <!-- All emails that do not match the AllowedOutboundAddresses will be sent to this address in Dev and QA mode -->
    <add key="TestEmailAddress" value="noreply@exceptionless.io" />
    <!-- Controls whether users can signup. -->
    <add key="EnableAccountCreation" value="true" />
    <!-- Controls whether daily summary emails are sent -->
    <add key="EnableDailySummary" value="true" />
    <!-- Folder used to store event post data -->
    <add key="StorageFolder" value="|DataDirectory|\storage" />
    <!-- Runs the jobs in the current website process -->
    <add key="RunJobsInProcess" value="true" />
    <!-- Internal project id keeps us from recursively logging to ourself -->
    <add key="InternalProjectId" value="PROJECT_ID" />
    <!-- Exceptionless Api Key that allows us to log any application exceptions -->
    <add key="Exceptionless:ApiKey" value="API_KEY" />
    <add key="Exceptionless:ServerUrl" value="" />
    <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />
  </appSettings>
  <system.net>
    <mailSettings>
      <smtp from="Exceptionless &lt;noreply@exceptionless.io&gt;">
        <network host="localhost" port="25" />
      </smtp>
    </mailSettings>
    <defaultProxy enabled="true" />
    <settings>
      <!-- This setting causes .NET to check certificate revocation lists (CRL) 
           before trusting HTTPS certificates.  But this setting tends to not 
           be allowed in shared hosting environments. -->
      <!--<servicePointManager checkCertificateRevocationList="true"/>-->
    </settings>
  </system.net>
  <system.web>
    <authentication mode="None" />
    <compilation targetFramework="4.6" debug="false" />
    <httpRuntime targetFramework="4.6" maxUrlLength="1024" />
    <customErrors mode="Off" />
  </system.web>
  <system.webServer>
    <httpErrors errorMode="Detailed"></httpErrors>
    <!-- ... -->
```

Menu just after creating a new project (where is my project? I only see my organization):

![exceptionless_home](https://cloud.githubusercontent.com/assets/817867/11647291/817fd98a-9d4d-11e5-9368-bd9b5e7309df.png)

Binding in IIS:

![binding_iis](https://cloud.githubusercontent.com/assets/817867/11647295/8c9b6668-9d4d-11e5-83d5-12f592454ba9.png)

What I'm doing wrong here?

Thanks.

Regards,
Fagner

**Comment by niemyjski** [comment]
What are the error messages in the logs? Can you try turning on remote errors so you can see them and then open up the f12 tools and pasting in the stack traces you get. Everything looks fine.

**Comment by niemyjski** [comment]
@fagnercarvalho, were you able to get this working? If not, can you join our gitter chat room and I'll jump on a remote meeting with you.

**Comment by fagnercarvalho** [comment]
Hello @niemyjski!

Sorry for the delay. Some information that I collected right now:

First of all, I was using my free Exceptionless account to log errors from my local Exceptionless app but now I receiving a error saying that my events are being throttled so I can't see any new events.

I basically receiving the following 2 errors when I navigating between pages:
![console-errors](https://cloud.githubusercontent.com/assets/817867/11773662/febc2e9c-a213-11e5-9fcc-d28d06025215.png)

After logging out from my account and trying to login again:
![error-login](https://cloud.githubusercontent.com/assets/817867/11773676/31e02ea4-a214-11e5-9a2a-52f4aacc0766.png)

If I try to access the app root path directly in a new tab after registering:
![error-access-after-login](https://cloud.githubusercontent.com/assets/817867/11773686/51408078-a214-11e5-9d40-d84c6f18e9e7.png)

All requests using the query string parameter access_token are referencing my Exceptionless account configured in my Web.config file:
![exceptionless-api](https://cloud.githubusercontent.com/assets/817867/11773705/a4ae8fca-a214-11e5-9a4f-46caee9454ec.png)

Requests after trying to create a new project (remember that I can't see my created project in the list):
![projects-request-api](https://cloud.githubusercontent.com/assets/817867/11773709/b718c874-a214-11e5-978f-5652fa8afdce.png)

My app.config:
``` javascript
(function () {
  'use strict';

  angular.module('app.config', [])
    .constant('BASE_URL', 'http://URL.cloudapp.net')
    .constant('EXCEPTIONLESS_API_KEY', 'API_KEY_FREE_EXCEPTIONLESS_ACCOUNT')
    .constant('FACEBOOK_APPID')
    .constant('GITHUB_APPID')
    .constant('GOOGLE_APPID')
    .constant('INTERCOM_APPID')
    .constant('LIVE_APPID')
    .constant('STRIPE_PUBLISHABLE_KEY')
    .constant('SYSTEM_NOTIFICATION_MESSAGE')
    .constant('USE_HTML5_MODE', true)
    .constant('USE_SSL', false);
}());
```

Regards,
Fagner

**Comment by niemyjski** [comment]
Thanks for the images, throttling will occur based on an hourly limit on our hosting service. For self hosted projects there are no limits.

1. I'm not sure what that first promise type error is, can you send us the stack trace for that.
2. That /api/v2/events 401 error is expected as it's the UI trying to send feature usage and error events to your self hosted instance but the api key in the app.config.js is invalid. We've made some improvements to this in the latest UI builds. The fix is to ignore it or create a new project on your self hosted install and update the config value.
3. That 401 after logging in would occur if the user name or password is incorrect. I'd try copy and pasting it to check. If you are still having problems, let me know. I can join a remote meeting with you and take a look. Just hit me up on gitter and we'll make it happen.
4. Both the UI and and Server side have exceptionless integration points to log to itself, if you don't configure the api keys in either of them, they won't log.
5. Exceptionless on the ui app is set to use the base url as the api end point to log to. So it won't be using your free account to log (or shouldn't be) with the config you have. 

If you'd like I would be more than happy to meet up with you and get this all working. Just send me a message in gitter.

**Comment by ejsmith** [comment]
@fagnercarvalho were you able to get this working?

**Comment by niemyjski** [comment]
Please reopen this issue if you were not able to get this working. I'd be more than happy to help you via a remote meeting.

**Comment by megakid** [comment]
I would be interested in reopening this as I too am getting the exact same symptoms on my self-hosted version.

As noted, I can create my own user account but then if I log out and back in again, it won't work and I will have to recreate the user account.

Once on the dashboard (after creating a new user) I can create the same project over and over.

I can see no errors in my Chrome dev tools.

I am running 1.7.4 with your config, on all default ports (50,000 for exceptionless, 9200 for elastic).  I am not planning on using redis so don't have that component.

**Comment by niemyjski** [comment]
Can you still reproduce this? If so, can I jump on a remote meeting with you and take a look.

**Comment by EtiennePeeters** [comment]
I'd like to comment on this, as I also had this issue. Turns out my Elasticsearch cluster was not working properly due to wrong configuration.
(I also tried running Exceptionless along with Elasticsearch 2.2, which resulted in the same issue.)

Now everything is working fine, using a properly configured Elasticsearch 1.7.3 cluster.

**Comment by Lord-Hasek** [comment]
Hey all,

I am encountering this issue as well in a self hosted environment. I'm running:

Elasticsearch 1.7.3
The latest Exceptionless release
IIS 8.5

I'm receiving all the same errors as @fagnercarvalho. Would we be able to set up a virtual meeting sometime after the 28th to take a look?

Thanks!

**Comment by niemyjski** [comment]
Sure can you send me a message on gitter (preferred) or email and we'll set something up whenever you are free.
