### ISSUE TITLE
No registration for type IEnumerable HttpConfiguration

### ISSUE THREAD

**Issue by muhammetsahin** [exceptionless/Exceptionless#168]
Hi,

I've setup exceptionless api on my host server. But 've got error like this:

No registration for type IEnumerable<Action<HttpConfiguration>> could be found.

![image](https://cloud.githubusercontent.com/assets/2045788/11842885/33caa5c6-a40f-11e5-947a-3015816d7f8b.png)

![image](https://cloud.githubusercontent.com/assets/2045788/11842906/4ab2f9b4-a40f-11e5-8919-041645736e50.png)

![image](https://cloud.githubusercontent.com/assets/2045788/11842917/59cd5c28-a40f-11e5-91ec-d1d768dca528.png)

Where did i wrong?

**Comment by muhammetsahin** [comment]
I solved myself. The problem was missing dll.

**Comment by niemyjski** [comment]
Thanks for the follow up! Please let us know how it's working out for you!
