### ISSUE TITLE
Allow to submit files as array of bytes with name and download it

### ISSUE THREAD

**Issue by matteomigliore** [exceptionless/Exceptionless#170]
Allow to submit the files with a method AddFile(string name, byte[] data) and download it in the Extended data tab.

**Comment by niemyjski** [comment]
I don't think we will ever implement this as it introduces many can of worms on both the client and server.  It would affect the following areas

* Client Storage (we enqueue the event offline, we'd now have to manage a large file).
* Client Submission (streaming this in).
* Server side event queueing and storage and event processing
* Managing these files during event retention and when bulk events are removed.

You could easily do this with a plugin:

```csharp
public class AzureBlobStoragePlugin : IEventPlugin {
        private const string KNOWN_FILE_NAME_KEY = "abc.exe";
        public void Run(EventPluginContext context) {
            if (context.Event.Data.ContainsKey(KNOWN_FILE_NAME_KEY)) {
                // Upload file to blob storage here

                // Link to the uploaded file in azure
                context.Event.SetProperty(KNOWN_FILE_NAME_KEY, "link to file in azure or xyz");
            }
        }
    }
```

One thing we will improve on is detecting links or file name extensions as part of extended data and hot link them/syntax highlighting them.

**Comment by matteomigliore** [comment]
From my point of view the AddFile method is just the AddObject but allowing to send a *little* amount of data, not large files, little XML/JSON/HTML...

Eventually you can implement the plugin, if you don't want to allow to store the data on your systems.

Thank you.

**Comment by niemyjski** [comment]
If it's just a little bit of data you can do this today with setproperty and we will get better at rendering it if the property name ends with the extension.

**Comment by matteomigliore** [comment]
Ok, so we will use the method AddObject("Test.xml", "<Root><Person>Bill</Person>"), right?

**Comment by niemyjski** [comment]
Yes, but I'd call set property (preference) instead as it's a single property, not a complex object https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/EventBuilder.cs#L150

**Comment by matteomigliore** [comment]
I don't understand, I've to wait for an update of the UI, right?

**Comment by niemyjski** [comment]
The data will show up as extended data right now it just won't have syntax highlighting

**Comment by niemyjski** [comment]
I'm closing this issue as this is possible right now via calling SetProperty on the EventBuilder. We are also currently looking into formatting/syntax highlighting of extended data

https://github.com/exceptionless/Exceptionless/issues/173

**Comment by matteomigliore** [comment]
Great. Thank you Blake!
