### ISSUE TITLE
Add "only if >= 1 exception" to Daily Summary notification choice.

### ISSUE THREAD

**Issue by Drel** [exceptionless/Exceptionless#176]
Currently, if I enable Daily Summary for notifications, I get a Daily Summary email notification regardless of whether any exceptions occurred ("Congrats! The "XXX" project was exceptionless!").  

I would like to have the option to only get a Daily Summary if one or more exceptions occurred.  Sure, I can filter these emails out, but I don't see much value in receiving them.

**Comment by niemyjski** [comment]
We need to sit down and have a discussion on notifications as a community and team. This feature request kind of ties into these issues (and should be discussed and merged into one).

* https://github.com/exceptionless/Exceptionless/issues/69
* https://github.com/exceptionless/Exceptionless/issues/76
* https://github.com/exceptionless/Exceptionless/issues/136

Currently we don't have any code in place but one could update the DailyNotificationsJob to do this; @ejsmith do you feel that we should send one out if you didn't get anything? What about if the project wasn't yet configured?

**Comment by niemyjski** [comment]
I'm closing this as it's now merged into 177.
