### ISSUE TITLE
Broken docker image v8.2

### ISSUE THREAD

**Issue by LukaszC86** [exceptionless/Exceptionless#1768]
Wrong version of .NET 9.0 (preview version) is shipped with the image :
![Image](https://github.com/user-attachments/assets/8fe5acac-0cf2-403d-a46a-d92b2881e953)

**Comment by LukaszC86** [comment]
@niemyjski you should use "--channel 9.0" instead of "--channel preview"

**Comment by niemyjski** [comment]
Thanks for the issue, Pushing new release now.
