### ISSUE TITLE
Custom Stacking Behavior

### ISSUE THREAD

**Issue by adamzolotarev** [exceptionless/Exceptionless#180]
It would be useful to have some sort of property on the event that you can set that would override the default stacking behaviour and let you stack things in custom ways.

Currently, as a workaround, if you want to override default exception stacking behavior, you can do this: 
```csharp
ExceptionlessClient.Default.CreateEvent().SetType(Event.KnownTypes.Error).SetSource("customSource");
```
And "customSource" will serve as a new stacking. But then you lose the Exception tab and you have to manually translate the Exception information.

But if instead you do
```csharp
exception.ToExceptionless().SetSource("customSource"); 
```
it still uses a default stacking behavior (exception type + method).

Not sure if it would be better to add a completely new method to set custom grouping (e.g., SetCustomStack("customStackName)") or just add a property (e.g., IsCustomGrouping) and just use the Source property to group the exceptions.

**Comment by niemyjski** [comment]
We had a quick talk about this over the weekend and we like this idea, would you be willing to take a stab at implementing this in a pull request?

Here is some of our thoughts on this:
* Create EventBuilder and Event extension methods on the client to handle this, but place them under a different extensions namespace (maybe Exceptionless.Advanced??). The reasoning for putting them in a different namespace is we want to make it crystal clear that this is something advanced and not a normal scenario and you understand what you are doing. This extension method should set an extended property on the event and call it something like `@StackSignature` with a string value that you want to stack on. The extension method that we create should validate that this value is set. 
* Update the [pipeline/AssignToStack pipeline action](https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Pipeline/010_AssignToStackAction.cs#L40) to use this value for the `StackSignatureData`. *Optional/Feedback* Should we remove this extended property from the event once we use it on signature data?

**Comment by niemyjski** [comment]
@ejsmith can you provide any additional feedback?

**Comment by ejsmith** [comment]
So 1st off, the fact that we aren't showing the error tab when there is an error object on the event is a bug. Event type shouldn't matter for showing that tab. Only that the data is present.

I am definitely on board with allowing custom stacking and agree that I am a little worried that people would see something like SetStackingKey and think they needed to set it. But I think if we do something like SetManualStackingKey then I think it is obvious enough that we can just include it with the other extension methods.  We would also want a good XML doc description saying what the method does.

- Add SetManualStackingKey(string stackingKey) that sets an extended property called @StackingKey (need to verify that this name matches our other @ names).
- Update the pipeline to add this as the only item in the StackSignatureData if it exists and is not empty.
- We would want to show the stacking key on the event to make sure that people know why it got stacked the way it did.

**Comment by niemyjski** [comment]
If you look at his first sample, he's only setting the error type and not an actual error model on the event.

**Comment by ejsmith** [comment]
@niemyjski Ahh, yeah. I missed that. It doesn't have any error object to add to the event.

**Comment by adamzolotarev** [comment]
Thanks! I'll look into it. 
And yes, I didn't submit any error object to the event. If I did, then I wouldn't be able to use "Source" as my custom grouping.

**Comment by ejsmith** [comment]
@adamzolotarev were you able to get a chance to look into this? I would like to have this for something I am doing as well.

**Comment by adamzolotarev** [comment]
Not yet. I'm going to look at it today/tomorrow.

**Comment by ejsmith** [comment]
Awesome! Let me know if you need any help. Here are some pointers:

This is where the current error stacking happens.

https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Plugins/EventProcessor/Default/20_ErrorPlugin.cs

I think we should have a step that happens before this that checks for the existence of @StackingKey in the event data dictionary. If that exists then we add it to the context.StackSignatureData and then we need to check to make sure that we don't have any StackSignatureData before we add our normal stacking info.

**Comment by adamzolotarev** [comment]
I updated Exceptionless and Exceptionless.Net. 
Tried it locally - looks like it's working. The stacking key is shown at stack level:
![image](https://cloud.githubusercontent.com/assets/6343727/12697739/71fa3f5c-c758-11e5-9f8b-2be65bb02370.png)

I didn't get to the part of displaying the stacking key at the event level. Should I submit a pull request for what I have now? And which branch should I be using then?

Changesets:
https://github.com/adamzolotarev/Exceptionless.Net/commit/a1bcc6c2d22fa58bac228bbdf78c5a6ecbcc889f
https://github.com/adamzolotarev/Exceptionless/commit/d9dc8387734b743943ef16540b554c91f3669665

**Comment by ejsmith** [comment]
Awesome! Yeah, create a branch and submit a pull request and we will check it out.

**Comment by niemyjski** [comment]
This has both been deployed on clients and on the server. Are we 100% happy with this as I'm in the process of writing a blog post for this.

**Comment by niemyjski** [comment]
.NET
https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/Extensions/EventBuilderExtensions.cs#L63
```csharp
try {
    throw new ApplicationException("Unable to create order from quote.");
} catch (Exception ex) {
    ex.ToExceptionless().SetManualStackingKey("MyCustomStackingKey").Submit();
}
```

Or you can set the stacking directly on an event (e.g., inside of a plugin).
https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/Extensions/EventExtensions.cs#L288

```csharp
event.SetManualStackingKey("MyCustomStackingKey");
```

JavaScript
https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/src/EventBuilder.ts#L119

```js
var client = exceptionless.ExceptionlessClient.default;
// Node.Js
// var client = require('exceptionless).ExceptionlessClient.default;

try {
  throw new Error('Unable to create order from quote.');
} catch (error) {
  client.createException(error).setManualStackingKey('MyCustomStackingKey').submit();
}
```

**Comment by niemyjski** [comment]
This feature has been implemented.
