### ISSUE TITLE
Support other clients to send exceptions to the Events API

### ISSUE THREAD

**Issue by skoub** [exceptionless/Exceptionless#181]
I think it could help the adoption of Exceptionless if it could accept other clients, like Raygun, to send exceptions to the Events API.

Raygun already have big support for many plateforms like .Net, Java, PHP, Javascript, etc and they are all open source. I know that you can configure the url that the clients use to contact their API server so maybe it's just a matter to set the url to Exceptionless API server and then map the data correctly to your model.

What's your thought?

**Comment by niemyjski** [comment]
I think that's a really good idea that we didn't think of and would help us in the short term to gain more client support (IOS, JAVA, PHP). This should be really simple to support, here is what would need to be done.

* Add a new RayGun/Service XYZ event [parser](https://github.com/exceptionless/Exceptionless/tree/master/Source/Core/Plugins/EventParser/Default). This would take a look at the user agent being submitted and then deserialize / translate the their json model into our generic event model.
* Update our [existing parser unit tests](https://github.com/exceptionless/Exceptionless/blob/master/Source/Tests/Plugins/EventParserTests.cs)

As you can see it wouldn't be very hard to add support for this. Would you be willing to take a stab at this? I'd be more than happy to help you or point you in the right direction. We give any non-trivial pull request a free year of the small plan on our hosted service (this would qualify for this).

**Comment by ejsmith** [comment]
Interesting idea. Yeah, this would actually be really easy to implement. Just need to translate from that format to ours. Our system already takes any random JSON data. Would just need to add the translation pipeline step and then point their OSS clients to our API endpoint.

**Comment by skoub** [comment]
I have opened your code last week-end to see where i could implement this but i haven't found it yet. Could you please guide me to the right direction?

* the parser must be version aware. Raygun can change their model in the next major version. I will need help on how to do this.

before we give it a go, do we have the right to do this? I know they are open source but is their licencing are compatible with you you want to do?

**Comment by ejsmith** [comment]
https://github.com/exceptionless/Exceptionless/tree/master/Source/Core/Plugins/EventParser/Default

We would add another plugin there to detect their useragent and then parse the JSON they send us and translate it into events in our system.

All of their clients are MIT license. So we can use them, modify them, redistribute them or whatever else.

**Comment by niemyjski** [comment]
In the Core project you'd need to create a new `IEventParserPlugin`. You could just start by copying the [JsonEventParserPlugin](https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Plugins/EventParser/Default/JsonEventParserPlugin.cs) and then parsing into a raygun event model and then convert that model to our model. Once you get there model deserializing into a model, it's just a means of copying that data into our event model.

Here are some important notes:

* Check the user agent and return null if you can't handle it. I'm thinking that if there major version changes we throw an exception?
* All there clients are open source and say you can copy/use the code as long as you copy the license file. BUT to be on the safe side, I'd HIGHLY recommend just closing there project and coding the model / everything around the raw client json / public spec they have documented (somewhere)? Then all work is original work and subject to our apache 2 license. If it was me I'd just look at fiddler of the json they post, and copy that raw json to a unit test and create a C# model using this: http://json2csharp.com or look at there api documentation for creating new clients. I'd advice against copying any code / models and to create it from scratch to be on the extra safe side.

**Comment by niemyjski** [comment]
Here is a link to there docs: https://raygun.io/docs/integrations/api that specifies the model as 

```json
{
	"occurredOn": "2015-09-08T01:55:28Z",
	"details": {
		"machineName": "ServerMachine1",
		"groupingKey": "ErrorGroup",
		"version": "1.0.0.1",
		"client": {
			"name": "Example Raygun Client",
			"version": "0.0.0.1",
			"clientUrl": "https://raygun.io/docs/integrations/api"
		},
		"error": {
			"innerError": {},
			"data": {
				"example": 5
			},
			"className": "ErrorClass",
			"message": "An error occurred",
			"stackTrace": [
			{
				"lineNumber": 55,
				"className": "BrokenService",
				"columnNumber": 23,
				"fileName": "BrokenService.cs",
				"methodName": "BreakEverything()"
			}]
		},
		"environment": {
			"processorCount": 4,
			"osVersion": "Windows 10",
			"windowBoundsWidth": 2560,
			"windowBoundsHeight": 1440,
			"browser-Width": 2560,
			"browser-Height": 1440,
			"screen-Width": 2560,
			"screen-Height": 1440,
			"resolutionScale": 1.0,
			"color-Depth": 24,
			"currentOrientation": "Landscape",
			"cpu": "Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz",
			"packageVersion": "package version",
			"architecture": "ARMv7-A",
			"deviceManufacturer": "Nokia",
			"model": "Lumia 920",
			"totalPhysicalMemory": 1024,
			"availablePhysicalMemory": 1024,
			"totalVirtualMemory": 1024,
			"availableVirtualMemory": 1024,
			"diskSpaceFree": [50000.52, 2000.104],
			"deviceName": "Nexus 7",
			"locale": "en-nz",
			"utcOffset": -12,
			"browser": "Mozilla",
			"browserName": "Netscape",
			"browser-Version": "5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36",
			"platform": "Win32"
		},
		"tags": ["tag1", "tag 2", "tag-3"],
		"userCustomData": {
			"domain": "WORKPLACE",
			"area": "51"
		},
		"request": {
			"hostName": "https://raygun.io",
			"url": "/docs/integrations/api",
			"httpMethod": "POST",
			"iPAddress": "127.0.0.1",
			"queryString": {
				"q": "searchParams"
			},
			"form": {
				"firstName": "Example",
				"lastName": "Person",
				"newsletter": true
			},
			"headers": {
				"Referer": "www.google.com",
				"Host": "raygun.io"
			},
			"rawData": "{\"Test\": 5}"
		},
		"response": {
			"statusCode": 500 
		},
		"user": {
			"identifier": "123456789",
			"isAnonymous": false,
			"email": "test@example.com",
			"fullName": "Test User",
			"firstName": "Test",
			"uuid": "783491e1-d4a9-46bc-9fde-9b1dd9ef6c6e"
		}
	}
}
```

The online viewer http://jsonutils.com created this

```csharp
 public class Client
    {
        [JsonProperty("name")]
        public string name { get; set; }
        [JsonProperty("version")]
        public string version { get; set; }
        [JsonProperty("clientUrl")]
        public string clientUrl { get; set; }
    }

    public class InnerError
    {
    }

    public class Data
    {
        [JsonProperty("example")]
        public int example { get; set; }
    }

    public class StackTrace
    {
        [JsonProperty("lineNumber")]
        public int lineNumber { get; set; }
        [JsonProperty("className")]
        public string className { get; set; }
        [JsonProperty("columnNumber")]
        public int columnNumber { get; set; }
        [JsonProperty("fileName")]
        public string fileName { get; set; }
        [JsonProperty("methodName")]
        public string methodName { get; set; }
    }

    public class Error
    {
        [JsonProperty("innerError")]
        public InnerError innerError { get; set; }
        [JsonProperty("data")]
        public Data data { get; set; }
        [JsonProperty("className")]
        public string className { get; set; }
        [JsonProperty("message")]
        public string message { get; set; }
        [JsonProperty("stackTrace")]
        public IList<StackTrace> stackTrace { get; set; }
    }

    public class Environment
    {
        [JsonProperty("processorCount")]
        public int processorCount { get; set; }
        [JsonProperty("osVersion")]
        public string osVersion { get; set; }
        [JsonProperty("windowBoundsWidth")]
        public int windowBoundsWidth { get; set; }
        [JsonProperty("windowBoundsHeight")]
        public int windowBoundsHeight { get; set; }
        [JsonProperty("browser-Width")]
        public int browser-Width { get; set; }
        [JsonProperty("browser-Height")]
        public int browser-Height { get; set; }
        [JsonProperty("screen-Width")]
        public int screen-Width { get; set; }
        [JsonProperty("screen-Height")]
        public int screen-Height { get; set; }
        [JsonProperty("resolutionScale")]
        public double resolutionScale { get; set; }
        [JsonProperty("color-Depth")]
        public int color-Depth { get; set; }
        [JsonProperty("currentOrientation")]
        public string currentOrientation { get; set; }
        [JsonProperty("cpu")]
        public string cpu { get; set; }
        [JsonProperty("packageVersion")]
        public string packageVersion { get; set; }
        [JsonProperty("architecture")]
        public string architecture { get; set; }
        [JsonProperty("deviceManufacturer")]
        public string deviceManufacturer { get; set; }
        [JsonProperty("model")]
        public string model { get; set; }
        [JsonProperty("totalPhysicalMemory")]
        public int totalPhysicalMemory { get; set; }
        [JsonProperty("availablePhysicalMemory")]
        public int availablePhysicalMemory { get; set; }
        [JsonProperty("totalVirtualMemory")]
        public int totalVirtualMemory { get; set; }
        [JsonProperty("availableVirtualMemory")]
        public int availableVirtualMemory { get; set; }
        [JsonProperty("diskSpaceFree")]
        public IList<double> diskSpaceFree { get; set; }
        [JsonProperty("deviceName")]
        public string deviceName { get; set; }
        [JsonProperty("locale")]
        public string locale { get; set; }
        [JsonProperty("utcOffset")]
        public int utcOffset { get; set; }
        [JsonProperty("browser")]
        public string browser { get; set; }
        [JsonProperty("browserName")]
        public string browserName { get; set; }
        [JsonProperty("browser-Version")]
        public string browser-Version { get; set; }
        [JsonProperty("platform")]
        public string platform { get; set; }
    }

    public class UserCustomData
    {
        [JsonProperty("domain")]
        public string domain { get; set; }
        [JsonProperty("area")]
        public string area { get; set; }
    }

    public class QueryString
    {
        [JsonProperty("q")]
        public string q { get; set; }
    }

    public class Form
    {
        [JsonProperty("firstName")]
        public string firstName { get; set; }
        [JsonProperty("lastName")]
        public string lastName { get; set; }
        [JsonProperty("newsletter")]
        public bool newsletter { get; set; }
    }

    public class Headers
    {
        [JsonProperty("Referer")]
        public string Referer { get; set; }
        [JsonProperty("Host")]
        public string Host { get; set; }
    }

    public class Request
    {
        [JsonProperty("hostName")]
        public string hostName { get; set; }
        [JsonProperty("url")]
        public string url { get; set; }
        [JsonProperty("httpMethod")]
        public string httpMethod { get; set; }
        [JsonProperty("iPAddress")]
        public string iPAddress { get; set; }
        [JsonProperty("queryString")]
        public QueryString queryString { get; set; }
        [JsonProperty("form")]
        public Form form { get; set; }
        [JsonProperty("headers")]
        public Headers headers { get; set; }
        [JsonProperty("rawData")]
        public string rawData { get; set; }
    }

    public class Response
    {
        [JsonProperty("statusCode")]
        public int statusCode { get; set; }
    }

    public class User
    {
        [JsonProperty("identifier")]
        public string identifier { get; set; }
        [JsonProperty("isAnonymous")]
        public bool isAnonymous { get; set; }
        [JsonProperty("email")]
        public string email { get; set; }
        [JsonProperty("fullName")]
        public string fullName { get; set; }
        [JsonProperty("firstName")]
        public string firstName { get; set; }
        [JsonProperty("uuid")]
        public string uuid { get; set; }
    }

    public class Details
    {
        [JsonProperty("machineName")]
        public string machineName { get; set; }
        [JsonProperty("groupingKey")]
        public string groupingKey { get; set; }
        [JsonProperty("version")]
        public string version { get; set; }
        [JsonProperty("client")]
        public Client client { get; set; }
        [JsonProperty("error")]
        public Error error { get; set; }
        [JsonProperty("environment")]
        public Environment environment { get; set; }
        [JsonProperty("tags")]
        public IList<string> tags { get; set; }
        [JsonProperty("userCustomData")]
        public UserCustomData userCustomData { get; set; }
        [JsonProperty("request")]
        public Request request { get; set; }
        [JsonProperty("response")]
        public Response response { get; set; }
        [JsonProperty("user")]
        public User user { get; set; }
    }

    public class Example
    {
        [JsonProperty("occurredOn")]
        public DateTime occurredOn { get; set; }
        [JsonProperty("details")]
        public Details details { get; set; }
    }
```

**Comment by niemyjski** [comment]
Now just need to copy a that plugin and the models I just posted above and deserialize the values into it :)

**Comment by skoub** [comment]
Great. And i guest i will have to modify the current parsers to not only test the api version but also your own user agent?

**Comment by niemyjski** [comment]
Yeah, and adjust the priority of the raygun parser to be after ours but before the default fallback plugin

**Comment by niemyjski** [comment]
Let me know if you have any questions and if you commit often I can leave feedback / help where needed.

**Comment by skoub** [comment]
i will give it a try later today. Can you also give me some hint on how i should contribute? I will fork your code, create a branch and code there?

I will also have to check your coding style.

**Comment by niemyjski** [comment]
Yeah, we have a guide here: https://github.com/exceptionless/Exceptionless/blob/master/CONTRIBUTING.md . But in general, sign our cla (if there is an error signing it just send an email to team@exceptionless.com with your info. Then  fork our project and code under the branch thirdpartyclients (just created it) and create a pull request that references this issue. If you need any help getting setup please let me know.

If you have resharper installed, you'll automatically pick up our styles. Also you can install this free extension [rebracer](https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58) which will also apply our bracket styles.

**Comment by niemyjski** [comment]
We are also in our [gitter room](https://gitter.im/exceptionless/Discuss) if you wish to chat.

**Comment by skoub** [comment]
i try to send my first exception with raygun but your api doesn't accept the request because raygun doesn't have an AuhtorizationHeader. Also, it doesn't use UserAgent so we will have to think how we can detect it's a raygun call.

I think we will have to rethink your api to accept the request without the authentification. Any idea?

**Comment by niemyjski** [comment]
Do you have this committed on your branch so I can pull it down and take a look?

**Comment by niemyjski** [comment]
I committed auth changes and an entries end point to the third party branch. Please merge them in and let me know if you have any questions.

**Comment by skoub** [comment]
you've said that the current parser should not test agains the userAgent. How do you want to deal with that? When raygun will post his data, one your your parser with take it before the real raygun parser.

**Comment by ejsmith** [comment]
The useragent will be set to raygun as the result of the changes that @niemyjski just made. So we can key off of that.

We also made it so that you can just setup a host header to map api.raygun.io to api.exceptionless.io and it will work.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless/pull/194

**Comment by niemyjski** [comment]
I'm going to close this to keep the issues clean. I'd like to meet up with you and help you get this pr finished up. Please send me a message and let me know when you are free.
