### ISSUE TITLE
Add UI for specifying user namespaces and common methods to project settings

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#182]
We already have support for specifying namespaces and common methods to ignore client side but we need to add a project configuration support for this and get it hooked up.

**Comment by ejsmith** [comment]
These need to be set in the project data dictionary. Add a new section called "Error Stacking"
- UserNamespaces: A comma delimited list of the namespace names that your applications code belongs to. If this value is set, only methods inside of these namespaces will be considered as stacking targets.
- CommonMethods: A comma delimited list of common method names that should not be used as stacking targets. This is useful when your code contains methods shared utility methods that throw a lot of errors.

**Comment by ejsmith** [comment]
Move Client Configuration to it's own tab.

**Comment by ejsmith** [comment]
Move delete bot data to the bottom

**Comment by niemyjski** [comment]
Should enable the option to specify bot user agents as well..

**Comment by ejsmith** [comment]
Yes, we should. That is a good idea. That should be in the client settings though so it will get sync'd to the clients.

**Comment by niemyjski** [comment]
No really. It's a server side setting too.

**Comment by niemyjski** [comment]
Just like data exclusions

**Comment by ejsmith** [comment]
It's client and server. Just like we send the data exclusions to the client and try to keep the client from event sending the data in the 1st place, we will do the same with user agents and try to keep ignored agents from ever being sent.
