### ISSUE TITLE
Improve email receipts and "view payment"

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless#186]
Email receipt really needs the organization name. Currently it only show the plan, amount, and that it was for Exceptionless

Both can use:
- billing contact name
- billing contact email
- VAT number / Tax ID
  and maybe postal address too (not sure if this is required)

Also send the invoice mails to the billing contact email details.

In the overview, maybe add Amount and Plan as columns.

**Comment by niemyjski** [comment]
I agree this needs to be done sooner than later. Do you have any advice on how we can make invoices more discoverable? I get asked on a weekly basis on "how do I find my invoices".

**Comment by srijken** [comment]
Admin -> Organizations is probably the way most people go to look for it. Maybe they don't realize they can click the organization name there? Maybe a shortcut link from the organizations page will help?

**Comment by niemyjski** [comment]
yeah, we can do that.

**Comment by niemyjski** [comment]
I'm merging this into #177 and we'll handle this scenario :)
