### ISSUE TITLE
how to Additional Data filtering?

### ISSUE THREAD

**Issue by lkh** [exceptionless/Exceptionless#207]
how to Additional Data filtering?

**Comment by lkh** [comment]
![image](https://cloud.githubusercontent.com/assets/534171/14166888/1314eb48-f752-11e5-82ca-6cf6b2856bad.png)

**Comment by niemyjski** [comment]
This Additional Data is part of the request info (`event.data['@request'].data`) and we are only indexing specific fields in the extended data. For now, if you want a specific field indexed and searchable you need to put the simple field in the events data dictionary via `EventBuilder.SetProperty("name", value)` or `event.data["name"] = value`; Then you can search by it by doing `data.name:value`. Does this work for you?

@ejsmith what do you think about this? We aren't indexing cookies, form fields or other things either and I'm not sure we should be either.

**Comment by ejsmith** [comment]
Yeah, I would recommend adding the thing you want to search by as a custom property on the event.  Then you can use data.myproperty:somevalue in the search box.
