### ISSUE TITLE
Selfhosting - Server URL Issue

### ISSUE THREAD

**Issue by manivannants** [exceptionless/Exceptionless#208]
Hi,
I have successfully hosted the Exceptionless in the IIS and was able to create projects.
The issue i am facing is submitting data from the client. The client is a winforms application.

If my hosted exception URL is **http://<IP Address>:50000**, what would be the server url the clients will be using?
<exceptionless apiKey="api_key" serverUrl ="http://<IP Address>:50000" enableSSL="false" />

Thanking in advance
Mani

**Comment by niemyjski** [comment]
You should set the `serverUrl` of your client to `http://localhost:50000` and everything will work :).

**Comment by niemyjski** [comment]
Please let me know if you have any questions.

**Comment by manivannants** [comment]
Well actually somehow the part of my url got truncated...
I have self hosted the Exceptionless in one of servers http://xxx.xxx.xxx.xxx:50000. When i browse this address, i get the login page and then able to setup projects and generate the API Key.

I am testing out with a windows forms app by forcing an exception and try to send it to exceptionless as below:
`ExceptionlessClient.Default.Configuration.ReadFromAppSettings();
  ExceptionlessClient.Default.Configuration.UseIsolatedStorage();
  ExceptionlessClient.Default.SubmitLog(ex.Message);
  ExceptionlessClient.Default.Configuration.UseFileLogger(@"C:\logs\Mylog.log", Exceptionless.Logging.LogLevel.Trace);

 Exceptionless.ExceptionlessClient.Default.Register();
 ex.ToExceptionless().Submit();`
  
In the app.config, 
`<exceptionless apiKey="api_key" serverUrl ="http://xxx.xxx.xxx.xxx:50000" enableSSL="false" />` 

The log reads as below:
DefaultEventQueue: Processing queue...
DefaultEventQueue: Sent 1 events to "http://xxx.xxx.xxx.xxx:50000".
DefaultEventQueue: Processing queue...
DefaultEventQueue: Sent 1 events to "http://xxx.xxx.xxx.xxx:50000".
DefaultEventQueue: Processing queue...
DefaultEventQueue: Processing queue...

But, i don't see any logs  captured in the hosted exceptionless. Your help would be very much appreciated. Do i need to open any port in the hosted server?

Thanks,
Mani

**Comment by manivannants** [comment]
Hi Blake,
Well actually somehow the part of my url got truncated...
I have self hosted the Exceptionless in one of servers http://xxx.xxx.xxx.xxx:50000. When i browse this address, i get the login page and then able to setup projects and generate the API Key.I am testing out with a windows forms app by forcing an exception and try to send it to exceptionless as below:
`ExceptionlessClient.Default.Configuration.ReadFromAppSettings();
ExceptionlessClient.Default.Configuration.UseIsolatedStorage();
ExceptionlessClient.Default.SubmitLog(ex.Message);
ExceptionlessClient.Default.Configuration.UseFileLogger(@"C:\logs\Mylog.log", Exceptionless.Logging.LogLevel.Trace);Exceptionless.ExceptionlessClient.Default.Register();
ex.ToExceptionless().Submit();`In the app.config, 
<exceptionless apiKey="api_key" serverUrl ="http://xxx.xxx.xxx.xxx:50000" enableSSL="false" />The log reads as below:
DefaultEventQueue: Processing queue...
DefaultEventQueue: Sent 1 events to "http://xxx.xxx.xxx.xxx:50000".
DefaultEventQueue: Processing queue...
DefaultEventQueue: Sent 1 events to "http://xxx.xxx.xxx.xxx:50000".
DefaultEventQueue: Processing queue...
DefaultEventQueue: Processing queue...But, i don't see any logs captured in the hosted exceptionless. Your help would be very much appreciated. Do i need to open any port in the hosted server?Thanks,
Mani

**Comment by niemyjski** [comment]
On a side note `enableSSL="false"` is deperecated and no longer supported so I'd remove it. What happens when you hit: `http://xxx.xxx.xxx.xxx:50000/api/v2/status`? 

Can you try submitting an event directly to the api via a get request (fix the link and click on it) and see if it's processed: `http://xxx.xxx.xxx.xxx:50000/api/v2/events/submit?access_token=YOUR_API_KEY&message=test`

**Comment by manivannants** [comment]
Hi,

I get the below message when i run  http://xxx.xxx.xxx.xxx:50000/api/v2/status:

{
  "message": "All Systems Check",
  "version": "3.3.2327 4cf70f24fd",
  "website_mode": "Production",
  "machine_name": "WIN-Q5IHVOCKBF4"
}


Also when i try to submit the event thru the below link [fixed api and ip address]
 http://xxx.xxx.xxx.xxx:50000/api/v2/events/submit?access_token=YOUR_API_KEY&message=test

I get a blank screen but still don't see that message in hosted exceptionless.

Regards,
Mani
--------------------------------------------
On Sun, 4/3/16, Blake Niemyjski <notifications@github.com> wrote:

 Subject: Re: [exceptionless/Exceptionless] Selfhosting - Server URL Issue (#208)
 To: "exceptionless/Exceptionless" <Exceptionless@noreply.github.com>
 Cc: "manivannants" <manivannants@yahoo.com>
 Date: Sunday, April 3, 2016, 8:05 PM
 
 On a side note
 enableSSL="false" is deperecated and
 no longer supported so I'd remove it. What happens when
 you hit:
 http://xxx.xxx.xxx.xxx:50000/api/v2/status?
 
 
 Can you try submitting an event directly to the api via a
 get request (fix the link and click on it) and see if
 it's processed:
 http://xxx.xxx.xxx.xxx:50000/api/v2/events/submit?access_token=YOUR_API_KEY&message=test
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by niemyjski** [comment]
Could you please join our gitter room: https://gitter.im/exceptionless/Discuss and we'll set up a meeting time to where I can take a look at this over team viewer if that works for you? Also could you ensure this machine has .net 4.6.1 installed as well as all windows updates.

**Comment by niemyjski** [comment]
Were you able to get this working?
