### ISSUE TITLE
Integrated authentication for self-hosting

### ISSUE THREAD

**Issue by bsimser** [exceptionless/Exceptionless#21]
Not an issue but a question (or request). Rather than service provider or user name/password is there a future for an integrated authentication version. Running on IIS we know who the user is internally so would be nice to not have to ask the user to log in. I'm sure a couple of hours I can create a fork with this option but just wondering if there are any plans to do this in master? Also does the system try to reach out (for example to https://collector.exceptionless.com) at all from behind the firewall? Thanks.

**Comment by adamzolotarev** [comment]
I'm guessing Windows Authentication hasn't been implemented yet. Just wondering, since the issue has been closed, but I don't see anything in the referenced commit related to Windows authentication.

**Comment by niemyjski** [comment]
It has not been implemented. @bsimser have you come to a solution for this?

**Comment by bsimser** [comment]
@niemyjski I'll pull out my old code which is v1 and update it for v3 and submit a PR with it. There were a few changes I had to do but I think the providers have got cleaner since I built my version.

**Comment by niemyjski** [comment]
Thanks! Yeah, we've made a ton of improvements/cleanup since v1.

**Comment by adamzolotarev** [comment]
Thank you! We wanted to use Windows authentication for self-hosting as well.

**Comment by niemyjski** [comment]
@bsimser would you mind submitting an updated pull request for this.
