### ISSUE TITLE
405 Method Not Allowed during signup/login

### ISSUE THREAD

**Issue by haliphax** [exceptionless/Exceptionless#210]
I'm installing a self hosted instance of Exceptionless, and it's broken from the get-go. I am running Windows Server 2012 R2 with IIS 8.5+ and Java 1.8+. ElasticSearch is installed and functional, .NET 4.6.1 has been installed, and ASP.NET and Static Content have been enabled in IIS. This is on a brand new server that does not have any other applications installed on it.

When you use the signup form, it is apparently sending a POST request to index.html, which IIS will block by default, since static resources do not generally accept anything other than GET. This results in a 405 error.

I can't find anything in the (sparse) self-hosted documentation detailing any installation/configuration step I've missed. Help! :(

**Comment by niemyjski** [comment]
Does your server have all windows updates and has been rebooted since installing them? Have you installed the yml file for elastic search? Can you please join our gitter channel and I'll help you to setup and configure exceptionless :). https://gitter.im/exceptionless/Discuss I'm going to close this as I'll help you via remote meeting.

**Comment by niemyjski** [comment]
@haliphax Would you be able to meet up?

**Comment by haliphax** [comment]
I fixed it by opening the *Modules* in IIS Manager for the newly-created site and using *Revert to Parent*. Everything suddenly started working. Strange thing is, I didn't change any of the module settings to begin with. :( At any rate, I'm creating a project and playing with it now!

**Comment by niemyjski** [comment]
That's weird. Please let us know if you have any questions or feedback

**Comment by haliphax** [comment]
Well, it's not sending events (or not catching them). I'll jump in gitter momentarily.
