### ISSUE TITLE
Smarter monthly throttling

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#212]
Current throttling calculation:
(total monthly events / hours in month) * 10

New throttling calculation:
(Events left in month / hours left in month) * 10

This would keep us from throttling accounts at the end of the month that haven't used a lot of their plan up. People feel cheated when we throttle and they still have a lot of events left in the month.

We can potentially calculate this rate once a day for each org depending on how expensive it is to calculate.

**Comment by niemyjski** [comment]
Merged into #112
