### ISSUE TITLE
Ignore exceptions based on type

### ISSUE THREAD

**Issue by ahmettaha** [exceptionless/Exceptionless#215]
Is it possible to add exception types to settings on the admin panel, so those types of exceptions are not calculated towards the quota.

**Comment by niemyjski** [comment]
@ejsmith what if we had a plugin that allowed you to ignore exceptions based on exception type. Like `System.OperationCanceledException` and even supported wild cards. That way if you have an exception totally blowing up you could ignore it in project settings until you fixed it.

It would be a stop gap. The negative is that it would potentially block you from seeing other valid exceptions.

**Comment by ejsmith** [comment]
Yeah, I think that would be nice.

**Comment by niemyjski** [comment]
This functionality is currently being tested and will be released next week with new clients depending on how dog fooding goes. This will be controlled short term by adding a project configuration setting key `@@error:System.OperationCanceledException` with a value of `false`. You can control any event type even with wild cards..

**key:** `@@feature:*` **value:** `false` (Turns off the submission of all feature usages)
**key:** `@@log:*` **value:** `Info` (Sets the min log level to info)
