### ISSUE TITLE
User account not persisted

### ISSUE THREAD

**Issue by rushfrisby** [exceptionless/Exceptionless#217]
What permissions do I need on my folders if I am self hosting? When I first go to the app and create an account it seems to be created, it lets me in to create an organization and project, but then if I close the browser and go back to the app it doesn't let me log in and I can create the same user account again, afterwhich the organization and projects are gone as well.

**Comment by rushfrisby** [comment]
Okay I guess i needed to fix the email config. I get the account verification email now, but it doesn;t work. The link goes to http://server/account/verify?token=token which gives me a 404. If I stick a # in there... http://server/#/account/verify?token=token it brings up the site, but then I get a red box saying there was an error verifying the account. Where can I check what the error is?

**Comment by niemyjski** [comment]
@rushfrisby When I've seen this in the past it's been two things: 
1. Invalid elasticsearch yaml config (are you using our config settings)
2. Does your server have .NET 4.6.1 installed and all windows updates + server reboot after installing them?

Does either of these two things fix this issue? If not let me know and I'd be more than happy to meetup and take a look.

**Comment by rushfrisby** [comment]
I have 4.6.1 installed and I'm pretty sure I've got all of the latest windows updates-I used the most recent version of Win2012 R2 on Azure.

I used your yaml config except elasticsearch kept crashing a few seconds after starting the service. I'm using the windows version on the same box as exceptionless. This is what was in the log file:

> [2016-04-18 13:03:03,207][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings. 
> Dynamic scripts can be enabled for all languages and all operations by replacing `script.disable_dynamic: false` with `script.inline: on` and `script.indexed: on` in elasticsearch.yml
> 	at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:145)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> 	at <<<guice>>>
> 	at org.elasticsearch.node.Node.<init>(Node.java:213)
> 	at org.elasticsearch.node.Node.<init>(Node.java:140)
> 	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
> 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
> 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
> 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

After changing the settings to what was suggested elasticsearch stopped crashing.

**Comment by niemyjski** [comment]
Looks like you tried to install elastic search 2.0. We only currently support 1.7.5 until https://github.com/exceptionless/Exceptionless/pull/183 is merged in (probably won't be until elastic 5.1 is released this summer as they are adding external cluster reindexing which would make it much easier to upgrade from 1.7.5)

**Comment by rushfrisby** [comment]
I'll try that and let you know how it goes. Thanks!

**Comment by niemyjski** [comment]
No problem! we want to update the status page to add some checks for elastic configuration settings and version

**Comment by rushfrisby** [comment]
Working now! Thanks! Looking forward to start using exceptionless.

**Comment by niemyjski** [comment]
Awesome!! Thanks for the heads up!

**Comment by niemyjski** [comment]
@rushfrisby feel free to join us on slack https://slack.exceptionless.com/

**Comment by carloskarass** [comment]
@niemyjski  Hi i need your help, in my work we deploy Exceptionless in self hosting on Windows Server 2012 R2 and IIS 8 (Not Express edition), but we have a problem with login or sing up for users.

**Comment by niemyjski** [comment]
What version are you deploying? If you want to jump on slack, we can setup a meeting and I can take a look with you.

**Comment by carloskarass** [comment]
Hi Blake,

We try again today, it was a problem with SSL, now we can connect clients
to server, the problem now is client app, does not write log in the dash
board.

we really appreciate your assistance.

Regards.

2016-06-07 7:16 GMT-06:00 Blake Niemyjski <notifications@github.com>:

**Comment by niemyjski** [comment]
I'm not sure what you're saying. If clients are reporting to the server, are you having problems with the exceptionless User interface (spa app that talks to the server). If so are you getting an error in your browser?

**Comment by carloskarass** [comment]
@niemyjski,
We have the exceptionless app on windows Server 2012 R2 and we access to the dashboard from others PC inside the LAN of the company.

When the Client app crash and "send" the exception in the try-catch , really does not save in the database, obviously dont see in the dashboard.


![1](https://cloud.githubusercontent.com/assets/19782432/15867636/67fe3a90-2ca1-11e6-8363-465fe4d809bf.PNG)
![2](https://cloud.githubusercontent.com/assets/19782432/15867640/6cc35876-2ca1-11e6-9100-bf08ee1edc14.PNG)
![3](https://cloud.githubusercontent.com/assets/19782432/15867644/7452ebf6-2ca1-11e6-89f4-ea112289f144.PNG)
![4](https://cloud.githubusercontent.com/assets/19782432/15867647/75f9a6d4-2ca1-11e6-8393-58899a960ed9.PNG)
![5](https://cloud.githubusercontent.com/assets/19782432/15867650/76b62cb4-2ca1-11e6-9586-7659328dc49e.PNG)

**Comment by niemyjski** [comment]
That all looks good. Have you went through the trouble shooting section of the guide: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting

If you could go through those, can you send me the results of the 3rd step (what's displayed on the status page).

**Comment by carloskarass** [comment]
@niemyjski 
Hi Blake,

We checked the guide, and we don´t found any diferences.

The only diference is that we change our locahost  by IP address in the archives.

This is the screenshot of status.
![6](https://cloud.githubusercontent.com/assets/19782432/15900341/6b93f314-2d5c-11e6-8007-f80897226313.JPG)

**Comment by niemyjski** [comment]
Can you double check your configuration, in the screenshot you sent earlier the web.config had mode production and your mode on the status page is set to dev. Which means you could be pointing to the wrong server or updated the wrong web.config. Also are your using elastic search 1.7.3 with our elastic.yml settings?

**Comment by carloskarass** [comment]
@niemyjski 

We are using ElasticSearch 1.7.5, we changed a mode production and still not working.

**Comment by niemyjski** [comment]
That will work, I don't know without actually taking a look at it as it all looks fine. You could try submitting directly to the server with: `/api/v2/events/submit?access_token=YOURAPIKEY&message=test` and seeing if it appears in the dashboard, that's posting directly to the server.

**Comment by niemyjski** [comment]
If you can join https://slack.exceptionless.com/ we can discus it more and set up a meeting to take a look at it.
