### ISSUE TITLE
Verify Elasticsearch configuration on status page

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#218]
The app will fail without it and a lot of self hosters are running into this behavior:
- https://github.com/exceptionless/Exceptionless/issues/217
- https://github.com/exceptionless/Exceptionless/issues/210
- https://github.com/exceptionless/Exceptionless/issues/167

**Comment by laughinggoose** [comment]
I'm interested in working on this. Would the desired outcome be to just compare the ES configuration to the one that's in the setup or just look at specific configuration keys?

**Comment by niemyjski** [comment]
With 4.0.1 we no longer require plugins and no configuration is required out of the box. I do think it would be good to maybe use the nest api and ping the servers or something to see if it's responding.

**Comment by laughinggoose** [comment]
I think that's already happening here: 
https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Utility/SystemHealthChecker.cs#L45

I'm not sure what the nest api is though.

**Comment by niemyjski** [comment]
I think we should be good now, this issue should be closed. Nest is the name of the API for talking to elasticsearch in .NET :) Are you seeing issue where the status page doesn't reflect the status of elasticsearch?
