### ISSUE TITLE
Active Directory Auth support

### ISSUE THREAD

**Issue by laughinggoose** [exceptionless/Exceptionless#223]
When I set up our install of self-hosted Exceptionless, I hacked in some Active Directory authentication to replace user accounts in Exceptionless.

Can I work on contributing this? I would be starting mostly from scratch because my changes were quick and applied to a much older version. Are there any roadblocks that I should keep in mind?

**Comment by niemyjski** [comment]
I'm not aware of any roadblocks and we would welcome a pull request for this! Please feel free to join our slack room: http://slack.exceptionless.com

**Comment by niemyjski** [comment]
I'm going to close this for now (to keep the issues clean), but we would love a pull request for this. I hope to talk to you more about this.

**Comment by niemyjski** [comment]
so if we had a server side config that said all logins will be active directory based... it could make things really simple https://www.linkedin.com/pulse/20140321182530-86053522-email-address-login-in-active-directory you can tell active directory to make a login alias that’s the actual email address. 

Then we don’t have to change anything anywhere except for marking them as read only and not allowing them to change there email address or maybe we allow you to change it cause your domain login could change. 

Then we look at the config setting to see if it’s a domain user and we add a check to see if it’s enabled after we get the user and it exists to see if there domain login is valid and on signup we check that setting and see if they are a valid domain user and it’s valid. We wouldn't need to change much work flow with this change :) we could also mark them as verified.

**Comment by niemyjski** [comment]
We still require signin via email address which can be supported via ad.

What happens is we add a new property for AD login, if that is set the only login / signup that is supported is via ad.

## Login
Right after we get the user and verify it's not null. We check to see if the ad settings is true, if it is, then we look up the user and see if they are valid, we also verify them if they are not verified. We reject if they are not valid or don't exist in active directory. This will not handle account creation..

## Signup

We check the ad setting and query the account for to see if it's valid and exists, if it doesn't we return immediately and don't create any user accounts. If it does, we create the account using everything on the signup model. 

It won't matter if you change your password later as we will be always checking the ad setting and verifying you that way.

**Comment by tekmaven** [comment]
I don't think LDAP/AD is the way to go.  It's better to support AD via ADFS, which I feel will integrate better into the existing Exceptionless stack. [ADFS supports OAuth 2.0](https://blogs.technet.microsoft.com/maheshu/2015/04/28/oauth-2-0-support-in-adfs-on-windows-server-2012-r2/).  It would be great if this could be offered as an SSO solution for customers on the hosted solution.  This could pave the way to support other services like Azure Active Directory for customers.  This would need to be configured on the account level.

**Comment by niemyjski** [comment]
@tekmaven while I agree with you 100% I think we need to support this short term and work towards ADFS as it would be really nice to have and support a generic solution. In the mean time AD support has been tested and merged in.
