### ISSUE TITLE
Problem with Turkish culture

### ISSUE THREAD

**Issue by muhammetsahin** [exceptionless/Exceptionless#228]
Hi,

I want to setup exceptionless on my machine. My machine culture is Turkish. And i got error with new project 

`{
   "took": 8,
   "timed_out": false,
   "_shards": {
      "total": 10,
      "successful": 10,
      "failed": 0
   },
   "hits": {
      "total": 5,
      "max_score": 1,
      "hits": [
         {
            "_index": "organizations",
            "_type": "project",
            "_id": "5730b170a714ca3c24feb362",
            "_score": 1,
            "_source": {
               "ıd": "5730b170a714ca3c24feb362",
               "organization_ıd": "5730b16fa714ca3c24feb361",
               "name": "Bayinet",
               "ıs_configured": false,
               "configuration": {
                  "version": 0,
                  "settings": {
                     "@@UserAgentBotPatterns": "*bot*,*crawler*,*spider*,*aolbuild*,*teoma*,*yahoo*"
                  }
               },
               "notification_settings": {
                  "5730b15ba714ca3c24feb360": {
                     "send_daily_summary": true,
                     "report_new_errors": true,
                     "report_critical_errors": true,
                     "report_event_regressions": true,
                     "report_new_events": false,
                     "report_critical_events": false
                  }
               },
               "delete_bot_data_enabled": true,
               "next_summary_end_of_day_ticks": 635984388000000000,
               "created_utc": "2016-05-09T15:49:04.1535252Z",
               "modified_utc": "2016-05-09T15:49:04.1535252Z"
            }
         },
         {
            "_index": "organizations",
            "_type": "organization",
            "_id": "5730b16fa714ca3c24feb361",
            "_score": 1,
            "_source": {
               "ıd": "5730b16fa714ca3c24feb361",
               "name": "Penta",
               "plan_ıd": "EX_UNLIMITED",
               "plan_name": "Unlimited",
               "plan_description": "Unlimited",
               "billing_change_date": "2016-05-09T18:49:03.8720377+03:00",
               "billing_changed_by_user_ıd": "5730b15ba714ca3c24feb360",
               "billing_status": 0,
               "billing_price": 0,
               "max_events_per_month": -1,
               "bonus_events_per_month": 0,
               "retention_days": -1,
               "ıs_suspended": false,
               "has_premium_features": true,
               "max_users": -1,
               "max_projects": -1,
               "created_utc": "2016-05-09T15:49:03.8720377Z",
               "modified_utc": "2016-05-09T15:49:03.8730422Z"
            }
         },
         {
            "_index": "organizations",
            "_type": "project",
            "_id": "5730b1dda714ca3c24feb363",
            "_score": 1,
            "_source": {
               "ıd": "5730b1dda714ca3c24feb363",
               "organization_ıd": "5730b16fa714ca3c24feb361",
               "name": "test",
               "ıs_configured": false,
               "configuration": {
                  "version": 0,
                  "settings": {
                     "@@UserAgentBotPatterns": "*bot*,*crawler*,*spider*,*aolbuild*,*teoma*,*yahoo*"
                  }
               },
               "notification_settings": {
                  "5730b15ba714ca3c24feb360": {
                     "send_daily_summary": true,
                     "report_new_errors": true,
                     "report_critical_errors": true,
                     "report_event_regressions": true,
                     "report_new_events": false,
                     "report_critical_events": false
                  }
               },
               "delete_bot_data_enabled": true,
               "next_summary_end_of_day_ticks": 635984388000000000,
               "created_utc": "2016-05-09T15:50:53.9158059Z",
               "modified_utc": "2016-05-09T15:50:53.9158059Z"
            }
         },
         {
            "_index": "organizations",
            "_type": "user",
            "_id": "5730b15ba714ca3c24feb360",
            "_score": 1,
            "_source": {
               "ıd": "5730b15ba714ca3c24feb360",
               "organization_ıds": [
                  "5730b16fa714ca3c24feb361"
               ],
               "password": "X1f6dQrpK7jjseHT3SCe5rMJLeENw271K68q/+6lrIg=",
               "salt": "PyX9Hxgj6Ni0MA3m",
               "password_reset_token_expiration": "0001-01-01T00:00:00",
               "full_name": "Muhammet",
               "email_address": "muhammet.sahin@net-bt.com.tr",
               "email_notifications_enabled": true,
               "ıs_email_address_verified": false,
               "verify_email_address_token": "ORkvjB4qgVRQdGpBAB4vZMXCmbs7fKgULcTRkaX6",
               "verify_email_address_token_expiration": "2016-05-10T15:48:43.4797486Z",
               "ıs_active": true,
               "roles": [
                  "client",
                  "user",
                  "global"
               ],
               "created_utc": "2016-05-09T15:48:43.5509008Z",
               "modified_utc": "2016-05-09T15:49:03.9827516Z"
            }
         },
         {
            "_index": "organizations",
            "_type": "token",
            "_id": "Yo4AWahJJCOCKCSeKyz62jHyC9eEga0oQjlaffH2",
            "_score": 1,
            "_source": {
               "**ı**d": "Yo4AWahJJCOCKCSeKyz62jHyC9eEga0oQjlaffH2",
               "user_**ı**d": "5730b15ba714ca3c24feb360",
               "type": 1,
               "created_by": "5730b15ba714ca3c24feb360",
               "created_utc": "2016-05-09T15:48:48.5437955Z",
               "modified_utc": "2016-05-09T15:48:48.5437955Z"
            }
         }
      ]
   }
}`

I think the problem caused by 'ı' it has to be 'i' not 'ı'

Thanks @niemyjski for your help.

**Comment by niemyjski** [comment]
There is some kind of bug here. I think it has to do with deserialization but it doesn't really make sense because both users and organizations work and they have the turkish characters but returning projects fail with no error messages.

**Comment by niemyjski** [comment]
@muhammetsahin is there any chance you could step through the `/api/v2/projects?access_token=YOUR_USER_TOKEN_STORED_IN_BROWSER_SESSION_DATA` on a turkish based machine under a debugger and see exactly what is going on here. We try to handle strings properly but looks like someplace it's not handling it correctly.

**Comment by muhammetsahin** [comment]
![image](https://cloud.githubusercontent.com/assets/2045788/15136943/c4bfa7ec-168e-11e6-9107-14640ccee36e.png)

**Comment by niemyjski** [comment]
@muhammetsahin, yes, one would need to pull down master and run it (the server) under a debugger. Then navigate to [http://local-app.exceptionless.io](http://local-app.exceptionless.io) which points to your local server and create a new project. Then hit the end point above (as shown in your screenshot) and step through it.

**Comment by muhammetsahin** [comment]
I solved by myself. 

I've changed some method in StringExtensions class

` public static string ToLowerUnderscoredWords(this string value)
        {
            var builder = new StringBuilder(value.Length + 10);
            for (int index = 0; index < value.Length; index++)
            {
                char c = value[index];
                if (Char.IsUpper(c))
                {
                    if (index > 0 && value[index - 1] != '_')
                        builder.Append('_');

                    var str = Char.ToLower(c);
                    //Changed here
                    if (str.Equals('ı'))
                        str = 'i';

                    builder.Append(str);
                }
                else
                {
                    builder.Append(c);
                }
            }

            return builder.ToString();
        }`

` private static bool CheckForMatch(string pattern, string value, bool ignoreCase = true)
        {
            bool startsWithWildcard = pattern.StartsWith("*");
            if (startsWithWildcard)
                pattern = pattern.Substring(1);

            bool endsWithWildcard = pattern.EndsWith("*");
            if (endsWithWildcard)
                pattern = pattern.Substring(0, pattern.Length - 1);

            if (ignoreCase)
            {
                pattern = pattern.ToLower();

                pattern = convertToTurkish(pattern);
            }

            if (startsWithWildcard && endsWithWildcard)
                return value.Contains(pattern);

            if (startsWithWildcard)
                return value.EndsWith(pattern);

            if (endsWithWildcard)
                return value.StartsWith(pattern);

            return value.Equals(pattern);
        }

        public static string convertToTurkish(string val)
        {
            val = val.Replace('ı', 'i');

            return val;
        }`


`  public static string ToLowerFiltered(this string value, char[] charsToRemove)
        {
            var builder = new StringBuilder(value.Length);

            for (int index = 0; index < value.Length; index++)
            {
                char c = value[index];
                if (Char.IsUpper(c))
                {
                    c = Char.ToLower(c);

                    if (c.Equals('ı'))
                        c = 'i';
                }
                bool includeChar = true;
                for (int i = 0; i < charsToRemove.Length; i++)
                {
                    if (charsToRemove[i] == c)
                    {
                        includeChar = false;
                        break;
                    }
                }

                if (includeChar)
                    builder.Append(c);
            }

            return builder.ToString();
        }`


`
        private static string ResolveEntityNotAngleAmp(Match matchToProcess)
        {
            string str;
            if (matchToProcess.Groups["decimal"].Success)
                str = Convert.ToChar(Convert.ToInt32(matchToProcess.Groups["decimal"].Value)).ToString();
            else if (matchToProcess.Groups["hex"].Success)
                str = Convert.ToChar(HexToInt(matchToProcess.Groups["hex"].Value)).ToString();
            else if (matchToProcess.Groups["html"].Success)
            {
                string entity = matchToProcess.Groups["html"].Value;
                switch (convertToTurkish(entity.ToLower()))
                {
                    case "lt":
                    case "gt":
                    case "amp":
                        str = "&" + entity + ";";
                        break;
                    default:
                        str = EntityLookup(entity);
                        break;
                }
            }
            else
                str = "X";
            return str;
        }`


And special thanks @ersoyvatansever

**Comment by niemyjski** [comment]
thanks for the heads up on this, I'm glad you were able to get this resolved locally.

**Comment by barankaynak** [comment]
The problem is still going on.

**Comment by niemyjski** [comment]
@barankaynak @muhammetsahin  Does this need to be changed to Char.ToLowerInvariant()?
