### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by rushfrisby** [exceptionless/Exceptionless#234]
I am self hosting. I created an account but am getting an error logging in. In the lower right hand corner there is a red message box saying:

> An error occurred while logging in. Please contact support for more information.

In case I was using the wrong password I initiated the password reset process, got the email, click the link, and reset my password... after which I still was not able to login.

Other users can log in fine.

Any ideas as to what I can do to fix this?

**Comment by niemyjski** [comment]
Try again in a half hour, we have security that kicks in after a few failed logins and it doesn't matter what you do, it won't be reset. If however, you do a password reset with a valid token we may want to lift this. Did that fix it?

**Comment by niemyjski** [comment]
Were you able to resolve this issue? Please let me know if you are still running into this behavior and we'll reopen this issue
