### ISSUE TITLE
New release with heartbeat API

### ISSUE THREAD

**Issue by baalazamon** [exceptionless/Exceptionless#236]
Current JavaScript Exceptionless client is calling hearbeat api that doesn't exist in release 3.3.2327. 

Is it possible to publish new version of Exceptionless that is compatible with JavaScript client?

**Comment by niemyjski** [comment]
@baalazamon yes, we will be pushing a new version probably next week. We are working on getting a beta out of the .net client first

**Comment by niemyjski** [comment]
In the mean time you could pull down master and run the build script or compile the solution and deploy the artifacts. We'll work on getting a release out there. Please feel free to join our slack channel.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless/releases/tag/v3.4.0 has been released
