### ISSUE TITLE
Ability to configure daily notification times

### ISSUE THREAD

**Issue by ericbrunner** [exceptionless/Exceptionless#245]
Hey,
Because the Daily Summary Emails aren't sent to that time we want and it is very hard  to configure (without Blake impossible for us) , it would be great when the scheduling time (the time when we want to received the emails for the Daily Summary) can be set in the User Setting somewhere in the Notification Tab like the mockup screenshot below:

You must also be able to set the local timezone.

Daily Summary Mockup
![dailysummary](https://cloud.githubusercontent.com/assets/6480047/17782670/fe7ebe02-6574-11e6-9363-15b6970cc92f.png)

thanks,
Eric

**Comment by niemyjski** [comment]
I think that it would be best to go off utc time and have a nice localized time ui where you pick the time you want it to run (offset from utc).

**Comment by ericbrunner** [comment]
Good

**Comment by caesay** [comment]
@niemyjski I can probably do this change if it'd help, seems like something simple to get my feet wet. Should the email times be specified at a user level or at a project/organization level? Seems like what the op really wants is for everyone on the team to receive a summary just before the work day starts for example in which case it doesn't really need to be a user setting.

**Comment by niemyjski** [comment]
@caesay I think this needs to be merged into https://github.com/exceptionless/Exceptionless/issues/177. We need to do a round of work and have this configurable and smarter. I think we'd start by having the Olsen time on the project or org (but what about multiple users in different timezones as part of a single org?)

I'm going to merge this into #177 . If you want we can talk on slack, there are some very low hanging fruit on #177 like adding tags and stack trace to emails :)
