### ISSUE TITLE
Azure Resource Template

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#247]
- Elasticsearch cluster
  - https://github.com/elastic/azure-marketplace
  - Remove Shield and other commercial plugins
  - Remove phone home
- Redis
- Api web app
  - WEBJOBS_STOPPED
- App web app
- Collector / Jobs web app
- Storage account
- Api and Collector go into same vnet as ES
- Refactor config to set defaults and reduce number of config settings
- Needs to support a prefix to allow creating multiple installs in a single Azure subscription
- Bonus: Setup CDN for app site

**Comment by niemyjski** [comment]
I'm going to close this until we decide we are doing this.
