### ISSUE TITLE
is no work in .NET 4.0?

### ISSUE THREAD

**Issue by niunan** [exceptionless/Exceptionless#249]
is no work in .NET 4.0?

**Comment by niemyjski** [comment]
Hello,

The v4 client version only supports .NET 4.5 and above. We did this for many reasons (easier to use async and simplifies a bunch of code while making .net standard support much easier). With that said, we will continue to support all versions of our clients. Any version prior to v4 supports .NET 4.0, as such please install the latest v3.5 client from nuget. If you need any help, please let me know!

For example, if you wanted to install the console app package, you would navigate to the older version and install via the command line or use the version selector in vs when installing the package: 

https://www.nuget.org/packages/Exceptionless/3.5.1738
