### ISSUE TITLE
how to set the RedisConnectionString?

### ISSUE THREAD

**Issue by RobbyHo** [exceptionless/Exceptionless#250]
as title..

**Comment by niemyjski** [comment]
Depending on where you are hosting, you'd need to set it to something like this: `localhost:6379,abortConnect=false` as shown here: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#redis

Please let us know if you have any questions.

**Comment by RobbyHo** [comment]
hi~ @niemyjski  thanks for your answer! I set RedisConnectionString follow https://gist.github.com/niemyjski/8aaf80196c00d6880cd9, but the web throw a exception:Invalid URI: this URI is NULL

**Comment by RobbyHo** [comment]
my redis server is avaliable,that run on CentOS at version 3.2.3

**Comment by niemyjski** [comment]
What is your actual connection string (I've updated that gist). If you are not on azure, you should leave out the usesll part. And if you have no password skip that too :). Can you paste the full stack trace?

**Comment by RobbyHo** [comment]
![image](https://cloud.githubusercontent.com/assets/8401517/18612083/76a26bca-7d82-11e6-87d3-88d1179b63b0.png)


the redis run on my local VM(hyper-v),password is required

![image](https://cloud.githubusercontent.com/assets/8401517/18612081/53521396-7d82-11e6-9c82-c0c6bd1032d7.png)

tks!

**Comment by niemyjski** [comment]
That redis connection string is fine. The error you are getting (via stack trace) is that your elastic search connection string isn't set. It's required and needs to be set to point to your elastic search instance.

**Comment by RobbyHo** [comment]
But, I want to use redis storage,the elastic search connection string is required?

**Comment by niemyjski** [comment]
We use Elastic Storage for persistent storage (required) and redis is optional for a distributed cache (which is required if you are going to run exceptionless (server) on multiple servers

**Comment by RobbyHo** [comment]
oh~I understand finally...My exceptionless is run successfully,thanks very much!
