### ISSUE TITLE
Different Exceptions are appearing together in the same Stack

### ISSUE THREAD

**Issue by jdtaylor91** [exceptionless/Exceptionless#251]
We are currently seeing a case where different errors are appearing together in the same stack, meaning we are unable to mark them as fixed individually.

These exceptions are all client-side exceptions that are caught by window.onerror (in javascript), the error is then passed up to the server and we create a new exception by passing in the exception message from the client as a string, i.e.

`new Exception(message);`

After that we are submitting the exception to Exceptionless as normal, but all of our client side Exceptions of this kind are being stacked together.

How do you determine which exceptions are similar? When we create an Exception in the fashion above should we be specifying something extra to ensure that all exceptions fashioned in that way aren't grouped together?

**Comment by niemyjski** [comment]
So just to follow:
1. You are not using our JavaScript client and are manually sending the javascript errors to the server for you to process. You are then wrapping this in a new .net exception object and submitting the error.

We take a look at the exception type and stack trace for generating a stack. So if you are creating a new exception instance, they will all be stacked the same as expected. You can define a manual stacking key as per the docs. If you can provide me with more info, I can give you a more detailed answer.

**Comment by jdtaylor91** [comment]
Thank you for the response, i wasn't aware of the manual stacking key functionality, we will look into incorporating that.

**Comment by niemyjski** [comment]
No problem, if you have any questions please let us know. I'd recommend using our js client as it is full featured and will handle this.
