### ISSUE TITLE
Would I install Exceptionless at linux system with mono?

### ISSUE THREAD

**Issue by Neil-Huang** [exceptionless/Exceptionless#257]

**Comment by niemyjski** [comment]
Yes, the Exceptionless package should run without any issues. It supports PCL profile, .NET Standard 1.2 and .NET 4.5. Our old client which supported .NET 4.0 and PCL Profile ran without issue. I haven't personally tested the new one on mono but it does run really well on OSX under .NET Core :). If you run into any issues please comment on this issue and we will reopen it!
