### ISSUE TITLE
AppElasticConfiguration  ConfigureIndexesAsync error?

### ISSUE THREAD

**Issue by lanfengqi** [exceptionless/Exceptionless#258]
AppElasticConfiguration.ConfigureIndexesAsync() Error:
[rest.suppressed          ] /logstash Params: {index=logstash}
MapperParsingException[mapping [logevent]]; nested: MapperParsingException[Mapping definition for [id] has unsupported parameters:  [index_name : id]];

elasticsearch 2.0/2.4/5.0

**Comment by niemyjski** [comment]
Did you mean to log this here: https://github.com/exceptionless/Foundatio.Repositories ? What are your steps to reproduce? The repositories master branch and 2.x package only supports elastic 1.7.5 but the 5.0 nuget package supports elastic 5.

Could you please create a new issue there and let me know everything I need to reproduce or create a pr with configuration or test that reproduces this behavior. That would be a huge help.
