### ISSUE TITLE
Today I receive 20000+ same summary email from exceptionless？

### ISSUE THREAD

**Issue by capqueen** [exceptionless/Exceptionless#259]
Today I receive 20000+ same summary email from exceptionless, it's all about
`Summary for 2016/11/14`
I can not stop it so I stop iis. 
Now how can i clear this problem? where to found the email job and to clear it?
May this is a bug or some setting wrong by myself? but other day's summary is right.

please help me,thanks.

**Comment by capqueen** [comment]
I set elasticsearch config script.disable_dynamic: true yesterday.
because I found my ubuntu server hacked by someone use elasticsearch's dynamic script.
Mybe it cause this problem?

**Comment by niemyjski** [comment]
Are you running jobs in process or out of process? Are you self hosting the latest release?

The way the job runs is that it emails and then immediately updates the project and increments the next send time.

You need dynamic scripting enabled for exceptionless to work. Your elasticsearch server should be locked down and not accessible outside of your network.

**Comment by capqueen** [comment]
Thanks, I clear the redis cache,and enable dynamic scripting,it all right.also I locked down my el server.

**Comment by niemyjski** [comment]
Thanks for the update
