### ISSUE TITLE
How to set a Project to keep a certain time Exceptionless data

### ISSUE THREAD

**Issue by geffzhang** [exceptionless/Exceptionless#260]
How to set a Project to keep a certain time Exceptionless data, such as a week, other data is deleted automatically, or automatically stored elsewhere

**Comment by niemyjski** [comment]
Are you looking to have retention based on a specific project other than on the organization level?

**Comment by geffzhang** [comment]
Do you have based on organization-level settings

**Comment by geffzhang** [comment]
Find a solution ：https://github.com/exceptionless/Exceptionless/issues/139
