### ISSUE TITLE
Maybe UI shows by mistake

### ISSUE THREAD

**Issue by wsrf16** [exceptionless/Exceptionless#268]
![image](https://cloud.githubusercontent.com/assets/11867768/22639641/f02b82e4-ec89-11e6-8f27-76bd856c6447.png)
![image](https://cloud.githubusercontent.com/assets/11867768/22639681/30118390-ec8a-11e6-86d1-a0b8d6c8f170.png)
![image](https://cloud.githubusercontent.com/assets/11867768/22640184/7f7cdf90-ec8c-11e6-8542-11d2349ffb77.png)

It show me "Total=3".Actually I have deleted it.It is empty after I entered "Total" item.

**Comment by niemyjski** [comment]
Can you reproduce this pretty consistently? Is this happening on a local hosted instance or on our hosted service? If it's happening locally do you have web sockets enabled (in iis config).  Items are queued for deletion and notifications are delayed by a second or two, so there will be some lag here. Can you please let me know the best way to reproduce this consistently.

**Comment by wsrf16** [comment]
It happened on local hosted instance.The fake messages has disappeared in this morning.It seems to work normally from now on.Sorry~I can not reproduce it now.

**Comment by niemyjski** [comment]
@wsrf16 that's okay, if you see this behavior again please let us know and I'll help troubleshooting it with you. We'd love to hear any feedback that you may have!

**Comment by wsrf16** [comment]
It happened on local hosted instance.The fake messages has disappeared after I closed the bowser.It seems to work normally from now on.Sorry~I can not reproduce it now.
I wonder where the summary information of log message be saved(eg. the number of total,unique,new,per hour).Is it cached in local cookies?This messages should be deleted successfully and I have could not found them in elasticsearch.But they are remain in the "dashboard" before I closed the browser.

**Comment by niemyjski** [comment]
nope, it's not cached locally at all. We use web sockets / long polling to update it (maybe the connection failed or was reconnecting while the data had changed). If refreshing the page fixed it I'm betting this was the cause. Do you remember if there were any errors in your console (if you looked)?
