### ISSUE TITLE
Constructing specific elastic query causes out-of-memory

### ISSUE THREAD

**Issue by caesay** [exceptionless/Exceptionless#269]
Hi,

I ran into a case where exceptionless was behaving badly on my production server - it would randomly after requesting certain pages spike up to 5GB's of memory usage and max out a single CPU core. (the page would never end up getting displayed). Once one of these bad pages has been hit, exceptionless refuses to respond again until the app pool process has been restarted. 

Initially I thought it might be a problem with the ES cluster, but there are only ~500 events in total on this entire cluster. Also, I can retrieve the entire dataset of all indexes from the cluster using another tool in just milliseconds and after spot checking everything seems to be working just fine.

To test exceptionless, I cloned the latest code (as of today - 2/6/2017) API and UI projects and wired it up to the same production elastic nodes, and sure enough - when viewing certain pages i get an out of memory exception in [`DataObjectConverter.cs L#113`](https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Serialization/DataObjectConverter.cs#L113). It only happens on the same specific log pages.

I stepped through from the event controller into the repository where it calls `FindAsync`, here [`EventRepository.cs L#126`](https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Repositories/EventRepository.cs#L126) but after that it starts going into some recursive elasticsearch code that i can't follow and goes out of memory slightly later (never returns from there).

I appreciate that this may be data-specific but I can't release access to this data because of certain data compliance reasons. That said, I'd like to help you guys track this down if I can, so please let me know what next steps you'd like me to take and any tests you'd like me to do.

**Comment by niemyjski** [comment]
I made some improvements to this in https://github.com/exceptionless/Exceptionless/commit/b397a5210181b10404e9d7bf927254950dc90d1f but it's still not fixed completely. The issue happens because `MaximumEventPostSize` was unbounded and so very large event posts could be submitted. We will eventually move our event parsing code to use stream based processing and that should fix this issue for good :). But in the mean time going forward MaximumEventPostSize will be set to a default of 1MB

**Comment by cmjacobs** [comment]
Just out of curiosity, if we know that we're not going to handling a lot of events but occasionally need to receive a large post (e.g., uploading a large log file), how much harm would come from increasing `MaximumEventPostSize` to a few MB (maybe as far as 10)

**Comment by niemyjski** [comment]
@cmjacobs It all depends on your server's available memory. Some work needs to be done on our end to enable the scenario where we can deserialize and process a stream of events. Currently events can be really compressed and when it's decompressed you can get out of memory errors. I'd recommend updating the setting and try it. It shouldn't be an issue

**Comment by cmjacobs** [comment]
@niemyjski I'll give it a shot. Thanks for the quick reply.
