### ISSUE TITLE
javascript client

### ISSUE THREAD

**Issue by luisrudge** [exceptionless/Exceptionless#27]
hey! I noticed a js client is on the roadmap. Is there any discussion around that?

**Comment by niemyjski** [comment]
I'm going to close this issue. We have started working on a JavaScript client but it's not ready yet. Status of the client can be found here (it will be committed once we do more work on it): https://github.com/exceptionless/Exceptionless.JavaScript

**Comment by niemyjski** [comment]
Please stay tuned to our javascript repo.. I'm making good progress and just added a bunch of tests as well as got it submitting a very basic event to our api :). Lots more work to do but we are getting closer!
