### ISSUE TITLE
Improved Aggregation of Errors

### ISSUE THREAD

**Issue by jakejgordon** [exceptionless/Exceptionless#271]
As a developer who is trying to see what distinct errors have recently happened in my application
I can be sure that each error in the Most Frequent panel really represents the same error
So that I don't accidentally ignore occurrences of different errors

See the below screenshot which has 43 "HttpException" errors that are actually mostly different errors under the covers:
![image](https://cloud.githubusercontent.com/assets/3045786/22692075/446c0b7c-ed0b-11e6-80f9-ae2169143b17.png)

When I drill into the error then i can see the recent occurrences are mostly different:

![image](https://cloud.githubusercontent.com/assets/3045786/22692092/5d38dca2-ed0b-11e6-9a0c-1ff41aa5fc45.png)

I'm not exactly sure how to solve this, but it's important to me as (I'm very lazy) I want to avoid having to drill through each error.

Yes, I know I should strive to get less errors :P

**Comment by niemyjski** [comment]
Are all of these being re thrown from an error handler with a new message? Do they all have the same stack trace? If they all have the same exact stack trace I'm not sure there is much we can do other then provide a custom stacking key?

**Comment by jakejgordon** [comment]
@niemyjski Good call -- this is probably the case. I'll try to check it out in the next few days/week and come back with more information.

**Comment by jakejgordon** [comment]
This issue was definitely on my end as I was rethrowing all exceptions and losing the inner exception. :)  Closing!
