### ISSUE TITLE
Need notification that messages are being hidden to reduce noise

### ISSUE THREAD

**Issue by edgarecayce** [exceptionless/Exceptionless#272]
I was doing some testing where I would log a bunch of debug messages.  I would see them show up in my Recent list, and then they would all disappear.  Thought I was going crazy.  Turns out they were being hidden by the Reduce Noise setting.  

I think this is all good, but it would help to 1) give a callout when that is happening to tell user what is up and how to configure 2) allow client IP exclusions to be set.

**Comment by niemyjski** [comment]
This is some great feedback, sorry I didn't reply sooner, I just saw this issue. We should show a banner in the app letting them know this is occurring :)

**Comment by niemyjski** [comment]
I'm merging this into #172
