### ISSUE TITLE
Ability to opt out of archiving post data

### ISSUE THREAD

**Issue by john-roland** [exceptionless/Exceptionless#275]
Hello,

We have a lot of space consumed on our EL server (self hosted), and the space is not released when we delete the project data.
After investigation, we found that there is a lot of folders and json files in the App_Data\storage folder.
Can you explain a bit what is used for ( the year/month/day folder hierarchy seems obvious, is it cache or something for stacks/events ?). Can we clean it up safely ?

note: we are not yet in EL 4.0, we have a lot of projects, and more than 5.5 millions events.

thank for your help,

John Roland

**Comment by niemyjski** [comment]
It's safe to delete the whole folder, we use it as archival so if we lose all backups we can replay all those events and recreate all events. We probably should look into adding a setting for this to discard them by default.

**Comment by john-roland** [comment]
ok, get it.
yes, on our side we will setup a job, cause, it's taking  a huge disk space (more than 5 millions json files there)

**Comment by niemyjski** [comment]
I'll make sure we add a setting and set it to discard by default.

**Comment by niemyjski** [comment]
This has been merged into master and will go into the next minor release! Thanks @laughinggoose 

If you need this sooner than later, we do have a ci feed you can pull the latest build from on appveyor just let me know if you need any assistance.
