### ISSUE TITLE
help on self hosting upgrade from 3.4 to 4.0

### ISSUE THREAD

**Issue by john-roland** [exceptionless/Exceptionless#279]
Hello guys,

I'm currently upgrading, and i've got a problem with the latest kibana script:

POST _reindex
{
"source": {
  "remote": {
    "host": "http://10.0.0.9:9200"
  },
  "index": "events-v1-*",
  "size": 200
},
"dest": {
  "index": "events-v1-error"
},
"script": {
  "lang": "painless",
  "inline": "ctx._index = 'events-v1-' + DateTimeFormatter.ofPattern('yyyy.MM.dd').format(OffsetDateTime.parse(ctx._source.date).toInstant().atZone(ZoneOffset.UTC)); if (ctx._source.updated_utc == null) { ctx._source.updated_utc = ctx._source.created_utc; } if (ctx._source.is_deleted == null) { ctx._source.is_deleted = false; } if (!ctx.containsKey('data') || !(ctx.data.containsKey('@error') || ctx.data.containsKey('@simple_error'))) return null;def types = [];def messages = [];def codes = [];def err = ctx.data.containsKey('@error') ? ctx.data['@error'] : ctx.data['@simple_error'];def curr = err;while (curr != null) { if (curr.containsKey('type'))  types.add(curr.type); if (curr.containsKey('message'))  messages.add(curr.message); if (curr.containsKey('code'))  codes.add(curr.code); curr = curr.inner;}if (ctx.error == null) ctx.error = new HashMap();ctx.error.type = types;ctx.error.message = messages;ctx.error.code = codes;"
}
}

I've got error messages like this one:

  "failures": [
    {
      "index": "events-v1-2016.09.06",
      "type": "events",
      "id": "57cecdef38c7390b08c3d718",
      "cause": {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "events-v1-2016.09.06",
        "index_uuid": "_na_",
        "index": "events-v1-2016.09.06"
      },
      "status": 404
    },

can you advise please ?

thank you

**Comment by niemyjski** [comment]
@john-roland Did you create the event index template (This step **Create Event Template so daily indexes can be created with the correct mappings:**)

**Comment by niemyjski** [comment]
@john-roland Did you create the event index template (This step **Create Event Template so daily indexes can be created with the correct mappings:**)

https://github.com/exceptionless/Exceptionless/wiki/Upgrading

```
PUT _template/events-v1
{
"template": "events-v1-*",
"settings": {
  "number_of_shards": 1,
  "number_of_replicas": 1,
  "analysis": {
    "analyzer": {
      "comma_whitespace": {
        "type": "pattern",
        "pattern": "[,\\s]+"
      },
      "email": {
        "type": "custom",
        "filter": [
          "email",
          "lowercase",
          "unique"
        ],
        "tokenizer": "keyword"
      },
      "version_index": {
        "type": "custom",
        "filter": [
          "version_pad1",
          "version_pad2",
          "version_pad3",
          "version_pad4",
          "version",
          "lowercase",
          "unique"
        ],
        "tokenizer": "whitespace"
      },
      "version_search": {
        "type": "custom",
        "filter": [
          "version_pad1",
          "version_pad2",
          "version_pad3",
          "version_pad4",
          "lowercase"
        ],
        "tokenizer": "whitespace"
      },
      "whitespace_lower": {
        "type": "custom",
        "filter": [
          "lowercase"
        ],
        "tokenizer": "whitespace"
      },
      "typename": {
        "type": "custom",
        "filter": [
          "typename",
          "lowercase",
          "unique"
        ],
        "tokenizer": "typename_hierarchy"
      },
      "standardplus": {
        "type": "custom",
        "filter": [
          "standard",
          "typename",
          "lowercase",
          "stop",
          "unique"
        ],
        "tokenizer": "comma_whitespace"
      }
    },
    "filter": {
      "email": {
        "type": "pattern_capture",
        "patterns": [
          "(\\w+)",
          "(\\p{L}+)",
          "(\\d+)",
          "(.+)@",
          "@(.+)"
        ]
      },
      "typename": {
        "type": "pattern_capture",
        "patterns": [
          "\\.(\\w+)",
          "([^\\()]+)"
        ]
      },
      "version": {
        "type": "pattern_capture",
        "patterns": [
          "^(\\d+)\\.",
          "^(\\d+\\.\\d+)",
          "^(\\d+\\.\\d+\\.\\d+)"
        ]
      },
      "version_pad1": {
        "type": "pattern_replace",
        "pattern": "(\\.|^)(\\d{1})(?=\\.|-|$)",
        "replacement": "$10000$2"
      },
      "version_pad2": {
        "type": "pattern_replace",
        "pattern": "(\\.|^)(\\d{2})(?=\\.|-|$)",
        "replacement": "$1000$2"
      },
      "version_pad3": {
        "type": "pattern_replace",
        "pattern": "(\\.|^)(\\d{3})(?=\\.|-|$)",
        "replacement": "$100$2"
      },
      "version_pad4": {
        "type": "pattern_replace",
        "pattern": "(\\.|^)(\\d{4})(?=\\.|-|$)",
        "replacement": "$10$2"
      }
    },
    "tokenizer": {
      "comma_whitespace": {
        "type": "pattern",
        "pattern": "[,\\s]+"
      },
      "typename_hierarchy": {
        "type": "path_hierarchy",
        "delimiter": "."
      }
    }
  }
},
"mappings": {
  "events": {
      "dynamic": "false",
      "include_in_all": false,
      "_all": {
        "analyzer": "standardplus",
        "search_analyzer": "whitespace_lower"
      },
      "_size": {
        "enabled": true
      },
      "dynamic_templates": [
        {
          "idx_reference": {
            "match": "*-r",
            "mapping": {
              "ignore_above": 256,
              "type": "keyword"
            }
          }
        }
      ],
      "properties": {
        "count": {
          "type": "integer"
        },
        "created_utc": {
          "type": "date"
        },
        "data": {
          "properties": {
            "@environment": {
              "properties": {
                "architecture": {
                  "type": "keyword"
                },
                "ip_address": {
                  "type": "text",
                  "index": false,
                  "copy_to": [
                    "ip"
                  ],
                  "include_in_all": true
                },
                "machine_name": {
                  "type": "text",
                  "boost": 1.1,
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  },
                  "include_in_all": true
                },
                "o_s_name": {
                  "type": "text",
                  "copy_to": [
                    "os"
                  ]
                }
              }
            },
            "@error": {
              "properties": {
                "data": {
                  "properties": {
                    "@target": {
                      "properties": {
                        "ExceptionType": {
                          "type": "text",
                          "index": false,
                          "copy_to": [
                            "error.targettype"
                          ],
                          "include_in_all": true
                        },
                        "Method": {
                          "type": "text",
                          "index": false,
                          "copy_to": [
                            "error.targetmethod"
                          ],
                          "include_in_all": true
                        }
                      }
                    }
                  }
                }
              }
            },
            "@level": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "@location": {
              "properties": {
                "country": {
                  "type": "keyword"
                },
                "level1": {
                  "type": "keyword"
                },
                "level2": {
                  "type": "keyword"
                },
                "locality": {
                  "type": "keyword"
                }
              }
            },
            "@request": {
              "properties": {
                "client_ip_address": {
                  "type": "text",
                  "index": false,
                  "copy_to": [
                    "ip"
                  ],
                  "include_in_all": true
                },
                "data": {
                  "properties": {
                    "@browser": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "@browser_major_version": {
                      "type": "text"
                    },
                    "@browser_version": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "@device": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "@is_bot": {
                      "type": "boolean"
                    },
                    "@os": {
                      "type": "text",
                      "index": false,
                      "copy_to": [
                        "os"
                      ]
                    },
                    "@os_major_version": {
                      "type": "text"
                    },
                    "@os_version": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    }
                  }
                },
                "path": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  },
                  "include_in_all": true
                },
                "user_agent": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                }
              }
            },
            "@simple_error": {
              "properties": {
                "data": {
                  "properties": {
                    "@target": {
                      "properties": {
                        "ExceptionType": {
                          "type": "text",
                          "index": false,
                          "copy_to": [
                            "error.targettype"
                          ],
                          "include_in_all": true
                        }
                      }
                    }
                  }
                }
              }
            },
            "@submission_method": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "@user": {
              "properties": {
                "identity": {
                  "type": "text",
                  "boost": 1.1,
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  },
                  "analyzer": "email",
                  "search_analyzer": "whitespace_lower",
                  "include_in_all": true
                },
                "name": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  },
                  "include_in_all": true
                }
              }
            },
            "@user_description": {
              "properties": {
                "description": {
                  "type": "text",
                  "include_in_all": true
                },
                "email_address": {
                  "type": "text",
                  "boost": 1.1,
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  },
                  "analyzer": "email",
                  "search_analyzer": "simple",
                  "include_in_all": true
                }
              }
            },
            "@version": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              },
              "analyzer": "version_index",
              "search_analyzer": "version_search"
            }
          }
        },
        "date": {
          "type": "date"
        },
        "error": {
          "include_in_all": true,
          "properties": {
            "code": {
              "type": "keyword",
              "boost": 1.1
            },
            "message": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "targetmethod": {
              "type": "text",
              "boost": 1.2,
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              },
              "analyzer": "typename",
              "search_analyzer": "whitespace_lower"
            },
            "targettype": {
              "type": "text",
              "boost": 1.2,
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              },
              "analyzer": "typename",
              "search_analyzer": "whitespace_lower"
            },
            "type": {
              "type": "text",
              "boost": 1.1,
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              },
              "analyzer": "typename",
              "search_analyzer": "whitespace_lower"
            }
          }
        },
        "geo": {
          "type": "geo_point"
        },
        "id": {
          "type": "keyword",
          "include_in_all": true
        },
        "idx": {
          "type": "object",
          "dynamic": "true"
        },
        "ip": {
          "type": "text",
          "analyzer": "comma_whitespace"
        },
        "is_deleted": {
          "type": "boolean"
        },
        "is_first_occurrence": {
          "type": "boolean"
        },
        "is_fixed": {
          "type": "boolean"
        },
        "is_hidden": {
          "type": "boolean"
        },
        "message": {
          "type": "text",
          "include_in_all": true
        },
        "organization_id": {
          "type": "keyword"
        },
        "os": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "project_id": {
          "type": "keyword"
        },
        "reference_id": {
          "type": "keyword"
        },
        "source": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          },
          "include_in_all": true
        },
        "stack_id": {
          "type": "keyword"
        },
        "tags": {
          "type": "text",
          "boost": 1.2,
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          },
          "include_in_all": true
        },
        "type": {
          "type": "keyword"
        },
        "updated_utc": {
          "type": "date"
        },
        "value": {
          "type": "double"
        }
      }
    }
}
}```

**Comment by john-roland** [comment]
yes, and I've got this output :

{
  "acknowledged": true
}

**Comment by john-roland** [comment]
and when i execute the next script, the output is:

{
  "took": 12316,
  "timed_out": false,
  "total": 4921941,
  "updated": 0,
  "created": 0,
  "deleted": 0,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": [
    {
      "index": "events-v1-2016.09.06",
      "type": "events",
      "id": "57cecdef38c7390b08c3d718",
      "cause": {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "events-v1-2016.09.06",
        "index_uuid": "_na_",
        "index": "events-v1-2016.09.06"
      },
      "status": 404
    },
    {
      "index": "events-v1-2016.09.05",
      "type": "events",
      "id": "57cd906e38c7390b08c3d6fa",
      "cause": {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "events-v1-2016.09.05",
        "index_uuid": "_na_",
        "index": "events-v1-2016.09.05"
      },
      "status": 404
....

**Comment by jdtaylor91** [comment]
I am also currently upgrading to use Exceptionless 4.0 and the last Kibana script is returning the same results as john-roland.

All previous scripts worked, it's just the last script that outputs thousands of "failures" of type "index_not_found_exception"

Is there an extra step that is required before this last script?

**Comment by jdtaylor91** [comment]
I think something is wrong with the script for step "i Create Event Template so daily indexes can be created with the correct mappings:"

It returns { "acknowledged": true }, but i am able to run it many times whereas if i try to run either of the others many times they respond with "index_already_exists_exception", which implies that the events index hasn't been created successfully.

Also, running the following command in kibana returns an empty set
`GET /events-v1-*`

**Comment by niemyjski** [comment]
What version of elaticsearch are you using? There was a bug in some versions of 5.x where you couldn't reindex from 1.7.5, into 5.x. We used 5.1.2 and I think it's fixed in 5.2.1 as well (are you using 5.2.0) by any chance?

Also, Do you have the following in your elasticsearch.yml? https://github.com/exceptionless/Exceptionless/blob/master/build/elasticsearch.prod.yml#L4 If so can you remove it? Did it fix it?

**Comment by niemyjski** [comment]
I've updated the docs with (https://github.com/exceptionless/Exceptionless/wiki/Upgrading#upgrading-from-v3-to-v4) more info. Can you please let me know how this goes.

**Comment by john-roland** [comment]
I'm running elasticsearch 5.1.2

my yml is:

cluster.name: exceptionless
action.destructive_requires_name: false
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
bootstrap.memory_lock: true
plugin.mandatory: mapper-size
http.port: 9400
reindex.remote.whitelist: 192.168.5.11:9200

**Comment by niemyjski** [comment]
Comment out the following line:

```
#action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
```

I forgot to put that in the docs :\, Elasticsearch has an open issue in there to allow index templates to be allowed.

**Comment by john-roland** [comment]
ok, i'm testing right now, the reindex script is running now... i cannot wait till it ends, sadly, but I'll tell you tomorrow.
but it looks on good tracks, thank you very much

**Comment by jdtaylor91** [comment]
I'm also running elasticsearch 5.1.2.

Commenting out that line has worked for me, thank you.

**Comment by niemyjski** [comment]
Awesome, I'm half wondering if we should just remove that line from our configs, but it's really useful to have in there (ensures indexes aren't auto created, like I've seen an alias being created as an alias in test code)

**Comment by niemyjski** [comment]
I'm going to close this for now, if you run into any issues, please let me know.

**Comment by john-roland** [comment]
yes, on my side i get the following error:

> Failed to connect to Console's backend.
> Please check the Kibana server is up and running

of course, Elasticsearch 1.7.5 and 5.1.2 are both running. maybe it's because i've got too much events ?
I also see that ElasticSearch 5.1.2 is taking more than 2 gb in RAM.. and a lot of CPU, even after this message is displayed.. maybe the script is still running ?

**Comment by jdtaylor91** [comment]
@john-roland, I also had this issue, the script should still be running though.

If you navigate to the logs\exceptionless-v4.log file within elasticsearch-5.1.2 you should be able to see logs for each daily index that it's creating.

I found that it took ~30 minutes to reindex 400,000 events, based on your above post if you have "4921941" then it may take a good few hours for you.

**Comment by john-roland** [comment]
thanks James, I'll be patient so..

**Comment by jdtaylor91** [comment]
I also had an issue with a java.net.SocketTimeoutException being thrown during the reindexing, this has then forced me to do it in batches using a range query.

I found the following video that @niemyjski did very useful to help work out what to do here

https://www.liveedu.tv/niemyjski/videos/k4JO7-exceptionless-weekly-demo-1-16-17

This is the script i've been using to do it in batches, in this example it will create anything before '2016-11-02'

`POST _reindex?wait_for_completion=false
{
"source": {
  "remote": {
    "host": "http://localhost:9200"
  },
  "index": "events-v1-*",
  "sort": { "date": "desc" },
  "query": {
    "range": {
      "created_utc": {
        "lte": "2016-11-02T00:00:00.0000000Z"
      }
    }
  }
},
"dest": {
  "index": "events-v1-error"
},
"script": {
  "lang": "painless",
  "inline": "ctx._index = 'events-v1-' + DateTimeFormatter.ofPattern('yyyy.MM.dd').format(OffsetDateTime.parse(ctx._source.date).toInstant().atZone(ZoneOffset.UTC)); if (ctx._source.updated_utc == null) { ctx._source.updated_utc = ctx._source.created_utc; } if (ctx._source.is_deleted == null) { ctx._source.is_deleted = false; } if (!ctx.containsKey('data') || !(ctx.data.containsKey('@error') || ctx.data.containsKey('@simple_error'))) return null;def types = [];def messages = [];def codes = [];def err = ctx.data.containsKey('@error') ? ctx.data['@error'] : ctx.data['@simple_error'];def curr = err;while (curr != null) { if (curr.containsKey('type'))  types.add(curr.type); if (curr.containsKey('message'))  messages.add(curr.message); if (curr.containsKey('code'))  codes.add(curr.code); curr = curr.inner;}if (ctx.error == null) ctx.error = new HashMap();ctx.error.type = types;ctx.error.message = messages;ctx.error.code = codes;"
}
}`

This will then give you a task back which you can then query to see the progress by using the following script

`GET _tasks/bqUgXd-hQv6_9WMcTw61Bg:11811`

**Comment by niemyjski** [comment]
@john-roland plugins run out of process now from elasticsearch so you'll need to setup kibana to run as a service on windows if you want it to run (it's a node app). I used the `sc create ..\.....\kibana.bat`. The ram usage is to be expected (https://github.com/exceptionless/Exceptionless/issues/281), by default it will try and allocate half of the available ram (this is configurable). I'd try launching the kibana.bat file in the console and see if any error messages are shown.

@john-roland @jdtaylor91 Yes, we used range queries which greatly slows down the import process (any query or sort does) but it helped us do it in batches. It's worth noting out that the max batch size of all events has to be less than 100mb or you can get an error or timeout. So if you have any large events, you may want to do a delete by query on the _size field or lower the reindex batch size to say like `size:100` or `size:200` Please note that it will return a task id and you can query the status of the task running. What we did is we reindexed using a query in 12 hour chunks of time using a small batch size of 200 due to some customers have large 200kb events... 

If you need any assistance, I'd be more than happy to jump onto a meeting and help

**Comment by niemyjski** [comment]
Were you able to get everything imported?

**Comment by john-roland** [comment]
yes, it's ok thanks
