### ISSUE TITLE
Verify you can create events index without mapper size plugin

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#280]
I got a report of the following error when self hosting:

```
Type: mapper_parsing_exception Reason: "Failed to parse mapping [events]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
```

**Comment by niemyjski** [comment]
The work around I believe for now is to install the following elasticsearch plugin: https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-size.html

**Comment by caesay** [comment]
I've added details about the mapper-size plugin to the self-hosting wiki for production deployments

**Comment by niemyjski** [comment]
Thanks!

**Comment by yetanotherchris** [comment]
Hi, it's worth noting this bug happens on the AWS Elasticsearch service (version 5). 

Annoyingly, you can't add plugins to their elasticsearch service.

The exception is:

```
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.<RequestAsync>d__9`1.MoveNext() in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 199
2017-02-20 12:09:10.1510  127 ERROR SaveEventAction Error processing action: SaveEventAction Message: Error creating the index events-v1-2017.02.20: Original: (400 - WebException) The remote server returned an error: (400) Bad Request.
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [events]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
 System.ApplicationException: Error creating the index events-v1-2017.02.20: Original: (400 - WebException) The remote server returned an error: (400) Bad Request.
Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [events]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""
 ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
```

**Comment by niemyjski** [comment]
I need to test this more but I have it working locally without mapper size plugin. I want to note here that there are some disadvantages of not running this plugin (I know you can't, but others reading this should know....). The main disadvantage is you lose the ability to see the average size of events and query by event size. This is important because if you change your maxeventpostsize property or get a massive event it can break reindexing (reindex won't work if there is an event over 100mb or the batch size is over 100mb). So it's a good thing to know and be able to check, otherwise you could be sifting through millions of events looking for the massive ones :).

**Comment by niemyjski** [comment]
I'll be pushing a new release soon once. We have a queue processing issue we've been tracking down and I think I just fixed it.

**Comment by niemyjski** [comment]
4.0.1 has been released https://github.com/exceptionless/Exceptionless/releases/tag/v4.0.1
