### ISSUE TITLE
Exceptionless v4 RAM usage

### ISSUE THREAD

**Issue by jdtaylor91** [exceptionless/Exceptionless#281]
I've just upgraded our self hosted Exceptionless instance to version 4, we're hosting this on a windows machine. The elasticsearch 5.1.2 service is now constantly using 2.5GB of RAM whereas previously it was only using 500MB of RAM.

Is this increase in RAM expected or is there additional configuration that is required to bring the RAM usage down?

Thanks,
James

**Comment by niemyjski** [comment]
This is expected, you can think of elasticsearch in terms of requirements much like sql server, it needs ram and disk io to do what it does best. By default you should give it a little less than half of the systems ram, you can of course change this behavior (see docs below). Please see the following:

https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html

**Comment by niemyjski** [comment]
Please let us know if you have any questions.

**Comment by jdtaylor91** [comment]
Thanks, those links have helped, i've now configured it to use less memory.
