### ISSUE TITLE
OnShutdown in aspnetcore

### ISSUE THREAD

**Issue by MihaMarkic** [exceptionless/Exceptionless#282]
I'm implementing ApplicationStopped in aspnetcore project like this:
`applicationLifetime.ApplicationStopped.Register(() =>  OnShutdown(sp));`
In OnShutdown I'm trying to send a message through exceptionless
`ExceptionlessClient.Default.SubmitLog("Shutdown");`
, but it says it is disposed. I guess you dispose it right before my code.
Using latest Exceptionless.AspNetCore.

**Comment by MihaMarkic** [comment]
I guess using ApplicationStopping is the proper way to go.

**Comment by caesay** [comment]
Use `ApplicationStopping` as you said, and also you might want to synchronously process the event queue:

    ExceptionlessClient.Default.ProcessQueue();

Exceptionless processes messages in the background so if your app shuts down before they are flushed I believe they could be lost.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Platforms/Exceptionless.AspNetCore/ExceptionlessExtensions.cs

We already call process queue on the onstopping event. You may need to wire up your handler before ours to do you'd log message can you try this and let me know

**Comment by niemyjski** [comment]
Did wiring up your handler before calling UseExceptionless() fix this issue? I'm going to close this but if you are still having this issue please let me know.
