### ISSUE TITLE
Possible JobResult error in EventPostsJob

### ISSUE THREAD

**Issue by laughinggoose** [exceptionless/Exceptionless#285]
I was looking through EventPostsJob and saw this: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Jobs/EventPostsJob.cs#L85

Shouldn't this be returning `JobResult.FailedWithMessage`?

**Comment by niemyjski** [comment]
@laughinggoose there could be an argument for both, we thought that we should just return success as the message as it doesn't need any work done as the project no longer exists, so it's the same as if we processed it. 

Do you think it would be better to have a failure message for when it can't be loaded like this? Looking t our others we seem to lean towards a failure message

**Comment by laughinggoose** [comment]
Based on your explanation it sounds like Success works! I just brought it up for the reason in your second paragraph - it seemed to not match the pattern.
