### ISSUE TITLE
Add names to api keys

### ISSUE THREAD

**Issue by brunomlopes** [exceptionless/Exceptionless#286]
For each project we have, we usually have a couple of api keys we create, for each large component. 
That way, if we need to someday replace the key, we don't need to do it on all the project parts.

But currently API keys are just random strings, and there's no easy way to map keys to "components".

A very simple solution to this would be to be able to "name" keys. It would be a plain text field, editable at will.

**Comment by ejsmith** [comment]
Yeah, that seems like a very reasonable request. Would you like some help in submitting a pull request for this feature?

**Comment by brunomlopes** [comment]
Thanks for the quick feedback. 
I'll be honest, at least for a couple of months I don't think I've got the time to dig into it.

**Comment by niemyjski** [comment]
I think this would be really nice to have an pretty simple to do, I think all we'd need to do is update the token model if it doesn't already have notes (I think it does) and ensure the patch operation allows notes to be updated. Then just update the UI. I really think everything server side is done already.

**Comment by niemyjski** [comment]
This change will be deployed shortly :)

**Comment by brunomlopes** [comment]
@niemyjski thanks :)
