### ISSUE TITLE
Can I use the latest Exceptionless  with the 2.0+ ES?

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless#288]
it's good for us that we can use exceptionless with 5.0+ES, but with some special reason, I have to use 2.0+ es, so does it support?

**Comment by niemyjski** [comment]
It might work and it's worth a try to see, but I doubt it will work. We only support 5.x and haven't tried 2.x as we were skipping the release.

**Comment by ZhiqiangTao** [comment]
thanks for your reply
