### ISSUE TITLE
Cannot send email using the 465 smtp port.

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless#290]
According to the document of microsoft, the System.Net.Mail cannot send email message through 465 port(https://blogs.msdn.microsoft.com/webdav_101/2008/06/02/system-net-mail-with-ssl-to-authenticate-against-port-465/).
But we want to use the tencent exmail account which have to use 465 port, so the mail sender component should be replaced another third part solution instead of System.Net.Mail.

**Comment by niemyjski** [comment]
We would be more than happy to accept a pull request for this functionality using the following library (https://github.com/jstedfast/MailKit) which should support implicit and explicit ssl (I wasn't aware of this limitation).

You should just have to update the following class: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Mail/SmtpMailSender.cs and verify that the templates (html and plaintext) as well as all headers are sent along like the current implementation.

**Comment by niemyjski** [comment]
This has been merged into master! If all goes well, we'll be pushing a release out very soon. Thanks again!
