### ISSUE TITLE
verify  mail

### ISSUE THREAD

**Issue by SongSong001** [exceptionless/Exceptionless#295]
Hello, I use the latest version of Exceptionless and Es is 5.2.1, configuration is successful, can receive the log, can also receive a validation email, but from the mailbox that connect back to the local site, enter the website, but still did not verify the state of the mailbox. Is there any way?

**Comment by caesay** [comment]
I'm assuming what you mean is that when you click the link in the "confirm email" message, it doesn't do anything?

Your exceptionless URL might not be correct in the configuration. After you click the link in the email you should get redirected to your account settings page, if you don't get redirected there it means the URL was wrong. If you are using url-rewriting, it should look like this inside `Web.config`:

    <add key="BaseURL" value="http://[your-domain]/" />

if not using url-rewriting, it should look like this:

    <add key="BaseURL" value="http://[your-domain]/#!" />

If it still doesn't work for you after adjusting the above can you post the confirmation link from the email so we can see?

**Comment by niemyjski** [comment]
I think it has to do with the missing hashbang at the end of the URL. We need to get a release out with this fixed

**Comment by niemyjski** [comment]
I'm closing this as it's fixed in master, we just need to get a minor release out.
