### ISSUE TITLE
Dashboard for All Projects in Organisation

### ISSUE THREAD

**Issue by luisvsilva** [exceptionless/Exceptionless#30]
It would be nice to implement a dashboard where you can see all exceptions being captured on all projects in your organisation.

**Comment by luisvsilva** [comment]
My Mouth is watering :) Will it have a migration path from Exceptionless 1.0 for self-hosted installations?

**Comment by niemyjski** [comment]
Yes, You'll have to set up new services like elasticsearch and run the migration script.
