### ISSUE TITLE
Odd filter behaviour

### ISSUE THREAD

**Issue by MihaMarkic** [exceptionless/Exceptionless#301]
Consider this text:

> It is night, waiting for next

If I search using "night" then I won't get any result. I have to search by "night," instead.

**Comment by niemyjski** [comment]
I'll take a look, probably has to do with our analyzer settings not splitting on punctuation. @ejsmith

**Comment by niemyjski** [comment]
I looked into this more and this should be covered as it's punctuation. Is there any chance you could add a unit test for this?

**Comment by MihaMarkic** [comment]
@niemyjski I looked into adding the test and started with checking out Exceptionless.Api.Tests.Repositories.EventIndexTests.GetByMessageAsync since it seems the proper target. Unfortunately it will fail with message below.
Is there something I'm missing?

> Exception thrown: 'FluentValidation.ValidationException' in mscorlib.dll
> Validation failed: 
>  -- Please specify a valid organization id.
>  -- Please specify a valid project id.
>  -- Please specify a valid stack id.

**Comment by niemyjski** [comment]
If you take a look at the `CreateEventsAsync` method you can see the raw events in the search\data folder. They all have a unique id but have the same org and project id.

```json
{
  "id": "54dbc16ca0f5c61398427b00",
  "organization_id": "1ecd0826e447ad1e78877555",
  "project_id": "1ecd0826e447ad1e78877ab2",
  "stack_id": "1ecd0826e447a44e78877ab1",
}
```

**Comment by caesay** [comment]
I can verify this has always been a problem for us, too. we always have to search by "night*" if we suspect it might end in punctuation.

**Comment by niemyjski** [comment]
We should add some tests for this and look into the analyzer settings.

**Comment by caesay** [comment]
Related: https://github.com/exceptionless/Exceptionless.UI/issues/140

**Comment by niemyjski** [comment]
I'm closing this as I'm merging this into #332

**Comment by niemyjski** [comment]
This is fixed in elastic 7
