### ISSUE TITLE
Supported Elasticsearch 5.4 ?

### ISSUE THREAD

**Issue by zhouyongtao** [exceptionless/Exceptionless#302]
Supported Elasticsearch 5.4 ?

**Comment by niemyjski** [comment]
Yes, Any 5.x release will work with the current version

**Comment by niemyjski** [comment]
Are you seeing an issue on 5.4?

**Comment by zhouyongtao** [comment]
i use es5.4 version, have something problem 
2017-05-22 20:41:16.9729   11 ERROR ElasticQueryParserConfiguration Original: (404 - WebException) The remote server returned an error: (404) Not Found.
Server: (404) Type: index_not_found_exception Reason: "no such index"
 System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()

**Comment by niemyjski** [comment]
When are you seeing this? Are you seeing this in our logs? Did you update the web.config to point to the elasticsearch server? You should be able to put the connection string into a browser (on the same box as your iss server and see a json result from elasticserach, does this happen?)

**Comment by zhouyongtao** [comment]
i have update the web.config , and es browser  json 
es  :
{
    "name": "0YunMtd",
    "cluster_name": "pms_es_node-01",
    "cluster_uuid": "KslvCC9NQOuMSblIwEP19A",
    "version": {
        "number": "5.4.0",
        "build_hash": "780f8c4",
        "build_date": "2017-04-28T17:43:27.229Z",
        "build_snapshot": false,
        "lucene_version": "6.5.0"
    },
    "tagline": "You Know, for Search"
}

**Comment by zhouyongtao** [comment]
more detail log：
```
2017-05-23 20:01:34.3650   22 TRACE UserRepository Cache hit: type=user key=5924198284d7b4226843a149 
2017-05-23 20:01:34.3650   37 TRACE UserRepository Cache hit: type=user key=5924198284d7b4226843a149 
2017-05-23 20:01:34.4431   41 TRACE OrganizationRepository POST /_mget
{"docs":[{"_index":"organizations","_type":"organization","_id":"5924199984d7b4226843a14a"}]}
 
2017-05-23 20:01:34.4431   42 TRACE OrganizationRepository POST /_mget
{"docs":[{"_index":"organizations","_type":"organization","_id":"5924199984d7b4226843a14a"}]}
 
2017-05-23 20:01:34.4431   32 TRACE OrganizationRepository POST /_mget
{"docs":[{"_index":"organizations","_type":"organization","_id":"5924199984d7b4226843a14a"}]}
 
2017-05-23 20:01:34.4588   18 TRACE ElasticQueryParserConfiguration GET /events/_mapping/events
 
2017-05-23 20:01:34.4588   38 TRACE ElasticQueryParserConfiguration GET /events/_mapping/events
 
2017-05-23 20:01:34.4588   18 ERROR ElasticQueryParserConfiguration Original: (404 - WebException) The remote server returned an error: (404) Not Found.
Server: (404) Type: index_not_found_exception Reason: "no such index"
 System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 164
2017-05-23 20:01:34.4588   38 ERROR ElasticQueryParserConfiguration Original: (404 - WebException) The remote server returned an error: (404) Not Found.
Server: (404) Type: index_not_found_exception Reason: "no such index"
 System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Projects\elastic\net-5\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 164
2017-05-23 20:01:34.4744   32 TRACE EventRepository POST /events-2017.05.22%2Cevents-2017.05.23/events/_search?ignore_unavailable=true
{"size":11,"sort":[{"date":{"order":"desc"}}],"query":{"bool":{"filter":[{"bool":{"must":[{"term":{"is_deleted":{"value":false}}},{"range":{"date":{"gte":"2017-05-22T12:00:00Z","lte":"2017-05-23T12:01:34.4588156Z"}}},{"term":{"is_fixed":{"value":"false"}}},{"term":{"is_hidden":{"value":"false"}}},{"term":{"organization_id":{"value":"5924199984d7b4226843a14a"}}},{"range":{"date":{"gte":"now/d-4d","lte":"now/d+1d"}}}]}}]}}}
```

**Comment by niemyjski** [comment]
I think that's fine, that's just saying the events index doesn't exist, could be because no events have been posted. What happens when you submit an event to the system, do you get errors when it tries to create the index?

**Comment by zhouyongtao** [comment]
POST http://172.23.216.124:81/api/v2/events HTTP/1.1
Accept: application/json
User-Agent: exceptionless/4.0.0
Authorization: Bearer rmpT5bpPC1LekMjx0BfolZ0QwIkrQgwvjRAZ27fX
Content-Type: application/json; charset=utf-8
Host: 172.23.216.124:81
Content-Length: 2731
Accept-Encoding: gzip, deflate

[{"type":"error","date":"2017-05-25T12:16:18.0914528+08:00","data":{"@version":"1.0.0.0","@error":{"modules":[{"module_id":1,"name":"Antlr3.Runtime","version":"3.4.1.9004","created_date":"2017-05-25T12:15:51.1130515+08:00","modified_date":"2017-05-25T12:15:51.1140566+08:00","data":{"PublicKeyToken":"eb42632606e9261f"}},{"module_id":2,"name":"Exceptionless.Mvc.Signed","version":"4.0.1951.0","created_date":"2017-05-25T12:15:51.1290934+08:00","modified_date":"2017-05-25T12:15:51.1290934+08:00","data":{"PublicKeyToken":"fc181f0a46f65747","ProductVersion":"4.0.1951$(VERSION_SUFFIX) 27129f3422"}},{"module_id":3,"name":"Exceptionless.Signed","version":"4.0.1951.0","created_date":"2017-05-25T12:15:51.140123+08:00","modified_date":"2017-05-25T12:15:51.1441332+08:00","data":{"PublicKeyToken":"fc181f0a46f65747","ProductVersion":"4.0.1951$(VERSION_SUFFIX) 27129f3422"}},{"module_id":4,"name":"Newtonsoft.Json","version":"6.0.0.0","created_date":"2017-05-25T12:15:51.3164469+08:00","modified_date":"2017-05-25T12:15:51.3184522+08:00","data":{"PublicKeyToken":"30ad4fe6b2a6aeed","FileVersion":"6.0.4.17603"}},{"module_id":5,"name":"WebApplication1","version":"1.0.0.0","created_date":"2017-05-25T12:15:51.4929815+08:00","modified_date":"2017-05-25T12:15:51.4934841+08:00"}],"message":"1011f11f-38a4-4dcd-8213-ccf4871a8e23","type":"System.ApplicationException","stack_trace":[{"file_name":"C:\\Users\\irving\\Desktop\\WebApplication1\\WebApplication1\\Controllers\\HomeController.cs","line_number":43,"column":17,"declaring_namespace":"WebApplication1.Controllers","declaring_type":"HomeController","name":"About","module_id":5,"data":{"ILOffset":26,"NativeOffset":120}}],"target_method":{"declaring_namespace":"WebApplication1.Controllers","declaring_type":"HomeController","name":"About","module_id":5}},"@environment":{"processor_count":4,"total_physical_memory":8010072064,"available_physical_memory":865783808,"command_line":"\"C:\\Program Files (x86)\\IIS Express\\iisexpress.exe\"  /config:\"C:\\Users\\irving\\Desktop\\WebApplication1\\.vs\\config\\applicationhost.config\" /site:\"WebApplication1\" /apppool:\"Clr4IntegratedAppPool\"","process_name":"iisexpress","process_id":"52940","process_memory_size":128950272,"thread_id":"5","architecture":"x64","o_s_name":"Microsoft Windows 10 企业版","o_s_version":"10.0.15063.0","machine_name":"DESKTOP-56GJHJ7","install_id":"a137902a920e4ef29bc188c8645e3365","runtime_version":"4.0.30319.42000"},"@request":{"user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36","http_method":"GET","host":"localhost","port":55757,"path":"/Home/About","referrer":"http://localhost:55757/","client_ip_address":"::1"}}}]``

**Comment by niemyjski** [comment]
would you be free for this morning (CST, aka next few hours) for a remote meeting?

**Comment by niemyjski** [comment]
All of that looks okay, which makes me think if you aren't seeing data, then something is wrong with event processing

**Comment by zhouyongtao** [comment]
![image](https://cloud.githubusercontent.com/assets/4192762/26479887/053f78aa-4209-11e7-9418-93677621c0d2.png)

**Comment by niemyjski** [comment]
I'd set the nlog config level to trace for a minute or two and try submitting an event (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting). If you could attach the logs that would be greatly appreciated.

**Comment by niemyjski** [comment]
@zhouyongtao were you able to get this working? If not, could you please attach the logs after submitting an event as described in the troubleshooting guide.

**Comment by zzSleep** [comment]
@niemyjski what are you doing now? I have some  questions ask you ,you must reply to my message

**Comment by niemyjski** [comment]
I was sleeping... Please ask each question that you have here and someone will answer them.

**Comment by zhouyongtao** [comment]
@niemyjski  thanks , I have solved the problem, which is the reason of file permission  ！

**Comment by niemyjski** [comment]
I'm not sure, the first steps I'd take with that is to delete everything in elastic search and if you are using Redis, clear the Redis db and restart the process. Does that help?

**Comment by tcguoxing** [comment]
3Q for your reply.
I have deleted all exceptionless and elastic search files, then I configure them according to your self hosting document. And it works well now in my local network. I dont know what I have done before yet.

**Comment by KantJoe** [comment]
> I'm not sure, the first steps I'd take with that is to delete everything in elastic search and if you are using Redis, clear the Redis db and restart the process. Does that help?

Hello,i met this error either,could u conclude some method to solve it?thanks

**Comment by niemyjski** [comment]
Can you open Kibana and run `GET _cat/indicies` and let me know what it says.

**Comment by KantJoe** [comment]
> Can you open Kibana and run `GET _cat/indicies` and let me know what it says.

thank u for concern,but my elasticsearch version is 5.6.1,and now i'd work off,later i will post the result.
to be continued

**Comment by KantJoe** [comment]
> _cat/indicies

hallo，here is result，by the way ,i post error log here


health |status| index    |        uuid         |          pri |rep| docs.count |docs.deleted |store.size |pri.store.size
--|--|--|--|--|--|--|--|--|--
green  |open  | organizations-v1| MBoPfy7BSOqQfRpjRdFDAQ  | 1 |  0        |  5        |    1   |  29.5kb   |      29.5kb
green|  open |  stacks-v1  |      oV_KPLskTBibp_YX6eQxcg |  1  | 0      |    0     |       0   |    191b    |       191b


2019-04-02 19:13:19.8760   74 ERROR CloseInactiveSessionsJob Job run "CloseInactiveSessionsJob" failed: Original: ( - WebException) 无法连接到远程服务器
 System.ApplicationException: Original: ( - WebException) 无法连接到远程服务器
 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 192.168.1.112:9200
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   在 System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.HttpConnection.<RequestAsync>d__14`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.<FindAsAsync>d__18`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Exceptionless.Core.Jobs.CloseInactiveSessionsJob.<RunInternalAsync>d__5.MoveNext() 位置 C:\projects\exceptionless\src\Exceptionless.Core\Jobs\CloseInactiveSessionsJob.cs:行号 35
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Foundatio.Jobs.JobWithLockBase.<RunAsync>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Foundatio.Jobs.JobWithLockBase.<RunAsync>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Foundatio.Jobs.JobExtensions.<TryRunAsync>d__0.MoveNext()
2019-04-02 19:14:21.0189   70 ERROR EventRepository Original: ( - ElasticsearchClientException) 发生一个或多个错误。
 Elasticsearch.Net.ElasticsearchClientException: 发生一个或多个错误。 ---> System.AggregateException: 发生一个或多个错误。 ---> Elasticsearch.Net.PipelineException: Failed to ping the specified node. ---> Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   在 Elasticsearch.Net.RequestPipeline.<PingAsync>d__59.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Elasticsearch.Net.RequestPipeline.<PingAsync>d__59.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.Transport`1.<PingAsync>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Elasticsearch.Net.Transport`1.<PingAsync>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
2019-04-02 19:14:21.0189   70 ERROR CloseInactiveSessionsJob Job run "CloseInactiveSessionsJob" failed: Original: ( - ElasticsearchClientException) 发生一个或多个错误。
 System.ApplicationException: Original: ( - ElasticsearchClientException) 发生一个或多个错误。
 ---> Elasticsearch.Net.ElasticsearchClientException: 发生一个或多个错误。 ---> System.AggregateException: 发生一个或多个错误。 ---> Elasticsearch.Net.PipelineException: Failed to ping the specified node. ---> Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   在 Elasticsearch.Net.RequestPipeline.<PingAsync>d__59.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Elasticsearch.Net.RequestPipeline.<PingAsync>d__59.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.Transport`1.<PingAsync>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Elasticsearch.Net.Transport`1.<PingAsync>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 Foundatio.Repositories.Elasticsearch.ElasticReadOnlyRepositoryBase`1.<FindAsAsync>d__18`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Exceptionless.Core.Jobs.CloseInactiveSessionsJob.<RunInternalAsync>d__5.MoveNext() 位置 C:\projects\exceptionless\src\Exceptionless.Core\Jobs\CloseInactiveSessionsJob.cs:行号 35
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Foundatio.Jobs.JobWithLockBase.<RunAsync>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Foundatio.Jobs.JobWithLockBase.<RunAsync>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Foundatio.Jobs.JobExtensions.<TryRunAsync>d__0.MoveNext()
2019-04-02 19:22:54.4778    9 ERROR ElasticQueryParserConfiguration Original: (404 - WebException) 远程服务器返回错误: (404) 未找到。
Server: (404) Type: index_not_found_exception Reason: "no such index"
 System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.GetResponse()
   在 Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)

**Comment by niemyjski** [comment]
Sorry for the late response. I'm really not sure what's going on here but since you are starting up Exceptionless for the first time to self host. I'd highly recommend using 5.0 and setting it up via docker: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting-Docker If you have any feedback that would be greatly appreciated. This is the model we are going for the next major version which is pending release (of better docs), I think it will really help in your situation as elasticsearch is a docker image and is guaranteed to work.

**Comment by niemyjski** [comment]
But in reguards to your error above, it sounds like an elasticsearch configuration issue. I'd check the elastic logs if you cannot use docker or choose to host elasticsearch outside of docker. The indexes will be created when Exceptionless first starts up and talks to elasticsearch. It sounds like it's not connecting to elasticsearch. You can verify it can talk to it by navigating to the elasticsearch connection string (e.g., `http://ip_here:9200`) in your browser. If you can hit that and you don't get an error you should be good to go.

**Comment by KantJoe** [comment]
Hallo,i just reinstall elastic on 5.0.0 and reinstall exceptionless,befor i start elastic,i'd authorization 'everyone' to elastic directory,and excetpionless is successfully start and sign up .but i tryed to add a log ,and it failed again,here is exceptionless logs and elastic logs:

exceptionless
`
2019-04-12 10:56:29.8283   51 ERROR ElasticQueryParserConfiguration Original: (404 - WebException) 远程服务器返回错误: (404) 未找到。
Server: (404) Type: index_not_found_exception Reason: "no such index"
 System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.GetResponse()
   在 Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
2019-04-12 10:56:29.8283   26 ERROR ElasticQueryParserConfiguration Original: (404 - WebException) 远程服务器返回错误: (404) 未找到。
Server: (404) Type: index_not_found_exception Reason: "no such index"
 System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.GetResponse()
   在 Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData)
`
elastic 
`
[2019-04-12T10:54:31,617][WARN ][o.e.h.n.Netty4HttpServerTransport] [m_NFDWE] caught exception while handling client http traffic, closing connection [id: 0x61013cc6, L:/0:0:0:0:0:0:0:1:9200 - R:/0:0:0:0:0:0:0:1:56539]
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[2019-04-12T10:54:38,740][INFO ][o.e.c.m.MetaDataCreateIndexService] [m_NFDWE] [stacks-v1] creating index, cause [api], templates [], shards [1]/[0], mappings [stacks]
[2019-04-12T10:54:38,951][INFO ][o.e.c.r.a.AllocationService] [m_NFDWE] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[stacks-v1][0]] ...]).
[2019-04-12T10:54:39,419][INFO ][o.e.c.m.MetaDataCreateIndexService] [m_NFDWE] [organizations-v1] creating index, cause [api], templates [], shards [1]/[0], mappings [webhook, organization, project, user, token]
[2019-04-12T10:54:39,552][INFO ][o.e.c.r.a.AllocationService] [m_NFDWE] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[organizations-v1][0]] ...]).
`

**Comment by KantJoe** [comment]
i try to add an item of elasticsearch.yml 
'action.auto_create_index: +a*,+b*,+c*,+d*,+e*,+f*,+g*,+h*,+i*,+j*,+k*,+l*,+m*,+n*,+o*,+p*,+q*,+r*,+s*,+t*,+u*,+v*,+w*,+x*,+y*,+z*'

and it looks no help for it

**Comment by niemyjski** [comment]
Hello, Something is going on here and it's hard to see the messages because they are translated in the stack. It looks like they started to create the indexes which caused the cluster to go to yellow and back to green. You could remove the elasticsearch.yml setting for `action.auto_create_index`. It might be worth cloning the repository and hitting f5 to start debugging and look at this under the debugger.

**Comment by KantJoe** [comment]
> Hello, Something is going on here and it's hard to see the messages because they are translated in the stack. It looks like they started to create the indexes which caused the cluster to go to yellow and back to green. You could remove the elasticsearch.yml setting for `action.auto_create_index`. It might be worth cloning the repository and hitting f5 to start debugging and look at this under the debugger.

Oh,i have an idea,how is i clone a data directory of elasticsearch,and if it is possible,i think the problem would be caught by application permission？

**Comment by KantJoe** [comment]
i found a error when i run elasticsearch-service.
`error application name: elasticsearch-service-x64.exe，version: 1.0.15.0，时间戳: 0x51543b9d
error module nam: jvm.dll，version: 8.0.1910.12，时间戳: 0x5bb8f127
exception code: 0xc0000005
error offset: 0x0000000000218078
error proccess ID: 0x4608
error application start time: 0x01d4f1d08fc1d202
error application path: D:\elasticsearch\bin\elasticsearch-service-x64.exe
error module path: C:\Program Files\Java\jdk1.8.0_191\jre\bin\server\jvm.dll
报告 ID: 5231675e-ed35-482f-bf38-1cd0d5a37df8
错误程序包全名: 
错误程序包相对应用程序 ID: `
