### ISSUE TITLE
Python client

### ISSUE THREAD

**Issue by john-roland** [exceptionless/Exceptionless#304]
Hello,

Is there any Python client for exceptionless ?

Thanks

**Comment by niemyjski** [comment]
Hey,

We currently don't have a python client but would be willing to accept a pr for one. Currently, you can make a very simple http post to our documented api for submission. I'd be more than happy to work with you on this. Please let me know if you have any questions.

http://api.exceptionless.com/docs/index#!/Event/Event_PostAsync

**Comment by john-roland** [comment]
Hi Blake,

Thank you for the quick answer :)

yes, I know the api quite well, we'll do that a bit for some non .net app

thanks again

**Comment by niemyjski** [comment]
Has it been pretty easy to work with our api?

**Comment by john-roland** [comment]
yes, very easy to make it work, even if at start I was a bit confused about which token to send.
Also, the samples are good, but when we wanted to send some more complex stuff we had to dig in the webapi code to get the list of params we can send, etc.

**Comment by niemyjski** [comment]
You'd use your client api key that's listed under manage project api keys tab. If you have an example of what we could add to the api docs that would be greatly appreciated.

**Comment by john-roland** [comment]
the most difficult was to find how to send the user and the date/time of the event. 
we found that the first was "identity" and the second one need a very specific format with the 'Z' seperator if i remember well.

**Comment by niemyjski** [comment]
Good point! Is there any chance you could open a new issue or pr for that and we'll get it resolved

**Comment by zhouyongtao** [comment]
@niemyjski  I have solved the problem, which is the reason of file permission ，thanks！
