### ISSUE TITLE
Notifications on exceeded exception rate in given period of time

### ISSUE THREAD

**Issue by Adiqq** [exceptionless/Exceptionless#305]
Hi,

It would be nice to have more control on notifications.
For example, "if there was >100 exceptions in last hour do some action (send e-mail)".
It would also be nice to have other channels for notification: Slack integration, POST notification to specified endpoint, so it would be easier to react quickly if something bad is happening.

**Comment by niemyjski** [comment]
Hey, The rate based notifications we have an issue tracking this (https://github.com/exceptionless/Exceptionless/issues/177). We currently do have slack and web hook support (you can find it on the manage project notifications tab. Were you able to find these? If you need any help, please let me know.
