### ISSUE TITLE
used SelfHosting, how settings verify email

### ISSUE THREAD

**Issue by 3223554** [exceptionless/Exceptionless#306]
verify email no work

![default](https://cloud.githubusercontent.com/assets/16113293/26816720/b36dbf30-4ac5-11e7-8169-efcfab1d3b1e.png)

**Comment by caesay** [comment]
It might help to review the self hosting documentation and follow the steps again closely especially where it talks about configuration files `app.config` and `app.config.*.js`. You can also check the exceptionless log file to see if its a mail transport issue, this should exist in `[APP]/Logs`

If you've verified your config files are correct and it's still not working then you can post your `app.config` and `app.config.*.js` and maybe also the log files somewhere and link it here so someone here can take a look.

**Comment by 3223554** [comment]
i see
https://github.com/exceptionless/Exceptionless/issues/290
i was download  latest release
but still can not work

my config

![qq 20170606165540](https://cloud.githubusercontent.com/assets/16113293/26821556/6239b510-4ad9-11e7-8c7e-4191a6d69362.png)
![default](https://cloud.githubusercontent.com/assets/16113293/26821566/688bbe36-4ad9-11e7-9d37-51e74c505eaa.png)

**Comment by 3223554** [comment]
@caesay

**Comment by caesay** [comment]
Please check the log file for any SMTP related error messages and post here with what you see

**Comment by 3223554** [comment]
iis log
[u_ex170606.txt](https://github.com/exceptionless/Exceptionless/files/1054401/u_ex170606.txt)
application log
[log.txt](https://github.com/exceptionless/Exceptionless/files/1054403/log.txt)
![default](https://cloud.githubusercontent.com/assets/16113293/26822485/c5047588-4adc-11e7-91b3-93426bdbd61e.png)

**Comment by 3223554** [comment]
oh 
I found this excption

![default](https://cloud.githubusercontent.com/assets/16113293/26823155/29515e0a-4adf-11e7-98f1-7b01261d5917.png)
ail from address must be same as authorization user MailKit.Net.Smtp.SmtpCommandException: mail from address must be same as authorization user？
how can i do？ I can't find authorization user configuration @caesay

**Comment by niemyjski** [comment]
@3223554 I think that's saying this value (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Settings.cs#L212) should match the Smtp user property. Can you try that and let us know. Also if you have any suggestions on how we can make this easier to diagnose in the future, that would be appreciated.

**Comment by 3223554** [comment]
ok thanks 
it can work
may I make a suggestion?
web.config  add  appconfig key 
default 
<add key ="SmtpFrom" value="yourstmpfrom" />

i read the source code before I know it can be added

**Comment by niemyjski** [comment]
Do you mean we should add the from section?

**Comment by 3223554** [comment]
yes

add default  
key ="SmtpFrom" value="xxxx" 

sorry ，my english is very poor。。。。

**Comment by niemyjski** [comment]
No problem, is there any chance you could add this in a pr? There are three spots, one in the web.config and one in the https://github.com/exceptionless/Exceptionless/blob/master/src/Jobs/App.config and one in the tests project's app.config

**Comment by 3223554** [comment]
ok thanks

**Comment by niemyjski** [comment]
I'm closing this, please let me know if this is still an issue.
