### ISSUE TITLE
More webapi documentation / samples

### ISSUE THREAD

**Issue by john-roland** [exceptionless/Exceptionless#307]
Hello,

It would be great to have more documentation about how to post complex event though the webapi:

* how to send the user identity
* how to send the datetime of the event (a specific format is needed)
* how to send advanced fields like stack trace, exception type, environment variables 

thank you,

**Comment by niemyjski** [comment]
Thanks! I'll make sure we get this added

**Comment by niemyjski** [comment]
I added samples for the basic use cases like user info and dates.  For users that need more advanced use cases I'd be more than happy to assist via support message. I'd recommend looking at our tests data as well or just posting an event using our client to see the full model (you can copy the raw json) 
https://github.com/exceptionless/Exceptionless/blob/master/tests/Exceptionless.Api.Tests/ErrorData/977.expected.json
