### ISSUE TITLE
Search in environment command line

### ISSUE THREAD

**Issue by john-roland** [exceptionless/Exceptionless#308]
Hi,

would it possible to search for the command line content ?
We use exceptionless a lot to store logs about command lines tool, and it would be very helpful.

Also, when we are searching for an event, it would be really better to have the real date/time instead of the "aday ago".. maybe it could be an global settings in the web.config ? but in our case having the timestamp would avoid opening each event to see if its the correct one

thanks

**Comment by niemyjski** [comment]
Is there something specific you want for the command line arguments? I'm guessing you just want to search for arguments a user might be passing in. We should probably  split on directory path spaces.

**Comment by john-roland** [comment]
yes, we are usually searching for a word or a part of a word in the arguments, might be an email address, a file path, etc. 
I think indexing the whole command line is good

**Comment by niemyjski** [comment]
Fixed in https://github.com/exceptionless/Exceptionless/commit/8c04e4fb0f8d6ba6e43d0448f117fd92e177df11
