### ISSUE TITLE
How to monitor system is health

### ISSUE THREAD

**Issue by platstar** [exceptionless/Exceptionless#310]
The exceptionless use a kind of queue system to write log.
https://exceptionless.com/version-2-0s-new-message-bus-queueing-systems/

so how could I monitor the queue is health?
Thanks for your answer.

**Comment by niemyjski** [comment]
Hello,

There are two methods of which you can use. The first and main endpoint I'd check would be the /api/v2/status (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Api/Controllers/StatusController.cs#L53) This checks the cache, elasticsearch and storage. If this is up you should be good, you can call this as a normal user and the result is cached very briefly.

If you are a global admin you can hit /api/v2/queue-stats (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Api/Controllers/StatusController.cs#L83) which will give you queue information :) If you have any questions, please let us know!
