### ISSUE TITLE
About landing problems

### ISSUE THREAD

**Issue by zhaohy0612** [exceptionless/Exceptionless#311]
Login tips
An error occurred while logging in. Please contact support for more informat.How to deal with?

**Comment by niemyjski** [comment]
If you are self hosting exceptionless, I'd follow the troubleshooting guide located here: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting Chances are that it can't talk to the server or your app.config.js is not pointing to the right server end point. If you are seeing this issue on our hosted service please let me know. If you could open the debugger tools and and paste in the network tab results that would be a help as well.
