### ISSUE TITLE
 by selfhosting can not receive any data

### ISSUE THREAD

**Issue by akaxb** [exceptionless/Exceptionless#312]
I've created it locally, Then I'm sure I got the correct key and ServerUrl, my client config code just like this
![image](https://user-images.githubusercontent.com/6300834/28310004-a36f0308-6bdd-11e7-9210-ec25172bbb9c.png)
![image](https://user-images.githubusercontent.com/6300834/28310036-bf933e82-6bdd-11e7-9c59-1a2582651e12.png)
![image](https://user-images.githubusercontent.com/6300834/28310183-2ad3b35c-6bde-11e7-9f6c-47dce8cb9b3b.png)
here is the log:
 Server: (400) Type: illegal_argument_exception Reason: "pipeline with id [events-pipeline] does not exist"
now i don't know what's wrong with it

**Comment by niemyjski** [comment]
What version of Elasticsaerch are you using? Have you ran through the troubleshooting guide? https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting

**Comment by akaxb** [comment]
the Elasticsaerch version is 5.3.0 
![image](https://user-images.githubusercontent.com/6300834/28345452-29a9cb9a-6c5d-11e7-871e-9c9fab9bf2fe.png)
i am try to update the Elasticsaerch to 5.5,and it's success,I am not proficient with Elasticsaerch ,I see on the official website，maybe that's the problem
![image](https://user-images.githubusercontent.com/6300834/28346284-8eea7784-6c62-11e7-8472-11a09bf44b3c.png)
thankyou

**Comment by niemyjski** [comment]
Thanks for the update. I'm guessing maybe it was just something configuration related.
