### ISSUE TITLE
Ability to delete a user account

### ISSUE THREAD

**Issue by ArvinHsieh** [exceptionless/Exceptionless#319]
i used self hosting in my projects. but the users have a abnormal user. the user always can't login. even password is correct. i want delete the user and register again. what can i do? thanks.

**Comment by niemyjski** [comment]
Currently the only way is to do this via elasticsearch `DELETE /organizations-v1/users/idhere` We currently don't have a view for managing users but that would be a nice to have to reuse the profile page and add a route for the user with a delete button. Would this be something you'd be willing to submit a pr for? What issues are they seeing with login? It would be great to get any issues fixed.

**Comment by ArvinHsieh** [comment]
I used DELETE /organizations-v1/users/idhere is work.
Thanks!!

**Comment by niemyjski** [comment]
If they are still having issues logging in, please let me know.

**Comment by sisbilir** [comment]
Hi @niemyjski! Anybody working on this enhancement?

**Comment by sisbilir** [comment]
@niemyjski I can work on it.

**Comment by niemyjski** [comment]
I'm closing this for now, but if anyone would be willing to submit a pr for this it would be greatly appreciated.
