### ISSUE TITLE
OS version filtering

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#324]
I can't get this to work, I've tried this:

os.version:6.1.7601.65536
os.version:"6.1.7601.65536"
os:6.1.7601.65536
os.major:6

This does work, but I'm looking for a specific version:
*  os:"Windows 7"

Do I need to do anything else or is it broken?

**Comment by niemyjski** [comment]
We do have tests covering this: https://github.com/exceptionless/Exceptionless/blob/master/tests/Exceptionless.Api.Tests/Search/EventIndexTests.cs#L293-L314

What is your events operating system field set to?

**Comment by Phyxion** [comment]
What 

OS Name | Microsoft Windows 10 Pro
OS Version | 6.2.9200.0

or


OS Name | Microsoft Windows 7 Home Premium
OS Version | 6.1.7601.65536
Architecture | x64


I can search by name, but searching by version isn't working. Or at least I can't get it to work as written on the documentation :(

**Comment by niemyjski** [comment]
Would be good to update the test cases with these two examples just to
verify. I'll try and get around to it this week (greatly appreciated if you
could submit a pr)

Thanks
-Blake Niemyjski

**Comment by Phyxion** [comment]
Does the os version search do anything for you at all (with live data)? I'm not sure why the tests are working (or why it isn't working here).

**Comment by niemyjski** [comment]
Yes, os.version:10.12.6 works for me. When I searched for a version of Mac.

**Comment by niemyjski** [comment]
I'm closing this as I'm merging this into #332

**Comment by niemyjski** [comment]
This should now be fixed, we have a text lower case analyzer and keyword field on os and version is now just a keyword field.
