### ISSUE TITLE
Searching custom extended data field of type string not returning results

### ISSUE THREAD

**Issue by TristanGaydon** [exceptionless/Exceptionless#325]
Running Exceptionless on a self hosted environment, v4.1.0 

I'm trying to search on custom data.

I have an extended data field of type string called "FriendlyErrorIdentifier".

I can (in Kibana) see that the event in elasticsearch has two fields related to this;
data.FriendlyErrorIdentifier	   	  Foo-7967BB
idx.friendlyerroridentifier-s	   	  Foo-7967BB

Searching as per the documentation with a search of data.friendlyerroridentifier:"Foo-7967BB" yields no results. I was unable to successfully search on any extended data field of type string, searching for an extended data field of type number worked as expected, e.g. data.callerlinenumber:38

**Comment by kiquenet** [comment]
How install EL in self hosted environment?

**Comment by niemyjski** [comment]
@TristanGaydon  When you try to search for `data.FriendlyErrorIdentifier:"Foo-7967BB"` in the client what is the query sent to elastic search? Could you try turning on fiddler and changing the elastic connection string to `http://ipv4.fiddler:9200` and looking at the query. I'd love to know what it was translated to.

@kiquenet Please see the self hosted docs: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting and please open a new issue if you need any assistance.

**Comment by TristanGaydon** [comment]
@niemyjski Hi Blake, Thanks for your reply. I've captured the request made to elasticsearch

```
POST http://127.0.0.1:9200/events-2017.10.26%2Cevents-2017.10.27%2Cevents-2017.10.28%2Cevents-2017.10.29%2Cevents-2017.10.30%2Cevents-2017.10.31%2Cevents-2017.11.01%2Cevents-2017.11.02/events/_search?ignore_unavailable=true HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: 127.0.0.1:9200
Content-Length: 914

{
  "size": 0,
  "_source": {
    "excludes": [
      "idx",
      "ip",
      "error"
    ]
  },
  "aggs": {
    "terms_stack_id": {
      "meta": {
        "@type": "keyword"
      },
      "terms": {
        "field": "stack_id",
        "size": 11
      },
      "aggs": {
        "min_date": {
          "meta": {
            "@type": "date"
          },
          "min": {
            "field": "date"
          }
        },
        "max_date": {
          "meta": {
            "@type": "date"
          },
          "max": {
            "field": "date"
          }
        },
        "sum_count": {
          "meta": {
            "@type": "integer"
          },
          "sum": {
            "field": "count",
            "missing": 1
          }
        },
        "cardinality_user": {
          "cardinality": {
            "field": "data.@user.identity.keyword"
          }
        }
      }
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "term": {
                  "is_deleted": {
                    "value": false
                  }
                }
              },
              {
                "range": {
                  "date": {
                    "gte": "2017-10-26T07:00:00Z",
                    "lte": "2017-11-02T17:27:52.8514335Z"
                  }
                }
              },
              {
                "term": {
                  "type": {
                    "value": "error"
                  }
                }
              },
              {
                "term": {
                  "is_fixed": {
                    "value": "false"
                  }
                }
              },
              {
                "term": {
                  "is_hidden": {
                    "value": "false"
                  }
                }
              },
              {
                "term": {
                  "idx.friendlyerroridentifier-s": {
                    "value": "Hub-7967BB"
                  }
                }
              },
              {
                "term": {
                  "organization_id": {
                    "value": "58efefa1691e3807ece2239c"
                  }
                }
              },
              {
                "range": {
                  "date": {
                    "gte": "now/d-181d",
                    "lte": "now/d+1d"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

I had the Exceptionless UI set to "last hour". We are using ElasticSearch v5.4.3

**Comment by niemyjski** [comment]
Thanks for that. I'll update our tests with this specific example just to make sure but that all looks right.

**Comment by niemyjski** [comment]
I'm closing this as I'm merging this into #332, but I'll try and look into this today.

**Comment by niemyjski** [comment]
@ejsmith I took a look into this and it appears the test is very flakey and we need to take a look into this. Do you have any idea why it would be doing this?

When it fails it creates a query like this:
```
POST /test-events/events/_search?ignore_unavailable=true
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "term": {
                  "idx.friendlyerroridentifier-s": {
                    "value": "Foo-7967BB"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

When it passes it creates a query like this 
```
POST /test-events/events/_search?ignore_unavailable=true
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "match": {
                  "idx.friendlyerroridentifier-s": {
                    "query": "Foo-7967BB",
                    "type": "phrase"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

Note: The second query creates a warning which we need to fix in elastic 6.. `#! Deprecation: Deprecated field [type] used, replaced by [match_phrase and match_phrase_prefix query]`

**Comment by niemyjski** [comment]
@TristanGaydon @ejsmith  I think I narrowed this down This fails if the server mapping isn't up to date which happens once a minute. If you wait a minute after inserting this event does the search results work? If not, please let me know.

**Comment by TristanGaydon** [comment]
@niemyjski unfortunately not; I'm unable to successfully search on any extended data field of type string regardless of the time I wait since it was submitted (I tried searching on exceptions from days and weeks ago).

**Comment by niemyjski** [comment]
This has been fixed in the elastic 7 branch and will go out in the next major release.
