### ISSUE TITLE
Improve implementation of high concurrent elasticsearch operations instead of `RetryOnConflict`

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless#328]
In high concurrent environment, the option `RetryOnConflict` for elastic operations is not reliable and there will be errors reported as following:
`
StackRepository Error occurred incrementing total event occurrences on stack "59cc6fe3bff2a3c6f00d7961". Error: Type: version_conflict_engine_exception Reason: "[stacks][59cc6fe3bff2a3c6f00d7961]: version conflict, current version [8360562] is different than the one provided [8360561]"
`
The RetryOnConflict has double-edges, although it can improve the success rate, but at the same time it will slow down the elasticsearch updating performance.
more information refer to: https://github.com/exceptionless/Exceptionless/commit/de17ef8ca10d98552e43e16c8d72a990b2419f77

**Comment by ejsmith** [comment]
Yeah, I'd love to see a PR taking a shot at this. I think we could just do something using the cache client to increment a value and then sync it to ES every X seconds. Something similar to what we are doing here:

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Services/UsageService.cs

**Comment by edwardmeng** [comment]
Thanks for your reference. I have noticed that in the UsageService, the usage count have been incremented in ES and cache at the same time, but not sync cache usage to ES every X seconds. So it improved the reading performance for the `GetUsage` method, but not the writing performance of the `IncrementUsage` method.

**Comment by niemyjski** [comment]
We increment in cache only (IncrementIf's) and populate the model from that. https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Services/UsageService.cs#L109 shows we check to see if it should be saved on the repository too. I'm not sure on your last sentence, we only save if usage just exceeded the limit or the last save was 5 minutes ago.

It would be nice to have some kind pattern here (sounds like a saga) that could be reused that basically says, for this giving time period of x, increment the stats and persist it at the end of this period or if this metric / value exceeds this threshold. It would be awesome if this could service restarts and handle saves of old data (but not required for first pass). The usage is a hot code path too and if we can optimize this (we've tried to make it faster and faster every now and then), the difference is the stack count needs to be saved more often as stats in the UI will reflect poorly. I'm fine with the grids being wrong but perhaps the stacks/id end point needs to pull updated metrics / we need to see how those stats are being loaded and pull those from cache.

**Comment by edwardmeng** [comment]
I'm trying to fix this and will request new pr for this issue after performance testing.

**Comment by edwardmeng** [comment]
We have done the draft version changes, and did some performance testing.
Before changes, there are 6973 events/second will be saved to elasticsearch
After changes, there are 7507 events/second will be save to elasticsearch
And there is no error anymore.

**Comment by niemyjski** [comment]
@edwardmeng awesome, is this on the current asp.net core master branch or old (if it's old, I'm curious what your numbers are against the current as I've done some more perf work but have some things we can do to get even more perf out of the system (Add a middleware for posting and batch up the saving of the payloads) :))?

**Comment by edwardmeng** [comment]
@niemyjski we have done the performance testing against the old netfx environment, the latest version before you update to netstandard 2.0
When the performance testing completed, we will request a new pr for this. but it will requires a new job to save stack event count separately.

**Comment by niemyjski** [comment]
Thanks for the PR!
