### ISSUE TITLE
Custom properties via api

### ISSUE THREAD

**Issue by matthew-churcher** [exceptionless/Exceptionless#330]
I'm sending a exception using @simple_error and the events api. How do I add custom properties like a hostname. It's not in any of the examples.
This is for python for which I understand there currently isn't an SDK. Tia matt

**Comment by niemyjski** [comment]
Hey,

You'd just need to put it in the data dictionary and we'll just pick it up. If you have any questions please let us know. Also, We'd be more than happy to accept a pr or a gist for a python client/wrapper :)

Just a heads up, we may change how we index custom properties in the very near future (probably going to need to map them in configuration somehow, we have yet to discus, but sending them below wouldn't change).

```json
{
  "data": {
     "HostName": "test"
  }
}
```
