### ISSUE TITLE
Self-hosting success, but the page opens is blank

### ISSUE THREAD

**Issue by Varorbc** [exceptionless/Exceptionless#335]
Self-hosting success, but the page opens is blank，please help me

exceptionless version : 4.1.2
elasticsearch  version : 5.5.2

**Comment by niemyjski** [comment]
Can you please elaborate on which page opens blank?

**Comment by Varorbc** [comment]
login

**Comment by niemyjski** [comment]
Can you please open the developer tools in your browser and take a screen shot of this page as well as the developer tools (after refreshing the page)

**Comment by Varorbc** [comment]
in server

![6 is y nratkrii si7 o](https://user-images.githubusercontent.com/5714438/34280937-2501c4a8-e6f6-11e7-9600-be40e539b047.png)

is blank

in client 
is ok

**Comment by niemyjski** [comment]
Thanks for that, it looks like you are getting two script errors and one of them is related to angular. Is there any chance you could copy the full stack trace (as text) of those two errors here so I can take a closer look. Also does this work in any other browsers?

**Comment by Varorbc** [comment]
stack:"TypeError: 无法获取未定义或 null 引用的属性“fn”
at Anonymous function (/app.min.a62ad1efed547861.js:6:22870)
at Anonymous function (/app.min.a62ad1efed547861.js:6:12076)
at Global code (/app.min.a62ad1efed547861.js:6:11759)"

stack:"ReferenceError: “angular”未定义
at Anonymous function (/app.config.77fc9ddd679d37dc.js:4:3)
at Global code (/app.config.77fc9ddd679d37dc.js:1:2)"

**Comment by niemyjski** [comment]
I'm really not sure on that error. Can you try in a different browser and see if you get the same errors. Also are there any failed requests?

**Comment by Varorbc** [comment]
other browser is ok

**Comment by niemyjski** [comment]
I'm really not sure on this error. What version of internet explorer are you using?

**Comment by metavige** [comment]
I have same issue. But I check Chrome DevTools, see some errors for 404.
I  installed into the application, Not a Web Site.

So I change all path in index.html, it's ok.

**Comment by niemyjski** [comment]
How did you deploy exceptionless? What version of IIS are you using? So you mean you are using a virtual directory?

**Comment by niemyjski** [comment]
I'm going to close this, if this is still an issue and respond with the information above.
