### ISSUE TITLE
hoping to provide a mechanism to set OccurrencesAreCritical

### ISSUE THREAD

**Issue by majian159** [exceptionless/Exceptionless#336]
The default does not repeat the notification.

We hope exceptions will always be notified via webhook, but 'OccurrencesAreCritical' defaults to false, which will have a lot of work to set for 'Future Occurrences Are Critical'.

**Comment by niemyjski** [comment]
Hello @majian159, thanks for opening an issue. Can you please explain what your goal is. I'm assuming you are wanting to get notified of every single occurrence that comes in? If that is the case then marking them as critical is not the solution.

**Comment by majian159** [comment]
@niemyjski Thanks, I will try it soon.

**Comment by niemyjski** [comment]
I'm curious, any reason you want a web hook notification for every occurrence?

**Comment by majian159** [comment]
Yes, the cost of accessing webhooks is very low, and we want to notify every error.

**Comment by niemyjski** [comment]
They aren't really low cost unless the server being called has no timeouts, and is low latency and not a very high throughput of events coming in (but still overhead involved). I'm just curious what is being done with every web hook occurrence.

**Comment by majian159** [comment]
Send an error message to an IM software,It doesn't matter if it fails.

**Comment by ejsmith** [comment]
I’m guessing @majian159 doesn’t get a lot of events and that is why he wants notification on all of them. It seems pretty reasonable for small projects or ones that are sending only select events or just don’t have many exceptions.

**Comment by majian159** [comment]
Yeah, one day we missed a lot of timeout exceptions (redis, sql and more) and we think every exception is important.

**Comment by niemyjski** [comment]
Yeah, I get wanting that just was curious how it was being used so we can get a better idea of usages and take that into consideration when working on features/functionality. It would be nice to open this up a bit and give rate based notifications / followup on exceptions once a day.

**Comment by majian159** [comment]
This is very good.

**Comment by niemyjski** [comment]
I'm closing this issue as this can be achieved by wiring up to the Submitting Event handler on the Exceptionless client and mark the event as critical, if you need any help doing this I'd be more than happy to help. I'm also going to update the notifications issue to make a note about web hooks and getting notified more frequently.
