### ISSUE TITLE
ArgumentOutOfRangeException: startIndex

### ISSUE THREAD

**Issue by wsrf16** [exceptionless/Exceptionless#341]
Today when I access to exceptionless It throws exception:
------------------------------
   System.String.Substring(Int32 startIndex, Int32 length) +14415512
   Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.GetIndexVersion(String name) +186
   Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.GetIndexDate(String index) +52
   Foundatio.Repositories.Elasticsearch.Configuration.VersionedIndex.<GetIndexesAsync>b__28_3(CatIndicesRecord i) +54
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +223
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +281
   System.Linq.<GetEnumerator>d__1.MoveNext() +229
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +452
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +70
   Foundatio.Repositories.Elasticsearch.Configuration.<GetIndexesAsync>d__28.MoveNext() +1935
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Foundatio.Repositories.Elasticsearch.Configuration.<GetIndexesAsync>d__36.MoveNext() +353
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Foundatio.Repositories.Elasticsearch.Configuration.<MaintainAsync>d__33.MoveNext() +345
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Foundatio.Repositories.Elasticsearch.Configuration.<ConfigureIndexesAsync>d__31.MoveNext() +884
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Exceptionless.Core.Extensions.<RunStartupActionsAsync>d__1.MoveNext() in C:\projects\exceptionless\src\Exceptionless.Core\Extensions\ContainerExtensions.cs:20
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Exceptionless.Api.AppBuilder.Build(IAppBuilder app, Container container) in C:\projects\exceptionless\src\Exceptionless.Api\AppBuilder.cs:97

**Comment by niemyjski** [comment]
Thanks for the report, @wsrf16 Could you please get me a list of your elastic indexes: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_list_all_indices.html Also what version of Exceptionless are you using?

**Comment by wsrf16** [comment]
Exceptionless.4.0.2816
By the way, the elasticsearch has been upgraded to 6.1.1.Whether it make exceptionless work abnormally?

**Comment by wsrf16** [comment]
green  open   events-v1-2017.11.20            5nzNk3NEQQaudkt8LUtexg   3   1       4119            0      8.9mb          4.4mb
green  open   events-v1-2017.11.30            qOn_I1s6SpumwYiYXP4SnQ   3   1      23916            0     45.9mb         22.9mb
green  open   events-v1-2017.12.19            3In56z3zRTGyl0trpc3uSw   3   1        369            0      1.3mb        702.2kb
green  open   events-v1-2017.11.02            _BtXcRpGQyaqxcrWln1dYw   3   1        680            2        2mb            1mb
green  open   lxrelation                      i_pAGIyITn6uaVVsEoM4ww   3   1   28684992            0      6.9gb          3.7gb
green  open   events-v1-2017.12.20            6xAekcv-Qv6qnWSC6ZeKhw   3   1       5578            0      9.6mb          4.8mb
green  open   .monitoring-kibana-6-2018.01.10 HNi9c2W-T-OCLhy5Rq8JeQ   1   1       3175            0      1.6mb        831.6kb
green  open   events-v1-2017.11.13            5iHhDq-XT72rZVb8iu3wKw   3   1          5            0     86.1kb           43kb
green  open   events-v1-2017.11.08            3L1XBLMqQgGVucuvzvqTBA   3   1       9920            0     18.3mb          9.1mb
green  open   organizations-v1                VJxq7eEeSLuSCEmenpjOTA   1   0         21           17     53.6kb         53.6kb
green  open   .monitoring-es-6-2018.01.10     v4niA2CERm2SvknjQeGxvw   1   1     441178         4862    420.2mb          229mb
green  open   .monitoring-kibana-6-2018.01.05 KZnXykcQQzi2oXR2Sntu7w   1   1       8631            0      4.2mb          2.1mb
green  open   productindex                    2GhjwTtVQSyAf5wocPmajg   5   1         11            0      119kb         59.5kb
green  open   logstash-2017.11.13             _UQBUb4IRkeQX8BXLE43Ow   5   1          3            0     41.2kb         20.6kb
green  open   events-v1-2017.12.22            ISIthpVeTBKirIqa-JzpFw   3   1       2315            0      5.1mb          2.5mb
green  open   events-v1-2017.11.16            ZmfjPuFBR-akA1ylLf1_Dg   3   1         60            0    464.3kb        232.1kb
green  open   events-v1-2017.12.11            En7JJHckTY6s5l09JAWmGw   3   1       3311            0      5.2mb          2.6mb
green  open   .monitoring-kibana-6-2018.01.07 n_HmsKu9Q_-Jh9mrN_akOQ   1   1       8631            0      4.2mb          2.1mb
green  open   .watches                        zsa5WakZQo-_fjk16AfJww   1   1          0            0       530b           265b
green  open   events-v1-2017.12.08            MHATk2UYRNSrBu5LpO8lzg   3   1       5745            0      9.8mb          4.9mb
green  open   events-v1-2017.11.14            uuIwrMu8TL2xi8COK3_rOQ   3   1       1894            0      3.9mb          1.9mb
green  open   .monitoring-kibana-6-2018.01.09 IF4oPkLrTbKq_FzhAThSxw   1   1       8630            0      4.1mb            2mb
green  open   events-v1-2017.11.03            3ggTUp0ISAOrYtr6PIRemA   3   1       3281            7      7.4mb          3.7mb
green  open   events-v1-2017.12.14            uEeaqSerRaaKu6nQzt0GPQ   3   1        105            0    536.2kb        268.1kb
green  open   events-v1-2017.11.10            HW5U2y8wR5OuFRbQau8g9Q   3   1      11667            0     22.5mb         11.2mb
green  open   .kibana_wym_bak                 wlpK9gHqSq6GDb5aTok6wA   5   1         52            0    370.8kb        190.1kb
green  open   events-v1-2017.12.25            WXWpVKsuQ_ihdYb5G90W1g   3   1         40            0    457.9kb        228.9kb
green  open   .monitoring-kibana-6-2018.01.03 vSBwuvfGSBicDzF2VJkJ0Q   1   1       8630            0      4.2mb          2.1mb
green  open   events-v1-2017.12.21            Kkr884PEQ6y2gLhoZdA7Fg   3   1       4873            0      8.7mb          4.3mb
green  open   events-v1-2017.11.29            E1bxvhSKRduETG0VKHh6PA   3   1      18611            0     36.5mb         18.2mb
green  open   events-v1-2017.12.07            XUy9QUnkR1CRc4-8AeOetQ   3   1       2743            0      4.6mb          2.3mb
green  open   events-v1-2017.12.13            8eEIUtRlSNi6LVREgc26wg   3   1        446            0      1.3mb        673.5kb
green  open   events-v1-2017.12.15            jMCCbHo5Tu-eqGYSf2xYMg   3   1        243            0    699.7kb        349.8kb
green  open   .monitoring-es-6-2018.01.05     5riKN5fSRuqfOt30FeY3kA   1   1    1312853         5272    930.6mb        474.2mb
green  open   .kibana_b_bak                   jdo8yWcIR2ubbWOkKlTdEg   5   1         12            0    122.6kb         61.3kb
green  open   .monitoring-es-6-2018.01.03     IajaD6DdRD-3scxBQi5Cug   1   1    1319040         6152    930.6mb        472.8mb
green  open   events-v1-2017.11.23            7w2vf49lSESNhVjeph88Tg   3   1       3060            0      6.1mb            3mb
green  open   events-v1-2017.11.07            Y9h9bREwR0WoBHdisK19yg   3   1       2539            0      4.7mb          2.3mb
green  open   events-v1-2017.12.04            e6aEhGTqQPSiWaxl2SmpgA   3   1       2900            0      6.1mb            3mb
green  open   events-v1-2017.11.06            QgjYXcePS_yQnu84Cm_KXw   3   1        352            0      1.2mb        660.8kb
green  open   events-v1-2017.11.15            NC2YKYTFQcaqgABFs3Oehg   3   1       3197            0        7mb          3.5mb
green  open   lxcmtgeo                        aUw5T365TW6gCUllu_h75Q   3   1    2261880            0    912.2mb        456.1mb
green  open   events-v1-2017.12.12            4qvybYiQRb63GeZgA1kbrg   3   1        767            0      2.6mb          1.3mb
green  open   .monitoring-es-6-2018.01.04     R_Ao-f4VTb-oWHx2qw8peQ   1   1    1312407         5714    946.7mb        475.8mb
green  open   .monitoring-kibana-6-2018.01.08 cnVUo0yPQB6ENGUhn7KmkA   1   1       8631            0      4.2mb          2.1mb
green  open   events-v1-2017.12.09            pE5Q4BVMRzO7QE3YNESzxA   3   1       5368            0      8.6mb          4.3mb
green  open   stacks-v1                       gL1EQdAxRg-_8H7K0oKyeQ   1   0         67            5     72.4kb         72.4kb
green  open   .monitoring-es-6-2018.01.09     Jy6XULK5SNCS7gOocWmHAQ   1   1    1312850         5714    935.4mb          468mb
green  open   .monitoring-es-6-2018.01.07     sxUzeVowSHmdKaR4_M3TJA   1   1    1312856         4804    930.9mb        465.8mb
green  open   events-v1-2017.10.30            -MX0QABWRsCwa2bsP1DCQg   3   1       5471            0      7.5mb          3.7mb
green  open   events-v1-2017.12.18            DgNBHuf3Sn-Lb_h5lmlFfA   3   1        267            0    912.8kb        456.4kb
green  open   events-v1-2017.11.09            tMOUDBRiRgS57HBQyYrqPQ   3   1       9194            0     17.8mb          8.9mb
green  open   events-v1-2017.11.22            LDkewqfyS5yWLJHm5uXmkQ   3   1          4            0     86.4kb         43.2kb
green  open   .monitoring-kibana-6-2018.01.06 GbCrxfRITc6zFaLB1jjIfw   1   1       8630            0      4.2mb          2.1mb
green  open   lxrewards                       XQu8VnqHTruq_6WP4FsJ5A   3   1      10016            0      5.7mb          2.8mb
green  open   news                            SdMm-8olSbCKu8MqfMNLOw   3   1       3584            0     56.5mb         28.2mb
green  open   events-v1-2017.11.28            3EUCOUUKQQKIW5F53Tr_iQ   3   1      20539            0     36.6mb         18.3mb
green  open   events-v1-2017.12.05            y37FtuZQTnCQPR1OmdFGFQ   3   1          4            0     64.4kb         32.2kb
green  open   events-v1-2017.12.01            2SXUzlPwRbmP2uZnQFcXeA   3   1      10502            0     20.1mb         10.1mb
green  open   events-v1-2017.12.06            W_pp-VfVT4KzHtq3tltOTg   3   1       3768            0      4.2mb          2.1mb
green  open   .kibana-6                       AGTlMSNhTJuJ8XQ4Z1KReQ   1   1         52            1    190.5kb         98.3kb
green  open   .monitoring-es-6-2018.01.08     GLWjONjIS0qcNnRvXlDF1Q   1   1    1312325         4392    934.5mb        466.4mb
green  open   res_center                      ZqC0jsHWQf6gQevy89jExA   3   1     569146            0      1.8gb          934mb
green  open   .monitoring-kibana-6-2018.01.04 -YX_cnc0QzeBGroMh0H4Iw   1   1       8630            0      4.2mb          2.1mb
green  open   events-v1-2017.11.27            Xi-Fm31vQkij76Poyj0x1Q   3   1       6593            0     10.6mb          5.3mb
green  open   events-v1-2017.11.21            wxS-0oskT8uR2G1dtUDZ7w   3   1       4855            0      8.1mb            4mb
green  open   .monitoring-es-6-2018.01.06     ZY8PZyfqSvi2Wss9VYHPCA   1   1    1312770         3958    941.7mb        468.2mb
green  open   events-v1-2017.11.24            muDALz-yR8eIE_4O6F8bGg   3   1       8116            0     14.6mb          7.3mb
green  open   .kibana-541                     6SgX8wnMQrGwAwvSijjZwQ   5   1         40            0    305.7kb          162kb

**Comment by niemyjski** [comment]
Exceptionless will not work on 6.11, it may work for a day but it will not work tomorrow when the next daily index needs to be created. Please revert to 5.6.5

**Comment by niemyjski** [comment]
Are you still running into this exact same error? I'm not seeing any index names that would be in an improper format, they all look great and should be parsed properly.

**Comment by wsrf16** [comment]
It is test environment.I prepare to revert to 5.6.5.
Another question:Only less than 10 messages can be listed in "Most Frequent" one time.How can I see more?
![image](https://user-images.githubusercontent.com/11867768/34803709-bbb19ad6-f6af-11e7-983c-fc2c30450573.png)

**Comment by niemyjski** [comment]
You can change to the most frequent view using the navigation to show 20 items.
