### ISSUE TITLE
I download 4.1.2816 version, Windows Defender tell me jobs execution file has trojan

### ISSUE THREAD

**Issue by metavige** [exceptionless/Exceptionless#348]
When I unzip zip file to IIS C:\inetpub\wwwroot, Windows Defender tell me those files are trojan.

Windows Defender Message: 
App_Data\jobs\continuous\RetentionLimit\RetentionLimitsJob.exe

Trojan:Win32/Peals.F!cl

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=%3CTrojan%3aWin32%2fPeals.F!cl%3E&threatid=%3C2147691764%3E

**Comment by caesay** [comment]
fwiw false positives for `Trojan:Win32/Peals.F!cl` have been poping up everywhere today with MSE.

https://www.google.co.uk/search?q=Trojan%3AWin32%2FPeals.F!cl+false+positive&rlz=1C1CHBF_en-GBGB778GB778&oq=Trojan%3AWin32%2FPeals.F!cl+false+positive&aqs=chrome..69i57j69i58j69i61l2.2743j0j7&sourceid=chrome&ie=UTF-8

@metavige your solution is to add an exclusion to MSE so it doesn't scan that file: https://answers.microsoft.com/en-us/protect/forum/protect_defender-protect_scanning/how-to-exclude-a-filefolder-from-windows-defender/f32ee18f-a012-4f02-8611-0737570e8eee

**Comment by niemyjski** [comment]
Thanks for letting us know about this. This is definitely a false positive / bad definition from Microsoft. There definitely is not a trojan or virus in the code (unless GitHub was somehow compromised and the file hash also changed which is very unlikely). Is there any good way to report this to Microsoft or do you think they are definitely working on this (Can you make sure to submit this as a false positive)?

I just scanned with eset:

<img width="675" alt="screen shot 2018-01-04 at 8 36 25 am" src="https://user-images.githubusercontent.com/1020579/34568118-654fde76-f12a-11e7-9b27-1429becd7b3a.png">

**Comment by niemyjski** [comment]
I'm going to close this for the time being, but will keep actively looking into this.

**Comment by metavige** [comment]
OK, thanks.
