### ISSUE TITLE
Server process affect when we use exceptionless

### ISSUE THREAD

**Issue by LTAravindh** [exceptionless/Exceptionless#350]
Hi,

I have used self hosted exceptionless in my application. My application throws 1000 error per hour. So, my application send 1000 requests/hour to exceptionless to log error. Hence, my application server gets hanged.

How can we avoid this issue?

Thanks,
Aravindh

**Comment by caesay** [comment]
1000 event per hour is 16 events per second, which should not be a problem. What kind of hardware are you running exceptionless on? what hardware are you running elastic search on? Can you see that the resources (CPU, Disk, Ram, etc) on one or both of those machines is being utilized at 100%? if so, you need to upgrade your servers.

Can you describe your issue a bit more? what application server is hanging - exceptionless or your own app? does it recover? etc.

**Comment by niemyjski** [comment]
Also, what version of the exceptionless server are you running?

**Comment by niemyjski** [comment]
Can you please send us more information along with any event logs or stack traces of where the hang is occurring. Also, are you running jobs out of process? We will be releasing asp.net core support which we've fixed a dead lock in the event processing job / slow preforming code. We are still doing optimizations but it's really promising. I'm going to close this for now, but will reopen once we get additional information.
