### ISSUE TITLE
Lost some logs

### ISSUE THREAD

**Issue by MaxXue** [exceptionless/Exceptionless#356]
Foreach 100 logs , we get 97/98 logs In the website, it's lost 1-2 logs.
 it not some error logs output in the ES Logs and Website Logs.
we used ExceptionLess-4.1.2861 and elasticsearch-5.1.2。
I hope to get your help。

**Comment by niemyjski** [comment]
Are you using redis for persistent storage? Did iss reset?

**Comment by MaxXue** [comment]
some friends tell me ,you can use redis + EventJob. I try it do my best, But It does't work. could you help me how can i  use redis . I will thank you very much

**Comment by niemyjski** [comment]
You just need to follow the steps here: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#redis If you can send me the steps you are using to submit the 100 log messages. I can attempt to reproduce.

**Comment by MaxXue** [comment]
My project is .NET Core WebApi . 

In the controller :

        try
            {
                throw new ApplicationException(Guid.NewGuid().ToString());
            }
            catch (Exception e)
            {
              for (int i = 0; i < 100; i++)
              {
                    string guid = Guid.NewGuid().ToString().Replace("-", "");
                    ExceptionlessClient.Default.CreateLog(typeof(ValuesController).FullName, guid, LogLevel.Info)
                    .AddTags("Test")
                    .SetUserIdentity(new UserInfo() { Identity = "00001", Name = "xhf" })
                    .Submit();
               // _log.InfoFormat("{0}", guid); // User Log4Net  in Local
              }
            }   

In the StartUp.cs 
`app.UseExceptionless(Configuration);`

In the appsettings.json
`"Exceptionless": {
    "ApiKey": "f1gA7EMWX5BMsyfu8GnbBfZ6PKyZhjXogSbkJ2ok",
    "ServerUrl": "http://192.168.1.132:8004" 
  }`

The ES and ExceptionLess Website follow your wiki the steps:

**Comment by MaxXue** [comment]
I follow your wiki steps and configure redis . It's working. 
but it still losts 2 logs. I send 100 logs, the logs dashboard count 98 logs. 
I have tried many times。It's 98%.

**Comment by MaxXue** [comment]
my friend tell me ,it maybe  IISExpress problem.
So I used iis to review this question,
it's better. three times (300logs) , it lost 2 logs。

**Comment by niemyjski** [comment]
I’ll try and run 1k logs through and see if I see anything with the code above

**Comment by niemyjski** [comment]
I've been able to reproduce this issue and dug through the logs and don't see anywhere where it's being cancelled. I'm working on creating a unit test to reproduce so we can dig deeper into this issue.

**Comment by MaxXue** [comment]
so it's a realy bug ？
I can give my website and EL、ES's config to help you find what's happen.
my friends tell me, he did't find any questions.
If you want any help , let me konw .
THANK YOU!

**Comment by niemyjski** [comment]
I tracked this down and it was fixed in the client here (https://github.com/exceptionless/Exceptionless.Net/commit/5643f52fa645bb6e6cda797109cce368a139f077). It had to do with the default in memory storage was capped at 100 items. I've boosted this to 1k and it will go out with the next release. Please let me know if you need me to push this sooner than later. I'd like to build up any other fixes into this release.

**Comment by niemyjski** [comment]
The client is now available on nugget and release notes are here: https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.2.2
