### ISSUE TITLE
Add MS Teams integration

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless#360]
Similar to the Slack integration, add a Teams integration that sends the correct JSON to the incoming webhook on the Teams side.

Card reference:
https://docs.microsoft.com/en-us/outlook/actionable-messages/card-reference

So we can have buttons to go directly to the stack and/or event like so:
![Thumbnail card example](https://docs.microsoft.com/en-us/microsoftteams/platform/assets/images/cards/thumbnail.png)

Playground:
https://messagecardplayground.azurewebsites.net/

**Comment by srijken** [comment]
Sample payload
```
{
	"@type": "MessageCard",
	"@context": "http://schema.org/extensions",
	"summary": "Exception in Get Test",
	"text": "Exception in Get Test",
	"themeColor": "6ebc1a",
	"title": "System.Exception: Test",
	"sections": [
		{
			"facts": [
				{
					"name": "Project",
					"value": ".NET Sample"
				},
				{
					"name": "Error type",
					"value": "System.Exception"
				},
				{
					"name": "Version",
					"value": "1.0.0.0"
				},
				{
					"name": "URL",
					"value": "http://localhost:52998/api/sync?text=dan"
				}
				
			],
			"potentialAction": [
				{
					"@type": "OpenUri",
					"name": "View event",
					"targets": [
						{ "os": "default", "uri": "https://be.exceptionless.io/event/5aaa8bbc174cf217ec2d6c63" }
					]
				},
				{
					"@type": "OpenUri",
					"name": "View stack",
					"targets": [
						{ "os": "default", "uri": "https://be.exceptionless.io/stack/5aa9b314f1eb5243644ed0c5" }
					]
				}
			]
		}
	]
}
```

Which results in:

![image](https://user-images.githubusercontent.com/1292085/37687025-3eb6e3bc-2c9a-11e8-9d1c-53f281d58a31.png)

**Comment by niemyjski** [comment]
@srijken have you had any more luck in teams support? Could you please submit a pr :)

**Comment by venkatesan-r-1509** [comment]
@niemyjski @srijken Do we have any updates on this? I tried adding into MS Teams generic webhook and not getting any.

**Comment by niemyjski** [comment]
I haven't heard anything on this from @srijken, I'll try and ping him.

**Comment by SeppPenner** [comment]
This would be a cool feature.

**Comment by niemyjski** [comment]
I'm going to close this until we get a pr or enough upvotes/comments. I'd also like to have this functionality but I do not have a teams account. If someone wants to open a pr for this that would be greatly appreciated and welcomed. It should be as straight forward process as we've already done the work for slack integration.

**Comment by SeppPenner** [comment]
When I have time, I can take a look at this. I can't promise anything, however.

**Comment by SeppPenner** [comment]
@niemyjski Where do I have to look to here? Or which interfaces need to be implemented?

**Comment by niemyjski** [comment]
I don't think there are any specific interfaces for this, Take a look at how we implemented slack, and then basically clone it to meet teams. We can refector later once it's working

**Comment by SeppPenner** [comment]
I need to work myself into Teams, but the API doesn't look that complicated.
