### ISSUE TITLE
How do I integrate Logstash?

### ISSUE THREAD

**Issue by leehavin** [exceptionless/Exceptionless#362]
How do I integrate Logstash?
I want to use Logstash to collect logs, can I add to exceptionless?

**Comment by niemyjski** [comment]
We don't integrate with log stash, one thing you could do is to use a logging framework like serilog and write to both exceptionless (using our serilog target) and log stash. You could also just write to us if you are self hosting and then use kibana dashboards ontop of our indexes. I hope this helps.
