### ISSUE TITLE
what's the roadmap for .net core?

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless#364]
hi guys:
in "https://github.com/exceptionless/Exceptionless/issues/329"
you said “ We are working on an asp.net core release which has **much much much** better performance and will really be awesome release :)”

I 'm eager to get this.
aha, so what's the roadmap of the .net core release? :)

**Comment by niemyjski** [comment]
Hey, we have the master branch that’s asp.net core and we’ve been running it in production since Christmas, we’ve been working through all the issues that have came up and need to work on the release artifacts so we can cut a release soon

**Comment by niemyjski** [comment]
I'm going to close this as we plan to release asp.net core support for the next release and hopefully soon. If you need it now, you can grab it from the master branch and reply to this issue if you need any help :).

**Comment by ZhiqiangTao** [comment]
cool cool cool
