### ISSUE TITLE
Question about "Running jobs out of process"

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless#365]
Now, I want to "Running jobs out of process" to pick up speed to write logs, but I found the folders("D:\Exceptionless.4.1.2861\wwwroot\App_Data\jobs\continuous") as below:
 **CloseInactiveSession
 DailySummary
 EventNotification
 EventPost
 EventPost2
 EventPost3
 EventPost4
 EventUserDescription
 MailMessage
 RetentionLimit
 WebHook
 WorkItem
 WorkItem2**

I am puzzled which job should be ran? only EventPost? or both EventPost2+EventPost3+EventPost4?
because they seem that have the same folder's name, only the suffixes are different.

**Comment by niemyjski** [comment]
If you configured the website to run out of process then you'll need to run all of those, you can exclude the ones that are suffixed with numbers (they are just copies that make it easier to run on azure). I'd recommend leaving the website to run in process config setting and then run an extra EventPost job out of process then it's much easier to process more events without firing up lots of jobs.

**Comment by ZhiqiangTao** [comment]
cool, thanks a lot. 

 :( Before, I always think that If I want to run any job out of process, the "RunJobsInProcess" config  **must** be **true** in the website config.

**Comment by JamesLoveForever** [comment]
must be false

**Comment by niemyjski** [comment]
It doesn't have to be, it's just recommended in high throughput instances as it adds more work the main web app must do.
