### ISSUE TITLE
Can you provide Chinese language support In Exceptionless.Web?

### ISSUE THREAD

**Issue by Varorbc** [exceptionless/Exceptionless#366]
Can you provide Chinese language support In Exceptionless.Web?

**Comment by niemyjski** [comment]
Hello,

I'm not sure what all we'd translate server side (maybe email templates) but we'd be more than happy to accept pull requests for this. Would you be willing to fork this repo in the pr (https://github.com/exceptionless/Exceptionless.UI/pull/155) and reopen this pr with any changes that need to be done which I think are very limited. This would be greatly appreciated and a huge help as we are all native English speaking and need community assistance. 

In the mean time I'm going to close this issue to keep the issue list clean but we would LOVE community assistance on translating the app and wiki text / readme. Please let us know if you have any questions or how we can help assist by replying to this issue.
