### ISSUE TITLE
Slack integration on a self hosted instance

### ISSUE THREAD

**Issue by VishalMadhvani** [exceptionless/Exceptionless#367]
I am running a self hosted instance of Exceptionless and am trying to enable slack notifications.
Unfortunately the Add slack notifications button does not show on the Project Integrations page.
Having traced this, it seems to be due to not having a slack app id in app.config.*.js.

Can someone please advise what I need to do to make this work?
Do I need to create a custom slack application and if so how should this app be configured?

Many thanks

**Comment by niemyjski** [comment]
Hey, 

It's been a while since I configured ours but I believe I had to register a slack app (https://api.slack.com/docs/oauth) and use it that way.  I'll check into this bit more if creating an app is required. @ejsmith do you remember if users need to create a separate slack app?

**Comment by niemyjski** [comment]
Yes, it looks like you'll have to create an app to get your own app credentials for slack, please don't distribute the app outside your organization (it's an option when setting up as it would really confuse users seeing two exceptionless apps). Would you please add some documentation on how to do this to the wiki and let me know if you need any assistance. 

I'm going to close this to keep the issue list clean but feel free to reply with any questions.

**Comment by natehitze** [comment]
Added documentation for this to the wiki: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#enabling-slack-integrations

**Comment by VishalMadhvani** [comment]
Hey
Thanks for the responses.

I had mostly come to the same conclusion but had some questions.
When configuring the slack app, why does the Incoming WebHooks feature need to be enabled? It seems to work fine without it.
I had also added the chat:write:bot permission scope to the app. Is this unnecessary?

Otherwise, seems to work 👍

**Comment by natehitze** [comment]
Hm - it's possible it doesn't require it. There was a page I can't find anymore where I tried to remove it and Slack said my app depends on it so I couldn't remove it. I've turned off the Incoming WebHooks feature on mine to see if the integration still works. I'll update the docs if it turns out to definitely not be needed. Thanks!

I believe chat:write:bot is not needed. I don't have it added on my app.

**Comment by niemyjski** [comment]
We post data to slack via the incoming web hooks so I think that has to be enabled. But if it works without it than maybe not? where do you find the permissions for the app? I'm not seeing that anywhere.

**Comment by VishalMadhvani** [comment]
In the OAuth & Permissions screen, there is a Scopes section where you can add permissions.

**Comment by natehitze** [comment]
I've turned off the Incoming Web Hooks feature in my app and my integrations are still working and I can create new ones that are working as well. I've updated the documentation to remove the instruction to enable the Incoming Web Hooks feature.

**Comment by niemyjski** [comment]
The only scope we have is `Post to specific channels in Slack - incoming-webhook`
