### ISSUE TITLE
How can I block errors from a specific host or URL?

### ISSUE THREAD

**Issue by nmg196** [exceptionless/Exceptionless#368]
How can I block errors from a specific hostname or URL?  I realise you can disable it in web.config, but is there a way to block individual URLs?  There doesn't seem to be a "url" event type. 

Thanks
Nick

**Comment by niemyjski** [comment]
Do you mean like 404's (which is a not found event type)? If you wish to block from a specific host or url you'd need to write a client side plugin (https://github.com/exceptionless/Exceptionless.Net/wiki/Adding-Plugins) which could also talk to project configuration for real time settings. Does this help?

**Comment by niemyjski** [comment]
I'm going to close this for now, please see my previous response. If you need any assistance please let us know.
