### ISSUE TITLE
It's still delay after running extra “EventPost” jobs

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless#369]
I often meet the delay situation as below pic:
![1](https://user-images.githubusercontent.com/16182251/38652209-7e1f565c-3e37-11e8-887a-6b0de44b4b8e.png)

then I found that there were many cache keys left in the redis as below:
![default](https://user-images.githubusercontent.com/16182251/38652307-f8526b26-3e37-11e8-85a0-84d6619cf695.png)

so, I run extra two  “EventPost” jobs(I always ), and expect that the keys can be quickly reduced.
![default](https://user-images.githubusercontent.com/16182251/38652370-45fe10a0-3e38-11e8-8868-1168c504778d.png)

**But, actually, It also seems not work.... there are still many cache keys existed.**

some screenshots as below:
1.es:
![default](https://user-images.githubusercontent.com/16182251/38652489-cadcd50e-3e38-11e8-9955-49845b5b3164.png)
![default](https://user-images.githubusercontent.com/16182251/38652959-db8b5554-3e3a-11e8-8efc-28d46fd6f367.png)

2.exceptionless web host machine:
![default](https://user-images.githubusercontent.com/16182251/38652535-f9484338-3e38-11e8-8bb0-099cf892c311.png)

3.redis cache and redis docker container:
![default](https://user-images.githubusercontent.com/16182251/38652570-1f63add2-3e39-11e8-9105-f798c9986bfb.png)
![image](https://user-images.githubusercontent.com/16182251/38671164-3fa8e802-3e7d-11e8-8cd4-baef408291fb.png)

4.Code segment:
![default](https://user-images.githubusercontent.com/16182251/38652666-8f504d94-3e39-11e8-82a7-e93e5bd09836.png)

Note:
I don't remember which release version I used before, but in that version,  if I run extra “EventPost” jobs, both the speed of customing the message and the useage of the cpu in the host machine are obvious growth. however, the Exceptionless.4.1.2861 I used is not.

so, how to handle this situation, I want to be as fast as possible.:)

**Comment by ZhiqiangTao** [comment]
Note:the container of the redis is only used for Exceptionless.

**Comment by niemyjski** [comment]
Firing up more jobs should make it much faster unless you are IO Bound. What is your disk usage look like?

**Comment by ZhiqiangTao** [comment]
@niemyjski I run many other jobs, but there are many conflicts as below:
![image](https://user-images.githubusercontent.com/16182251/38712149-6904a86a-3efc-11e8-9f75-928ca19de223.png)
but the message is  still delay:
![image](https://user-images.githubusercontent.com/16182251/38712212-be4bff1c-3efc-11e8-9c77-ad1916d8ee5a.png)

other screen short:
![image](https://user-images.githubusercontent.com/16182251/38712170-849fb664-3efc-11e8-89cb-6508346dc7a0.png)
![image](https://user-images.githubusercontent.com/16182251/38712177-8e1c12fa-3efc-11e8-9d42-0cb305e1329f.png)
![image](https://user-images.githubusercontent.com/16182251/38712181-96673444-3efc-11e8-8aa7-2129ef1353cf.png)

**Comment by ZhiqiangTao** [comment]
@niemyjski yeah, I always restart the jobs before, just like you said above,  they seem to die off after a little bit of time.
just like that only one job (in web process) is working alone

**Comment by ZhiqiangTao** [comment]
![image](https://user-images.githubusercontent.com/16182251/38737391-9d7417d8-3f61-11e8-9aba-fa40a2eddc19.png)
hi, I have another issue in the pic:
1.the cache value **almost always** be 1(with 60s ttl) when I run N jobs for long time; 
2. the cache value  will be N+1(one is the web job instance and others are N jobs', I guessed) after I start N jobs **at first**.
3. does the lock cache key limit the speed of writing logs?

**Comment by ZhiqiangTao** [comment]
I am sure that all the hardware status are healthy

**Comment by ZhiqiangTao** [comment]
![image](https://user-images.githubusercontent.com/16182251/38739055-6a5e0a70-3f66-11e8-93a7-63fb012e0521.png)
I find some GC logs in my es docker container, does this will affect the speed?

**Comment by niemyjski** [comment]
Yeah, looks like a ton of time is spent collecting gc. Could you try increasing the ram on the Elasticsearch nodes (It's sitting idle is the weird part)? How much is specified now? Please note that I'm working on getting our asp.net core support out which did fix an issue with some dead locks that could occur in the jobs due to a bug in our DeepClone implementation when dealing with JTokens. This could also be what you are running into. I'll try and post back once I get a preview build done of master.

**Comment by ZhiqiangTao** [comment]
I use blow command to run my es container:
![image](https://user-images.githubusercontent.com/16182251/38740858-249f813a-3f6b-11e8-83f7-119902826ddb.png)
I have set "
![image](https://user-images.githubusercontent.com/16182251/38740900-3408660a-3f6b-11e8-9e77-fbe5a7a672d7.png)
"
but it seems not work for me.

**Comment by niemyjski** [comment]
That's going to set the min / max heap to 10gb of memory. Does your server have 10gb free? I show 15gb currently In use from that picture you sent. so if you have 3 nodes on that one box you don't have enough ram.

**Comment by niemyjski** [comment]
You want to set it to half the available memory if the box is dedicated to elastic, if you are using docker, I'd use half / 3 for each node.

**Comment by ZhiqiangTao** [comment]
![image](https://user-images.githubusercontent.com/16182251/38741186-e9c195c0-3f6b-11e8-971f-44953e3ec21a.png)
I have 3 nodes in different machines. I'm sorry

**Comment by niemyjski** [comment]
It's all good, the only thing I can think of is upgrading to elastic 5.6.8 docker image from 5.2 that you are using and see if that helps. We are running 5.6.8 in production.

**Comment by ZhiqiangTao** [comment]
thanks a lot, I will have a try in tomorrow

**Comment by ZhiqiangTao** [comment]
@niemyjski hi, I'm not use es 5.6.2, but I change my es cluster from "-Xms8g -Xmx8g" to ""-Xms7g -Xmx7g"" and restart  with the new env conig.
I find that both  the GC  times/s  and  the memory gc released are reduced:
![image](https://user-images.githubusercontent.com/16182251/38764170-5e2dd37c-3fdc-11e8-9c8c-a4395a68f805.png)
I guess that if there are many messages(large, frequent) need insert, the es GC will work frequently, but it seems that it will "**block**" somethings!

Now, the speed of writing message seems like well :)
**Thanks a lot**, I'm going to keep watching for much time, and will feedback in time

**Comment by niemyjski** [comment]
Thanks! Please keep a lookout on our releases page, we'll have the asp.net core support released within the next month (I Believe :). We've already fixed those errors you reported above:) I'm going to close this in the mean time, but please let us know if you have any questions.
