### ISSUE TITLE
ExceptionlessClient.Default.Startup(string) throws TinyIoCResolutionException (Xamarin Forms)

### ISSUE THREAD

**Issue by GeirGrusom** [exceptionless/Exceptionless#372]
```csharp
ExceptionlessClient.Default.Startup("xxx");
```

When calling this method I get the following exception
This is a Xamarin Forms application for Android

> TinyIoC.TinyIoCResolutionException: Unable to resolve type: Exceptionless.Logging.IExceptionlessLog
> Unable to resolve type: Exceptionless.Logging.NullExceptionlessLog

Exceptionless Version 4.2.1989

edit: added inner exception

**Comment by niemyjski** [comment]
What version of Xamarin are you using as well as what is the target framework settings? Are you using our .NET Standard 2.0 support? What all do I need to do to reproduce locally? @MihaMarkic Have you ran into this before?

**Comment by MihaMarkic** [comment]
It's been some time since I've used it. From error description I'd assume it's a linker issue - it strips out _unused_ code.
Make sure you mark the interface in question as required. Here is some [starting point](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker) to try out.

**Comment by niemyjski** [comment]
Thanks! Could you please try excluding our assembly using the starting
point link above and see if that fixes it.

>

**Comment by GeirGrusom** [comment]
Actually, the issue isn't quire resolved since the only way I get it to work is by not linking at all, even "Link Sdk Assemblies Only" breaks Exceptionless.

Disabling linking can be done in Project properties -> Android Options -> Linking but it's not really desirable.

I'll try to investigate what the actual issue is and see what I come up with.

**Comment by MihaMarkic** [comment]
That's interesting. I'd start with "Link Sdk Assemblies Only", see what exception is thrown and what type can't be resolved, mark that type as _required_, repeat until it works.

**Comment by MihaMarkic** [comment]
Also, can you create a simple as possible repro project?

**Comment by GeirGrusom** [comment]
That's what i was thinking, but I kind of feel like that's a little bit of a flimsy solution.

I'm debugging through it now and as far as I can see IExceptionlessLog *is* being registered as `NullExceptionlessLog`. What I do think is a little bit suspicious is that `RegisterDefaultServices` sets up each instance using a `Lazy<T>`. Now I haven't actually ever used TinyIoC before, but isn't that the default behavior of DI containers? Unless you pass an instance, a new instance will only be created when requested?

[Line in question](https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Dependency/DependencyResolver.cs#L32)

The documentation has this to say:

> By default TinyIoC will register concrete classes as multi-instance and interface registrations as singletons.

According to this, can't these lines be simplified to:

```csharp
resolver.Register<IExceptionlessLog, NullExceptionlessLog>();
```

**Comment by GeirGrusom** [comment]
It seems odd to me that the linker would remove `NullExceptionlessLog`. To me it seems that it's obviously in use.

**Comment by GeirGrusom** [comment]
@MihaMarkic yes, I'll try to make a trivial repro.

**Comment by GeirGrusom** [comment]
[Reproduction](https://github.com/GeirGrusom/ExceptionlessException)

**Comment by GeirGrusom** [comment]
Okay I've managed to get it to run using `PreserveAttribute`. Generally the issue is that the linker removes the constructors from a bunch of classes since they are only ever invoked by the IoC container.

I have sent an mail upwards before I sign the CLA, but just in case, here is a list of classes that I altered to make this work:

* NullExceptionlessLog
* HandleAggregateExceptionsPlugin
* EventExclusionPlugin
* ConfigurationDefaultsPlugin
* ErrorPlugin
* SimpleErrorPlugin
* VersionPlugin
* SubmissionMethodPlugin
* CancelSessionsWithNoUserPlugin
* DuplicateCheckerPlugin
* DefaultEventQueue
* InMemoryObjectStorage
* PersistedDictionary
* DefaultSubmissionClient

I added an internal class `PreserveAttribute` and applied this to each class `[Preserve(AllMembers = true)]`, though I suspect it's only required to be applied on the constructors since this is the only thing that the linker is normally incapable of figuring out.
