### ISSUE TITLE
Provisional headers are shown

### ISSUE THREAD

**Issue by Varorbc** [exceptionless/Exceptionless#374]
In Chrome

![image](https://user-images.githubusercontent.com/5714438/40639285-ba064dd0-6342-11e8-9d8d-b187e712fa36.png)

In Edge

![image](https://user-images.githubusercontent.com/5714438/40639305-e591daa0-6342-11e8-9772-52f194009530.png)

**Comment by Varorbc** [comment]
I pulled the latest UI and put it in the wwwroot directory and opened localhost:50000, and found that many resources were blocked by browsers.

**Comment by niemyjski** [comment]
Were you able to find the root cause?
