### ISSUE TITLE
log4net can not be transmitted to the server.

### ISSUE THREAD

**Issue by billy52123** [exceptionless/Exceptionless#375]
I use exceptionless on the API is normal, but when I use on the console can not be transmitted to the server.

**Comment by niemyjski** [comment]
Hello,

Can you please give us more information like the console messages.

**Comment by billy52123** [comment]
Sorry I forget I use to exceptionless.Log4net then My settings are as follows.
I use the log4net version 2.0.8.0 and  Exceptionless.Log4net version 4.3.2004.0
My settings is
<log4net>
  <appender name="RollingFileAppender" type="Exceptionless.Log4net.ExceptionlessAppender, Exceptionless.Log4net">
    <apiKey value="My API Key" />
    <serverUrl value="My Server Ip" />
    <param name="Encoding" value="UTF-8"/>
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%-5p %date{yyyy/MM/dd HH:mm:ss} %-20c{1} %-20M %m%n" />
    </layout>
  </appender>
  <root>
    <level value="ALL"/>
    <appender-ref ref="RollingFileAppender"/>
  </root>
</log4net>

This setting use to WebApi can finish but use to console it be fail

**Comment by billy52123** [comment]
OK I know problem but I try to use ExceptionlessClient.Default.ProcessQueue(); this can not use,but I try to sleep(10) that can walk.
Why ExceptionlessClient.Default.ProcessQueue(); can not to do

**Comment by niemyjski** [comment]
I'd recommend commenting out the server url and api key portion of this configuration and just setting it via the readme. When you specify it here, we create a second instance (that's internal) and not accessible and so calling anything on `ExceptionlessClient.Default` will not work.

**Comment by niemyjski** [comment]
Did this solve the issue?

**Comment by billy52123** [comment]
so I just can use sleep(10) to solve this question?

or have any method can solve this question.

**Comment by billy52123** [comment]
OK I know this question is solve.
very thank you.
you are a very good author.

**Comment by niemyjski** [comment]
I wouldn't call sleep but if you don't set the api key in the log4net config you can still call process queue on the default instance.
