### ISSUE TITLE
when mvc integerate webapi, how to config it?

### ISSUE THREAD

**Issue by tomkluas** [exceptionless/Exceptionless#376]
which package should be install ?
[Exceptionless.WebApi](https://www.nuget.org/packages/Exceptionless.WebApi/) or [Exceptionless.Mvc ](https://www.nuget.org/packages/Exceptionless.Mvc/) ?
if both install , visual studio tell me ExceptionlessClient in two dll
please help me!

**Comment by niemyjski** [comment]
Hello,

You can install both side by side and integrate together. You'll just need to follow both readmes and make sure both are of the same version. We do this for several of our projects. Please let me know if you have any questions or run into any issues.
