### ISSUE TITLE
new version？

### ISSUE THREAD

**Issue by Varorbc** [exceptionless/Exceptionless#377]
Is it possible to provide a roadmap and let us know when there is a new version?@niemyjski

**Comment by niemyjski** [comment]
Were working towards releasing the next version, it keeps getting pushed back. Were finalizing asp.net core with the new LTS version of core. Were actively working towards supporting elastic6 and running everything in Kubernetes. We are also have a little work to finish localization as there are a few small issues that have prevented us from deploying it (seems there are issues when deploying via iss)

**Comment by niemyjski** [comment]
We got the localization changed deployed, fixed some route issues. We are still seeing a ton of exceptions with some of the new stack stat changes that speed up the pipeline. I'm working on finishing up the unit tests for that and then we will cut a new release (you might have seen we bumped the major).

**Comment by Caskia** [comment]
Is there an update?

**Comment by niemyjski** [comment]
I'm working on updating the artifacts for release.

**Comment by Varorbc** [comment]
Excuse me, I asked again, how is the progress? Also want to ask if the new version supports elastic6

**Comment by niemyjski** [comment]
We got all the release artifacts and are working on cleaning up configuration as we decided we were already breaking it so we wanted to break it a bit further and do it how we want for the long term using ms config, which is in a branch right now with pr then we release. It will be on elastic 5, thinking we are skipping 6 and going to 7.

**Comment by niemyjski** [comment]
If you could help test the nightlies in master that would be greatly appreciated.

**Comment by Varorbc** [comment]
Sorry, I really can’t find a little time recently.

**Comment by niemyjski** [comment]
I just wanted to let you know we just pushed a new major version :) https://github.com/exceptionless/Exceptionless/releases/tag/v5.0.0
