### ISSUE TITLE
Exceptionless setup issue.

### ISSUE THREAD

**Issue by Johnwrnd** [exceptionless/Exceptionless#379]
I carefully followed the tutorial for self-hosting(production) [here](https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting) but didn't do any of the optional steps nor activated SSL. I installed ElasticSearch, setup the root in IIS, modified the web.config and added the ElasticSearch connection string(http://localhost:9200) and i can see the login page. However, i can't register because i keep getting the **"A user already exists with this email address."** message no matter the e-mail adress i enter. I can randomly enter letters and still get the same message. What exactly am I doing wrong? 

Thanks in advance for any help i may get here.

**Comment by fanslead** [comment]
See the HandleNonHttpsRequest(filterContext)
 ![image](https://user-images.githubusercontent.com/22066473/42753387-58ce48e0-8923-11e8-93a6-65d9e889f0ed.png)

**Comment by Johnwrnd** [comment]
Where is it located?

**Comment by Johnwrnd** [comment]
I will download the source code to modify it and use it then. I will report the results later then. Thanks!

**Comment by Johnwrnd** [comment]
I made the change and build a Release version(anycpu) with the solution. Do i have to overwrite the .dlls in the bin folder of the wwwroot? because i did that and can't run the application because of some assembly error which most probably is due to some mix framework issues.

**Comment by niemyjski** [comment]
Yes, did that solve the problem? What does it say as the error in the network tab of your browser. Have you tried the troubleshooting tips?

**Comment by Johnwrnd** [comment]
I copied the dll to the bin folder but as previously explained i get an error than a dependency could not be loaded.

![exception](https://user-images.githubusercontent.com/815025/42760208-01d319e4-890a-11e8-9f88-5850a8196873.jpg)

**Comment by niemyjski** [comment]
It's because the version you compiled with is different than what was out there. Can you go back to the release and try the troubleshooting tips and let us know what the network tab says when you try to signup

**Comment by Johnwrnd** [comment]
I will go through the troubleshooting tips and report back.

**Comment by niemyjski** [comment]
You'd just need to copy all the dlls that were compiled instead of just the one. No you don't need cabana when running in production mode. We're going to be moving the whole server to be docker releases for the next release to remove all of these issues. One thing you could do is generate an ssl cert or use the free ssl certs out there and install one for this web process.

**Comment by fanslead** [comment]
When will the new version of asp.net core be released

**Comment by Johnwrnd** [comment]
Glad to hear is going to be fixed in the next release but in the mean time what can I do? I commented the "HandleNonHttpsRequest" line and published a release then i took everything and replace the bin folder with it. It runs now but still stuck just like before with the same message.

![signup](https://user-images.githubusercontent.com/815025/42820371-4a1a4a0c-89d6-11e8-9359-1b4bc3e567b2.jpg)

**Comment by Johnwrnd** [comment]
btw....the MongoDB isn't needed anymore am I correct?

**Comment by niemyjski** [comment]
You can pull master and use the latest artifacts, we'll release it soon. We are about to cut the UI release and we are trying to hurry and finish up the 2.1 migration which is LTS.  

@Johnwrnd what does your network tab say for errors? MongoDB is no longer needed.

**Comment by Johnwrnd** [comment]
I got no errors anymore but was checking a old tutorial on how to build/publish master and setup the server from it and noticed MongoDB was used in the tutorial. I also noticed that the publish miss a lot of dlls found in the oficial release version(bin folder). All i need to know is what do i need and how to grab the master branch, publish it and get exceptionless ready to run just like the official release.

**Comment by Johnwrnd** [comment]
Actually all I need is a Release build with the fix suggested here and I will be happy until the next big update rolls out.

**Comment by niemyjski** [comment]
It's all in the appveyor yaml file. We'll work on pushing out a release really soon. Can you in the mean time add a cert to your site using lets encrypt?

**Comment by Johnwrnd** [comment]
Glad to hear that! i will try to add a cert but i already tried using the self-hosting tutorial and it didn't work. For some reaons it seems to refuse to use the database which is one of my main issues apart from login.

**Comment by niemyjski** [comment]
My apologies for the late reply. If you can jump on our slack and send a message I can try and take a look at this with you over screen share.

**Comment by Johnwrnd** [comment]
I joined Slack now.

**Comment by Johnwrnd** [comment]
Wanna thank you a lot for your great help once again!!! as suggested it would be great to explain the steps we did in case someone is going through the same issue.
