### ISSUE TITLE
Hello i have a problem

### ISSUE THREAD

**Issue by billy52123** [exceptionless/Exceptionless#381]
I want test the if Exceptionless can not connection it can write log to local?
I google this setting I try it (storagepath="D:\Test\ExceptionlessStorage")  add to web.config
(this is a webapi Project) but i disconnect internet it can not do anything.
please help me thanks~

**Comment by niemyjski** [comment]
The storage path only allows persistent storage of events (which helps if your app crashes randomly and those events will be submitted later on app restart at the cost of serialization overhead). If the submission client can't connect, by default it starts discarding future events. I'm assuming you want to log even while offline? If this is the case, you'd need to implement your own queue (copy our DefaultEventQueue and remove the logic for disabling the client).

**Comment by niemyjski** [comment]
Hello,

You'd have to write some code for this functionality. If no connection can be made events will be discarded. You'd need to implement your own event queue   or inherit from https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Queue/DefaultEventQueue.cs#L163 and change how suspend works so it's not suspended. Then you'd need to wire it up to the DI container (`client.Configuration.Resolver`), just look for usages of the DefaultEventQueue for more information.

Please let us know if you have any questions.
