### ISSUE TITLE
'Mark fixed' should accept version numbers as x.x

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#384]
Currently it requires at least x.x.x, but it should accept x.x as well (and probably auto pad the rest to zero's).

**Comment by niemyjski** [comment]
You'd need to clone and make a change in the semver component that I added here: https://github.com/exceptionless/Exceptionless.UI/commit/826dfe007f86735aef22b0dc09836290d38bc46b

**Comment by Phyxion** [comment]
Thanks, sorry for the delay. My knowledge of angular is almost non existing but seems just JS so I've submitted a PR there.

**Comment by niemyjski** [comment]
Thanks for the PR!
