### ISSUE TITLE
Copy of NewtonsoftJson

### ISSUE THREAD

**Issue by elementum** [exceptionless/Exceptionless#385]
Is there a reason you have a copy of NewtonsoftJson in Exceptionless project instead of referencing newtonsoft nuget package?
If you really do need it internally for proper functionining why would not make it internal without polluting global scope?

Quite a few times I mistakenly used attributes from exceptionless, essentially ruining my app.

**Comment by nj** [comment]
@niemyjski Have you considered taking advantage of [dependencies](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element) for NuGet, doing a minimum version and perhaps even maximum in edge cases for future releases with conflicts?

I'm aware that adding it manually won't be covered by that solution, but could alternatively be handled by some validation part during initialization, validating the Json version installed, putting a warning or something output in that case.

Using a older or newer version on either side is bad, as it also could conflict with the project where Exceptionless is used within too. Not sure which is worse.

Nowadays, hopefully most uses package-management, so should handle most cases anyway.

**Comment by nj** [comment]
(besides that, I guess this issue rather belongs to the [Exceptionless.Net](https://github.com/exceptionless/Exceptionless.Net) repo)

**Comment by EricZimmerman** [comment]
maybe consider switching to ServiceStack.Text as its free (up to a point) and a lot faster than newtonsoft?

**Comment by niemyjski** [comment]
We just need to internalize it and make it all internal. I'll try and get the the powershell script updated unless someone can do that in a pr. I doubt we'd pick up service stack. It's free but last time I checked it's dual licensed which has some issues.

**Comment by niemyjski** [comment]
Would you mind submitting a pr for this?

**Comment by yang-xiaodong** [comment]
@niemyjski  I have submit a PR to fix this problem.

https://github.com/exceptionless/Exceptionless.Net/pull/199

**Comment by niemyjski** [comment]
This has been merged in
