### ISSUE TITLE
How to convert Stacktrace offsets to something meaningful?

### ISSUE THREAD

**Issue by EricZimmerman** [exceptionless/Exceptionless#387]
is it possible to go from this:

at Foo.Forms.Main.ToggleHidden() at offset 22
at Foo.Forms.Main.Unload() at offset 63

to something actually meaningful to determine where an error happened? what is the offset? characters? bytes?

**Comment by niemyjski** [comment]
There really isn't much we can do in this case. Offsets can change during the runtime and are not very reliable. The best thing to do is deploy the pdb's if you can along side your assemblies so you get file and line numbers. I hope this helps.
