### ISSUE TITLE
The type "ExceptionlessClient" exists in both "Exceptionless.Signed" and "Exceptionless"

### ISSUE THREAD

**Issue by vindberg** [exceptionless/Exceptionless#388]
Using the AspnetCore latest version of Exceptionless.Signed 4.3.2012 im getting this error message in visual studio.

Im trying to limit the exceptionless to log only "errors" (loglevel).

```
		var client = new Exceptionless.ExceptionlessClient(); // Gives error

			loggerFactory.AddConsole(LogLevel.Error);
			loggerFactory.AddExceptionless(key);
```

Thanks.

**Comment by niemyjski** [comment]
Hey,

Can you try using the unsigned version of Exceptionless to resolve this issue. I think we also need a signed version of the logging package to properly fix this. I think we want to deprecate all the signed nuget packages and just sign the standard package by default.

**Comment by vindberg** [comment]
Thanks, the unsigned version worked.
