### ISSUE TITLE
Does the.Net Core version no longer support self hosting mode?

### ISSUE THREAD

**Issue by LuceLuo** [exceptionless/Exceptionless#389]
Does the.Net Core version no longer support self hosting mode?

Do you only provide API, no longer provide Web interface similar to.NetFramework mode?

**Comment by niemyjski** [comment]
Yes, it still supports it and will have a ui, we are however will be moving to a docker only release in the future.

**Comment by LuceLuo** [comment]
@niemyjski I really hope to arrive as soon as possible.

**Comment by niemyjski** [comment]
We got configuration done and are testing it in dev environments running inside of k8, should be soon enough
