### ISSUE TITLE
Add user into organization without invite

### ISSUE THREAD

**Issue by LTAravindh** [exceptionless/Exceptionless#390]
H,

I'm using selfhosted exceptionless.
I need to add a user into all the organization without invite them. Is this possible?

Thanks,
Aravindh LT

**Comment by niemyjski** [comment]
Hello,

Currently the only way to add a user is via invite on the manage organization page. If they signup for an account, you can invite them with the same email address and they will be automatically added to the org. What were you wanting to do for adding a user? Have it be like google and it generates a temporary email and password?
