### ISSUE TITLE
Carriage Return on the message

### ISSUE THREAD

**Issue by dboa** [exceptionless/Exceptionless#391]
Hello guys, 

I have a question,
I'm building an inegration between my company's new system and it's legacy system, and they asked me to log the errors on the company's exceptionless platform.

I would like to know if it's possible for the message to have multiple lines.
I tried a buch of stuff (/b,/n etc) and nothing worked.
I'm thinking it's not possible.

Thank you all for your time.

**Comment by niemyjski** [comment]
Sorry for the late reply :( Yes, your message content can have multiple lines but it's not something we recommend but is supported. The UI will try and strip out line feeds after X lines in the ui (but the message is still there) to prevent a message with many line breaks from taking over the entire screen. It's better to put that data as extended data (SetProperty(name, content)) in the message so then it's searchable and viewable in a much nicer format. 

https://github.com/exceptionless/Exceptionless.Net/wiki/Sending-Events#sending-additional-information

Please let us know if you have any questions.
