### ISSUE TITLE
/api/v2/projects/config occur 404 error

### ISSUE THREAD

**Issue by liuyl1992** [exceptionless/Exceptionless#394]
my Exceptionless version is '4.3.2012.0' ,when i call method : 'ExceptionlessClient.Default.Startup()',
in fact ,sdk call '/api/v2/projects/config' ,but occur error  for 404 
![image](https://user-images.githubusercontent.com/16396828/48327158-279f1080-e678-11e8-8259-4c4be5d4311f.png)

![image](https://user-images.githubusercontent.com/16396828/48327170-35ed2c80-e678-11e8-8f81-f30e5f5c3146.png)

**Comment by liuyl1992** [comment]
![1542084694 1](https://user-images.githubusercontent.com/16396828/48391773-2dadf380-e743-11e8-9a3b-ed00b86dd75b.jpg)
![1542084773 1](https://user-images.githubusercontent.com/16396828/48391774-2e468a00-e743-11e8-9fa6-6ed839a748d3.png)

**Comment by niemyjski** [comment]
Were you able to get to the bottom of this, was the server url configured properly?
