### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by leewalton** [exceptionless/Exceptionless#397]
I'm looking for a Java API for Exceptionless.

It looks like there has been previous interest in supporting a Java API, but there doesn't appear to be any active development of one?

**Comment by niemyjski** [comment]
Hello,

My apologies for the extremely long delay in response. We would love to have a Java API and would be willing to work with the community to build one. Would you be interested in helping with this?

**Comment by witskeeper** [comment]
i want Java too   ,  and  i will try to build one.

**Comment by niemyjski** [comment]
It would be super nice to port our .net one to java. I wonder if a converter could get us most of the way there.

**Comment by niemyjski** [comment]
I'm going to close this, we want java support and if someone sends us a pr for it or we have time to add it we will. I'd be more than happy to help put anyone in the right direction.
