### ISSUE TITLE
Display limit on number of projects

### ISSUE THREAD

**Issue by danielrogersenable** [exceptionless/Exceptionless#398]
We have an instance of Exceptionless with more than 100 projects. We have noticed that the dropdown list at the top of the page only displays 100 projects (which appears to correspond to the first 100 projects listed in the Admin > Projects area).

Projects beyond this limit of 100 do not appear in the dropdown list and so only seem to be accessible by paging through the list of projects in the admin area and viewing the dashboard from there. Further, when viewing one of these projects a message appears at the top of the page saying "Setup your first project" and informing us that the organisation currently has no projects.

Currently all our projects are in a single organization; however we believe that separating projects into different organizations within the same instance does not resolve this issue.

As such we have the following requests/observations:

1) Is there a way we can bypass the limit of 100 projects displayed in the list, or otherwise improve the experience of finding projects in Exceptionless when we have more than 100 projects? 

2) We are unsure how the projects in the administration area are ordered - this does not appear to be by name or date created, which means the projects displayed in the dropdown list appear to be relatively arbitrary, and the process of finding a project through the admin UI is very manual as a result. Would it be possible to introduce either a default sorting on this page by name, or to add user sorting to this page?

3) (Lower priority) Could the issue with the incorrect "Setup your first project" message appearing for organisations which do have projects be resolved?

Please do let me know if there's any more information we can supply, or if any of these issues are ones we can resolve ourselves with the right configuration.

**Comment by niemyjski** [comment]
Hello, Sorry about the delayed response, the holidays were a bit crazy. 

1. We're working on a new version of the UI and would like to add better support for handling this scenario.
2. I think we should sort them by name, I'll get this updated.
3. Where are you seeing this? I've not seen this behavior before. Can you provide me with some more information on what I need to do to see this issue.

**Comment by danielrogersenable** [comment]
Thanks for your response, and no worries about the delay.

1 and 2 - Thanks for this. Do you have a rough idea of when this new UI is likely to be delivered? We have a workaround which should help us get round this in the short term, but it would be handy to have a ballpark idea in case we need a longer-term solution.

3 - The following repro steps should show it:
a) Create more than 100 projects (this is within a single organisation, but I don't think that is essential to reproduce the issue)
b) Within the Admin > Projects area, find a project which is not in the list of "All Projects" at the top. (With the current paging I believe these will be the projects on the 11th page onwards in this area).
c) Select one of these projects and select "View Dashboard"
d) The message "Setup your first project" appears at the top of the page.

Hopefully that's enough to reproduce it - let me know if I can give you any more information.

**Comment by niemyjski** [comment]
It's slowly going and we wish It was done already, you can track the status on the angular ui repo pr. The first step is to just get us to current parity and then add to it.

Thanks, I'll take a look.

**Comment by niemyjski** [comment]
Can you please confirm if this is still an issue? We've done a ton of work on project filtering

**Comment by neilkennedy** [comment]
Hi @niemyjski. We have an on-premise install of v2.6.1111 and are seeing the same issue described here. Is this fixed in the latest v2.8?

**Comment by niemyjski** [comment]
Yes, you would also need to upgrade the backend to 5.0 as well. I'm going to close this for now, but if you upgrade and run into any issues please let me know.
