### ISSUE TITLE
Extremely slow the first time

### ISSUE THREAD

**Issue by PhyxionNL** [exceptionless/Exceptionless#40]
Once the data is loaded, it is working fine but the first time it is loaded (even though the w3wp process is still there) it takes like 5-10 minutes for the data to load (the page doesn't load except for the title). Idle for a few minutes and it'll take the same 5-10 minutes again until we see something to load. The server we run this on is more than fast enough to handle some exceptions. Is this something that is known/expected or ...?

**Comment by Phyxion** [comment]
Being fed up with the terrible performance I decided to install it also on my dev machine. I fired up the profiler and noticed that it takes 30+ seconds here for Jurassic Js Engine to complete. When I switch to V8 or MSIE it loads within 5 seconds. Is there any reason why Jurassic is used?

**Comment by ejsmith** [comment]
You can switch to the other JS engines. The reason why we were using the Jurassic engine is because it doesn't require special permissions on the server.

In Exceptionless 2.0, we aren't using a JS engine at all so that issue should go away completely.

**Comment by Phyxion** [comment]
Thank you for the information, I'll use V8 for now then and wait until 2.0 is ready!
