### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#400]
4.1.0 was released in 2017, it's now 2019, it would be nice if a new release was created 👍

**Comment by niemyjski** [comment]
We are a lot closer today than we were even a month ago and I want to get a release out ASAP but I also don't want to rush it (The only thing I can think of that I'd like to do before cutting a release would be to get health checks finalized and the jobs also using health checks). We got configuration done and working good. We've talked about simplifying our dependencies maybe even more but I think that's at a future time to make configuration even easier. We are completely moved into Kubernetes now in prod. I need to look into seeing if it even makes sense doing zip based release for 5.0 as we were planning on making 5.0 completely docker based. If you want to try 5.0 out and let us know how it works the images are available on our docker hub: https://hub.docker.com/u/exceptionless

**Comment by Phyxion** [comment]
Thanks for the reply, sounds good but I'm not using docker so a zip release would be appreciated 👍

**Comment by jimgarwacki** [comment]
Will the docker images work on Windows or do they require Linux (new to containers/Docker, so sorry if this is a dumb question)?

**Comment by niemyjski** [comment]
They require linux

**Comment by Phyxion** [comment]
That's why a zip release is welcomed 👍 I've been using Exceptionless since the beginning, please don't forget about the users not being able to (or want to) use Docker.

**Comment by jimgarwacki** [comment]
Any specific version/distribution of linux?

**Comment by niemyjski** [comment]
They are just running linux containers of which you can run on windows too (or should be able to (https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers). We don't know what the deployment methods will be for release, we want it to be super easy for everyone to install and upgrade and manage. Docker really makes that really easy and a lot of people have told us that as well. You can clone master right now and just do docker-compose up and run everything which is awesome :).

**Comment by niemyjski** [comment]
We got the health checks out there in prod and will be making minor tweaks here and there. Release should be incoming soon.

**Comment by Phyxion** [comment]
Glad to hear, looking forward to that, thanks for the update @niemyjski!

**Comment by Phyxion** [comment]
Any date @niemyjski? Maybe not close this issue until it's released? 👍

**Comment by niemyjski** [comment]
We are code complete now and have been running it in production for two weeks now without any issues. We have decided that we will tag a release on GitHub when we have docs documenting the new configuration (migration), running with docker-compose, as well as helm. Please use the docker images located [here](https://hub.docker.com/u/exceptionless) for a stable 5.x build. These should work on both windows and linux and we will do additional testing to ensure it's a smooth migration.

We understand that we traditionally released a zip release with artifacts, but going forward with the 5.x release we are only going to release via docker images. We have limited resources to support both models and this is the future industry wide. This will allow everyone to seamlessly upgrade or downgrade with ease while ensuring configuration and dependencies are running correctly thus reducing troubleshooting. We are going to spend time updating the documentation to make this process easier. 

Please note that if you wish to deploy with the traditional model, you can clone the repository, build the project and deploy the artifacts as you always have.

**Comment by Phyxion** [comment]
I can't use Docker so it's a shame that there will not be a zip release anymore. I've tried in the past to create a combined version with UI (similar to current zip) but couldn't get it to work. Some guide on that would be welcome if you don't want to release a zip anymore.

**Comment by niemyjski** [comment]
Are there any specific reasons/limitations that you cannot use docker? I'd like to understand this more. You'd need to compile the project manually and then copy the build artifacts. I'd say if you want to use Exceptionless outside of docker the easiest way is going to be pull down the code, build it in release mode and then copy the Exceptionless.Web artifacts and host it like you would an asp.net core website. You'll want to run jobs in process or you'll need to create one or more additional website instances for jobs.

**Comment by Phyxion** [comment]
I already use the virtualization from CPU and docker doesn't run as it needs Hyper-V. I also don't want to loose all the data I already have in Exceptionless (which is quite a lot), and as there's no good way to keep existing API keys I'd rather use the existing data.

A few weeks ago I've tried to build project (seemed to build OK) and UI, but UI only showed blank page with tons of errors in console. I'll have to retry this some day I think...

**Comment by niemyjski** [comment]
We need to dig into this further and document the process, but I believe all you'd need to do is ensure nested virtualization is enabled and run your docker image on one of the vms or on the main machine. You don't have to lose any elastic data. You can use your existing elastic infrastructure and update configuration to point to it.

If you could log any issues you are having with trying to build that would be greatly appreciated.

**Comment by Phyxion** [comment]
I cannot run Docker as I already use the virtualization features of the CPU for other purposes and Hyper-V would block that. Due to other requirements this is not possible to change at the moment. I suspect there are more people not able to run docker, so that's why a zip release is still welcome. 

(I could indeed reuse Elastic but then the point of running it in containers would be even less as it would just be for hosting) 

I'll have to take another look at building and combining everything here but I guess I have to continue to run the old version for now...

**Comment by Phyxion** [comment]
OK, I had some time to further look into this and I've managed to combine this project and the UI (still needs a little more testing but looks very promising). For it to work, there needs a little bit of code added to this project in order to serve the .less files. Nothing major, just a few LOC. **Would you accept a PR for that?**

Furthermore, I'm not sure if this is normal for heartbeats (through web browser)? This also happens in my local docker instance.
XHR GET http://localhost:5000/api/v2/events/session/heartbeat?id=test@test.com&close=false&access_token=v6NRoiMSbAQ1DLFbsRE36GQF1sRYxBHM0DnKVrQs
[HTTP/1.1 200 OK 3ms]
->
XML Parsing Error: no root element found
Location: http://localhost:5000/api/v2/events/session/heartbeat?id=test@test.com&close=false&access_token=v6NRoiMSbAQ1DLFbsRE36GQF1sRYxBHM0DnKVrQs
Line Number 1, Column 1:

Anyway, what I did (if someone else needs it):
- Build Exceptionless (this solution) and publish Exceptionless.Web on new profile, Release / netcoreapp2.2 / Self-Contained or Framework Dependent / win-x64 (or whatever you need there). This takes some time to first publish, be patient. You will also need to copy appsettings.yml and set whatever you need.
- Open Exceptionless.UI/src folder and run npx bower install.
- Copy everything from UI to the published Exceptionless.Web/wwwroot. You don't need all the grunt stuff.

If you use IIS, make sure you set app pool to No Managed Code and install ASP.NET Core IIS package.

**Comment by Phyxion** [comment]
OK, I had some time to further look into this and I've managed to combine this project and the UI again. For it to work, there needs a little bit of code added to this project in order to serve the .less files. Nothing major, just a few LOC. **See the PR for that.**

Furthermore, I'm not sure if this is normal for heartbeats (through web browser)? This also happens in my local docker instance.
XHR GET http://localhost:5000/api/v2/events/session/heartbeat?id=test@test.com&close=false&access_token=v6NRoiMSbAQ1DLFbsRE36GQF1sRYxBHM0DnKVrQs
[HTTP/1.1 200 OK 3ms]
->
XML Parsing Error: no root element found
Location: http://localhost:5000/api/v2/events/session/heartbeat?id=test@test.com&close=false&access_token=v6NRoiMSbAQ1DLFbsRE36GQF1sRYxBHM0DnKVrQs
Line Number 1, Column 1:

Anyway, what I did (if someone else needs it):
- Build Exceptionless (this solution) and publish Exceptionless.Web on new profile, Release / netcoreapp2.2 / Self-Contained or Framework Dependent / win-x64 (or whatever you need there). This takes some time to first publish, be patient. You will also need to copy appsettings.yml and update it to whatever you need.
- Open Exceptionless.UI/src folder and run npx bower install & npx bower install & npx grunt build.
- Exceptionless.UI/src/dist to the published Exceptionless.Web/wwwroot. 
- Update app.config.xyz.js with whatever you need.

That should do it 👍 

If you use IIS, make sure you set app pool to No Managed Code and install ASP.NET Core IIS package.

**Comment by Phyxion** [comment]
@niemyjski I've noticed that since I've upgraded to this new version, no new data is shown in UI anymore. The storage/archive/.. and storage/q/... (this one contains a few thousand empty folders) are huge and I can see they're getting filled with new data. So for some reason the data isn't propagated to the UI. I'm not that knowledgeable about the inner workings of Exceptionless, but I'm guessing this has something to do with the jobs. Or would it be something else? I have `RunJobsInProcess: true` in appsettings.yml and tried to restart the site but that didn't work. I can see the GeoLite2-City.mmdb getting updated so at least some of the jobs are working.

Going through the log, I've noticed this is repeatedly logged:

> System.ApplicationException: Error creating index events-v1-2019.03.11: Server: (400) Type: mapper_parsing_exception Reason: "Failed to parse mapping [events]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]"" 
   at Foundatio.Repositories.Elasticsearch.Configuration.IndexBase.CreateIndexAsync(String name, Func`2 descriptor)
   at Foundatio.Repositories.Elasticsearch.Configuration.DailyIndex.EnsureIndexAsync(DateTime utcDate)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)
   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts)

Did anything change in the elastic db that needs a manual update or something?

**Comment by Phyxion** [comment]
Seems my murmur size plugin got removed, no idea what caused that, it all looks good now 👍

**Comment by niemyjski** [comment]
Hey, sorry for the late reply. Are you using the ui in the master branch? Is any data being put into elastic search? Hmm, looks like it's failing to create the index because of the missing size plugin.. I'm assuming you are using the new docker image for elastic? @ejsmith we need to create our own elastic image.

**Comment by Phyxion** [comment]
I found a post of you somewhere on elastic search site with pretty much this error and I've reinstalled the murmur size plugin and after restarting exceptionless it immediately imported all the data into elastic and the UI is showing the new content again. I'm using non-docker elastic instance (just the installer).

**Comment by niemyjski** [comment]
I just wanted to let you know we just pushed a new major version :) https://github.com/exceptionless/Exceptionless/releases/tag/v5.0.0
