### ISSUE TITLE
Is there a documentation for deployment under docker?

### ISSUE THREAD

**Issue by LuceLuo** [exceptionless/Exceptionless#402]
When I deployed the UI, BaseURL was always ex-api.localtest.me:5000. I tried to modify it through environment variables, but it didn't work. Is there a detailed deployment operation document?

**Comment by niemyjski** [comment]
How did you deploy? What branch did you deploy? Did you update the app.config.js?

**Comment by LuceLuo** [comment]
我直接用的https://hub.docker.com里面的镜像
https://hub.docker.com/r/exceptionless/ui-ci

**Comment by niemyjski** [comment]
You need to set environment variables `-e EX_ApiUrl ='http://ex-api.localtest.me:5000'`. The config will be generated inside of the docker container on startup (https://github.com/exceptionless/Exceptionless.UI/blob/master/bootstrap). Starting last night we prefixed all of our environment variables with `EX_`.

**Comment by niemyjski** [comment]
We'll be working on documentation as well, but we'd appreciate any help or feedback as well :). We'll be testing and tweaking this week and cutting a release real soon :).

**Comment by niemyjski** [comment]
I'm going to close this for now, please let us know if you have any additional questions.

**Comment by LuceLuo** [comment]
Thks
