### ISSUE TITLE
Can you support don't use ssl config?

### ISSUE THREAD

**Issue by jianxuanbing** [exceptionless/Exceptionless#404]
Because I plan to deploy it in the LAN. In the docker deploy, create account check email address always jump to https://xxxxx. `RequireHttpsAttribute` can custom config?

**Comment by niemyjski** [comment]
@jianxuanbing were you able to resolve this issue?

**Comment by cheetahing** [comment]
you can write like this.is work well

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$Version.zip" -OutFile "elasticsearch-$Version.zip"

**Comment by niemyjski** [comment]
I believe this has been resolved and was an issue with HSTS. Can you please confirm with the latest images. Please respond back and let us know and we'll reopen the issue.
