### ISSUE TITLE
Start-ElasticSearch.ps1 bug fix

### ISSUE THREAD

**Issue by cheetahing** [exceptionless/Exceptionless#409]
this download srcipt need ssl
Invoke-WebRequest "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$Version.zip" -OutFile "elasticsearch-$Version.zip"

fix by

  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  Invoke-WebRequest "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$Version.zip" -OutFile "elasticsearch-$Version.zip"

**Comment by niemyjski** [comment]
Thanks for reporting this issue and the suggested fix. I’m going to close this as we are in the process of deleting this file as we move completely to docker.
