### ISSUE TITLE
Can you support more databases, not just Elasticsearch?

### ISSUE THREAD

**Issue by SeppPenner** [exceptionless/Exceptionless#410]
It would be a good feature if `Exceptionless` was more configurable. E.g. make it ready to use plugins for different database providers and then let the community build the plugins for the different databases. Is there any intention to do so? I could need `Exceptionless` for PostgreSQL and do not want to copy and adjust the whole project though...

If you take a look at this project for example: https://grafana.com/plugins?type=datasource, they have a plugin system to support multiple data sources. (Just as a reference to get the idea).

**Comment by SeppPenner** [comment]
If there was such a thing like a plugin system, I could offer some help for MySQL, PostgreSQL and OracleDB if wished.

**Comment by niemyjski** [comment]
Thanks for the feature quest, we'd be open to supporting postgre but have no resources for the massive undertaking it would be. First, you'd need to implement an implementation of [Foundatio.Repositories](https://github.com/FoundatioFx/Foundatio.Repositories) as well as parsers [Foundatio.Parsers](https://github.com/FoundatioFx/Foundatio.Parsers). This would need to support all the dynamic aggregation queries we support today as well as time series based aggregations. Both of these would need to be done before we'd even consider this feature and it's no small undertaking. It's one of the core reasons we moved off of MongoDB, because it was a PITA to support time series based aggs...

**Comment by niemyjski** [comment]
For the reasons above, I'm going to close this and we can reopen it if support is added to the above two projects. We'd be more than happy to point you in the right direction on any of this, please feel free to join our slack.

**Comment by SeppPenner** [comment]
> It's one of the core reasons we moved off of MongoDB, because it was a PITA to support time series based aggs...

Well, you could use [TimescaleDB](https://www.timescale.com/) to achieve this with PostgreSQL, I would assume. I understand that it's a huge effort to do this.

**Comment by SeppPenner** [comment]
@niemyjski Where should I look at first?

If I understood correctly:
1. Clone https://github.com/FoundatioFx/Foundatio.Repositories
2. Add a new project called `Foundatio.Repositories.PostgreSQL`
3. Implement the interfaces with the code (and probably check how it's done for Elasticsearch and adopt things)

Am I correct with this?

**Comment by niemyjski** [comment]
Yes this is a good first start, for #3 you'd need to create a parsers implementation to translate the lucene syntax to postgres queries/aggregations.

**Comment by SeppPenner** [comment]
Okay, thanks. I will try and see if there are some issues I don't understand 👍

**Comment by SeppPenner** [comment]
This is way more complicated then I thought it was. I think I will provide this feature with a completele new product here: https://github.com/SeppPenner/ExceptionLesser because it's easier than.

**Comment by niemyjski** [comment]
I don't think it's any easier. I'm curious why you'd want to use Blazor or postgre here? I get that you get ACID and many other things, it just doesn't make sense for most things. Sure we could implement repositories for postgre and that would be awesome. That would allow us to at least someday switch out and store everything other than stacks and events in postgre.

**Comment by SeppPenner** [comment]
My problem is that I'm not really used to the lucence syntax. Plus, if you're already working with one or two different databases, you do not want to maintain a third (I'm using mainly SQL like databases, I used MongoDB once, but I didn't like the query language). SQL databases (Especially Postgres with TimescaleDB are getting so fast that NoSQL doesn't really provide a benefit in my opinion. Ok, when using text search and stuff like that, Elasticsearch is better, of course). That's the thing...
