### ISSUE TITLE
An error occurred while marking this stack as fixed.

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#411]
On this page, mark it as fixed, enter 1.1
`https://exceptions.url.com/#!/stack/5c95134126e349325cd32381`

This does the following request:
`https://exceptions.url.com/api/v2/stacks/5c95134126e349325cd32381/mark-fixed?version=1.1`
Returns 400, "Invalid semantic version". 

I suspect this is because the UI isn't sending the version correctly? It does show as "1.1.0" in UI but the URL is only adding "1.1" it seems.

What is equally weird, if I do 1.1.0-1 in UI, the URL becomes `...?version=1.1.0.1`, yet the same error is returned. If I manually modify the request in Firefox to `?version=1.1.0-1`, it's returning 202 (accepted).

Marking stacks as fixed on the "project" page works OK.

**Comment by niemyjski** [comment]
We should automatically be translating `1.1` to `1.1.0`. Are you using the elastic6 branch or master? `1.1.0-1` should be sent to the server as such.

**Comment by Phyxion** [comment]
You mean the angularv6 branch? I'm using the master branch. It's only happening on the stack page, the project page is sending the version correctly.

**Comment by niemyjski** [comment]
I've made the ui more responsive to help with this, like you'd have to type `1.1` and instantly click mark fixed. Regardless, I looked at the code and updated it to use our semantic version parser we use everywhere else which has great coverage and covers many more scenarios. This will go out in the next minor release or update to use the latest docker nightlies.
