### ISSUE TITLE
How can i deal with repeat logs

### ISSUE THREAD

**Issue by 786744873** [exceptionless/Exceptionless#414]
When I try to post a large of same logs to platform.  I noticed that some logs was repeat and become one.How canI do something to make my platform to set logs not repeat? thanks sir

**Comment by niemyjski** [comment]
Are you referring to you have stacks of logs based on the log source? Or are you referring to you are seeing duplicate log messages because you have your program running on multiple machines?

**Comment by niemyjski** [comment]
@786744873 can you please respond to the questions above.
