### ISSUE TITLE
any changes in es index  between 4.x and the .net core version?

### ISSUE THREAD

**Issue by witskeeper** [exceptionless/Exceptionless#415]
i am using the .net framework verion which is  4.x
if i upgrade  to the lastest  .net core version.
do i need to do something in elasticsearch index ?

**Comment by niemyjski** [comment]
There should be no changes to the Elasticsearch indexes for 5.x, you'll just need to run the docker containers that are currently up with our ci label. We're finalizing the docs and then well be pushing the official feeds. Please let us know if you have any questions.

**Comment by witskeeper** [comment]
good job，that’s good news for everyone who want to upgrade to .net core version.

**Comment by cuibty** [comment]
+1

**Comment by niemyjski** [comment]
The only changes needed are to host the site in docker and point elastic connection string to your existing elastic instance :).  See this for more information: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting-Docker
