### ISSUE TITLE
Why do I deploy it on the server, but always show that the mailbox already exists when I create the user

### ISSUE THREAD

**Issue by oiovwv** [exceptionless/Exceptionless#416]

**Comment by niemyjski** [comment]
Hello,

I'm not sure what you are asking. Can you please explain it further and paste in any errors/screenshot minus user data that you get.

**Comment by oiovwv** [comment]
Sorry, I didn't describe it clearly, please see the picture below.
![image](https://user-images.githubusercontent.com/30096827/56942510-b8e24080-6b4d-11e9-9149-261cba539c0e.png)
After I try to set up the environment locally, when I register my account, 'A user already exists with this email address' will always be displayed, regardless of whether this email address is registered or not.
Thank you very much for your reply

**Comment by niemyjski** [comment]
I'd check your network tab and see why that is failing. My guess would be that you need to configure the base url property in the app.config.js file. Have you done this?

**Comment by niemyjski** [comment]
Were you able to figure this out? Typically it's because the base url is wrong.I'm going to close this until more information is provided.

**Comment by ColorfulCodingLife** [comment]
hi, I also encountered a same problem that show me "a user already exists with this email adress" in the docker container environment.Below is my configuration in docker-compose.yml
`version: '3.4'

services:
  api:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/api-ci:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job-ci:latest
    command: run-all
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui-ci:latest
    environment:
      AppMode: Development
      BaseUrl: http://ex-api.localtest.me:5000
    ports:
      - 5100:80

  elasticsearch:
    image: exceptionless/elasticsearch:1
    environment:
      cluster.name: 'exceptionless'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # kibana:
    # depends_on:
      # - elasticsearch
    # image: exceptionless/kibana:1
    # environment:
      # xpack.security.enabled: 'false'
    # ports:
      # - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  esdata:
    driver: local
  appdata:
    driver: local`

**Comment by ColorfulCodingLife** [comment]
Is this a problem with baseurl errors? and can you give me any suggestions?  thanks...

**Comment by niemyjski** [comment]
I think so, I think your api url is wrong as the environment variable isn't defined (https://github.com/exceptionless/Exceptionless.UI/blob/master/bootstrap#L3) Can you try setting this.
