### ISSUE TITLE
BasicAuthentication for elasticsearch in .net core version?

### ISSUE THREAD

**Issue by witskeeper** [exceptionless/Exceptionless#417]
BasicAuthentication for elasticsearch in .net core version?

**Comment by niemyjski** [comment]
I'm not sure what you are asking, you want to authenticate to elastic search using basic auth? I'm not sure if the nest client supports this: https://github.com/elastic/elasticsearch-net/issues/2505 If it does, please open a pr for this, it would be easy to add support for it via the elastic options configuration class.

**Comment by niemyjski** [comment]
Thanks for the pr!
