### ISSUE TITLE
docker-compse up failed

### ISSUE THREAD

**Issue by JOJOJOFran** [exceptionless/Exceptionless#418]
after downloaded all images,then show me the error message:

Building api
ERROR: Cannot locate specified Dockerfile: Dockerfile

docker-compose version 1.24.0
Docker version 18.09.5

**Comment by niemyjski** [comment]
What is your exact docker command? You should be able to run `docker-compose up`.

**Comment by JOJOJOFran** [comment]
> What is your exact docker command? You should be able to run `docker-compose up`.

now, I can run elasticsearch ,kibana,and exceptionless ui on localhost,but i can't sign up,beacuse it always warn the email address has existsed

**Comment by JOJOJOFran** [comment]
> What is your exact docker command? You should be able to run `docker-compose up`.

I use the yaml file from your respository:
https://github.com/exceptionless/Exceptionless/blob/master/docker-compose.yml

**Comment by JOJOJOFran** [comment]
> What is your exact docker command? You should be able to run `docker-compose up`.

oh ,I've ran it successfully on mac os,but I still meet some tourble on centos,can i find some exact documents dbout  self-hosting on centos by docker or other way.

**Comment by JOJOJOFran** [comment]
I sloved it,but I don't know why the way is effective,  that I run docker-compose up with docker-compose.6x.yml  at first,and then I  turn to use docker-compose.yml .(of course must use available port and volume path)

if I run the command with  docker-compose.yml at first, docker will  show me the error message:
Building api
ERROR: Cannot locate specified Dockerfile: Dockerfile

**Comment by niemyjski** [comment]
Ah yeah, we need to remove the 6x in there it shouldn't be used as it's not currently supported... That's really weird that you get that, if you could get to the bottom of it that would be a huge help for us. Here is the docks we have for self hosting with the new model (these will replace the old ones). https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting-Docker
