### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by cuibty** [exceptionless/Exceptionless#420]
https://github.com/exceptionless/Exceptionless/blob/master/docker-compose.yml

docker-compose up -d

email : test@exceptionless.io
password: tester

![Snipaste_2019-05-05_22-21-07](https://user-images.githubusercontent.com/12811343/57195946-82138c80-6f8a-11e9-86e5-a75f5a13fc16.png)

**Comment by niemyjski** [comment]
When using `docker-compose` the default mode is production, as a result test users are not created. You'll need to create a new user. Please let us know if you have any questions.

**Comment by cuibty** [comment]
@niemyjski 

![Snipaste_2019-05-07_10-41-11](https://user-images.githubusercontent.com/12811343/57267979-a8cde200-70b4-11e9-9273-ba16d7ab6f10.png)

![Snipaste_2019-05-07_10-37-05](https://user-images.githubusercontent.com/12811343/57267990-b2574a00-70b4-11e9-95b6-fd72dccbae28.png)

**Comment by niemyjski** [comment]
Sorry for the late reply, I just saw the notification for this. Are you accessing this page on the same url that you are running the docker container on?

**Comment by cuibty** [comment]
no, the docker (centos) running in VirtualBox is on a LAN with my PC. @niemyjski

**Comment by niemyjski** [comment]
I'm wondering if it's because the host `ex-api-localtest.me:5000` is banned where you are at. If you hit that url does it point to your api server? If not, can you change the the base url via environment variable to point to localhost. Take a look at the bootstrap.sh script for the variable you need to set. Was this the issue?

**Comment by jianxuanbing** [comment]
> I'm wondering if it's because the host `ex-api-localtest.me:5000` is banned where you are at. If you hit that url does it point to your api server? If not, can you change the the base url via environment variable to point to localhost. Take a look at the bootstrap.sh script for the variable you need to set. Was this the issue?
I suggest that support can not be done with Https, because deploying IP addresses in a LAN environment is not convenient for internal use.

**Comment by jianxuanbing** [comment]
> I'm wondering if it's because the host `ex-api-localtest.me:5000` is banned where you are at. If you hit that url does it point to your api server? If not, can you change the the base url via environment variable to point to localhost. Take a look at the bootstrap.sh script for the variable you need to set. Was this the issue?

I suggest that support can not be done with Https, because deploying IP addresses in a LAN environment is not convenient for internal use.

**Comment by niemyjski** [comment]
We've removed the https middleware and redirect. Can you please try 5.0 release? We've also updated the docker-compose file this week to point to the official stable images.
