### ISSUE TITLE
the exceptionless supported on net framework 3.5?

### ISSUE THREAD

**Issue by steveleeCN87** [exceptionless/Exceptionless#421]
for maximum compatibility, our component uses net framework 3.5, but exceptionless cannot be installed.
how can do installed for the net framework 3.5?
tanks.

**Comment by niemyjski** [comment]
Hello,

I believe you the last version to support v3.5 was https://www.nuget.org/packages/Exceptionless/3.5.1738. You'd need to install the 3.x packages. Please note that this package is supported by our api but you are missing out on critical client fixes. We recommend targeting v4.5 and above as that's what is currently supported by us as well as Microsoft.
