### ISSUE TITLE
problem with docker-compose.yml

### ISSUE THREAD

**Issue by napoleonjang** [exceptionless/Exceptionless#429]
Hi,
without modify docker-compose.yml, exceptionless web site goes well(http://localhost:5100) , including create new user,  create new project.
however, there is error when submit exception in an asp.net core mvc project with following config:
 
appsettings.json:
![image](https://user-images.githubusercontent.com/2639201/60396131-1e63a500-9b70-11e9-848a-9ad53e00e7eb.png)

Startup.cs:
![image](https://user-images.githubusercontent.com/2639201/60396153-510d9d80-9b70-11e9-9dd2-63eab402d16a.png)

when test submitting an exception info,  error in client log file(d:\\exceptionless.log):
![image](https://user-images.githubusercontent.com/2639201/60396194-8c0fd100-9b70-11e9-9011-15f03160a9c2.png)

http://localhost:5100/api/v2/events      returns 405 http code.
please hlep me~~ :(  
Thanks.

**Comment by napoleonjang** [comment]
ps: fiddler capture info: 
![image](https://user-images.githubusercontent.com/2639201/60396314-45bb7180-9b72-11e9-9dbd-9e78f9f4cedd.png)

**Comment by napoleonjang** [comment]
> Hi,
> without modify docker-compose.yml, exceptionless web site goes well(http://localhost:5100) , including create new user, create new project.
> however, there is error when submit exception in an asp.net core mvc project with following config:
> 
> appsettings.json:
> ![image](https://user-images.githubusercontent.com/2639201/60396131-1e63a500-9b70-11e9-848a-9ad53e00e7eb.png)
> 
> Startup.cs:
> ![image](https://user-images.githubusercontent.com/2639201/60396153-510d9d80-9b70-11e9-9dd2-63eab402d16a.png)
> 
> when test submitting an exception info, error in client log file(d:\exceptionless.log):
> ![image](https://user-images.githubusercontent.com/2639201/60396194-8c0fd100-9b70-11e9-9011-15f03160a9c2.png)
> 
> http://localhost:5100/api/v2/events returns 405 http code.
> please hlep me~~ :(
> Thanks.

**Comment by caoxiaosheng** [comment]
Hello，
Can you tell me how to solve it?
Thanks.

**Comment by niemyjski** [comment]
The ServerUrl needs to point to the backend port not the ui port on `5100`.

**Comment by caoxiaosheng** [comment]
> The ServerUrl needs to point to the backend port not the ui port on `5100`.

It works!
Thanks. @niemyjski
