### ISSUE TITLE
Please add the following Request.ServerVariable values to reported Exceptions

### ISSUE THREAD

**Issue by badgerdigital** [exceptionless/Exceptionless#43]
HTTP_X_REWRITE_URL
SCRIPT_NAME
PATH_TRANSLATED
APP_PHYSICAL_PATH

**Comment by niemyjski** [comment]
Would you be happy with these in the RequestInfo extended data or do you want to see them as first class on the request info object..

Would you be able to provide a short description of each of these items (might be needed for xml docs).

**Comment by niemyjski** [comment]
Would you be able to provide a short description of each of these items (might be needed for xml docs).

**Comment by niemyjski** [comment]
@badgerdigital Would you mind providing a description of these four paths.

**Comment by niemyjski** [comment]
I'm closing this unless others ask for it or the community feels it adds value overall. I think those fields only pertain to url rewriting?? Here is how you can do this today:

```csharp
[Priority(95)]
public class AddCustomServerVariables : IEventPlugin {
    public void Run(EventPluginContext context) {
        var requestInfo = context.Event.GetRequestInfo();
        if (requestInfo == null)
            return;

        HttpContextBase httpContext = context.ContextData.GetHttpContext();

        // if the context is not passed in, try and grab it
        if (httpContext == null && HttpContext.Current != null)
            httpContext = HttpContext.Current.ToWrapped();

        try {
            if (httpContext?.Request?.Headers == null)
                return;

            requestInfo.Data["HTTP_X_REWRITE_URL"] = httpContext.Request.Headers["HTTP_X_REWRITE_URL"];
        } catch (Exception) {}
    }
}
```

Then register it on startup like this:

```csharp
ExceptionlessClient.Default.Configuration.AddPlugin<AddCustomServerVariables>();
```
