### ISSUE TITLE
Unable to work under. net standard

### ISSUE THREAD

**Issue by zfeihong** [exceptionless/Exceptionless#434]
![14](https://user-images.githubusercontent.com/20945947/61165583-13881780-a555-11e9-9439-e427290a21c1.png)

**Comment by niemyjski** [comment]
The asp.net core package requires netcoreapp due to diagnostic hooks. You should place the AspNetCore package in your web entry points and reference the exceptionless package anywhere else it’s needed. I hope this helps, let us know if you have any other questions.
