### ISSUE TITLE
docker-compose faild and can't login

### ISSUE THREAD

**Issue by 786744873** [exceptionless/Exceptionless#435]
When I Clone this repository and run `docker-compose up`.I can success launch default browser,but I can not login and regist my account.I used CentOS.
![image](https://user-images.githubusercontent.com/24601648/61203429-f2722300-a71c-11e9-9b09-b074a7b94f77.png)
![image](https://user-images.githubusercontent.com/24601648/61203485-0e75c480-a71d-11e9-8023-3ca174e1e4ae.png)

**Comment by niemyjski** [comment]
Is the local-test.me domain name blocked for you?

**Comment by 786744873** [comment]
I do nothing about local-test.me,May be this domain doesn't work. and I only use https://github.com/exceptionless/Exceptionless/blob/master/docker-compose.6x.yml to build my container, but when I create new account,this email input checked always failed.You can try it on CensOS or Cloud like AliCloud

**Comment by niemyjski** [comment]
Hello,

You cannot use the 6.x yml as that is not supported (we have it in there
for testing but it needs to be removed). Can you see if you can even view
the localtest.me domain name. I'm wondering if it's blocked all it does is
reroute localhost traffic through their domain name and give you ssl.

Thanks
-Blake Niemyjski

**Comment by 786744873** [comment]
How can I modify some files to make this email check option use my local engining?I seached from official documen but get no result

**Comment by niemyjski** [comment]
Set an environment variable or docker variable with `Ex_Email_ConnectionString` set to an smtp uri. https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/EmailOptions.cs#L59-L63

Did it work once you used the non 6.x docker compose file

**Comment by niemyjski** [comment]
Can you pull latest from GitHub and run docker-compose again. I filled out default settings for base url and it's working now. It also makes it easier to configure.
