### ISSUE TITLE
Exceptionless API , Always 403 Error: Forbidden

### ISSUE THREAD

**Issue by woshilangdanger** [exceptionless/Exceptionless#436]

**Comment by niemyjski** [comment]
Can you please give us more information, how are you hosting it., etc..

**Comment by woshilangdanger** [comment]
ok, thinks ,I use swagger ui , like the api of login, when  i post then login api,it always response 403 Error
![Uploading QQ图片20190718171900.png…]()

**Comment by woshilangdanger** [comment]
![error pic](https://user-images.githubusercontent.com/35796921/61503568-c4395f80-aa0a-11e9-9b58-85ab49304f1c.png)

**Comment by woshilangdanger** [comment]
![more](https://user-images.githubusercontent.com/35796921/61503651-2f833180-aa0b-11e9-9465-ca2354d1ecca.png)

**Comment by woshilangdanger** [comment]
I use the Exceptionless.Web and host as an API on docker

**Comment by woshilangdanger** [comment]
> Can you please give us more information, how are you hosting it., etc..

ok，thanks.

**Comment by woshilangdanger** [comment]
> Can you please give us more information, how are you hosting it., etc..

i have find the answer to the question, the filter like this `o.Filters.Add<RequireHttpsExceptLocalAttribute>()

 public RequireHttpsExceptLocalAttribute() {
            IgnoreLocalRequests = true;
        }`
but i am not use the ssl

**Comment by niemyjski** [comment]
Thanks, I'll take a look, perhaps we should remove that attribute.

**Comment by 1093439315** [comment]
I also have this problem.I use the docker image and hope to update it as soon as possible.

**Comment by niemyjski** [comment]
I’ll be back tomorrow at my desktop and I’ll dig into this more. Sorry about the docker issues. Are you both just using the standard docker compose file?

**Comment by 1093439315** [comment]
yes. i delete the code :o.Filters.Add(new RequireHttpsExceptLocalAttribute()) fix it!

**Comment by niemyjski** [comment]
We're investigating this and think we have a solution for it.

**Comment by rteam** [comment]
is there any progress?

**Comment by niemyjski** [comment]
I'd like to discard the middleware completely and have it be controlled via a reverse proxy with ssl termination, but this makes it much harder todo if you just want to use docker compose. I'm looking at the best way to allow you to put a pfx certficate to the attached docker storage and then  have kestrel do the lifting which would make this easier. I also want to play around and see if I can get kestrel to do the https only if configured so we wouldn't need the redirect.

**Comment by niemyjski** [comment]
This has been merged in. We'll be cutting a release shortly.
