### ISSUE TITLE
Which the version of  elasticsearch? if i use the master tag. the error like this 

### ISSUE THREAD

**Issue by woshilangdanger** [exceptionless/Exceptionless#437]
![QQ图片20190724131341](https://user-images.githubusercontent.com/35796921/61766976-554a7500-ae15-11e9-9505-04e4bd4a058f.png)

**Comment by woshilangdanger** [comment]
the elasticsearch version is 5.6, i used exceptionless_ui  & exceptionless_api  in docker on linux

**Comment by woshilangdanger** [comment]
i used the ServerUrl and config it as the api url
![2](https://user-images.githubusercontent.com/35796921/61767302-7364a500-ae16-11e9-8f33-f9ee9ca9e097.png)

**Comment by woshilangdanger** [comment]
the es error like this.
![3](https://user-images.githubusercontent.com/35796921/61769870-53d17a80-ae1e-11e9-909c-63d3ca53fe1e.png)

**Comment by niemyjski** [comment]
Those warnings are fine, what docker image are you using for Elasticsearch?

**Comment by woshilangdanger** [comment]
> Those warnings are fine, what docker image are you using for Elasticsearch?

pull elasticsearch 5.6 from docker hub

**Comment by woshilangdanger** [comment]
it has an error ,what failed to parse mapping [events]?

**Comment by woshilangdanger** [comment]
but i used the elasticsearch 5.6 on windows and connect it, it's ok

**Comment by woshilangdanger** [comment]
elasticsearch  Root mapping definition has unsupported parameters [_size : {enabled=true}]

**Comment by woshilangdanger** [comment]
oh,i find the answer and i also need to install the plugin of mapper-size .

**Comment by niemyjski** [comment]
I think this is due to you are not using our docker image for elasticsearch which we have included the mapper-size plugin. If you wish to exclude this plugin add ?enable-size-plugin=false to the elasticsearch connection string. Also, I'd recommend updating to the latest code as we fixed some issues with our compose file
