### ISSUE TITLE
set env BaseUrl doesn't work

### ISSUE THREAD

**Issue by 786744873** [exceptionless/Exceptionless#438]
I userd my [docker-compose.yml](https://send.firefox.com/download/ef043aae49607749/#cTetyudzhGFPWBaWKEvlaw) can build docker container success.
![image](https://user-images.githubusercontent.com/24601648/61989869-24ae4980-b068-11e9-8bbf-c380b4aec60b.png)
But when I visited http://192.168.103.240:5100/#!/signup，it notice me Email has existed.And the host address is error too.
![image](https://user-images.githubusercontent.com/24601648/61989883-7ce54b80-b068-11e9-9e00-f6a96ac5ebf9.png)
How can I solve this problem?Thanks.

**Comment by niemyjski** [comment]
Hello,

Please see my latest commits to this repository for an updated docker-compose file. You are missing the `EX_BaseURL` environment variable on the jobs and api config which points to the url of the ui and then the `EX_ApiUrl` environment variable on the ui-ci image which points to the api server.
