### ISSUE TITLE
Resend verification email can not  verification

### ISSUE THREAD

**Issue by 491134648** [exceptionless/Exceptionless#440]
Click activate the email to jump to /type/error/dashboard, account information is still you must first verify your email address

![image](https://user-images.githubusercontent.com/9816794/62865750-d5436b00-bd41-11e9-8c4c-32baf52e1561.png)

![image](https://user-images.githubusercontent.com/9816794/62865826-0c198100-bd42-11e9-973d-c6889c40166d.png)

**Comment by niemyjski** [comment]
I'm not fully understanding the request, are you saying the email you click on is taking you to the dashboard? Can you paste in the raw url that is sent to you in the email minus the domain name? I'm wondering if the url is incorrect?

**Comment by niemyjski** [comment]
I'm going to close this until more information is provided. Can you please see if my questions above helped resolve this issue.
