### ISSUE TITLE
mail notifications configuration rule?I can't get an incorrect email notification

### ISSUE THREAD

**Issue by 491134648** [exceptionless/Exceptionless#441]
when I was Self Hosting,I configured my email notification rules and the email verification was passed, but I couldn't get my error notifications, but I could get 404 and other mail pushes
version: v4.1.0
WebsiteMode: Production
![image](https://user-images.githubusercontent.com/9816794/62921205-96adbf00-bdda-11e9-8a9b-c09492fbedd3.png)
![image](https://user-images.githubusercontent.com/9816794/62921292-e7bdb300-bdda-11e9-9af9-7c099ade6d52.png)
![image](https://user-images.githubusercontent.com/9816794/62921309-ee4c2a80-bdda-11e9-81ce-717ce45c091b.png)

**Comment by niemyjski** [comment]
What do the application logs say when you submit an email? Are you using Redis? If so what does the email queue look like `keys q:mailmessage:*` (I think this is the key prefix)

**Comment by niemyjski** [comment]
Were you able to look into the cache keys and get this resolved? I'm going to close this until more information is provided.
