### ISSUE TITLE
Way to preserve the Organization and Projects while Self-Hosting

### ISSUE THREAD

**Issue by ehurem** [exceptionless/Exceptionless#443]
Hello,

Is there a way to preserve the Organization and all Projects with their respective API Keys while using the Self-Hosted version of Exceptionless?

For example: I set up an instance of Self-Hosted Exceptionless with one account, organization and a couple of Projects named Test1, Test2 on my local machine.
Now, if I want to setup the self-hosting on another machine, is there a way to have the exact same account, organization and the projects Test1, Test2 already configured - as in compressing the whole exceptionless folder and unzipping it on the other machine?

**Comment by niemyjski** [comment]
Yes, you'd need to backup elastic search data via snapshots and restore them into the new instance: https://github.com/exceptionless/Exceptionless/wiki/Elasticsearch-setup-guide#backups Please let us know if you have any questions or feedback.

**Comment by niemyjski** [comment]
I just wanted to let you know we just pushed a new major version :) https://github.com/exceptionless/Exceptionless/releases/tag/v5.0.0
