### ISSUE TITLE
most usage events hidden in exceptionless

### ISSUE THREAD

**Issue by a422241894** [exceptionless/Exceptionless#444]
@niemyjski   When my project post **usage** events to exceptionless, some event are dispalyed, and most events are hidden, see the screenshot as below:
![11](https://user-images.githubusercontent.com/15519822/63506469-2f91b800-c508-11e9-919b-eed736248a72.png)
![22](https://user-images.githubusercontent.com/15519822/63506486-36202f80-c508-11e9-95a7-97d861b908cb.png)
why are these events hidden?

**Comment by niemyjski** [comment]
Did you ever mark the stack of events has hidden? I'd go into the stack for those usage events and make sure they are not marked as hidden. If that's not the case then go into project settings and uncheck the box for bot data and see if that helps.

**Comment by a422241894** [comment]
@niemyjski 
I didn't mark the stack of event as hidden, event when I uncheck the box for bot data in project settings
and clear all index data in elasticsearch, some new usage events and exceptions will be hidden, it's really strange.
![1](https://user-images.githubusercontent.com/15519822/63559481-64dbeb80-c584-11e9-9d8b-a2efa28a949e.png)
![2](https://user-images.githubusercontent.com/15519822/63559483-64dbeb80-c584-11e9-990c-a8703f33180a.png)
![3](https://user-images.githubusercontent.com/15519822/63559484-64dbeb80-c584-11e9-8268-36d5d9c2c938.png)

**Comment by niemyjski** [comment]
That's really odd, can you wipe out all your stacks and events and enable logging (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting) to either debug or trace and send some events through that reproduce this issue. There is really only one real code path that would do that and that's the reduce noise checkbox (https://github.com/exceptionless/Exceptionless/search?l=C%23&p=1&q=IsHidden).

**Comment by niemyjski** [comment]
Were you able to get more information from my previous reply?

**Comment by niemyjski** [comment]
Can you please update this issue and we will reopen it once we have enough information to find the root issue.
