### ISSUE TITLE
Fail to sign up

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless#446]
Environment:
1. centos+docker
2.exceptionless version info:
informational_version | "5.0.3479+f605edff70a4d7ef0bfe063c1e536e9af6b215b7"
app_mode | "Production"
machine_name | "61c1a595fb24"

steps:
1. docker run -d \
-e "EX_AppMode= Production" \
-e "EX_BaseURL= http://myip:5100" \
-e "EX_ConnectionStrings__Cache= provider=redis" \
-e "EX_ConnectionStrings__Redis= server=myip:9905,abortConnect=false" \
-e "EX_ConnectionStrings__Elasticsearch= server=http://myip:9200;shards=3;replicas=1" \
-e "EX_ConnectionStrings__MessageBus= provider=redis" \
-e "EX_ConnectionStrings__Queue= provider=redis" \
-e "EX_ConnectionStrings__Storage= provider=folder;path=/app/storage" \
-e "EX_RunJobsInProcess= false" \
--name exceptionless_api --memory 500m --restart=always -v /data/el/data_api:/app/storage -p 5000:80 -t exceptionless/api:latest

2.docker run -d \
-v /data/el/data_job:/app/storage \
-e "EX_AppMode= Production" \
-e "EX_BaseURL= http://myip:5100" \
-e "EX_ConnectionStrings__Cache= provider=redis" \
-e "EX_ConnectionStrings__Redis= server=myip:9905,abortConnect=false" \
-e "EX_ConnectionStrings__Elasticsearch= server=http://myip:9200;shards=3;replicas=1" \
-e "EX_ConnectionStrings__MessageBus= provider=redis" \
-e "EX_ConnectionStrings__Queue= provider=redis" \
-e "EX_ConnectionStrings__Storage= provider=folder;path=/app/storage" \
--name exceptionless_job --memory 500m --restart=always -t exceptionless/job:latest

3.docker run -d \
-p 5100:80 \
-e "AppMode= Production" \
-e "EX_ApiUrl= http://myip:5000" \
-e "EX_Html5Mode= true" \
--name exceptionless_ui --memory 500m --restart=always -t exceptionless/ui:latest

4.goto:http://10.9.159.232:5100/signup
5. sign up my user info, but failed as below:
![image](https://user-images.githubusercontent.com/16182251/64517854-b2e24480-d323-11e9-894f-fb03cf4d2405.png)
![image](https://user-images.githubusercontent.com/16182251/64517884-c55c7e00-d323-11e9-98a0-cef3f0205524.png)
![image](https://user-images.githubusercontent.com/16182251/64517906-cb525f00-d323-11e9-95e6-9e7c09e21d92.png)
![image](https://user-images.githubusercontent.com/16182251/64518006-f5a41c80-d323-11e9-92f4-609e43e4b8b9.png)

e...what's wrong?
Ps: due to some personal reason, I can't use the docker-compose up instead of "docker run"

**Comment by ZhiqiangTao** [comment]
upload some docker logs:
1. api log
![image](https://user-images.githubusercontent.com/16182251/64519642-1621a600-d327-11e9-821f-c60940fa3582.png)
2. job log
![image](https://user-images.githubusercontent.com/16182251/64519687-318cb100-d327-11e9-978c-9975f530d25e.png)
![image](https://user-images.githubusercontent.com/16182251/64519697-38b3bf00-d327-11e9-9464-55c70319f510.png)
3. ui log
![image](https://user-images.githubusercontent.com/16182251/64519739-4d905280-d327-11e9-9347-7d9a3026cc63.png)

**Comment by ZhiqiangTao** [comment]
my fault, 
in my docker run command:
-e "EX_BaseURL=  http://10.9.159.232:5100" \  is wrong
-e "EX_BaseURL=http://10.9.159.232:5100" \   is right

**Comment by niemyjski** [comment]
Thanks for the update, I'm glad you got this working. Have you considered using our docker-compose file (it probably would have prevented this)?
