### ISSUE TITLE
api exception:response content-length mismatch: too many bytes written

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless#447]
after I used
![image](https://user-images.githubusercontent.com/16182251/65022754-1bed3c00-d964-11e9-9a7e-e5ea33244b8c.png)

and then I will catch many many below exception:
![image](https://user-images.githubusercontent.com/16182251/65022796-30c9cf80-d964-11e9-8348-499c35fcf956.png)

and I found that many logs don't be inserted successfully due to above exception.

what's wrong with this?

**Comment by ZhiqiangTao** [comment]
note: I migrated from an old version (4.x self host on windows)

**Comment by niemyjski** [comment]
Hello, I'm really not sure on this one perhaps it has to do with your max event post size. Can you try reducing this number.

**Comment by niemyjski** [comment]
Did that fix it?

**Comment by ZhiqiangTao** [comment]
not fix, it seems that this exception does not affect inserting. I said above " many logs don't be inserted " is due to another reason (my fault actually)

**Comment by niemyjski** [comment]
if you continue to get this let me know, I'd like to get to the bottom of it. Perhaps we are setting a header for content length and the payload size is different?

**Comment by ZhiqiangTao** [comment]
@niemyjski  strangely， this exception is disappear recently........
