### ISSUE TITLE
Migrate Projects And Events From v4 To v5

### ISSUE THREAD

**Issue by LydellM** [exceptionless/Exceptionless#448]
We have an existing self-hosted v4 instance of Exceptionless and would like to update to v5 at some point. Is there a way to migrate our existing data (projects, events, etc.) from v4 to v5? We are using file storage to store the events. Let me know if you need more info from me. Thanks!

**Comment by niemyjski** [comment]
There is no migration needed for data on disk or elastic. If you update the paths and connection string in docker-compose you could use your existing cluster and storage. I'd recommend doing this until the next major version as it would make the migration to Elasticsearch 7 a bit easier. However, if you wanted to move it over you could just copy the files from the current structure into the directory configured in the docker compose and then do an elasticsearch snapshot in the old cluster and restore it in the new cluster.

**Comment by niemyjski** [comment]
Please let us know if you have anymore questions or need anymore help.

**Comment by LydellM** [comment]
Ok, that makes sense. I'm not very familiar with Docker, so I was thinking I needed to move data and stuff. Thank you!
