### ISSUE TITLE
Exceptions in Web API MessageHandlers are not logged

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless#45]
When an exception occurs in a message handler when using WebAPI, it is not logged. See the code example below.

    // OWIN startup class
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var configuration = new HttpConfiguration();           
            configuration.MessageHandlers.Add(new MyCustomHandler());
            
            // extra configuration
        } 
    }

    public class MyCustomHandler : DelegatingHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            return base.SendAsync(request, cancellationToken).ContinueWith(t => 
                {
                    throw new Exception("This is not logged");
                });
        }
    }

**Comment by niemyjski** [comment]
We are thinking about releasing a WebApi21 client that has these changes. I'll let you know as soon as we have more info.

**Comment by srijken** [comment]
Is there a similar workaround for the 2.0 version of the API? The `ProcessUnhandledException` method is no longer available.

**Comment by niemyjski** [comment]
I've updated the existing code above. You can also call either one of the two (the first one won't provide any contextual data like request info).

```csharp
ExceptionlessClient.Default.SubmitUnhandledException(ex);
```

or

```chsarp
    public class ExceptionlessExceptionLogger : ExceptionLogger {
        public override void Log(ExceptionLoggerContext context) {
            var contextData = new ContextData();
            contextData.MarkAsUnhandledError();
            contextData.SetSubmissionMethod("ExceptionLogger");
            contextData.Add("HttpActionContext", context.ExceptionContext.ActionContext);

            context.Exception.ToExceptionless(contextData).Submit();
        }
    }
```

**Comment by vindberg** [comment]
Im also trying to log the request info but im the context.ExceptionContext.ActionContext is null. Any ideas?

Thanks in advance.

**Comment by niemyjski** [comment]
I think context has a request object on it and the ActionContext may be null (I'm not sure the use cases when it is). Any chance you could investigate what it would take to add the context.Request to the context data and check for that in our web plugin as well? Can we even get the info we need from it?

**Comment by vindberg** [comment]
The context.Request object does contain some info. But im still missing the request body (Content). Thanks for getting back.

**Comment by niemyjski** [comment]
We weren't logging the request body (only if it was a post), But in the case it's unhandled, some information is always better than none.

**Comment by niemyjski** [comment]
@vindberg Is there any chance you could submit a pull request for this? If not, I'll try my best to look into this soon.

**Comment by niemyjski** [comment]
@vindberg @srijken would you mind submitting a pull request for this. Also do you think we should add this to the documentation for web api?

**Comment by niemyjski** [comment]
Issue moved to [exceptionless/Exceptionless.Net #86](https://github.com/exceptionless/Exceptionless.Net/issues/86) via [**ZenHub.io**](https://www.zenhub.io/)
