### ISSUE TITLE
XMLHttpRequest  has been blocked by CORS policy

### ISSUE THREAD

**Issue by 12371601** [exceptionless/Exceptionless#450]
ENV:Exceptionless-5.0.0

there is one problem with exceptionless on docker when i open this url http://ex-ui.localtest.me:5100/#!/login  and login
Fail:
Access to XMLHttpRequest at 'http://ex-api.localtest.me:5000/api/v2/auth/login' from origin 'http://ex-ui.localtest.me:5100' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

below is hosts file
192.168.137.200 ex-api.localtest.me
192.168.137.200 ex-ui.localtest.me
192.168.137.200 elasticsearch

could you help us ?

**Comment by niemyjski** [comment]
Hello, were you able to solve this issue?

**Comment by 12371601** [comment]
i change the port
#edit 9200 to 9201  , 9300 to 9301  because they were used by skywalking







------------------ 原始邮件 ------------------
发件人: "Blake Niemyjski"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 上午10:01
收件人: "exceptionless/Exceptionless"<Exceptionless@noreply.github.com>;
抄送: "12371601"<12371601@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [exceptionless/Exceptionless] XMLHttpRequest  has been blocked byCORS policy (#450)




Hello, were you able to solve this issue?

**Comment by YanmaY** [comment]
我改了端口也不行，之前还成功过，后来改了docker-compose.yml，然后就不能登录了，报跨域的错误，然后又把docker-compose.yml改回去，还是登录不了，郁闷

**Comment by niemyjski** [comment]
@YanmaY the default docker-compose should be good to go: https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml
