### ISSUE TITLE
How can I use zh-cn in my self hosting?

### ISSUE THREAD

**Issue by CQJonnyLin** [exceptionless/Exceptionless#451]
> I see #155 how to use zh-cn,but I set  **constant('LANGUAGE','zh-cn')**  not success.

Can you help me?

Think you very much

**Comment by niemyjski** [comment]
You need to upgrade to the latest 5.x version and use the latest docker ui image which is in the docker-compose file. Please see the hosting docs for more info

**Comment by CQJonnyLin** [comment]
Thank you very much.
Now our team has not been used docker and k8s.I will set up a local test environment to test.
