### ISSUE TITLE
Why Remove Elasticsearch:1 Image

### ISSUE THREAD

**Issue by jianxuanbing** [exceptionless/Exceptionless#454]
I use docker deploy excepionless. but I found out docker hub remove elasticsearch image.
![image](https://user-images.githubusercontent.com/7100363/66181639-1e5dce80-e6a4-11e9-9dd5-5311c9861fc2.png)

**Comment by niemyjski** [comment]
We didn't remove it, please keep using the elasticsearch:1 image. The 7.4.0
images will be tied to the 6.x release.
Thanks
-Blake Niemyjski

**Comment by ejsmith** [comment]
@niemyjski I did remove it. Because I changed the naming convention to match the version of ES. So there is an exceptionless/elasticsearch:5.6.16 now. The docker-compose file has been updated to match.
