### ISSUE TITLE
Selfhosting setup does not work

### ISSUE THREAD

**Issue by jesha1995** [exceptionless/Exceptionless#455]
When I use "docker-compose up" it gives an error 
ERROR: manifest for exceptionless/elasticsearch:1 not found: manifest unknown: manifest unknown

It seems the TAG has been removed and now it is impossble to do a fresh install of exceptionless on docker.

**Comment by ejsmith** [comment]
Sorry about that. We changed how we are creating our custom docker images and I overly aggressively cleaned up the old image. I have updated the docker-compose in the master branch and it should be good now.

**Comment by jesha1995** [comment]
Thanks a lot, been having fun trying to get it working in ECS on amazon without using the docker compose file.
