### ISSUE TITLE
Performance ingesting events

### ISSUE THREAD

**Issue by john-roland** [exceptionless/Exceptionless#456]
Hello,

we have Exceptionless 4.1 self hosted, and the events are appearing almost 10 minutes later in the UI... 
Can you give me some advice how to improve this ? can I run more jobs to ingest the events ? the webserver is really low in CPU usage.. so it looks like we could use it more.
Or maybe the issue is in the elastic indexes ? i can see that the "stack-v1" index is almost 1 Gb, with 15000 documents.. and the status is yellow (not a good sign, but i don't know what it means)

Any advise about how to improve the performances would be helpful

thank you

John

**Comment by niemyjski** [comment]
You can run more jobs but it would be good to identify the root cause. Is Elasticsearch bogged down (it's memory and IO intensive)? Are the jobs running (what's the cpu usage look like, you said low)? You could bump up the job count and see if that helps but kind of sounds like elastic may need more configuration. Are you running a single node of elasticsearch?

**Comment by john-roland** [comment]
hey Blake :)
thanks for your feedback.

I will ask my sys admin about the elastic usage... i think we have one node with 32GB of RAM and 8 cpu. you might be right that it is the bottleneck.

I've noticed that if i restart the application pool, then there is some more recent events on the dashboard, but after a short period of time, they start to be older..


The cpu on the webserver is less than 5 %.
the configuration in web.config is as below:

 <add key="RunJobsInProcess" value="true" />
 <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />

so i guess it's normal to not see any other processes ? i've tried to run them in a command prompt (is it EventPostJob.exe ?) but i don't see any difference..

btw, how can i see which jobs a running and how many ?

**Comment by niemyjski** [comment]
I think it would be best to focus on upgrading to 5.x which requires no data migration. It runs on asp.net core in docker and it's way more efficient in every regard and you can be 100% certain how it runs as it all runs in docker using the same prod images we use. You should see output as long as it's configured to be run out of process (config is updated to point to Redis etc.)

**Comment by john-roland** [comment]
yeah, but sadly we don't have the infra yet to host any docker or kubernetes... and i will have no resource for this as the project here is to replace EL by a in house system (not my decision :-(  and I just want to make it work as good as possible until it's decommissioned.
I'm checking the elastic server as it seems to be the issue

**Comment by ejsmith** [comment]
I'm guessing that you are running a single box installation which is really meant more for simple setup and not geared toward performance. It runs a single instance of all the jobs in process. Most likely you could change it to run more than 1 instance of the event queue processing job to make it work better. We can definitely do more to improve things when running in a simple single box configuration, but we just wanted to make it easy to run for now.

**Comment by john-roland** [comment]
actually it is runing on two servers, a front end and an elasticsearch on linux.
I think I've spotted the issue: it was coming from the stacks-v1 index that had become huge (1 gb) and the jobs struggle to insert the events..
I don't know why there was so many stacks btw... for now we have just restart from blank stacks & events indexes
