### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by kiquenet** [exceptionless/Exceptionless#458]
IMHO, Maybe useful course in Pluralsight for how install it on premise, configuration, or use it the cloud.

Like Raygun
https://app.pluralsight.com/library/courses/raygun-dotnet-getting-started/table-of-contents

**Comment by niemyjski** [comment]
Would you mind doing a video for us? I'd be more than happy to help with any behind the scenes work.

**Comment by niemyjski** [comment]
I'm going to close this as there is currently no task for us todo. We'd love to have videos and blog posts and would promote any community posts or videos!
