### ISSUE TITLE
ExceptionLess5.0 does not receive log information

### ISSUE THREAD

**Issue by wmowm** [exceptionless/Exceptionless#459]
I built ExceptionLess5.0 on the test server (http://log.wmowm.com), but it can't receive the log. When I send the test log to (https://be.exceptionless.io), I can Received, I will run the project on the server ExceptionLess5.0, still can not receive the log, how to troubleshoot the problem?
![QQ截图20191012184216](https://user-images.githubusercontent.com/16713889/66700399-4abbbf80-ed22-11e9-8892-26db5237526a.png)

**Comment by niemyjski** [comment]
I'd enable client logging (https://github.com/exceptionless/Exceptionless.Net/wiki/Troubleshooting) and ensure the client is configured to send to your sever url. Do you see any errors in the browser when you are viewing the ui at that domain? Also I'd make sure you revoke the api keys you posted here :-) and generate new ones.

**Comment by wmowm** [comment]
I tried to delete all the keys, and newly generated, generated new key: kXzBCVxoiE8BV7THID2KTdjPpHl71TEXrmgkRy58, I check the ui log in docker, there is an exception
Error getting mapping for index events
Server Error (Index=events Type=index_not_found_exception): no such index
[404] GET /events/_mapping/events

**Comment by niemyjski** [comment]
@wmowm can you output the log of elasticsearch docker container. Also if you can join our slack channel if possible we can talk through this in real time.

**Comment by niemyjski** [comment]
I'm going to close this for lack of reply, if you can send us the required information we'll reopen this issue and do our best to get you up and running.
