### ISSUE TITLE
Exceptionless.Signed Unauthorized.

### ISSUE THREAD

**Issue by tinylit** [exceptionless/Exceptionless#460]
Failed to download package 'Exceptionless.Signed.4.3.2027' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg'.
  The SSL connection could not be established, see inner exception.
    Authentication failed because the remote party has closed the transport stream.
  Failed to download package 'Exceptionless.Signed.4.3.2027' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg'.
  The download of 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : Failed to download package 'Exceptionless.Signed.4.3.2027' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg'. [/app/Exceptionless.sln]

**Comment by niemyjski** [comment]
This sounds like an issue with myget, I'd try again or pull the packages off nuget which is the preferred source unless you need a nightly build.
