### ISSUE TITLE
源代码下载下载，有三个项目不能再vs2017、2019中打开

### ISSUE THREAD

**Issue by kfj1688** [exceptionless/Exceptionless#462]
Exceptionless.Web
Exceptionless.Job
Exceptionless.Tests

**Comment by niemyjski** [comment]
Do you have the latest dotnet core sdk installed (2.2.402)?

**Comment by jiangzm** [comment]
> Exceptionless.Web
> Exceptionless.Job
> Exceptionless.Tests

Please try to describe the title and content of the issue in English as this is not a Chinese respositry, Thanks.

@kfj1688 我仿佛看到你在说，我张嘴了怎么还没给我吃呢。

**Comment by niemyjski** [comment]
I'm not sure what your question is, can you please post it in English and we will help you as best as we can.
