### ISSUE TITLE
The nuget server is so slow

### ISSUE THREAD

**Issue by DUWENINK** [exceptionless/Exceptionless#463]
look my docker compose log `

root@DWK-Ubuntu:/home/duwenink/Exceptionless-5.0.0# docker-compose up                                         
Building api
Step 1/34 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2.401 AS build
 ---> 08657316a4cd
Step 2/34 : WORKDIR /app
 ---> Using cache
 ---> 47863949bf12
Step 3/34 : ARG VERSION_SUFFIX=0-dev
 ---> Using cache
 ---> c3e5e8ed3d57
Step 4/34 : ENV VERSION_SUFFIX=$VERSION_SUFFIX
 ---> Using cache
 ---> 27b827a0f5c5
Step 5/34 : COPY ./*.sln ./NuGet.Config ./
 ---> Using cache
 ---> 8f1adfae3223
Step 6/34 : COPY ./build/*.props ./build/
 ---> Using cache
 ---> d7d0fc44c6b6
Step 7/34 : COPY src/*/*.csproj ./
 ---> Using cache
 ---> 833df687d11f
Step 8/34 : RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done
 ---> Using cache
 ---> 00374f591102
Step 9/34 : COPY tests/*/*.csproj ./
 ---> Using cache
 ---> 35896e9af1b0
Step 10/34 : RUN for file in $(ls *.csproj); do mkdir -p tests/${file%.*}/ && mv $file tests/${file%.*}/; done
 ---> Using cache
 ---> 12a445ea3e08
Step 11/34 : RUN dotnet restore
 ---> Running in 53c93097095c
  Failed to download package 'Foundatio.Hosting.8.1.2092-pre' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/foundatio.hosting/8.1.2092-pre/foundatio.hosting.8.1.2092-pre.nupkg'.
  The HTTP request to 'GET https://www.myget.org/F/exceptionless/api/v3/flatcontainer/foundatio.hosting/8.1.2092-pre/foundatio.hosting.8.1.2092-pre.nupkg' has timed out after 100000ms.

`

i am use  the proxy and slow too

**Comment by niemyjski** [comment]
The build should be using nuget dependencies, but myget should be fast. @ejsmith would be nice to just push rebuilt docker images that contain built artifacts.

**Comment by ejsmith** [comment]
Those pre packages will move to GitHub once it allows anonymous access. Also, we should probably have 2 docker-compose files. 1 that builds from source and one that uses the lastest CI built images and then maybe another one that uses official released images.

**Comment by niemyjski** [comment]
Is there any reason to have one that builds from source? If I have a precompiled one why would I ever want to build from source when the compiled code is always going to be the same?

**Comment by DUWENINK** [comment]
we are china devlopments,For well-known reasons ,we can not get this...

**Comment by niemyjski** [comment]
@ejsmith one more reason for having prebuilt packages.

**Comment by DUWENINK** [comment]
Thx~!!!!

**Comment by niemyjski** [comment]
This should be fixed in the 6.x release, I'm working on updating the release notes and upgrade guide.
