### ISSUE TITLE
ExceptionLess In what form are logs kept?File or db?

### ISSUE THREAD

**Issue by uqianle** [exceptionless/Exceptionless#464]
And Mine VS2017 OR VS2019 won't work on this project

**Comment by niemyjski** [comment]
They are kept in Elasticsearch, please ensure that you have the latest .NET Core 2.2 SDK installed. Does this resolve the issue?

**Comment by uqianle** [comment]
I sure the .NET Core is the latest! 2.2.402

**Comment by niemyjski** [comment]
I'm closing this as I think this is resolved it not can you let me know specifically what the remaining issues are.
