### ISSUE TITLE
 Failed to download package 'Exceptionless.Signed.4.3.2027' 

### ISSUE THREAD

**Issue by squarezx** [exceptionless/Exceptionless#465]
Step 11/34 : RUN dotnet restore
 ---> Running in b1dd5c2a7e4b
  Restore completed in 19.74 sec for /app/src/Exceptionless.Core/Exceptionless.Core.csproj.
  Restore completed in 20.22 sec for /app/src/Exceptionless.Insulation/Exceptionless.Insulation.csproj.
  Failed to download package 'Exceptionless.Signed.4.3.2027' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg'.
  The server returned an invalid or unrecognized response.
  Failed to download package 'Exceptionless.Signed.4.3.2027' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg'.
   Received an unexpected EOF or 0 bytes from the transport stream.
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : Failed to download package 'Exceptionless.Signed.4.3.2027' from 'https://www.myget.org/F/exceptionless/api/v3/flatcontainer/exceptionless.signed/4.3.2027/exceptionless.signed.4.3.2027.nupkg'. [/app/Exceptionless.sln]
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error :  Received an unexpected EOF or 0 bytes from the transport stream. [/app/Exceptionless.sln]
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : The feed 'exceptionless-ci [https://www.myget.org/F/exceptionless/api/v3/index.json]' lists package 'Exceptionless.Signed.4.3.2027' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/app/Exceptionless.sln]
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error :   Unable to find package 'Exceptionless.Signed.4.3.2027'. [/app/Exceptionless.sln]

**Comment by niemyjski** [comment]
Hello, Are you still running into this issue? We are going to be moving our dependencies onto GitHub here shortly but the following packages should be pulled from nuget and not myget.

**Comment by squarezx** [comment]
yes,the issue is still running

**Comment by niemyjski** [comment]
This package is on nuget https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Web/Exceptionless.Web.csproj#L12 I wonder why it's being pulled from myget (https://www.nuget.org/packages/Exceptionless.Signed/). @ejsmith I'm guessing here that in the nuget configuration any defined feeds are pulled first? Would be good to get these on GitHub packages and update the default feeds so it's always accessible.

**Comment by niemyjski** [comment]
I removed the myget source in the latest build for now, can you please try the nightly (`5.0.3525-pre`) when it's finished building (https://ci.appveyor.com/project/Exceptionless/exceptionless/builds/28854868).
