### ISSUE TITLE
5.0 Unable to send email notification

### ISSUE THREAD

**Issue by wuzongwen** [exceptionless/Exceptionless#469]
![微信截图_20191206184603](https://user-images.githubusercontent.com/16460092/70317414-aef98c00-1858-11ea-86a3-b2e5a16c0820.png)

**Comment by niemyjski** [comment]
Hello,

What issue are you running into? Are there errors in the email job log? If so can you paste any error log messages you are running into?

**Comment by wuzongwen** [comment]
no error,but can't send mail,and I have clicked resend
![微信截图_20191207111418](https://user-images.githubusercontent.com/16460092/70368184-be251c00-18e2-11ea-917b-384a63ee11e1.png)

**Comment by niemyjski** [comment]
You'll need to look at the docker logs for the email job to see what the issue was. Try triggering an email and then look at the logs to see what it says. It should tell you the issue.

**Comment by niemyjski** [comment]
I'm going to mark this as closed until more information is provided. You can also increase the log levels if the mail job is not giving you enough detailed information as talked about here: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting, My guess would be your mail server requires some extra validation like a verified sender (which can be done in our configuration). If you can provide the logs I'll do my best to tell you the next steps.
