### ISSUE TITLE
How is existing redis configured

### ISSUE THREAD

**Issue by alvin-su** [exceptionless/Exceptionless#472]

**Comment by niemyjski** [comment]
I’m not sure what you mean, we configure it via connection string

**Comment by alvin-su** [comment]
EX_ConnectionStrings__Redis: server=127.0.0.1:6379,password=zxrc607,abortConnect=false

It already exists. Can you configure it this way?

**Comment by niemyjski** [comment]
Yes, that looks right, you'll also need to configure what ever you want to use it like cache and message bus to point to it by specifying a connection string for those of `provider=redis;` which tells it to use reds and look it up by that that named connection string.

**Comment by niemyjski** [comment]
I'm closing this but please let me know if this is not working and we'll reopen this.
