### ISSUE TITLE
No logs will be recorded every day at 8am

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#475]
No logs will be recorded every day at 8am

**Comment by niemyjski** [comment]
Can you please provide more information like versions and behaviors you are seeing as well as any log messages.

**Comment by yun6cc** [comment]
The current situation is that after 8 o'clock every day, exceptionless can correctly receive the log information submitted by the application service,
![image](https://user-images.githubusercontent.com/17695936/71860979-a33b0700-312f-11ea-85c8-28d7121b3af0.png)

 but it does not seem to write to elasticsearch. Now I restart the application service IIS site, and it will record the log normally Yes, found this in elasticsearch log.

![image](https://user-images.githubusercontent.com/17695936/71860948-8bfc1980-312f-11ea-9772-71d888fad792.png)

 Is there something wrong with my elasticsearch configuration?

**Comment by niemyjski** [comment]
What is your utc time zone offset? Seems like there may be issues with creating the index, and there is nothing else in the logs right before 8pm? What happens if you restart the app at 7:55pm?

**Comment by yun6cc** [comment]
My side is China's time zone, which is East 8 district. The problem was before 8am, not afternoon. The log before 8 am can be recorded normally. I have repeatedly confirmed. The last entry is 2020-01-07 07:59:38. At 8 o’clock, it is not recorded.

**Comment by niemyjski** [comment]
What version of Elasticsearch are you running? I'm pretty sure 8am for you is midnight utc which is when the daily index rolls over. Can you turn on verbose logging as per the self hosting troubleshooting docs and send the output around 7:59-8:01am. Sounds like something is goofy going on, also can you please ensure you are on the latest 5.6.x Elasticsearch.

**Comment by yun6cc** [comment]
hello,Elasticsearch version is
{
"name": "R0YDX9v",
"cluster_name": "elasticsearch",
"cluster_uuid": "DI3pi06GQBiqfY_9E8guAw",
"version": {
"number": "5.6.16",
"build_hash": "3a740d1",
"build_date": "2019-03-13T15:33:36.565Z",
"build_snapshot": false,
"lucene_version": "6.6.1"
},
"tagline": "You Know, for Search"
}

And i have confirmed that it is a time zone issue, but after I changed the server time to UTC time yesterday, the index will not be created automatically. Is there any solution?

**Comment by yun6cc** [comment]
There is a log posted at 7: 59-8: 01 AM, and I still have no effect after I change the server time to UTC. My personal computer and local environment are connected to Elasticsearch service, and then it is possible to allocate the Exceptionless ServerUrl of the application station to this machine, but it is not possible to deploy to the production server after publishing. This should confirm that the interaction between Exceptionless and Elasticsearch in the production environment is missing the configuration, but it has not been known what it is.

**Comment by yun6cc** [comment]
Now I can confirm one thing. I cannot create the elascsearch index when I deploy to IIS. Only in F5 directly in VS. Even if it's deployed to my local IIS. But my dotnet exceptionless.web.dll can't run. Excuse me, in a windows environment, except IIS, how to run Exceptionless in the console mode?
![111](https://user-images.githubusercontent.com/17695936/72231891-d16d8a80-35f8-11ea-9d98-f884eccb2bcc.png)
![222](https://user-images.githubusercontent.com/17695936/72231894-d599a800-35f8-11ea-8119-31c8cfd77b1d.png)

**Comment by niemyjski** [comment]
I'd recommend upgrading to the latest version which is hosted in docker. It sounds like IIS is part of the problem and I'm not really sure why.

**Comment by yun6cc** [comment]
It's really sad. The current server system is still win2016. There is no Linux system for the time being. Although win2016 can also run docker, the configuration is too cumbersome. Can you help analyze the problem of exceptionless IIS under win2016 system?

**Comment by niemyjski** [comment]
Hello,

You can get the linux containers working on Windows Server 2016 (https://www.ntweekly.com/2019/09/20/how-to-run-linux-containers-on-windows-server-2016-version-1709/) with one of the latest Windows Updates. I don't have a windows server 2016 machine to test on.

I'd recommend **enabling `Verbose` logging**, downloading the source on a local machine that has IIS and debugging index creation at the next time of day and **hit f5 with break on all exceptions.** If you can **send me the exception that is occurring I can fix it.**

This is one of the core reasons why we moved to docker containers. We get consistent repeatable behavior that just works. Yes, it takes a little bit more work to initially setup (or about the same if you didn't have IIS Configured), but it makes upgrades easy and really simplifies support because you don't see the endless weird issues with IIS configuration / rewrite rules / why isn't this working.

**Comment by niemyjski** [comment]
Can you please see if this is still an issue with 6.x release

**Comment by niemyjski** [comment]
Were you able to see if this is still an issue with 6.x release. I'm really not sure what's going on. If this is still an issue once running on 6.x let me know and we'll reopen this. We haven't been able to reproduce this issue.
