### ISSUE TITLE
Improve Self Hosted ExceptionLess Experience 

### ISSUE THREAD

**Issue by Nonobis** [exceptionless/Exceptionless#49]
Hi,

I have installated Redis & MongoDb via Chocolatey (as service) on my Windows 2012 Server.
=> Redis & Mongo Db as running.

On this same server, i am trying to install Exceptionless.Api.IIS in IIS. But's it's not working.... no log, nothing. I haven't login screen.

The website is :
    on dedicaced pool, on .Net 4.0.
    Binded to xxx.domain.ltd on port 80.

web.config :
    BaseURL : => url binded to website in IIS
    WebsiteMode : Production

Could you help me ?
How can i activate log ?

Thansk by advance.

**Comment by niemyjski** [comment]
@Nonobis we added an account creating setting in 2.0 (EnableAccountCreation). I'm going to close this issue with specifics on how we intend to improve the self hosted experience. I also reated an issue to look into the websockets issue.
