### ISSUE TITLE
support java 

### ISSUE THREAD

**Issue by alvin-su** [exceptionless/Exceptionless#510]
Is there a support plan for Java project types?

**Comment by niemyjski** [comment]
Hello,

We would like to support java project types but it comes down to requests and resource allocation.  You can submit events today from java very easily via an http POST call (https://github.com/exceptionless/Exceptionless/wiki/API-Usage). I'd be more than happy to point you in the right direction. In the mean time, I'm going to close this until this gets more upvotes / comments. We would also be willing to accept a pr for a Java client.
