### ISSUE TITLE
AuthController Signup Failed, Active Directory Authentication Failed

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#529]
Hi, 
I'm hoping to get some help in case someone else has encountered a similar issue as me. 

- We are using the last self-hosted version of Exceptionless 4.1.0. 
- The Web.config is updated with the correct LDAP connection string
- There is one user that is unable to sign up even though they are entering the correct password for their account.

The error in the log file states: 
`2020-02-24 13:38:44.3204  117 ERROR AuthController Signup failed for "username@redacted.com": Active Directory authentication failed.`

I turned trace logging on in the Nlog.config and this is what appeared when the user tried to sign up again. 

```
{
  "id": "5e5599789ce0440fbcb51436",
  "organization_id": "5e2a1d279ce043129c93e9b6",
  "project_id": "5e2b08f89ce0440b68b37c73",
  "stack_id": "5e2b174b9ce046016cb07bf2",
  "is_first_occurrence": false,
  "is_fixed": false,
  "is_hidden": false,
  "created_utc": "2020-02-25T22:02:41.4977772Z",
  "updated_utc": "2020-02-25T22:02:41.5602801Z",
  "idx": {
    "referrer-s": "http://redacted.com:50000/#!/signup"
  },
  "is_deleted": false,
  "type": "error",
  "source": "http://redacted.redacted.com:50000/api/v2/auth/signup",
  "date": "2020-02-25T22:02:32.115+00:00",
  "tags": [
    "UI"
  ],
  "message": "[400] http://redacted.redacted.com:50000/api/v2/auth/signup",
  "data": {
    "response": {
      "data": "",
      "status": 400,
      "config": {
        "method": "POST",
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "jsonpCallbackParam": "callback",
        "url": "http://redacted.redacted.com:50000/api/v2/auth/signup",
        "data": {
          "name": "First Last",
          "email": "username@redacted.com",
          "password": "REDACTED"
        },
        "withCredentials": false,
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json;charset=utf-8"
        },
        "cached": false
      },
      "statusText": "Bad Request",
      "xhrStatus": "complete"
    },
    "referrer": "http://redacted.redacted.com:50000/#!/signup",
    "@version": "2.7.1163",
    "@error": {
      "modules": [
        {
          "module_id": 0,
          "name": "http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js",
          "version": "3.2.1",
          "is_entry": false,
          "created_date": "0001-01-01T00:00:00",
          "modified_date": "0001-01-01T00:00:00"
        },
        {
          "module_id": 1,
          "name": "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js",
          "version": "3.3.7",
          "is_entry": false,
          "created_date": "0001-01-01T00:00:00",
          "modified_date": "0001-01-01T00:00:00"
        },
        {
          "module_id": 2,
          "name": "http://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js",
          "version": "4.17.4",
          "is_entry": false,
          "created_date": "0001-01-01T00:00:00",
          "modified_date": "0001-01-01T00:00:00"
        },
        {
          "module_id": 3,
          "name": "https://js.stripe.com/v2/",
          "is_entry": false,
          "created_date": "0001-01-01T00:00:00",
          "modified_date": "0001-01-01T00:00:00"
        },
        {
          "module_id": 4,
          "name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "is_entry": false,
          "created_date": "0001-01-01T00:00:00",
          "modified_date": "0001-01-01T00:00:00"
        },
        {
          "module_id": 5,
          "name": "http://redacted.redacted.com:50000/app.config.77fc9ddd679d37dc.js",
          "is_entry": false,
          "created_date": "0001-01-01T00:00:00",
          "modified_date": "0001-01-01T00:00:00"
        }
      ],
      "message": "[400] http://redacted.redacted.com:50000/api/v2/auth/signup",
      "type": "Error",
      "data": {
        "@target": {
          "ExceptionType": "Error",
          "Method": "responseError()",
          "Message": "[400] http://redacted.redacted.com:50000/api/v2/auth/signup"
        }
      },
      "stack_trace": [
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 15,
          "column": 25532,
          "is_signature_target": true,
          "name": "responseError",
          "module_id": 0
        },
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 12,
          "column": 13042,
          "is_signature_target": false,
          "name": "i",
          "module_id": 0
        },
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 12,
          "column": 13447,
          "is_signature_target": false,
          "name": "<anonymous>",
          "module_id": 0
        },
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 12,
          "column": 19144,
          "is_signature_target": false,
          "name": "n.$digest",
          "module_id": 0
        },
        {
          "file_name": "redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 12,
          "column": 20958,
          "is_signature_target": false,
          "name": "n.$apply",
          "module_id": 0
        },
        {
          "file_name": "redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 12,
          "column": 17017,
          "is_signature_target": false,
          "name": "<anonymous>",
          "module_id": 0
        },
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 10,
          "column": 30140,
          "is_signature_target": false,
          "name": "e",
          "module_id": 0
        },
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 10,
          "column": 31602,
          "is_signature_target": false,
          "name": "<anonymous>",
          "module_id": 0
        },
        {
          "file_name": "http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js",
          "line_number": 3,
          "column": 8853,
          "is_signature_target": false,
          "name": "b",
          "module_id": 0
        }
      ]
    },
    "@request": {
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
      "is_secure": false,
      "host": "redacted.redacted.com",
      "port": 50000,
      "path": "/",
      "client_ip_address": "xx.xx.xx.xxx",
      "cookies": {
        "EpNet_ActiveMenuLayout": "skinny",
        "mongoMachineId": "11217306",
        "__stripe_mid": "7c210711-53f0-4941-9916-76cacbeff19a",
        "__stripe_sid": "7aa55a92-f06c-45e1-ad5f-3f8bf9eac623"
      },
      "data": {
        "@browser": "Chrome",
        "@browser_version": "75.0.3770",
        "@browser_major_version": "75",
        "@os": "Windows 10",
        "@is_bot": false
      }
    },
    "@submission_method": "errorHttpInterceptor"
  },
  "reference_id": "deba4b198c"
}
```

Not sure if this is relevant but accessing http://redacted.redacted.com:50000/api/v2/auth/signup from both client/server displayed this in the browser:

```
{
  "Message": "The requested resource does not support http method 'GET'."
}
```

**Comment by Edreih** [comment]
I followed the [troubleshooting documentation](https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting) and the errors showing up in Exceptionless pertaining to this are:

`Error: Possibly unhandled rejection: {"data":{"Message":"Authorization has been denied for this request."},"status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","headers":{"Accept":"application/json, text/plain, */*"},"cache":{},"url":"http://redacted.redacted.com:50000/api/v2/organizations","cached":false},"statusText":"Unauthorized","xhrStatus":"complete"}`

```
Error: [400] http://redacted.redacted.com:50000/api/v2/auth/signup
at responseError() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 15:col 25505
at i() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 12:col 13038
at Anonymous function() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 12:col 13447
at n.prototype.$digest() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 12:col 18985
at n.prototype.$apply() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 12:col 20956
at Anonymous function() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 12:col 17015
at e() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 10:col 30138
at Anonymous function() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 10:col 31590
at b() in http://redacted.redacted.com:50000/app.min.a62ad1efed547861.js:line 3:col 8844
```

anyone seen anything like this before?

**Comment by niemyjski** [comment]
That doesn't make any sense, the controller log says it's getting POSTed and your last code snippet says it's doing a get request. Is the browser doing a POST?

**Comment by Edreih** [comment]
Thank you for your response. 
It looks like a POST to /api/v2/auth/signup and a GET to /api/v2/organizations , two different requests. I got the second code snippet today after inserting project API key in app.config

This may also be a separate issue but I'd like to mention that on the server accessing localhost:50000 it is a blank page with only the favicon showing up... so I cannot access the api documentation.

**Comment by niemyjski** [comment]
What does your docker-compose export for ports for the api? I think it should be port 5000 not 50000 perhaps that is the issue? Have you tried debugging this by starting up an instance in VS and then pointing the UI to that?

**Comment by Edreih** [comment]
We aren't and can't use docker for the time being. We are self hosting Exceptionless (`version: "4.1.2861 359390c442"`). 

I don't think the Exceptionless port would matter for authenticating a user with our AD. 5/6 users that signed up were able to authenticate. 1 user cannot. This user belongs to the same AD groups as us. We even tried clearing both the Redis and Elasticsearch databases with no luck. Does this issue look like an AD or Exceptionless problem? Or any ideas on how to pinpoint it?

Btw, I was able to access the API documentation directly by appending `docs/index` to the end of the URL. 
Using the `POST /api/v2/auth/signup` operation did not work and showed status code of 400 with an empty response body.

**Comment by niemyjski** [comment]
I'm really not sure at this point, we do not use active directory and we are running on version 6.0 currently. Can you please try pulling down the code and running it locally under the debugger and try to step through it. Seems like an AD Issue because you are getting `Authorization has been denied for this request.` which seems like it is what would be returned from any ad call.

**Comment by Edreih** [comment]
Thank you. 
I've managed to fix this error with a workaround. We used the API with PowerShell to signup instead of the UI; It worked and authenticated with AD.

**Comment by Edreih** [comment]
I wanted to add this comment in case it helps others. 

**Problem**
Some users unable to sign up to self-hosted Exceptionless using LDAP authentication.

**Investigation**
During debugging, we noticed signup is calling the function `GetUsernameFromEmailAddress` in `ActiveDirectoryLoginProvider.cs`. This function searches the AD directory and returns the _first_ username its finds from the email address the user entered. Sometimes, there can be two usernames tied to an email address (such as an admin account). The user may have different passwords for their regular vs admin account. So if an admin username is returned and the password entered does not match, an error will occur.

**Solution**
In order for Exceptionless to pull the correct username for a user, your LDAP connection string needs to be more _specific_. Compare the OU for users vs admin users. For example, the connection string that worked for us is: `LDAP://ldap.example.com/OU=Standard Users,OU=User Accounts,DC=example,DC=com`.

**Comment by niemyjski** [comment]
Awesome thanks for the heads up. Any chance you'd be willing to add this to the wiki and or submitting a pr to throw a detailed exception when two users are resolved.
