### ISSUE TITLE
Excessive messages in queue causes Event Processing Failure

### ISSUE THREAD

**Issue by ocbaker** [exceptionless/Exceptionless#53]
Hey,

I'm currently running the latest master branch of Exceptionless on an Azure Server and testing it with reporting from a game server we had a game loop function that threw an error on every tick (so you can imagine, there were a lot of error, turned out to be around 6,000 in 10 minutes)

We quickly identified this error and fixed it, however we noticed that the Exceptionless Web UI was no longer reporting new bugs (even test ones) I ended up having to restart the backend servers (excluding elastic) and the API Worker for the error queue to start being processed again, however after it had got through around 3,500 messages the API seemed to freeze again and required the same restart.

Some good news is that even when the API freezes it is still accepting new events, so you will not loose any events over this time. so it seems like one of the Jobs for events and perhaps one of the backend servers is being overloaded and does not handle that correctly.

The test server was a D2 Azure instance and had no signs of struggling with the load it was given.

If you need any more information please let me know.

**Comment by ocbaker** [comment]
A bit of an update, I managed to encounter this issue again and after manually starting the Event Job the Exceptionless UI starts populating all the old messages. So somehow the JobRunner must be crashing on IIS and doesn't restart itself. If I can get this job runner to crash I'll post some more information.

**Comment by niemyjski** [comment]
Thanks for the report. We are also currently looking into this issue, we saw the same thing happen during stress testing under very high load.

**Comment by niemyjski** [comment]
Are you using azure web jobs?

**Comment by ocbaker** [comment]
No, Just running manually on a VM at the moment.

**Comment by niemyjski** [comment]
So your using in process jobs?

**Comment by ocbaker** [comment]
I have a couple of IIS servers setup for the UI and API, and I've using the backend servers bat. For the time being I am also manually running the EventPosts Job run.bat

**Comment by niemyjski** [comment]
So are you just using vms?  Did you update your web.config to turn off in process jobs? Also, if you are doing a lot of logging, you may want to tell the client to use InMemoryQueues ( https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Bootstrapper.cs#L83 ) This will prevent the events from being persisted to disk (at the expense that you will lose any log events when the process exits prematurely).

**Comment by ocbaker** [comment]
I was watching the server and the RunJobs process starting doing this: http://i.imgur.com/Whrzn46.png

It was spamming the console. Restarting the job fixed the issue and refreshing the browser the events started updating realtime again.

My Disk HAT isn't that bad, I've not noticed any bottlenecks really during normal operation: http://i.imgur.com/mwMuRuB.png

**Comment by niemyjski** [comment]
What I see from that error is that Redis went down but if you never restarted it that wouldn't be the case. Thanks for the info, we are still trying to track this down.

**Comment by ocbaker** [comment]
Another update, since that error above now rather than throwing that error the RunJobs process just silently quits, the only indication is that the dashboard no longer updates. Starting the Job again it continues like normal.

**Comment by niemyjski** [comment]
We made some updates that may improve this.. Is there any chance you can pull down latest and see if you can still reproduce. I'll be doing the same.

**Comment by niemyjski** [comment]
We've made a bunch of changes tonight and we think we have solved this issue. Can you please try the latest code and see if you can reproduce. If you can please comment on this issue and we will reopen it.
