### ISSUE TITLE
Stack events discarding and snoozing

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#530]
One of the biggest issues we currently have with Exceptionless is users having some rogue event going off and eating up their entire monthly plan limits. In the past we tried to say that users should fix this on their side of things and didn't give them any tools to do anything about it on the Exceptionless side. This results in peoples accounts getting throttled and the value we are providing to that user being diminished. One of the big reasons we took that stance is because we are paying for bandwidth and computing power required to process those events on our side and then discard them. We have decided that we are going to do the right thing for the users and eat that cost by allowing stacks of events to be marked as discarded. Any events coming in that match that stack will be thrown away and not count against your plan.

In order to do this, we are going to do a refactoring on stacks to add a new `status` field and get rid of the `IsHidden` and the `IsRegressed` flag as well. Status will be able to be one of `open`, `discarded`, `fixed`, `regressed`, `snoozed`, `ignored`.

Snoozing would be a new feature that would let you mark a stack as snoozed for X amount of time. During that time, the stack would be filtered out of the normal stack lists and you would not receive any notifications for events on that stack. Ignored status would work the same except it would be a permanent ignore.

In addition, for a long time we have wanted to make events immutable. We currently bulk update events to mark them as hidden when their corresponding stack is marked as hidden. Bulk updating millions of events is really expensive especially because Elasticsearch is rather slow for updating documents. We are going to take the stance that events are immutable and are basically just a log message. They can be searched and filtered, but marking a stack as fixed has no effect on its events. You would not be able to filter events based on fixed status. Making events immutable as well as making their associated daily indexes read only after a couple days (can't add events that happened more than a few days into the past) would allow us to optimize event index storage as well.

## Server

- [x] Add new `Status` and `SnoozedUntilUtc` properties to `Stack`, make sure that status and snoozed are indexed so that queries like `status:discarded` work.
- [x] Remove `IsHidden`, `IsRegressed` and `DisableNotifications` from `Stack`, remove from index settings
- [x] Remove `IsFixed`, `IsHidden` and `IsDeleted` from `PersistedEvent`, remove from index settings
- [x] Remove all code that is updating the `PersistedEvent` - `IsFixed` and `IsHidden` properties
- [x] Make sure we do not send any notifications for stacks with status of `fixed`, `discarded`, `ignored` or `snoozed`]
- [x] Make sure that we don't break existing webhooks by adding pseudo fields for is_fixed and is_hidden that are derived from status
- [x] Change spam detection (user agents and massive amounts for single IP) to discard the events instead of hiding them
- [x] Make sure that events are completely immutable (only thing being updated are session start events for now)
- [x] Discard any events coming in where the stack is marked as discarded. Do not count these against the organizations plan limits, but increment a counter just so we know how many events are being discarded
- [x] `/change-status` should clear `snoozeUntilUtc`
- [x] Figure out why `status:Open` is treated as a premium feature usage
- [x] Figure out why no stacks are being returned
- [x] Move all event deletes into a queue so that we can pause delete processing during migrations as they will no longer support soft deletes
- [x] Add a job that looks for stacks where the snoozed until date is past and changes status back to open
- [x] Update email templates to change disable notifications option to actions for discard and snooze 
- [x] Create migration to add new mappings to stack index and set stack status
- [x] If stack filter has `status:open`, then negate the stack query to get a smaller list of stack ids
- [x] If stack filter hits 10k limit, then negate the stack query to see if it returns a smaller list of stack ids
- [x] If stack filter still hits 10k limit, then make sure message is shown to the user to tell them narrow their filter criteria
- [x] Consider increasing the 10k ES terms limit
- [ ] Job to delete stacks that have a last occurrence date older than the organizations retention period
- [x] Delete stack is just soft delete
- [x] Delete all project data is just marking all stacks as deleted
- [x] Job to cleanup deleted stacks / events after some period of time (definitely should cleanup stacks, might not be worth processing power to delete events in the middle of indexes and cause a lot of index fragmentation)
- [ ] Verify summary emails are still working
- [ ] Add Event Visitor to remove any queries containing `status:`. Currently filters are applied across all stack and event requests. If the filter contains `status` then nothing is returned.

## UI 
- [x] Update default stack filter to exclude `fixed`, `discarded`, `ignored` or `snoozed` statuses
- [x] Update UI Stack grid bulk actions to allow Mark Discarded, Mark Not Discarded, Mark Ignored, Mark Not Ignored, Mark Fixed, Mark Not Fixed, Delete.
- [x] Add ignore action to UI
- [x] Update UI to remove disable notifications actions on stacks
- [x] Update UI to change hide stack action to discard action
- [x] Update UI to add snooze action. Modal will be shown that asks how long to snooze for. Changes status to snoozed and adds a date for when the stack should be snoozed until
- [x] Remove Most Recent view
- [x] Remove Most Frequent section from Timeline. 
- [x] Change Most Recent section to be called Events. Make it show 20 items instead of 10.
- [x] Move new Timeline view to the bottom of the list of views in the nav. 
- [x] Rename Dashboard to Timeline
- [x]  Add Redirects for changed routes
- [x] Update UI Translations
- [x] Fix Sentinel: Failed connecting to configured master for service: exceptionless errors 
- [x] Surface error message when hitting the 10k terms limit so users know they need to narrow their filter

## Other
- [ ] Update search documentation

**Comment by ejsmith** [comment]
One questions is, should a stack be able to be both snoozed and regressed at the same time? I don't think it makes sense. I think the only way a stack can be marked as regresses is if it was already marked as fixed. Marking as fixed is effectively the same thing as snooze (hidden in lists by default and no notifications). If a new event happens that goes to that stack with a new version than the fixed in version then the stack would be marked as regressed and notifications would resume and it would show back up in the stack lists.

**Comment by ejsmith** [comment]
I think we should add an `ignored` status as well which is just permanently snoozed. No notifications.

**Comment by niemyjski** [comment]
I agree, I was thinking the same thing

**Comment by ejsmith** [comment]
I started working on this and got rid of all event updates except the one where it is updating the session information on an event. Not sure how we can keep from updating that.

**Comment by niemyjski** [comment]
We need to get this up in an environment, it's a bit hard to try stuff out on the client with nothing server side.

**Comment by niemyjski** [comment]
This is a table that I created because I kept on getting slightly confused when working with the ui

| Previous Property   | `status`       | Description                                         |
| ------------------- |:------------ |:----------------------------------- |
|                                  | `open`          | The default                                         |
|                                  | `discarded ` | Won't count again event limit (new)|
| `is_fixed`                 | `fixed`           | The default                                        |
|  `is_regressed`       | `regressed`  | The default                                        |
|  `is_hidden`             | `snoozed `    | time based snooze, no notifications |
| `is_hidden`, `disable_notifications` | `ignored `     | permanent snooze, no notifications |

**Comment by ejsmith** [comment]
How was it confusing you?? It’s a problem if the people that are working on it are confused.

**Comment by ejsmith** [comment]
@niemyjski UI looks good other than /dashboard not getting redirected. I think it makes sense. I think there are other things we can do to improve things, but I think this is good for now.

**Comment by ejsmith** [comment]
Running into big issues trying to get events immutable while still allowing users to view slices of their data. If I want to see my most frequent issues over the last 24 hours, I need to join the data available in the stacks and events collections which isn't something that Elasticsearch supports. So you are left either de-normalizing data which is what we are doing now and ending up updating millions of event documents every time someone changes a status or the other option is we do our own application side join where we start by filtering down to a big list of potential stack ids and then filtering events by that big list of ids in order to do aggregations that will tell you what stacks have the most number of events or users, etc. We are thinking that we REALLY want to not be in the business of updating millions of documents every time someone changes a status for many reasons. So we are going to try and implement application side joins.

1. Gonna need to create a query processor that will break out filters into things that apply to stacks and things that apply to events.
2. Query stacks to get down to a list of stack ids that fit the filter criteria.
  a. We can use the date filter against the first and last occurrence fields to help narrow the list down.
  b. There is a limit of 10,000 for terms filters in Elasticsearch. Need to show message saying user needs to narrow down criteria if we exceed the 10,000 limit.
  c. Possibly inverse the entire filter to get a shorter list of stack ids. Should be less non-open stack ids than open ones. Maybe we try this as a fallback when the 10,000 limit has been exceeded.
3. Query events using the events part of the user filter in combination with our list of stack ids from the previous query.
  a. Use a terms query with aggregations that return the total event count and user count. (Already doing this)
  b. This is where paging is happening just like it is currently implemented.
  c. Returns a terms list of unique stack ids in the desired sort order (ie. Most Affected Users).
4. Take resulting list of stack ids and the correlated aggregation data and splice it together with the stack documents to get a paged list of stacks in the correct sorted order with their corresponding event count and user counts. (Already doing this)

**Comment by ejsmith** [comment]
Migration
- Add `Status` and `SnoozeUntilUtc` fields to stack index
- Script that sets the `Status` field on stack index based on whether or not the fixed field is set

**Comment by ejsmith** [comment]
- `status:fixed` => `@stack:(status:fixed)` => `(stack_id:(id1 id2 id3))`
- `type:error fixed:false hidden:false date:[2020-05-08..2020-06-08]` => `type:error @stack:(-status:fixed) @stack:(status:open OR status:regressed) date:[2020-05-08..2020-06-08]` => `type:error (stack_id:(id1 id2 id3)) (stack_id:(id4 id5 id6)) date:[2020-05-08..2020-06-08]`
  - Fixed and hidden need to go to stack query
  - `hidden:false` translates to `status:open OR status:regressed` as those are the only 2 statuses that should normally be visible.
  - Results in 2 stack id list filters. Don't make assumptions about grouping stack queries together. We will work on a query optimizer that merges those together at a later time.

**Comment by niemyjski** [comment]
@ejsmith Need a little discussion on this. I tried putting this on discord but t was a bit much..

Retention Limits Job:
  _eventDeletionQueue.EnqueueAsync(new EventDeletion {
      OrganizationIds = new []{ organization.Id },
      UtcEndDate = cutoff
  });

Throttle Bots Plugin:
  _eventDeletionQueue.EnqueueAsync(new EventDeletion {
      OrganizationIds = new []{ firstContext.Event.OrganizationId },
      ClientIpAddress = clientIpAddressGroup.Key,
      UtcStartDate = SystemClock.UtcNow.Floor(_throttlingPeriod),
      UtcEndDate = SystemClock.UtcNow.Ceiling(_throttlingPeriod)
  });

EventController:
  - HTTP Delete (ids):
      _eventDeletionQueue.EnqueueAsync(new EventDeletion { EventIds = ids });



StackController:
  - HTTP Delete (ids):
      Soft deletes the stack..

Project Controller:
  Reset Project Data (should soft delete stacks only):
    string workItemId = await _workItemQueue.EnqueueAsync(new RemoveProjectWorkItem {
        OrganizationId = project.OrganizationId,
        ProjectId = project.Id,
        Reset = true
    });

  Delete Project (should soft delete project and remove all tokens so no more submission happens):

Delete Organization (should soft delete org and remove all tokens so no more submission happens):


Problems:
- When it comes to org and project deletion I almost want to queue the deletion
  process but it really just needs to remove tokens which I could do inline and
  then call base and have it soft delete the projects.
- For project reset, Seems like I'd want to enqueue it as described above only to
  batch soft delete stacks.. Thinking it would be nicer to just enqueue that to 
  a work item handler but it might be really nice to just pause a queue / have a 
  dedicated one for that...

- Thinking of removing the RemoveProject and Remove Organization work item handler
  jobs completely. They shouldn't be called or triggered. We need a dedicated 
  cleanup job which would go and clean up soft deletes.

- Later have a new job that looks at projects and orgs for free plans that haven't
  been used, queue emails to be sent and at some cutoff soft delete (cleanup job will do it)

- Idea is to have no work item handler jobs to do any big work like deletes.

**Comment by niemyjski** [comment]
Just added search documentation.
