### ISSUE TITLE
With 6.8 Elasticsearch version which docker should I use!

### ISSUE THREAD

**Issue by a14907** [exceptionless/Exceptionless#538]
My Elasticsearch version is 6.8
And I start my exceptionless by docker, So whick version(docker tag) should I use?
Are there any notes about the version relationship between them?

**Comment by niemyjski** [comment]
Hello, we don't support version 6.x at all. We currently only support Elasticsearch 7.x with version 6.0. You should use the `exceptionless/elasticsearch:7.6.0` image.

**Comment by ejsmith** [comment]
I believe latest version of the app would probably work against Elasticsearch 6.8 as well.
