### ISSUE TITLE
Bulk actions in the log filter are misleading

### ISSUE THREAD

**Issue by ocbaker** [exceptionless/Exceptionless#54]
I had a server that was sending errors into a log like fashion, we updated the server to report these warnings and errors to exceptionless. We found pretty quickly that a certain error was being spammed into the log with the same message everytime.

I thought that if I used the filter (message:[message]) and then did a bulk action on the remaining of the Most Recent then it would only delete the messages I had filtered since the UI was only reporting the number of log messages that matched my filter. However when I did the bulk action it deleted all my log items.

I think that expected behaviour for a situation like this would be to only delete the items that were presented to you in the returned filter results or inform the users about the number of items that they are about to delete so they can check the filtered number to see if these numbers match. (Which they wouldn't in my case)

**Comment by niemyjski** [comment]
Thanks for your feedback. 

Did you delete items from the Most Frequent? If you delete items from the Most Recent (events) it will only delete those events. But if you delete from the Most Frequent (stacks) you are removing the whole stack and all of it's event occurrences (which we don't know the count of without doing a query). What do you think the message should be when trying to delete a stack or events (You are trying to delete (4) stacks and all of its events??)?

**Comment by ocbaker** [comment]
Just so I am clear on the logging dashboard I see: http://i.imgur.com/8ZB246Q.png
as you can see I have a lot of unhandled rpc messages (most of the log is tem actually)
You can see in the next screenshot I've filtered only the type of message that I want to delete:
http://i.imgur.com/zn43Bw3.png

Now, in the second image if I click the checkbox on the (global) stack item and choose the option delete I am expecting 62,822 messages to be deleted. however increase I get all 153,142 log messages deleted.

I think that the message should be something that says like "This action (delete) will *not* take your filter into consideration, are you sure?" Or if the functionality is updated to account for the filter I'm not sure if a message change would be expected at that point? Does the behaviour I am explaining sound expected for deleting stacks in a filter result?

**Comment by niemyjski** [comment]
Yeah, the stack just shows you how many log messages match the search filter for that stacking target. When you delete a stack you are deleting everything. I'll have a discussion with the team about clarifying the delete message.

If you set the source of the log message you create (Ex. the type of the class that's sending it), they will be stacked by that instead of falling into a global stack.

**Comment by ocbaker** [comment]
Can that be arbitrary? So could I use that to create a stack of "rpc 10" for example?

**Comment by niemyjski** [comment]
You can set it to anything :). It just takes a string. You can even put extended data on the log message. We have a overload that sets the log level too (Trace, Info, Debug, Warn, Error). We only special case those log levels in the ui but you can set that to anything as well. I think there is a limit on the string length (but it would be hard to hit it unless you put a massive string as the source).

**Comment by niemyjski** [comment]
@ocbaker Would you mind submitting a pull request for this change

**Comment by niemyjski** [comment]
@ocbaker do you think maybe the best solution would say `Are you sure you want to delete these stacks and all related events?` instead of `Are you sure you want to delete these stacks?`

**Comment by niemyjski** [comment]
Issue moved to [exceptionless/Exceptionless.UI #84](https://github.com/exceptionless/Exceptionless.UI/issues/84) via [**ZenHub.io**](https://www.zenhub.io/)
