### ISSUE TITLE
Can't verify my email. (6.0.0)

### ISSUE THREAD

**Issue by BinGuoGuo** [exceptionless/Exceptionless#545]
When I registered my account and sended an email to my emailbox, I received the verification link. But this link is not work. My account is still unverified after I clicked it.

Below is the api log:
`[02:51:23 INF] xxxxxxxxx@qq.com signed up.`
`[02:52:34 WRN] Token mOBvtGA6iHW7u2abPsJirFcxIiQLboXwHa1xF0Kd for /api/v2/projects/config `
`not found.`
`[02:52:34 INF] HTTP GET /api/v2/projects/config?v=1 responded 401 in 5.5533 ms`

By the way, I can't receive any email before I added below code at src\Exceptionless.Core\Configuration\EmailOptions.cs line 50

> string emailConnectionString = config.GetConnectionString("Email");
            if (!String.IsNullOrEmpty(emailConnectionString)) {
                var uri = new SmtpUri(emailConnectionString);
                options.SmtpHost = uri.Host;
                options.SmtpPort = uri.Port;
                options.SmtpUser = uri.User;
		**options.SmtpFrom = uri.User;**
                options.SmtpPassword = uri.Password;
            }

**Comment by niemyjski** [comment]
Are you getting the email? Is the link pointing to the correct url for the front end? You can configure the SmtpFrom by setting an environment variable for it like the others. It doesn't need to come from the uri.

**Comment by BinGuoGuo** [comment]
Yes,I got the account confirmation email, and the verify address is "http://192.168.x.x:5100/account/verify?token=/tr44tjsAHqks85ahnclxGaI8ZQphkK1k1DCwSfZW"

I clicked it then the page redircted to the main page,I found my account still unverified.

But I can use this token （tr44tjsAHqks85ahnclxGaI8ZQphkK1k1DCwSfZW） on Swagger's api （/api/v2/users/verify-email-address/{token}）to activate my account.

**Comment by niemyjski** [comment]
That token looks wrong with the forward slash. Can you see if that is the problem?

**Comment by BinGuoGuo** [comment]
I've tried to remove the forward slash. It didn't work too.
Followed are my steps:

1. I registered an account on` http://192.168.xxx.xxx:5100/#!/login`
2. I copied the url from email (`http://192.168.xxx.xxx:5100/account/verify?token=GlWcRYIE9EL6IuJB3QgxP0fJ85sG2MB9cI1lqAYr)` into the browser ,but it redirected to this address (`http://192.168.xxx.xxx:5100/account/verify?token=GlWcRYIE9EL6IuJB3QgxP0fJ85sG2MB9cI1lqAYr#!/login`)
3. I checked my account,it shows `Email not verified. Resend verification email.`

My docker container infos are:

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                            NAMES
8db7ee3e6b52        exceptionless/job:latest                "dotnet Exceptionles…"   2 days ago          Up 3 hours                                                           exceptionless_jobs_1
97d7b1a37933        exceptionless/api:latest                "dotnet Exceptionles…"   2 days ago          Up 3 hours          0.0.0.0:5000->80/tcp                             exceptionless_api_1
a57b6776dcc0        docker.elastic.co/kibana/kibana:7.6.0   "/usr/local/bin/dumb…"   2 days ago          Up 3 hours          0.0.0.0:5601->5601/tcp                           exceptionless_kibana_1
766912a3d1cb        exceptionless/ui:latest                 "bootstrap"              2 days ago          Up 3 hours          0.0.0.0:5100->80/tcp                             exceptionless_ui_1
d4fcf349bd25        redis:5.0-alpine                        "docker-entrypoint.s…"   2 days ago          Up 3 hours          0.0.0.0:6379->6379/tcp                           exceptionless_redis_1
528fc131623d        exceptionless/elasticsearch:7.6.0       "/usr/local/bin/dock…"   2 days ago          Up 3 hours          0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   exceptionless_elasticsearch_1

```
They are maybe helps...
I want to provider more infomation about this issue, but I have no idea what infos are useful to help diagnosis. If you need other details, please let me know.

**Comment by BinGuoGuo** [comment]
Add my docker images:

```
$ docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
exceptionless/elasticsearch            7.6.0               0229ff089833        13 days ago         799MB
exceptionless/api                      latest              3a55f0310a93        2 weeks ago         258MB
exceptionless/job                      latest              1b6e6b00a059        2 weeks ago         255MB
docker.elastic.co/kibana/kibana        7.6.0               b36db011e72c        6 weeks ago         1.01GB
redis                                  5.0-alpine          b68707e68547        2 months ago        29.8MB
exceptionless/ui                       latest              ae3ef2f4d14d        7 months ago        135MB
```

**Comment by niemyjski** [comment]
What are your environment settings set to in docker compose?

**Comment by BinGuoGuo** [comment]
Yes.I changed the `EX_BaseURL`(URL to UI) to http://192.168.xx.xxx:5100 in `api model` and `jobs model`, and changed the `EX_ApiUri` to https://192.168.xxx.xxx:5000 in `ui mode`l.

Finnally I uncommented the `EX_ConnectionStrings__Email` and changed the value to smtps://xxx.turbo%40qq.com:passwordxxx@smtp.qq.com:465 in `api model` and `jobs model`.

Here is my docker-compose file, some sensitive words are replaced by "xxx".
[docker-compose.txt](https://github.com/exceptionless/Exceptionless/files/4362321/docker-compose.txt)

**Comment by niemyjski** [comment]
Thanks, I'll take a look.

**Comment by niemyjski** [comment]
I'm unable to reproduce this under the debugger. The account verify always works. Can you open chrome and look at the request to `/api/v2/users/verify-email-address/TOKEN` and let me know what this response and url is.

**Comment by nodyang** [comment]
> Yes.I changed the `EX_BaseURL`(URL to UI) to http://192.168.xx.xxx:5100 in `api model` and `jobs model`, and changed the `EX_ApiUri` to https://192.168.xxx.xxx:5000 in `ui mode`l.
> 
> Finnally I uncommented the `EX_ConnectionStrings__Email` and changed the value to smtps://xxx.turbo%40qq.com:[passwordxxx@smtp.qq.com](mailto:passwordxxx@smtp.qq.com):465 in `api model` and `jobs model`.
> 
> Here is my docker-compose file, some sensitive words are replaced by "xxx".
> [docker-compose.txt](https://github.com/exceptionless/Exceptionless/files/4362321/docker-compose.txt)


I configured the mail the way you did. I haven't received any information

**Comment by BinGuoGuo** [comment]
@nodyang  You should configure the SmtpFrom by setting an environment variable or add it in source code.

**Comment by BinGuoGuo** [comment]
@niemyjski  I can't access the address `http://192.168.xxx.xxx:5000/api/v2/users/verify-email-address/yrVYFRgpGIk1nKgDkGBTSbqb6yVKLSOnC6DHSXhR` directly. It returns me a 401 http error. Then I try it again on swagger api `http://192.168.xxx.xxx:5000/docs/index.html` with an authorization, it works!

I have no idea why I can't do this by using the email content.It seems like my website didn't access the verification api.
Below is the access record when I click the email button
![debug](https://user-images.githubusercontent.com/30474925/77715577-ed3cd600-7016-11ea-812c-0a7b84305c60.jpg)

**Comment by niemyjski** [comment]
The verification url gets generated and sent by the front end. I don't know what would be different by hitting an ip vs localhost other than port forwarding which seems to be the common denominator. I'll have to try this. Can you look in elasticsearch GET /organization-v1/_doc/ORGID and see if the token: `yrVYFRgpGIk1nKgDkGBTSbqb6yVKLSOnC6DHSXhR` is valid.

**Comment by BinGuoGuo** [comment]
I've tried to look at `localhost:9200/organization-v1/_doc/Milan`,but I got a error:
`{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [organization-v1]","resource.type":"index_expression","resource.id":"organization-v1","index_uuid":"_na_","index":"organization-v1"}],"type":"index_not_found_exception","reason":"no such index [organization-v1]","resource.type":"index_expression","resource.id":"organization-v1","index_uuid":"_na_","index":"organization-v1"},"status":404}`

I'm sorry I don't know much about the usage of elasticsearch...and kibana.

**Comment by niemyjski** [comment]
It would be GET /organizations-v1/_doc/ORGID org id would have to be a object id.. You can grab it from the ui on manage project. Also It's organizations with an s (my bad).

**Comment by BinGuoGuo** [comment]
I can't GET `/organizations-v1/_doc/5e70d55e583f33000124be11`, I got the same 404 error.
But I can GET `/prod-organizations-v1/_doc/5e70d55e583f33000124be11`
Here is the JSON result:

> {
"_index":"prod-organizations-v1",
"_type":"_doc",
"_id":"5e70d55e583f33000124be11",
"_version":1,
"_seq_no":0,
"_primary_term":1,
"found":true,
"_source":{
"id":"5e70d55e583f33000124be11",
"name":"Milan",
"plan_id":"EX_UNLIMITED",
"plan_name":"Unlimited",
"plan_description":"Unlimited",
"billing_change_date":"2020-03-17T13:49:18.2286855Z",
"billing_changed_by_user_id":"5e70d00c583f33000124be10",
"billing_status":0,
"billing_price":0.0,
"max_events_per_month":-1,
"bonus_events_per_month":0,
"retention_days":180,
"is_suspended":false,
"has_premium_features":true,
"max_users":-1,
"max_projects":-1,
"usage":[
{
"date":"2020-03-01T00:00:00Z",
"total":0,
"blocked":0,
"limit":-1,
"too_big":0
}
],
"created_utc":"2020-03-17T13:49:18.2314116Z",
"updated_utc":"2020-03-17T13:49:18.2314116Z"
}
}

It seems  have no token field...

**Comment by niemyjski** [comment]
If you don't see it in the list, then the user has already been added to the org (will happen if it's an existing user) or the invite was never sent / errored out while adding.

It should look something like this:

```json

    "max_users" : -1,
    "max_projects" : -1,
    "invites" : [
      {
        "token" : "U04JbBo1fm6m2w3vJNtR1Xv7Nn02o0jMACcUKswb",
        "email_address" : "xyz+test22222@abc.com",
        "date_added" : "2020-04-03T12:13:47.9583972Z"
      }
    ],
    "usage" : [
      {
        "date" : "2020-03-01T00:00:00",
        "total" : 0,
        "blocked" : 0,
        "limit" : -1,
        "too_big" : 0
      }
    ],
```

Is there any chance you can join our slack (link in the readme) and we can talk in real time about this and perhaps start a zoom to look at it?

**Comment by niemyjski** [comment]
Is there any chance you can join our slack (link in the readme) and we can talk in real time about this and perhaps start a zoom to look at it?

**Comment by BinGuoGuo** [comment]
Yes, I'd like to help improve Exceptionless. Now I've joined the slack.

**Comment by niemyjski** [comment]
Looks like the `EX_BaseURL` is missing the `/#!` at the end (because `EX_Html5Mode: 'true'` wasn't set on the app container

**Comment by niemyjski** [comment]
We just need to update the default docker-compose to enable html5 mode and test it.

**Comment by niemyjski** [comment]
I updated the default docker compose.

**Comment by landonzeng** [comment]
> Are you getting the email? Is the link pointing to the correct url for the front end? You can configure the SmtpFrom by setting an environment variable for it like the others. It doesn't need to come from the uri.

Can the environment variable of smtpfrom be set in docker without changing the current code? 
For example: ex_ ConnectionStrings__ SmtpFrom： uri.User
Is that going to work?

**Comment by BinGuoGuo** [comment]
> > Are you getting the email? Is the link pointing to the correct url for the front end? You can configure the SmtpFrom by setting an environment variable for it like the others. It doesn't need to come from the uri.
> 
> Can the environment variable of smtpfrom be set in docker without changing the current code?
> For example: ex_ ConnectionStrings__ SmtpFrom： uri.User
> Is that going to work?

It should be `EX_SmtpFrom: balabala@xxx.com`

**Comment by landonzeng** [comment]
> > > Are you getting the email? Is the link pointing to the correct url for the front end? You can configure the SmtpFrom by setting an environment variable for it like the others. It doesn't need to come from the uri.
> > 
> > 
> > Can the environment variable of smtpfrom be set in docker without changing the current code?
> > For example: ex_ ConnectionStrings__ SmtpFrom： uri.User
> > Is that going to work?
> 
> It should be `EX_SmtpFrom: balabala@xxx.com`

好的，谢谢兄弟，这个地方的账号必须是EX_ConnectionStrings__Email的发送邮箱吗？还是可以随意？

**Comment by niemyjski** [comment]
I'm not sure what your last message said but yes @BinGuoGuo is correct.

**Comment by landonzeng** [comment]
> I'm not sure what your last message said but yes @BinGuoGuo is correct.

The problem has been solved. Thanks
