### ISSUE TITLE
Broken Filter when selecting part of graph

### ISSUE THREAD

**Issue by ocbaker** [exceptionless/Exceptionless#55]
I selected part of the graph to drill down to see where an error was happening and I got an error loading stats.

Something annoying was it took me a while to realise that my search had actually caused an error, I got a message about stats not working but I didn't really click that it was to do with the filter, it would be cool if the colour of the icons on the top bar could turn red if this kind of error happened for example.

The request: 
```
http://.../api/v2/stats?filter=fixed:false+hidden:false&offset=60&time=2015-02-20T17:45:59-2015-02-20T18:12:36
```
The Response: 
```
{
  "message": "An error has occurred. Please check your search filter."
}
```

**Comment by niemyjski** [comment]
That search query looks right does it still error out every time? I'm not seeing any failures on our server side for stats (we log all of them).

Yeah, I agree there should be some kind of visual clue that the search filter might be bad but I'm not sure when we should highlight the ui for it. The query could fail for a number of reasons not related to the search filter.

**Comment by ocbaker** [comment]
It errors everytime.

**Comment by niemyjski** [comment]
Yeah, I'll try a few things after the initial 2.0 release and see how we can make this better.

**Comment by niemyjski** [comment]
I was able to reproduce the error and I am taking a look into it.
