### ISSUE TITLE
Job run EventPostsJob failed: Unable to retrieve payload 'q\a4c\a4c5fca52ae8468e814224b1c2ecfbde.payload'

### ISSUE THREAD

**Issue by nodyang** [exceptionless/Exceptionless#562]
Job run EventPostsJob failed: Unable to retrieve payload 'q\a4c\a4c5fca52ae8468e814224b1c2ecfbde.payload'

**Comment by nodyang** [comment]
> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /prod-events-v1-2020.03.30. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]" CausedBy: "Type: mapper_parsing_exception Reason: "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]""

**Comment by niemyjski** [comment]
You'd get this error if you are not using our docker containers or you don't have the `mapper-size` plugin installed. You can either install this elastic plugin or turn it off via the elasticsearch connection string by adding a query string of `enable-size-plugin=false`
