### ISSUE TITLE
is not working 

### ISSUE THREAD

**Issue by nodyang** [exceptionless/Exceptionless#563]
You'd get this error if you are not using our docker containers or you don't have the `mapper-size` plugin installed. You can either install this elastic plugin or turn it off via the elasticsearch connection string by adding a query string of `enable-size-plugin=false`

_Originally posted by @niemyjski in https://github.com/exceptionless/Exceptionless/issues/562#issuecomment-605991065_

3Q I installed mapper-size and it doesn't seem to work very well

I need to pay attention to something. Or provide more help or information

**Comment by niemyjski** [comment]
Can you please expand on it doesn't seem to work very well? Are you running into an error with it enabled?

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/77963243-9df4ef00-730f-11ea-8d88-73098aea4c8e.png)
isload 
 Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [stack_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

**Comment by niemyjski** [comment]
We index stack id as a keyword field, I'm not sure if you are running into any specific issues or not? We use the mapper-size to get an average size per document.
