### ISSUE TITLE
Add multiple objects of the same type does not work

### ISSUE THREAD

**Issue by matteomigliore** [exceptionless/Exceptionless#58]
If you call multiple times the AddObject with the same type but different instances, only the last is added.

**Comment by niemyjski** [comment]
This is by design. If you call AddObject the key is inferred by the object type if you don't specify a name (which would be the second parameter).

**Comment by matteomigliore** [comment]
Yes, but it should be a problem in some cases, for example I can add more dictionaries or dynamic objects. I think that you should consider to compare instances instead of only the types.

**Comment by niemyjski** [comment]
This has been fixed in the latest nightly build of the client. This can be found on myget in a little bit or on nuget the next time we push the client.
