### ISSUE TITLE
[Suggestion]EventPostsJob throw an error "Unable to retrieve payload ...." when Depolyed on K8s

### ISSUE THREAD

**Issue by i542873057** [exceptionless/Exceptionless#580]
When i using  the helm files in k8s folder to  install exceptionless . I get an error "Unable to retrieve payload ....". After my debugging,i found the EventPostsJob will get the Payload file first. But the payload file will create at web project..so it can't find the file and throw the error .If i use the third party cloud storge and everything is ok,but i use my owner nfs to save file.
so i think should amount pvc storage in "jobs.yaml" file to the section "jobs-event-posts".
Like this:
![image](https://user-images.githubusercontent.com/16971894/79314441-445a0a80-7f34-11ea-930c-d918fbde8c4b.png)

**Comment by ejsmith** [comment]
Yeah, there is a lot of work to be done in that department to make things work better. Really the only time our app can work with local storage is if everything is running in process. Because in Kubernetes you can't attach the same storage to multiple pods.
