### ISSUE TITLE
I just want to keep the log within 7 days

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#592]
Hello, thank you very much for providing this open source tool.

But now there is a big problem. I just want to keep the log within 7 days, but I don't know what to do. Can you tell me something?

This is really important to me!
@niemyjski

**Comment by niemyjski** [comment]
You can do this by setting an environment variable `EX_MaximumRetentionDays` to `7`. 

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/AppOptions.cs
