### ISSUE TITLE
PHP client

### ISSUE THREAD

**Issue by ZeroX66** [exceptionless/Exceptionless#60]
Hi there!

I think we need a PHP client so we can use this in WordPress and other scenarios or why not an WordPress plugin :)

/Regards, Micke

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
@ZeroX66 Would you mind submitting a pull request for a PHP Client?

**Comment by niemyjski** [comment]
I'm going to close this in the meantime until a pull request or code is submitted to us for this.

**Comment by ZeroX66** [comment]
But I don’t have any client for that? Why you don’t request it ?

**Comment by WangNingkai** [comment]
I think I can submit  a pull request ,but i don't have  specific enents API documentation . @niemyjski
