### ISSUE TITLE
Document required / recommended resources

### ISSUE THREAD

**Issue by alexanderadam** [exceptionless/Exceptionless#609]
[I'm currently looking for self-hosted alternatives to Sentry](https://stackoverflow.com/questions/61204374/make-sentry-on-premise-installation-more-lightweight) and I wasn't able to find anything regarding the required resources of Exceptionless.
So it would be great if you could document the resources for self-hosted Exceptionless (i.e. Memory/CPU).

**Comment by ejsmith** [comment]
@alexanderadam did you look at our [Self-Hosting](https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting) docs? That is currently all we have. Would love if you could help us by improving those docs and adding some resource requirements to it.

**Comment by alexanderadam** [comment]
Wow, thank you for the fast response! :pray: 

I did have a look at them but I can't see any requirement specs and I probably would have to set the project up first to getting to know them. But currently I'm still in the exploration phase and I don't have an Exceptionless instance running. That's why I'm asking.

**Comment by niemyjski** [comment]
Our docker containers run linux which has the .NET Core 3.1 configured. You must meet the minimum requirements for docker or k8s.

**Comment by niemyjski** [comment]
Please feel free to respond to this issue, I'm going to close it unless any further questions are presented.
