### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless#61]
Because data are not kept for a long time (3 days to 180 days).
Because using web API is not very user friendly.

Thank you.

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
@CyberSinh Would you mind submitting a pull request for this?

**Comment by niemyjski** [comment]
I'm closing this for now, if more people vote on this or submit a pull request we'll open it back up. Currently you can use the api to get access to all of your content.
