### ISSUE TITLE
Question: integration to open/update/closing issues in source code issue trackers (i.e. Gitea, GitLab, Gogs or GitHub)

### ISSUE THREAD

**Issue by alexanderadam** [exceptionless/Exceptionless#610]
I saw that it is possible to integrate Slack webhooks, so I am curious whether Exceptionless has the flexibility to integrate generic scripts on certain events or whether there's any other possibility to integrate issue trackers of self-hosted source code apps like [Gitea](https://github.com/go-gitea/gitea), [GitLab](https://gitlab.com/gitlab-org/gitlab), [https://github.com/gogs/gogs](https://github.com/gogs/gogs) or [GitHub](https://github.com/enterprise).

All of them have APIs that should make an integration possible (see for instance the [Gitea API](https://try.gitea.io/api/swagger)).

**Comment by ejsmith** [comment]
@alexanderadam I would love to have 1st class integrations with all of them, but we have limited resources. If it's something that you'd like to contribute to the project then that would be awesome!! If not then your best bet would be to use a webhook and create a handler that talks to the API and does whatever you are wanting to do.

**Comment by niemyjski** [comment]
I'm going to close this for now, we'd love to have native first class integrations for these various services and would be willing to accept pr's for them. In the mean time webhooks or Zapier can be used to target these integrations.
