### ISSUE TITLE
Dockerfile publishing failed

### ISSUE THREAD

**Issue by 1301536601** [exceptionless/Exceptionless#613]
Use the downloaded dockerfile
RUN dotnet restore Prompt：
/usr/share/dotnet/sdk/3.1.101/NuGet.targets(123,5): error : Unable to load the service index for source https://f.feedz.io/foundatio/foundatio/nuget/index.json. [/app/Exceptionless.sln]
/usr/share/dotnet/sdk/3.1.101/NuGet.targets(123,5): error :   Resource temporarily unavailable [/app/Exceptionless.sln]
ERROR: Service 'api' failed to build: The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by niemyjski** [comment]
When did you download the docker file? We no longer require building the source.

**Comment by ejsmith** [comment]
@1301536601 I assume you are trying to build the app and not just run the app? If so, you don't even need to use the Dockerfile to build it. We just use it for repeatability and for creating the docker images that we deploy. If you are trying to do the same then it will use the feedz nuget source to try and pull packages. So if it was down or something then the build would probably fail.

**Comment by niemyjski** [comment]
I think feedz might be blocked in china, and this is why we are running into all these issues.

**Comment by niemyjski** [comment]
Please let us know if you are trying to run or build the app.

**Comment by niemyjski** [comment]
Can you please try the docker-compose file located here: https://github.com/exceptionless/Exceptionless/blob/feature/discard-join/docker-compose.yml

**Comment by wufengren** [comment]
@niemyjski I tried this docker-compose file and published successfully, but I have another issue in the signup page. No matter which email I give, it always would be prompted "A user already exists with this email address".

![211855](https://user-images.githubusercontent.com/56917658/81696417-7197cb00-9496-11ea-8a61-8ec497877ab6.png)

**Comment by niemyjski** [comment]
Check your browser network tab, I'm guessing it's due to api server configuration on the client's config.js not pointing to your web server.

**Comment by yaoxiadu** [comment]
Your mirror can be downloaded, what is the URL

**Comment by niemyjski** [comment]
@yaoxiadu You'd need to follow the self hosted documentation and put the ip or hostname of your server hosting exceptionless in the url.

I'm closing this as the new docker-compose file has been merged into the master repo.
