### ISSUE TITLE
docker-compose run and Account registration failed

### ISSUE THREAD

**Issue by Amber-Wish** [exceptionless/Exceptionless#615]
when i type my email, It prompts "mailbox already exists". it is my first run.
I see the following information from the docker log：
`jobs_1  | [03:54:18 INF] Waiting for startup actions to be completed for 09:55...
api_1   | [03:54:18 ERR] Health check Cache completed after 0.2008ms with status Unhealthy and 'Cache Not Working.'
jobs_1  | [03:54:18 ERR] Health check Elasticsearch completed after 1046.6579ms with status Unhealthy and 'Elasticsearch Ping Failed'
api_1   | [03:54:19 ERR] Health check Elasticsearch completed after 1047.3136ms with status Unhealthy and 'Elasticsearch Ping Failed'
jobs_1  | [03:54:19 ERR] Health check Cache completed after 0.2048ms with status Unhealthy and 'Cache Not Working.'
api_1   | [03:54:20 ERR] Health check Cache completed after 0.2537ms with status Unhealthy and 'Cache Not Working.'
jobs_1  | [03:54:21 ERR] Health check Elasticsearch completed after 2001.4816ms with status Unhealthy and 'Elasticsearch Ping Failed'
api_1   | [03:54:21 ERR] Health check Elasticsearch completed after 1047.1251ms with status Unhealthy and 'Elasticsearch Ping Failed'
jobs_1  | [03:54:22 ERR] Health check Cache completed after 0.1867ms with status Unhealthy and 'Cache Not Working.'
api_1   | [03:54:22 ERR] Health check Cache completed after 0.166ms with status Unhealthy and 'Cache Not Working.'
`

**Comment by Amber-Wish** [comment]
I posted my docker-compose.yaml code
`version: '3.7'

services:
  api:
    image: exceptionless/api:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://XX.XXX.178.XX:5151      #UI地址，my ali cloud server IP
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://XX.XXX.178.XX:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=127.0.0.1:6379,password=xxxxxx,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80 # This can be commented out if using reverse proxy.
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://XX.XXX.178.XX:5151     #UI地址，my ali cloud server IP
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://XX.XXX.178.XX:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=127.0.0.1:6379,password=xxxxxx,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://XX.XXX.178.XX:5000        #API，my ali cloud server IP
      EX_Html5Mode: 'true'
      #EX_EnableSsl: 'false'
      #EX_EnableAccountCreation: 'false'
    ports:
      - 5151:80 # This can be commented out if using reverse proxy.

#  reverseproxy:
#    depends_on:
#      - api
#      - ui
#    image: valian/docker-nginx-auto-ssl
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ssldata:/etc/resty-auto-ssl
#    environment:
#      ALLOWED_DOMAINS: '(ex-ui|ex-api).mydomainn.com'
#      SITES: 'ex-ui.mydomainn.com=ui;ex-api.mydomainn.com=api'

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local`

**Comment by Amber-Wish** [comment]
I posted my docker-compose.yaml code：

version: '3.7'

services:
  api:
    image: exceptionless/api:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://XX.XXX.178.XX:5151      #UI地址，my ali cloud server IP
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://XX.XXX.178.XX:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=127.0.0.1:6379,password=xxxxxx,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80 # This can be commented out if using reverse proxy.
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://XX.XXX.178.XX:5151     #UI地址，my ali cloud server IP
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://XX.XXX.178.XX:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=127.0.0.1:6379,password=xxxxxx,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://XX.XXX.178.XX:5000        #API，my ali cloud server IP
      EX_Html5Mode: 'true'
      #EX_EnableSsl: 'false'
      #EX_EnableAccountCreation: 'false'
    ports:
      - 5151:80 # This can be commented out if using reverse proxy.

#  reverseproxy:
#    depends_on:
#      - api
#      - ui
#    image: valian/docker-nginx-auto-ssl
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ssldata:/etc/resty-auto-ssl
#    environment:
#      ALLOWED_DOMAINS: '(ex-ui|ex-api).mydomainn.com'
#      SITES: 'ex-ui.mydomainn.com=ui;ex-api.mydomainn.com=api'

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local

**Comment by Amber-Wish** [comment]
My es service and redis service are running locally

**Comment by Amber-Wish** [comment]
Can someone help me

**Comment by niemyjski** [comment]
I'd check your connection string for elasticsearch, you can see from the container logs that it can't connect to elasticsearch. I'm going to close this issue but please respond back if you have any additional questions.
