### ISSUE TITLE
External access

### ISSUE THREAD

**Issue by nickzhao0617** [exceptionless/Exceptionless#616]
i have installed the exceptionless in local windows system. 
after installation, the website only native access is allowed. I want to know how to allow external IP access the website.
i have tried to modify 'web.config' and 'app.config.*.js' 
![image](https://user-images.githubusercontent.com/15995512/81541356-8d6f7400-93a5-11ea-970c-8ded12386260.png)
![image](https://user-images.githubusercontent.com/15995512/81541391-995b3600-93a5-11ea-92a8-b31ce3811b93.png)

**Comment by niemyjski** [comment]
You'll need to look into port forwarding via your router / firewalls. Also, I'd recommend using the latest release which uses docker. We no longer support IIS.
