### ISSUE TITLE
Why the email always reminds me that it already exists

### ISSUE THREAD

**Issue by yaoxiadu** [exceptionless/Exceptionless#620]
http://120.78.123.43:5100/#!/signup

**Comment by yaoxiadu** [comment]
http://120.78.123.43:5000   Can't open, why

**Comment by wufengren** [comment]
save problem.

**Comment by niemyjski** [comment]
Have you ensured that the api url you defined in the docker compose is accessible via your browser? You may also have to do port forwarding to expose that port if you are trying to access the server out of the servers network.

**Comment by chengfeng19** [comment]
save problem

**Comment by niemyjski** [comment]
Have you ensured that the api url you defined in the docker compose is accessible via your browser? You may also have to do port forwarding to expose that port if you are trying to access the server out of the servers network.

**Comment by chengfeng19** [comment]
Thank you. It has been solved.
