### ISSUE TITLE
How to config more than one redis?

### ISSUE THREAD

**Issue by a14907** [exceptionless/Exceptionless#629]
In the environment var, I set like this :

`- name: EX_ConnectionStrings__Redis
            value: "server=redis-1.web:6379,abortConnect=false"`

this is for one redis.

and I want to setting more than one redis instance.How?

like this?

`server=redis-1.web:6379,abortConnect=false;redis-2.web:6379,abortConnect=false;`

These redis are organized by redis sentine. Is this redis provider support redis sentine?

If not support, Is it possible for me to provide more than one redis connections and the provider are smart enough to handle these redis connections ?

**Comment by ejsmith** [comment]
Sentinel is not currently support by `StackExchange.Redis` but I have recently been [working with them to try and get it supported](https://github.com/StackExchange/StackExchange.Redis/pull/1431). Once that work is done then we plan to use a sentinel setup ourselves and it will be supported in Exceptionless. Let them know in [that issue](https://github.com/StackExchange/StackExchange.Redis/pull/1431) that this is important to you.

**Comment by a14907** [comment]
> Sentinel is not currently support by `StackExchange.Redis` but I have recently been [working with them to try and get it supported](https://github.com/StackExchange/StackExchange.Redis/pull/1431). Once that work is done then we plan to use a sentinel setup ourselves and it will be supported in Exceptionless. Let them know in [that issue](https://github.com/StackExchange/StackExchange.Redis/pull/1431) that this is important to you.

StackExchange.Redis support more than one redis connectionstrings! so how exceptionless support this. That is the problem. What I want to know is the way to config this.

**Comment by niemyjski** [comment]
We don’t support redis cluster, we are waiting for that pr

**Comment by ejsmith** [comment]
@a14907 I haven't actually tried it, but we are just passing through the `server=` part of the connection string `EX_ConnectionStrings__Redis` to `StackExchange.Redis` connect. So if you can do multiple in that (which I think you can) then you should be able to do the same.

**Comment by a14907** [comment]
> @a14907 I haven't actually tried it, but we are just passing through the `server=` part of the connection string `EX_ConnectionStrings__Redis` to `StackExchange.Redis` connect. So if you can do multiple in that (which I think you can) then you should be able to do the same.

It works!

**Comment by ejsmith** [comment]
Awesome.

**Comment by a14907** [comment]
> Awesome.

setting like this:

name: EX_ConnectionStrings__Redis

value: "server=redis-0.web:6379,redis-1.web:6379,redis-2.web:6379,abortConnect=false"
