### ISSUE TITLE
How to set ElasticSearch account password？

### ISSUE THREAD

**Issue by eli1331413** [exceptionless/Exceptionless#631]
When the account and password are set on my ElasticSearch server, how can my program be set to connect to the server？

**Comment by niemyjski** [comment]
It's `key=pair;` syntax with known keys: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/ElasticsearchOptions.cs#L66-L67 

Like this: `server=http://localhost:9200;username=blah;password=blah;`
