### ISSUE TITLE
No open sessions to check

### ISSUE THREAD

**Issue by chengfeng19** [exceptionless/Exceptionless#635]
After successful deployment, the Api and UI can run normally, but the exception message cannot be written to the error message, the log message shows No Open Sessions to check, it seems that the Job cannot be started.

**Comment by niemyjski** [comment]
Can you please attach any available logs for more context. Where are you seeing the No Open Sessions?

**Comment by chengfeng19** [comment]
version: '3.7'

services:
  api:
    depends_on:
#      - elasticsearch
      - redis
    image: exceptionless/api:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://exceptionlesscoreui.1hai.cn #URL to UI
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://172.xx.x.xxx:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80 # This can be commented out if using reverse proxy.
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://exceptionlesscoreui.1hai.cn
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://172.xx.x.xxx:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://exceptionlesscoreapi.1hai.cn
      EX_Html5Mode: 'true'
      EX_EnableSsl: 'false'
      EX_EnableAccountCreation: 'true'
    ports:
      - 5100:80 # This can be commented out if using reverse proxy.

#  reverseproxy:
#    depends_on:
#      - api
#      - ui
#    image: valian/docker-nginx-auto-ssl
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ssldata:/etc/resty-auto-ssl
#    environment:
#      ALLOWED_DOMAINS: '(ex-ui|ex-api).mydomainn.com'
#      SITES: 'ex-ui.mydomainn.com=ui;ex-api.mydomainn.com=api'

#  elasticsearch:
#    image: exceptionless/elasticsearch:7.7.0
#    environment:
 #     discovery.type: single-node
 #     xpack.security.enabled: 'false'
 #     ES_JAVA_OPTS: -Xms2048m -Xmx2048m
 #   ports:
 #     - 9200:9200
 #     - 9300:9300
 #   volumes:
 #     - esdata7:/usr/share/elasticsearch/data
  
#  kibana:
#    depends_on:
#      - elasticsearch
#    image: docker.elastic.co/kibana/kibana:7.7.0
#    ports:
#      - 5601:5601

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local

**Comment by ejsmith** [comment]
That message "No open sessions to check" is normal. It's not an error. It's just saying that there aren't any sessions currently open when it's looking for them to do maintenance on. @niemyjski we probably shouldn't be logging that out every time or we should change it to a more descriptive message.

**Comment by chengfeng19** [comment]
Thank you. At present, API (HTTPS) site is deployed in Docker system, local test generation environment API, and abnormal data will be lost with a high probability.

**Comment by yun6cc** [comment]
> Thank you. At present, API (HTTPS) site is deployed in Docker system, local test generation environment API, and abnormal data will be lost with a high probability.
> exceptionlessClient.SubmitException() method The current anomaly is that after one wave is written, the second wave will not be written properly

哥们儿你好，我现在也出现了你的这个问题，你这边有处理好的吗？求指教！

**Comment by niemyjski** [comment]
Can you create the exact steps we need to reproduce this error. Also, can you please translate your last message.

**Comment by niemyjski** [comment]
Can you create the exact steps we need to reproduce this error. Also, can you please translate your last message.
