### ISSUE TITLE
Exceptionless v5 to v6 migration

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#658]
As mentioned here:
https://github.com/exceptionless/Exceptionless/issues/638#issuecomment-646634863

I've been further experimenting with it and I'm unable to resolve it. What I've already tried:
- Use 7.8.0 tag of ES.
- Migrate all existing ES v5 data first to another docker instance and then migrate from that.

The error remains the same. What's weird is that it doesn't always stop at the same date. Both ES instances are still running (and working well as far as I can tell).

**Comment by niemyjski** [comment]
I'd try upgrading using v6 and not 6.1.0. Also would you mind editing the https://github.com/exceptionless/Exceptionless/wiki/Upgrading upgrade log with any steps we missed about the whitelist. Maybe turn up the elastic log levels to see why it's crashing maybe it's a massive event or something like that?

Also you should turn off all jobs while migrating so it isn't messing with indexes or the like (saves this step ASPNETCORE_URLS)

**Comment by Phyxion** [comment]
> Also you should turn off all jobs while migrating so it isn't messing with indexes or the like (saves this step ASPNETCORE_URLS)

Any guide on that? I've been fiddling around with the settings a bit but all it ended up was closing the container as nothing running anymore.

**Comment by niemyjski** [comment]
Don't start the jobs or set the app setting to not run jobs in process. You don't even need the web container to do the migration just elastic instances and the one migration job.

**Comment by niemyjski** [comment]
Are you using the all in one image? If so, set `EX_RunJobsInProcess` to `false`

**Comment by Phyxion** [comment]
I'm using the separate docker file with separate containers, but I can try adding EX_RunJobsInProcess to the compose file. I will give it a try with the v6 upgrade as well.

**Comment by niemyjski** [comment]
We just haven't ran the migration with 6.1 and Eric removed sorting from the reindex job in nightlies

**Comment by ejsmith** [comment]
That wouldn't have any affect as it wasn't supported anyway. I guess the point is though that we didn't test the migration that we did ourselves and know that it works against newer versions of Exceptionless so it would be better to use the one we know that works.

Are you not getting any sort of feedback or error messages? Either in the app logs or Elasticsearch?

**Comment by Phyxion** [comment]
> Are you not getting any sort of feedback or error messages? Either in the app logs or Elasticsearch?

Yes/no, the only error is this (for each day):

`[11:16:09 ERR] Error creating the index prod-events-v1-2020.05.01: Original: (503 - ElasticsearchClientException) Request failed to execute. Call: Status code 503 from: PUT /prod-events-v1-2020.05.01. ServerError: Type: process_cluster_event_timeout_exception Reason: "failed to process cluster event (create-index [prod-events-v1-2020.05.01], cause [api]) within 30s"
Server: (503) Type: process_cluster_event_timeout_exception Reason: "failed to process cluster event (create-index [prod-events-v1-2020.05.01], cause [api]) within 30s"`

Until it just gives up. This is all there is, the ES logs don't show anything out of the ordinary, at least not to me. I'll give the v6.0 a try soon and also try to copy the data to my local PC, which is much faster and might help with the timeouts (if it's actually a timeout and not something else).

**Comment by niemyjski** [comment]
Seems weird you'd get a timeout for this. Is your cpu pegged by any chance on the elastic instance?

**Comment by ejsmith** [comment]
Yeah, it seems like ES is maybe running out of resources or something? It sounds like you have multiple instances of ES running inside of docker? If so, that could be a problem.

**Comment by Phyxion** [comment]
There should be enough CPU and memory available, even when migration is running the CPU usage rarely goes above  ~10%. There's about 24GB of RAM free as well, so I guess this shouldn't be an immediate problem. All instances are responding fine, during and after migration, so I'm not sure if it's a resource problem, but I'll give it another try soon.

**Comment by ejsmith** [comment]
Hmm... not sure then. Nothing else to go on? It just hangs and doesn't show any error messages or any feedback in any of the app or ES logs?

**Comment by Phyxion** [comment]
Not that I know of. The system is running fine. But I gave it another try and lo and behold:
[09:00:29 INF] Updated aliases
[09:00:29 INF] datamigration job completed.

This time I used exceptionless/job:6.0.0, which was necessary as 6.1.0 gave a missing task_id error which I was unable to resolve, and performed the migration from the system with the old ES to local PC (ES7).

I've tried `EX_RunJobsInProcess` on just the jobs image but that didn't stop it from launching, but changing the host as mentioned above worked OK so that wasn't much of a problem.

I have now also started using the single container docker instance (with a compose file). Data is being logged. Happy days at least 😜

**Comment by Phyxion** [comment]
I have also updated the wiki with the information so this can now be closed.

**Comment by ejsmith** [comment]
@Phyxion thats great to hear!

**Comment by Phyxion** [comment]
Went with semi docker instead as couldn't get reverse proxy ip forwarding to work (all users showed as docker ip address). I just dockered elastic and redis. I'll try to get full docker to work some day 😁

**Comment by PhyxionNL** [comment]
@ejsmith Been giving it a try now but I can't get it to work out of the box. Exceptionless keeps using the docker IP (i.e. ::ffff:172.18.0.1) for events on Environment > IP Address. The forwarding headers are set up correctly. Other containers, such as https://hub.docker.com/r/telefonica/remote-ip, show the remote ip address correctly. 

The problem lies in the fact that the forward headers are not completely configured in Startup > ConfigureServices at the moment. There needs to be a configuration option to specify the KnownProxies of the ForwardedHeadersOptions. I can submit a PR for this if you'd like. I have already verified that adding the docker IP to KnownProxies fixes this issue. I would create a property KnownProxies here https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/AppOptions.cs.

**Comment by niemyjski** [comment]
@PhyxionNL Can you open a new issue for this? We've seen this happen from time to time as well but haven't been able to track it down in our cluster. We'd love a pr for this! How would you know the known proxies, especially at scale?

**Comment by PhyxionNL** [comment]
Yes, let me do that. I'm not running a cluster, but it might not always be required to set these. I don't see any documentation here https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1 to set these dynamically.

**Comment by ejsmith** [comment]
Very interesting... I'm digging into this. Thank you for helping us with this issue!
