### ISSUE TITLE
provide python logging handler

### ISSUE THREAD

**Issue by hiwjcn** [exceptionless/Exceptionless#664]
provide python logging handler

**Comment by niemyjski** [comment]
This is something I've been wanting to add and even went a head and created a repo (https://github.com/exceptionless/Exceptionless.Python) but we've been working on other tasks like the status change which has massive benefits. Please follow that repo or feel free to submit a pr. If you wanted to submit events to our api via http you can do so via here:  https://github.com/exceptionless/Exceptionless/wiki/API-Usage
