### ISSUE TITLE
Unable to log

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#665]
After I deployed elasticsearch independently,
 exceptionless could not record logs.
 exceptionless.job output log is below.

![1](https://user-images.githubusercontent.com/17695936/86208650-8c87e100-bba3-11ea-899d-8b97198fd089.png)

The following is elasticsearch information

![2](https://user-images.githubusercontent.com/17695936/86208667-93aeef00-bba3-11ea-9482-9ef0acbf38ec.png)

**Comment by ejsmith** [comment]
You need to have the `mapper-size` plugin installed.

https://github.com/exceptionless/Exceptionless/blob/master/build/docker/elasticsearch/Dockerfile#L4-L6

**Comment by yun6cc** [comment]
Thanks, the problem just now is fine, this problem occurs again after adding the mapper-size plugin.

 System.ApplicationException: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: 
PUT /prod-events-2020.07.01/_doc/5efc28f4bb96fb0001a57d4f?op_type=create&pipeline=events-pipeline&refresh=false. ServerError: Type: illegal_argument_exception Reason: "pipeline with id [events-pipeline] does not exist"
2020-07-01T06:11:00.018715949Z Server: (400) Type: illegal_argument_exception Reason: "pipeline with id [events-pipeline] does not exist"

**Comment by yun6cc** [comment]
@ejsmith  help!!!

**Comment by yun6cc** [comment]
Ok after updating the latest version.
