### ISSUE TITLE
403 Forbidden with Docker Image

### ISSUE THREAD

**Issue by toolsfactory** [exceptionless/Exceptionless#666]
trying to call exceptionless api with the docker image exceptionless/exceptionless running in docker compose results in 403 Forbidden. UI can be accessed as expected.

dockercompose.yaml
exceptionless:
    image: exceptionless/exceptionless:6.1.0
    volumes:
      - ./exceptionless/data:/usr/share/elasticsearch/data
    ports:
      - 5001:80

postman: 
request to http://localhost:5001/api/v2/events?access_token=mytoken
response 403 Forbidden

same request without access token results in 401 showing that in general the api is reachable

**Comment by ejsmith** [comment]
If you select shell from the setup screen in the UI, it should show you a curl command to send events to the API. Did you see that?

**Comment by toolsfactory** [comment]
Hi Eric,
first of all, thanks for this great project and making it available as open source - and also for the fast response.

In the end i fixed the issue, Was a combination of some points together with slackness on my side.
a) inside docker compose I was using the wrong port. 5001 is only available only outside the docker network - I should have used 80
b) a minor error in setting up the exceptionless net client
c) too focused on a problem inside the exceptionless docker image (I read #436)
d) Most of the GET request seem not be authorized for the project api key which with c) made me think in the wrong direction

Thank
Michael

**Comment by ejsmith** [comment]
That's good to hear @toolsfactory. Let us know if you have any other questions.
