### ISSUE TITLE
How to change API key ?

### ISSUE THREAD

**Issue by emejibka** [exceptionless/Exceptionless#670]
Hello.

We lost data in elasticsearch and we can`t restore it from backup because we dot`n have backup ;(
I setup new exception instance. I can create new projects and users. But how to change API key?

**Comment by niemyjski** [comment]
You'd need to create new api keys and manually update the api keys via kibana/curl (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html). Please let us know if you have any questions.
