### ISSUE TITLE
I don't know why Log can‘t’ send to my windows server. But Login、Register and create new project all normal in my windows server

### ISSUE THREAD

**Issue by wuzhixing** [exceptionless/Exceptionless#672]
I used ExceptionLess 4.1.2861 Releaes Version in windows server 2019.
can login、register and create new project.
so i create new Apikey in my Wpf Client.but it can't send log to server.
i used "Fiddler" to watch. this api return 500 errorcode.I don't why?because i can login、register.
![image](https://user-images.githubusercontent.com/40681332/87496395-02c82100-c643-11ea-8c8a-00518c1a087b.png)

**Comment by wuzhixing** [comment]
this api return 500 errorcode.(/api/v2/events)

**Comment by ejsmith** [comment]
Have you tried running newer versions of Exceptionless? We are on version 6.1 now.

**Comment by wuzhixing** [comment]
new versions can running in IIS？

**Comment by ejsmith** [comment]
They could with some work, but we moved everything to docker to make them easier to use. Literally the only requirement is docker. https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting

**Comment by wuzhixing** [comment]
all right. i will try in free time.

**Comment by wuzhixing** [comment]
thank you very much.

**Comment by niemyjski** [comment]
I'm going to close this as it seems solved, if you have any questions please let us know.
