### ISSUE TITLE
Unable to load the service index for source https://www.myget.org/F/exceptionless/api/v3/index.json. [/app/Exceptionless.sln]

### ISSUE THREAD

**Issue by quliting** [exceptionless/Exceptionless#673]
i use docker-compose.yml to build the ex.it show me need dockerfile.i add docker,then tips need .csproj .finally i and source in .
at end.it show the flowed error.i can visit the link.

[https://github.com/exceptionless/Exceptionless/issues/607](url)
[root@console Exceptionless-5.0.0]# docker-compose up -d
Building api
Step 1/34 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2.401 AS build
 ---> 08657316a4cd
Step 2/34 : WORKDIR /app
 ---> Using cache
 ---> 39811e059457
Step 3/34 : ARG VERSION_SUFFIX=0-dev
 ---> Using cache
 ---> e4cbef139076
Step 4/34 : ENV VERSION_SUFFIX=$VERSION_SUFFIX
 ---> Using cache
 ---> c80590efbca0
Step 5/34 : COPY ./*.sln ./NuGet.Config ./
 ---> Using cache
 ---> e8b3c62fdd90
Step 6/34 : COPY ./build/*.props ./build/
 ---> Using cache
 ---> c40817c6e293
Step 7/34 : COPY src/*/*.csproj ./
 ---> Using cache
 ---> 38b14f4a19e3
Step 8/34 : RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done
 ---> Using cache
 ---> 434e0c19e989
Step 9/34 : COPY tests/*/*.csproj ./
 ---> Using cache
 ---> 460cdbf820d2
Step 10/34 : RUN for file in $(ls *.csproj); do mkdir -p tests/${file%.*}/ && mv $file tests/${file%.*}/; done
 ---> Using cache
 ---> 963075377aa0
Step 11/34 : RUN dotnet restore
 ---> Running in 6da532eaa276
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : Unable to load the service index for source https://www.myget.org/F/exceptionless/api/v3/index.json. [/app/Exceptionless.sln]
/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error :   Resource temporarily unavailable [/app/Exceptionless.sln]
ERROR: Service 'api' failed to build: The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by niemyjski** [comment]
Hello,

Please upgrade to 6.0 which has resolved this issue. You can grab the latest docker-compose file from the repository.

**Comment by ejsmith** [comment]
@quliting we now have a single docker image you can run as simple as this `docker run --rm -it -p 5000:80 exceptionless/exceptionless:6.1.0` take a look at the self-hosting docs for more info:

https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting

**Comment by quliting** [comment]
@ejsmith  i know this page.but i don't know how to setting data in mysql 、es、redis；the docker-compose.yml has the data setting.

**Comment by quliting** [comment]
@niemyjski  hey guys i download the new docker-compose.yml,when i new issue.i think the docker-compose is 6.0

**Comment by niemyjski** [comment]
Hello, I'm not sure what you are asking. Elasticsearch ad redis connection strings can be set as shown here: https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml We don't support mysql.

**Comment by quliting** [comment]
@niemyjski  yes i find it.but it shows error "need Dockerfile";
is the version not the news?

**Comment by quliting** [comment]
@niemyjski 
我是中国人，英文不是很好，

**Comment by niemyjski** [comment]
Can you please attach a snippet of the whole error. English is my main language (I don't know any Chinese) could you please post your main language as well as (https://translate.google.com) and I'll do my best to help :-)

**Comment by quliting** [comment]
version: '3.7'

services:
  app:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/app:6.1.0
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://101.132.166.176:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5001
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - appdata:/app/storage
      - ssldata:/https

  jobs:
    depends_on:
      - app
    image: exceptionless/job:6.1.0
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://101.132.166.176:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://101.132.166.176:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  elasticsearch:
    image: exceptionless/elasticsearch:7.7.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata7:/usr/share/elasticsearch/data
  
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5601:5601

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local






i use this docker-compose .when i visit it.it shows:

![image](https://user-images.githubusercontent.com/14035957/88077167-89ce4980-cbad-11ea-81de-6d684780a572.png)

**Comment by quliting** [comment]
Service Unavailable

**Comment by niemyjski** [comment]
You'll get that when the app is starting up. Hit 5000/ready and 5000/healthy to get an idea of why it's not working.

**Comment by quliting** [comment]
ok sir .i'll do it .

**Comment by niemyjski** [comment]
Did that fix it?

**Comment by quliting** [comment]
Health check Elasticsearch completed after 2000.9006ms with status Unhealthy and 'Elasticsearch Ping Failed;

![exceptionless](https://user-images.githubusercontent.com/14035957/88513973-da193180-d01b-11ea-8189-5b252c1c9a7f.png)

**Comment by quliting** [comment]
i can visit http://101.132.166.176:9200

**Comment by niemyjski** [comment]
Can you view your elasticsearch instance server url from the machine that's hosting exceptionless? Also, I'd highly recommend securing your elasticsearch instance and not having it publicly visible.

**Comment by quliting** [comment]
esurl is :http://101.132.166.176:9200/
it works.
![image](https://user-images.githubusercontent.com/14035957/88747719-f1722f00-d181-11ea-85f7-39bde54235bf.png)

i dont't know what is wrong!

**Comment by quliting** [comment]
what should i do to slove this problem

**Comment by ejsmith** [comment]
Why did you change the EX_ConnectionStrings__Elasticsearch environment variable? The default from here should work: https://github.com/exceptionless/Exceptionless/blob/55148f092a231c4a69f073f418cbf62a42d2c43a/samples/docker-compose.yml#L12

It's an internal service and shouldn't be exposed to the outside world. It can be accessed using its internal service name of elasticsearch.

**Comment by quliting** [comment]
### okay.i know.



### 
version: '3.7'

services:
  app:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/app:6.1.0
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5001
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - appdata:/app/storage
      - ssldata:/https

  jobs:
    depends_on:
      - app
    image: exceptionless/job:6.1.0
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://localhost:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  elasticsearch:
    image: exceptionless/elasticsearch:7.7.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata7:/usr/share/elasticsearch/data
  
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5601:5601

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local

### the same error;


[14:25:18 ERR] Health check Cache completed after 0.1478ms with status Unhealthy and 'Cache Not Working.'
[14:25:20 ERR] Health check Elasticsearch completed after 2000.4617ms with status Unhealthy and 'Elasticsearch Ping Failed'
[14:25:21 ERR] Health check Cache completed after 0.15ms with status Unhealthy and 'Cache Not Working.'
[14:25:23 INF] Waiting for startup actions to be completed for 02:05...

**Comment by quliting** [comment]
@ejsmith  key are you here?

**Comment by niemyjski** [comment]
That all looks good, are you hosting elasticsearch on a different server? If so you need to update the `EX_ConnectionStrings__Elasticsearch` connection string. Otherwise what you have looks good and you don't need to expose your elasticsearch to the internet.

**Comment by niemyjski** [comment]
I'm going to close this, can you please let us know if this is still an issue after configuring your connection string
