### ISSUE TITLE
Exceptionless 6.1.0 Configuration (self-hosted)

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#676]
Hi,
How can I configure a self-hosted instance of Exceptionless 6.1.0?
For context, I took the build artifacts out of a docker container with `docker cp` and then hosted those files with IIS. Exceptionless is working but it's not fully configured.

The web.config in the root directory looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <location path="." inheritInChildApplications="false">
   <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Exceptionless.Web.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
</location>
</configuration>
```
Where can I configure a Redis connection string, LDAP connection string, etc? I'm familiar with seeing the config file have sections like `connectionStrings` and `appSettings`. I've tried adding those sections manually to the config file with no luck.

Thank you.

**Comment by niemyjski** [comment]
Hello,

The front end settings are stored in an `app.config.xxxxxx.js` file and server settings are located in an `app settings.yml` file. Please note we recommend running only our docker containers as no longer officially support hosting in IIS. Please let us know if you have any questions.

**Comment by Edreih** [comment]
I'd love to use Docker/k8s but unfortunately unable to due to some policies.

Anyway, thank you for the help! I was able to configure it with `appsettings.yml`. Another thing that worked was using the configuration editor in IIS to set environment variables in the `system.webServer/aspNetCore` section.

**Comment by niemyjski** [comment]
Thanks for the followup.
