### ISSUE TITLE
How to close disk cache?

### ISSUE THREAD

**Issue by wuzhixing** [exceptionless/Exceptionless#682]
Exceptionless default open disk cache. how to close? I used 6.1.0 version.

**Comment by niemyjski** [comment]
Hello,

I'm not sure what you are asking, can you please rephrase your question.

**Comment by wuzhixing** [comment]
when i send log to server. server always add some new json file in disk. I can delete there file and does not affect the operation of the program.

**Comment by wuzhixing** [comment]
＃275 
like this qustion.I don't not how to deal with it. I don't find switch in 'docker - compose.yml' file.

**Comment by niemyjski** [comment]
You need to set `EX_EnableArchive` to `false`. @ejsmith I'm thinking we default this to off for everyone and make it opt in, in production.

**Comment by wuzhixing** [comment]
Good. this qustion is solve.thank you so much. In my opinion, I think it can be turned off by default. Because developers don't use backup very often.

**Comment by wuzhixing** [comment]
I have a question about how long the login token is valid when Login.

**Comment by niemyjski** [comment]
It expires after 3 months.

**Comment by niemyjski** [comment]
I agree with the archive setting. Can you please create a new issue to track this.
