### ISSUE TITLE
exceptionless automatically delete index

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#685]
I don't know why, the exceptionless is running well, 
but the login fails suddenly. 
I looked at the Elasticsearch log and found that an index was deleted.
Elasticsearch log is as follows。
![20200812170324](https://user-images.githubusercontent.com/17695936/89997246-7b5fe300-dcbe-11ea-8a8b-3496751841f7.png)
@ejsmith  help!!!

**Comment by niemyjski** [comment]
Something in elastic triggered all of your indexes to be deleted, and will need to be restored from a backup. We don't have anything in exceptionless that would delete all the indexes.  Maintain indexes job which would clean up only event indexes. Did you run any commands against elasticsearch? I'd make sure you are not port forwarding your elasticsearch instance to the internet.

**Comment by yun6cc** [comment]
Good morning, for the past 21 days, I have been waiting for the problem to appear. As expected, it was deleted at 2020-09-02 22:36:52 last night. Recently I have been looking for elasticsearch for any mechanism that triggers the delete operation, but I have not found it. Can you give me some suggestions?
![20200903071127](https://user-images.githubusercontent.com/17695936/92046077-bc767f00-edb4-11ea-859d-eeca345e4717.png)

**Comment by niemyjski** [comment]
What are your settings for `MaximumRetentionDays` (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Repositories/Configuration/Indexes/EventIndex.cs). This is the only thing I could think of that would delete it. We don't have anything else that would do this. So it is fine for 21 days and then does this? Is there anything in the logs for `MaintainIndexesJob`? I really wish I knew what was triggering this. If we are the ones deleting this it's pretty critical.

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Jobs/Elastic/MaintainIndexesJob.cs
https://github.com/FoundatioFx/Foundatio.Repositories/blob/master/src/Foundatio.Repositories.Elasticsearch/Jobs/MaintainIndexesJob.cs

**Comment by niemyjski** [comment]
I guess that setting wouldn't even matter. Maintain indexes wouldn't touch non daily index like tokens and stacks. Is there anything in the application logs around this time?

**Comment by niemyjski** [comment]
I'm going to close this as we haven't gotten any other reports nor follow up logs. Can you try upgrading to 7.1 and see if you still see this behavior. Also, I wonder if this could somehow be a date localization issue but we haven't gotten any reports of that either in Foundatio Repositories.
