### ISSUE TITLE
How to configure log expiration time to avoid unlimited data growth

### ISSUE THREAD

**Issue by conanl5566** [exceptionless/Exceptionless#686]
How to configure log expiration time to avoid unlimited data growth

**Comment by niemyjski** [comment]
This is a duplicate of #592 

You can do this by setting an environment variable EX_MaximumRetentionDays to 7.

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/AppOptions.cs#L53

Would you mind adding a section for this to the self hosting wiki page?
