### ISSUE TITLE
Exceptionless will be captured by Fiddler 4 and other software

### ISSUE THREAD

**Issue by wuzhixing** [exceptionless/Exceptionless#688]
Exceptionless will be captured by Fiddler 4 and other software, and then sent a lot of spam logs maliciously. Is there any way to prevent it from being captured?

**Comment by wuzhixing** [comment]
![image](https://user-images.githubusercontent.com/40681332/90500419-5fcf5f00-e13a-11ea-9fd8-596e712ab858.png)

**Comment by wuzhixing** [comment]
![image](https://user-images.githubusercontent.com/40681332/90500554-93aa8480-e13a-11ea-8527-9cbc24b96d55.png)

**Comment by wuzhixing** [comment]
![image](https://user-images.githubusercontent.com/40681332/90500752-d704f300-e13a-11ea-9347-6fb038baee21.png)

**Comment by wuzhixing** [comment]
I use the above method to send logs.

**Comment by niemyjski** [comment]
Use HTTPS for submission, we have the ability in the user interface to disabled and remove api keys as well.

**Comment by wuzhixing** [comment]
那就好了，这样我就不用自己写https进行提交，这样可以节省很多工作量。因为用https进行提交还要自己构造一些固定的常用的数据，例如版本号、运行环境、系统名等等

**Comment by niemyjski** [comment]
Can you please post your response in English (even via google translate)

**Comment by wuzhixing** [comment]
That's good. In this way, I don't have to write my own HTTPS to submit, which can save a lot of work. Because if you submit with HTTPS, you have to construct some fixed and commonly used data, such as version number, running environment, system name, and so on

**Comment by wuzhixing** [comment]
Sorry. I forget translate.

**Comment by niemyjski** [comment]
We support https out of the box with a tiny bit of configuration. If you need any help or have any other concerns let us know.

**Comment by wuzhixing** [comment]
Good.
