### ISSUE TITLE
Configurable rule based notifications

### ISSUE THREAD

**Issue by PhilipDn** [exceptionless/Exceptionless#69]
With the v2 release, a change has been made to email notifications. We no longer receive an email notification for each error. As I understand it, now we will only receive an email any time a new event occurs / is critical / is a regression. (I think the intent was to reduce the volume of emails from Exceptionless, and also so that "when you see an email alert it means something".) Also, it's now my understanding that a specific error will only have a single instance of "regression"; if it has been marked as fixed/closed and then occurs again, it will be re-opened and this will be a one-time regression. [The definition of a regression in Exceptionless has not changed; only my understanding of the details.

I understand the reason for this change, and that some users would find this useful. However, for our organization, we don't typically see a large volume of errors and we like to be notified of each instance. Sometimes, the same error repeats because we haven't had time to fix it yet, or sometimes it's a new circumstance that causes the same error (that we thought we had fixed in code, but not yet marked as fixed in Exceptionless).

Perhaps, to avoid sending thousands of notifications, perhaps you could consider sending a "digest" notification if there are more than a certain number of errors requiring notification in some time period (5 minutes, 30 minutes?). That is, do something like track the timestamp of the most recent notification sent to a user; and if any notification is required again - if it's more than 5/30 minutes (or some other interval) since the last message, send it as a new message, but if it's less than 5/30 minutes, wait until 5/30 minutes and send a summary/count of notifications to the user with a link to view all the errors.

Note that sometimes the volume/frequency of a specific error is a very useful indicator of a more serious problem (such as a failure in a database table, or a problem with an external web service used by the application), and receiving only a single notification for a new error that's occurring multiple times may mask that situation.

**Comment by PhilipDn** [comment]
Alternatively, perhaps you could allow a project to be marked as "all errors for this project will be considered critical"; and then we would receive a notification for every error in that project. I know that, after an error is logged, you can set an option on that error to identify all future occurrences of the error as critical; I'm suggesting allowing that to be set as the default for all errors in a project.

**Comment by niemyjski** [comment]
One of the things you could do is use the bulk actions to mark a stack as critical but that doesn't seem like a good solution at all (not addressing the problem, just putting a bandaid on it).  We already do deduping and rate limiting on emails. The issue with sending one with each occurrence is if you got bunch emails in a short window of time from the same occurrence then a new actual critical occurrence wouldn't get an email notification.

**Comment by niemyjski** [comment]
The thing is would you read a digest email? It seems like it would be nice to send an email anytime a large amount of errors come in (lets say you average 5 an hour, and then all of a sudden you get 15), that would trigger an email. That might take a large amount of work to detect that (but would be cool to have)..

On a side note, It might be nice to have a plugin that runs server side that automatically marks timeout and connection related exceptions as critical. 

@ejsmith  thoughts

**Comment by ejsmith** [comment]
Yeah, it would be nice. I'm sure we could figure out a rate per stack, but to keep that rate for every single stack over time would be interesting. Guess we would have to store it in redis short term and occasionally persist it to ES.

**Comment by niemyjski** [comment]
You might be able to cheat a bit with something like this: 
```
(Total Occurrences / (Now - FirstOccurrence).TotalHours) > StackCountForLastHourInRedis
```

**Comment by PhilipDn** [comment]
Alternatively, would you consider adding a new option to notifications - to allow notification for all errors (similar to the way that v1 worked)? [You can add warnings or similar if a user selects this option to inform the user that this may result in a large volume of email.]

**Comment by niemyjski** [comment]
I'll bring this up with the team for discussion.

**Comment by ejsmith** [comment]
There is more to this than just volume of email. It's a huge load on the system and costs us money as well. I think what we need to do is allow instance level notifications, but do it intelligently where we throttle them.

**Comment by PhilipDn** [comment]
Thanks for the added explanation of system load and costs. I realize my use case is probably unusual (an exception, if you will), and that you are designing the system for the majority of your users, especially those with a large volume of projects and web applications with millions of daily users.

I'll give this some more thought and let you know if I have any other suggestions.

**Comment by niemyjski** [comment]
I think a good compromise would be to send a followup at an interval for a specific stack after it happens. Like you'll get notified 5, 30 and 60 minutes after a new occurrence. If you get an email on every occurrence/summary on a stack a week after it happened it's just noise.

**Comment by niemyjski** [comment]
@KasperLK commented on Apr 9, 2015
Time when the daily project summary should be send
Quiet hours
Quiet days (weekend)
It should also be possible to configure the above on organization level, with option to overwrite on selected projects.

Option to get a daily summary on organization level instead for one mail per project.

**Comment by niemyjski** [comment]
I'm closing this as it's now merged into 177.
