### ISSUE TITLE
Exceptionless logs delayed

### ISSUE THREAD

**Issue by ganeshran** [exceptionless/Exceptionless#690]
Hi, for the last few days, the lag between our logs being submitted by clients and showing up in the exceptionless site started increasing rapidly. It is now more than 24 hours.

We use AWS Elasticsearch with Redis as cache. I dont know much about Exceptionless internals but any pointers towards debugging the source of the delay would be highly appreciated. Many Thanks.

**Comment by niemyjski** [comment]
I'd check to see the queue length in redis for the event posts job. I'd also create more event posts job instances.

**Comment by ganeshran** [comment]
Thanks @niemyjski I searched redis for the pattern q:EventPost:* and found around 17K keys matching. 

Is there a better filter to monitor the queue length?

**Comment by ganeshran** [comment]
I installed the Redis Desktop manager and the Queue length is 24K now. Going through past issues, the solution is to run more event processing jobs. I searched for a setting and doc but wasnt able to find it.

Could you please point me in the direction on how to do this? Is it as simple as running the executable (in App Data/jobs folder) in command line.  Many thanks!

![image](https://user-images.githubusercontent.com/1933770/90763277-4ebf5300-e2de-11ea-9701-83caea188184.png)

Exceptionless API status page screenshot 
![image](https://user-images.githubusercontent.com/1933770/90763467-a8c01880-e2de-11ea-9b0c-d731eba392c3.png)

**Comment by niemyjski** [comment]
You can also call `/api/v2/queue-stats` https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Web/Controllers/StatusController.cs#L63 as a global admin to view the stats as well. Did scaling up help?

**Comment by ganeshran** [comment]
Thanks @niemyjski I just asked the admin to give me superuser privileges to do that as I am getting a 403 while accessing the API endpoint.

For scaling up is it enough to copy paste more EventPost folders in the jobs folder? Could you please point me in the direction of a doc which tells how to increase the number of jobs processing the queue? Thanks in advance!

![image](https://user-images.githubusercontent.com/1933770/90787489-aec4f200-e2fc-11ea-9c29-9c3be8337123.png)

**Comment by niemyjski** [comment]
It depends on how you are hosting it. Anyway that increases the number of jobs running will work. We use kubernetes and scale the number of pods.

**Comment by ganeshran** [comment]
We self host it on a VM on IIS. The jobs are ran in process.  The exceptionless version is older (4.1). I checked the web.config and they dont have a setting of how many event jobs should run. It's just to control whether the jobs are run in process or not. 

I'll dig further. Thank you

**Comment by niemyjski** [comment]
I'd recommend running the jobs out of process if possible as you can scale them. You could also just update the configuration of one out of process event post job and launch the process to catch up. Also upgrading to the latest versions will make massive differences. We cut our job instances down massively after moving to .Net Core.

**Comment by niemyjski** [comment]
Did this help? Please let us know and we'll reopen this issue.

**Comment by ganeshran** [comment]
Hi @niemyjski , unfortunately it didnt. We are deploying the latest version of Exceptionless to see if that helps

**Comment by niemyjski** [comment]
Can this issue be closed? Did updating to the latest version resolve your issues?

**Comment by ganeshran** [comment]
Hi Blake yes please close this issue. It didnt happen after we upgraded to latest version
