### ISSUE TITLE
Added global role to elasticsearch but hasnt reflected in Exceptionless

### ISSUE THREAD

**Issue by ganeshran** [exceptionless/Exceptionless#694]
I updated ElasticSearch to add the global role to my user id. It is reflected in the "me" call during login. However when I try to make a call which is only available to global admins (e.g. QueueStats), it throws a 401 unauthorised. 

I have recycled the app pool and restarted the IIS web server to invalidate any cache but it still doesnt work. any idea how to make it work.  Many thanks

Exceptionless version.
![image](https://user-images.githubusercontent.com/1933770/91040832-d078ee80-e606-11ea-8abc-d36ada41a72c.png)

**Comment by niemyjski** [comment]
Did you invalidate the redis cache?

**Comment by ganeshran** [comment]
Thanks for your reply @niemyjski . Could you please let me know how to do it, is it a key that has to be deleted? I looked at the self hosting docs but couldnt find it

**Comment by niemyjski** [comment]
Are you using in memory cache client or are you using redis? The easiest way is to just use the Redis-cli and remove all keys. https://stackoverflow.com/questions/6851909/how-do-i-delete-everything-in-redis

**Comment by ganeshran** [comment]
@niemyjski we are using Redis. I stopped the IIS web server and all the event post jobs. And deleted all the keys in the Redis cache. the User key in the cache also shows the global role in it. 

However the api/v2/queue-stats still throws a 401.

![image](https://user-images.githubusercontent.com/1933770/91055354-72570600-e61c-11ea-9f19-b2fad6e42039.png)

**Comment by niemyjski** [comment]
Hello,

I'm not sure, can you try debugging the source and stepping through. I've never ran into this issue before with this route.  You could enable verbose logging as well and hit the route and see what the logs say.

**Comment by niemyjski** [comment]
Were you able to get this figured out?

**Comment by ganeshran** [comment]
Hi @niemyjski unfortunately no. This never got solved. We ended up installing the latest version on a fresh machine to get around the issue

**Comment by niemyjski** [comment]
I'm going to close this as I don't have any additional repo steps or information to go off of. If anyone else runs Into this behavior please let us know
