### ISSUE TITLE
Job run EventPostsJob failed: Unable to retrieve payload

### ISSUE THREAD

**Issue by xyyp224** [exceptionless/Exceptionless#695]
>>>>>>>>docker-compose.yml

version: '3.4'

services:
  api:
    depends_on:
      - redis
    image: exceptionless/api:latest
    container_name: exceptionless-api
    restart: on-failure
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://xxx.cn:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://xxx.cn:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80 # This can be commented out if using reverse proxy.
    volumes:
      - ./api/appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job:latest
    container_name: exceptionless-jobs
    restart: on-failure
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://xxx.cn:5000
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://xxx.cn:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - ./jobs/appdata:/app/storage

  ui:
    image: exceptionless/ui:latest
    container_name: exceptionless-ui
    environment:
      AppMode: Production
      EX_ApiUrl: http://xxx.cn:5000
    ports:
      - 5100:80

  redis:
    image: redis:alpine
    container_name: exceptionless-redis
    restart: on-failure
    ports:
      - 6379:6379

 elasticsearch:
    image: exceptionless/elasticsearch:7.7.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      http.cors.enabled: "true"
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    volumes:
      - /data/db/es/esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
>>>>>>>>>

![QQ图片20200830171702](https://user-images.githubusercontent.com/69830165/91655732-7637cc00-eae5-11ea-8f22-fe031bf7a0ac.png)

please help   :(

**Comment by niemyjski** [comment]
Your volumes for the api and jobs need to be the same

**Comment by xyyp224** [comment]
thanks. it's ok...
