### ISSUE TITLE
Status feature follow up

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#700]
- [x] Fix bug with using status field on free plans
- [x] Create migration to fix issue with duplicate stacks that were created during deployment of 7.0
- [x] Test duplicate stack data fix in dev
- [x] Run duplicate stack data fix in prod
- [x] Fix concurrency issue when creating new stacks
- [x] Verify that no new duplicate stacks are created in prod
- [x] Create job to cleanup orphaned event data that is causing issues with our stack exclusion based filtering
- [x] Test orphan data job in dev
- [x] Run orphan data cleanup job in prod
- [x] Add menu entry under reports to see discarded stacks
- [x] Add menu entry under reports to see fixed stacks
- [x] Add menu entry under reports to see ignored stacks
- [x] Add menu entry under reports to see snoozed stacks
- [x] Add status badge to stack summaries (except for open). Also don't show it on reports
- [x] Create release notes for 7.0
- [x] "All Events" header to "All" change icon to `fa-th-large`
- [x] "Timeline" to "Events" change icon to `fa-calendar`
- [x] New view has "Newest" as grid header, which is wrong.  Should say "New Stacks".
- [x] Fix broken stat box links in All area.
- [x] Add separator between "All" and "reports" in nav links.
- [x] Add link to "Events" stat box in each area that goes to the Events view.
- [x] New view doesn't seem to filter by stacks created within the date range, numbers don't match up from what the new stacks stat box says when clicking on it
- [x] Add documentation about status and how to use them and when to use each
- [ ] Write blog post about new 7.0 Exceptionless talking mostly about status and snoozing, and how marking a stack as discarded will discard incoming events and they won't count against your plan limits, etc.
- [ ] Promote blog post on social media
- [ ] On pages like Most Freq, change the grid header to be "Most Frequent Stacks" (add Stacks) to clarify what they are.  Same on "Most Users" and "New" views.

**Comment by niemyjski** [comment]
Do we still agree that we should
