### ISSUE TITLE
Cleanup async stack traces

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#703]
Check out [Ben.Demystify](https://github.com/benaadams/Ben.Demystifier) and https://github.com/NickCraver/StackExchange.Exceptional/blob/main/src/StackExchange.Exceptional.Shared/ExceptionalUtils.StackTrace.cs

**Comment by niemyjski** [comment]
Do we want to do something server side for this? Or can this be closed now that we are doing this on the client.

**Comment by ejsmith** [comment]
Probably can close for now, but I really would like to push more of this behavior to server side and make it easier to post simple errors with just string stack traces and not have to populate some really complex error model.
