### ISSUE TITLE
 Liveness probe failed

### ISSUE THREAD

**Issue by lhl102401** [exceptionless/Exceptionless#705]
I am trying to deploy ExceptionLess in K8S, But I've deployed Redis and ElasticSearch separately, So I changed it ex-setup.sh file ,Now any POD describe: **Liveness probe failed: Get http://172.20.1.189:80/health**，Maybe My helm configuration is wrong ?
Many Thanks.

**Comment by lhl102401** [comment]
``helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl create namespace ex-dev

# install exceptionless app
APP_TAG="2.9.1"
API_TAG="6.1.0"

ELASTIC_CONNECTIONSTRING="http://0.0.0.0:9200"
EMAIL_CONNECTIONSTRING="smtps://user%40domain.com:password@smtp.domain.com:465"
QUEUE_CONNECTIONSTRING="provider=azurestorage;$QUEUECONNECTIONSTRING"
REDIS_CONNECTIONSTRING="0.0.0.0:6379"
STORAGE_CONNECTIONSTRING="provider=azurestorage;$STORAGECONNECTIONSTRING"

helm install ex-dev ./exceptionless --namespace ex-dev --values ex-dev-values.yaml \
    --set "app.image.tag=$APP_TAG" \
    --set "api.image.tag=$API_TAG" \
    --set "jobs.image.tag=$API_TAG" \
    --set "elasticsearch.connectionString=$ELASTIC_CONNECTIONSTRING" \
    --set "email.connectionString=$EMAIL_CONNECTIONSTRING" \
    --set "queue.connectionString=$QUEUE_CONNECTIONSTRING" \
    --set "redis.connectionString=$REDIS_CONNECTIONSTRING" \
    --set "storage.connectionString=$STORAGE_CONNECTIONSTRING" \
	--set "config.EX_Scope=dev"

**Comment by niemyjski** [comment]
Did you set your connection strings to elastic correctly? Exec into the pod and curl the health endpoint or hit the health end point of the api

**Comment by lhl102401** [comment]
I'm not sure , Redis and  ElasticSearch on the public net . after the problem, curl the Health Exec into the POD the result is something like this
# curl -I http://127.0.0.1/health
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

**Comment by niemyjski** [comment]
redis and elastic should not be exposed publicly.  I'd make sure the port is mapped it might be on 5000 locally in the container

**Comment by lhl102401** [comment]
Thanks , Public IP and Port is only in the learning phase. I will try to modify the mapping port, I also notice your new release, I will continue to try

**Comment by niemyjski** [comment]
Did you get this working?

**Comment by lhl102401** [comment]
Hi, thank you very much. It hasn't been solved yet, but I am busy with other work. I must have passed too many wrong arguments. Maybe Next week I'll be able to follow up on this

**Comment by niemyjski** [comment]
Thanks, please keep us updated.

**Comment by niemyjski** [comment]
Were you able to resolve this issue?

**Comment by lhl102401** [comment]
Hi，thank you niemyjski !  I rewrote the 'yml' and installed it successfully .I think my PVC and PV are still not perfect. I will continue to improve them if I have time . thank you very much !

**Comment by niemyjski** [comment]
Let me know if this shouldn't be closed and we'll reopen it. But please feel free to open a discussion with us or submit a pr for any changes you think we should make based on your findings.

**Comment by lhl102401** [comment]
Our manager asked for deployment ‘ExceptionLess’ in K8S , but I personally think it should be deployed separately.If deploying 'docker-compose mode
' separately is an excellent choice.'Helm mode' is too comprehensive and too automatically deployed.maybe it has a lot to do with my ability, which is my personal feeling.
My expectation for deployment is simple configuration,Easy to add or subtract applications.
Thank you for your constant attention to my question !!




 
From: Blake Niemyjski
Date: 2020-11-18 22:26
To: exceptionless/Exceptionless
CC: H; Author
Subject: Re: [exceptionless/Exceptionless] Liveness probe failed (#705)
Let me know if this shouldn't be closed and we'll reopen it. But please feel free to open a discussion with us or submit a pr for any changes you think we should make based on your findings.

**Comment by niemyjski** [comment]
If you won't have very many events coming through the system and you won't be needing to store hundreds of thousands or millions of events I'd probably just do docker-compose. If you are going to be doing more than that we strongly recommend using k8s and that's what we use in production and dev. It can scale to every level and just works. There is a learning curve to k8s and I'm learning more every time I use it, but it is clearly the future and it's available on all major cloud providers!

**Comment by lhl102401** [comment]
We just started using K8S，not too much experience, lots of failures，It must be fully tested in an experimental environment before it can be used.
I would do better if I managed K8S full-time, but more unrelated work is affecting me .It's not good for me or the company.
I hope to get to the other end of the K8S curve as soon as possible too. Thank you !
