### ISSUE TITLE
  Why can't I find the k8s helm deployment document for exceptionless

### ISSUE THREAD

**Issue by worldofchu** [exceptionless/Exceptionless#706]
Hi!
Why can't I find the k8s helm deployment document for exceptionless?    I found the "https://github.com/exceptionless/Exceptionless/blob/master/k8s/azure-k8s.sh"  is  404!

**Comment by worldofchu** [comment]
In addition, I hope to have helm package to adapt to traifik2. X+

**Comment by ejsmith** [comment]
Sorry about that. I just updated the link. We converted the scripts to powershell since we can run those in both Windows or Linux.
https://github.com/exceptionless/Exceptionless/blob/master/k8s/ex-setup.ps1

**Comment by niemyjski** [comment]
@worldofchu were you able to get everything figured out?

**Comment by niemyjski** [comment]
Please let us know if you have any questions or need additional information and we'll open this issue back up
