### ISSUE TITLE
exceptionless Data is too large to be included.

### ISSUE THREAD

**Issue by landonzeng** [exceptionless/Exceptionless#707]
Excuse me, how can I realize  even if the data is large I also hopes to request parameters recorded in the form of json，Including user account information, etc

**Comment by niemyjski** [comment]
Are you saying the post data is being removed for being too large that nothing is being sent in? Or are you not getting any request information? Are you using ASP.NET Core?  Also, please note that we don't recommend sending in any p2 information as we believe that should live locally.

**Comment by landonzeng** [comment]
> Are you saying the post data is being removed for being too large that nothing is being sent in? Or are you not getting any request information? Are you using ASP.NET Core? Also, please note that we don't recommend sending in any p2 information as we believe that should live locally.

OK, thank you for your answer，I can get p2 information by integrating Skywalking

**Comment by niemyjski** [comment]
There are no limitations on what you send us or yourself. If you can send us the follow up to my questions I can point you in the right direction.
