### ISSUE TITLE
Self hosted signup email verification and invitation processes not working

### ISSUE THREAD

**Issue by brentljohnson** [exceptionless/Exceptionless#71]
I have confirmed that both a development (StartBackendServers.bat, etc) and production (Redis, ElasticSearch and MongoDB windows services) fail to correctly process URLs on emails generated by the above processes.
Clicking on the "Verify Address" and "Join Organisation" embedded email links opens a new browser tab on a blank page. The corresponding user document in MongoDB is not updated.
My environment appears to be functional otherwise with organisation and project maintenance working correctly and new exceptions displayed in real-time when viewing the dashboard.

**Comment by niemyjski** [comment]
Do you also have the [Exceptionless.UI](https://github.com/exceptionless/Exceptionless.UI) setup and configured? Is your [BaseUrl](https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Web.config#L15) property set to the location the UI project is hosted at?

**Comment by niemyjski** [comment]
I'll run through this set up later tonight or early in the morning and try to reproduce. This is on our test check list and there are no other reported case but it's always worth triple checking.

**Comment by brentljohnson** [comment]
Yes, ui website is running.  BaseURL on api website is setup to match ui website.

**Comment by brentljohnson** [comment]
Development ui website his hosted using "grunt serve".  Link behaviour described above is for production hosted in IIS.  Development returns 404:

![capture](https://cloud.githubusercontent.com/assets/11605239/6815516/7513cbbc-d2ef-11e4-9ae6-1b0e47a8bb4d.JPG)

**Comment by niemyjski** [comment]
Thanks, I'll take a look

**Comment by niemyjski** [comment]
I think I found out the reason you are seeing this is due to the missing hashbang `#\` in the url. Are you currently setup on IIS using the web.config we provided? Did you set [`USE_HTML5_MODE`](https://github.com/exceptionless/Exceptionless.UI/blob/master/src/app.config.js#L13) to true? Doing both of these should resolve this issue completely. I just made a [commit](https://github.com/exceptionless/Exceptionless/commit/628a92a956e541766ab373406a4c0b1e0eaa075e) that updated the BaseUrl to the app which should make it clearer and work in debug mode.

**Comment by niemyjski** [comment]
Please let me know if this resolved this issue.

**Comment by brentljohnson** [comment]
Including the # in the api's BaseURL fixed it.  Under debug I still get a minor issue with the change of my user to email address verified not appearing until the cache expires (the update applies correctly in MongoDB).  Invites working perfectly in my production environment.  
Thanks for your quick responses.

**Comment by niemyjski** [comment]
Could you please create a new issue with the exact steps to reproduce and I'll take a look into that ASAP.
