### ISSUE TITLE
Filtering by Process Name (Environment tab)

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#718]
Hi,
I'd like to know how to filter events by "Process Name" which is found on the "Environment" tab. I've tried `process.name:"sample"` and variations of that with no luck. The [wiki page](https://github.com/exceptionless/Exceptionless/wiki/Filtering-Searching#custom-extended-data) does not seem to have information about some of the fields on this tab. Is this possible?

![image](https://user-images.githubusercontent.com/11253613/93142698-2b54b180-f6ac-11ea-94b2-33cc9b81b476.png)

Thank you very much

**Comment by niemyjski** [comment]
Hello,

We currently don't index the process name (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Repositories/Configuration/Indexes/EventIndex.cs#L399-L406). Is there a specific use case you are wanting to search by it? Typically we put each application into its own project. But in our case we would still have `dotnet web.dll` and `dotnet job.dll`

**Comment by Edreih** [comment]
Thank you sir. Yes, this use case would be very beneficial since the Process Name correlates with the Windows service that sent the error/log. Filtering through 1000+ events for only errors belonging to the "Audit" service would help in troubleshooting. 

Is there another way of getting that data, maybe through Extended data and filtering through that?

**Comment by niemyjski** [comment]
Yes, you can add default tags as part of configuration (https://github.com/exceptionless/Exceptionless.Net/wiki/Configuration#adding-custom-tags-with-every-report) and then just filter on tags. We'd like to have environments but until then tags work the best.

**Comment by Edreih** [comment]
Thanks for help sir. We were able to accomplish the filtering needed by using Extended Data; I will now close my question.
