### ISSUE TITLE
After upgrading to 7.0.0, the background log cannot be displayed. The index is created normally.

### ISSUE THREAD

**Issue by yun6cc** [exceptionless/Exceptionless#719]
After upgrading to 7.0.0, the background log cannot be displayed. The index is created normally.
backend
![3](https://user-images.githubusercontent.com/17695936/93282821-d4f98700-f801-11ea-94b1-f40a1a08ce22.png)
elasticsearch-head
![2](https://user-images.githubusercontent.com/17695936/93282828-d62ab400-f801-11ea-9050-9246dbc1f952.png)
docker-compse logs
![1](https://user-images.githubusercontent.com/17695936/93282835-d75be100-f801-11ea-9111-068f33314352.png)

**Comment by niemyjski** [comment]
There is a migration job `DataMigration` you will need to run. I'm working on the upgrade documentation and will reply when that is updated.

**Comment by niemyjski** [comment]
I've added a guide located here : https://github.com/exceptionless/Exceptionless/wiki/Upgrading#upgrading-from-v6-to-v7 Can you please let me know if you have any questions/feedback or run into any issues.
