### ISSUE TITLE
Redis vs Elasticsearch Question. Redis database size is small, is this normal?

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#721]
Hi,
I have about 2 million events in Exceptionless. During the sending of these events, the Redis database went up to 1MB then shrank down to 4KB. Is that normal behavior for Redis? What is Redis used for within Exceptionless compared to Elasticsearch? Is it simply for caching? 

I notice those 2M events took up disk space in our Elasticsearch instance, not in Redis. So I assume Elasticsearch is the long term storage?

Any insight is appreciated. Thank you

**Comment by niemyjski** [comment]
We use it for caching as well as for queues and message bus when it's configured with a redis connection string. If you have a lot of data coming in the queues could take up that space. Our cache usage in prod the last time I checked is normally between 200-500mb but can grow past that and shrink back down. You can see where we use redis by looking at: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Insulation/Bootstrapper.cs

We use Elasticsearch for all of our storage. Please let us know if you have any questions :).
