### ISSUE TITLE
execptionless 注册 邮箱被使用

### ISSUE THREAD

**Issue by clayzhangwl** [exceptionless/Exceptionless#723]
本地docker-compose 部署
提示  邮箱已经被占用

**Comment by niemyjski** [comment]
Hello,

Can you please translate your question to English. Thanks in advance.

**Comment by clayzhangwl** [comment]
local 
Docker compose deployment

Prompt mailbox is occupied

**Comment by niemyjski** [comment]
I'm not sure what your question or issue is. Are you trying to configure external email? Are you running into an issue?

**Comment by clayzhangwl** [comment]
I want to build a local system with docker compose, but the registered account and the wrong email address are occupied

**Comment by niemyjski** [comment]
Also there is some documentation here for this: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#simple-setup-wssl-support-and-smtp Please let us know if you have any questions.
