### ISSUE TITLE
New feature usage logging requires a "using" statement

### ISSUE THREAD

**Issue by PhilipDn** [exceptionless/Exceptionless#73]
I have tried the new feature usage logging:
 http://exceptionless.com/logging-feature-usages-with-exceptionless/ 

I probably won't use this immediately, but I can see the potential for this to be a useful logging option.

However, I found that I needed to add a "using Exceptionless;" statement to the code-behind file where I was using this. Otherwise the "SubmitFeatureUsage" method is not recognized even if I add the namespace to the method call, such as:

Exceptionless.ExceptionlessClient.Default.SubmitFeatureUsage("Signup");

You may want to add this requirement to the page that describes feature usage logging.

**Comment by niemyjski** [comment]
Thanks I will get this updated asap!

**Comment by niemyjski** [comment]
I just updated the blog post here: http://exceptionless.com/logging-feature-usages-with-exceptionless/.

**Comment by PhilipDn** [comment]
Thanks.
