### ISSUE TITLE
[Minor] Would you consider changing the default Gravatar icon (that's new in v2)?

### ISSUE THREAD

**Issue by PhilipDn** [exceptionless/Exceptionless#74]
The new web user interface for v2 includes a new icon at the top right corner of the screen. The first several times that I noticed this (peripherally), I thought it looked like a power on/off icon. I didn't click it because I had no interest in any of the actions that I thought it might allow (stopping the error collection process, shutting down, closing the window, etc.); there is no tooltip when hovering over the icon to provide a clue to its purpose.

Now that I have tried clicking on it, I see that it's account-related and that the icon is the default Gravatar icon (a white/blue rotated "G") that at a brief glance could be mistaken for a "power" icon, such as (for example):
 http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/blue-jelly-icons-symbols-shapes/017859-blue-jelly-icon-symbols-shapes-power-button.png 

I was previously aware of Gravatar, but I have never registered and created my own custom gravatar, so the default Gravatar icon was not immediately obvious to me.
 
Instead of using the default Gravatar icon:
 http://www.gravatar.com/avatar/00000000000000000000000000000000 
 
May I suggest using the Gravatar "mystery-man" icon:
 http://www.gravatar.com/avatar/00000000000000000000000000000000?d=mm&f=y 
To me, this looks more like an "account" or "user" icon (while the original default still reminds me more of a power/on-off icon).

**Comment by niemyjski** [comment]
Yes, I agree this is a needed change. Would you mind submitting a [pull request](https://github.com/exceptionless/Exceptionless.ui) for this behavior? Looks like we would just need to load the provider in the app.js file and set the default as shown [here](https://github.com/wallin/angular-gravatar)

**Comment by PhilipDn** [comment]
I'm not yet set up for pull requests from github, but I can try that in the near future.

However, if I'm reading the source code correctly, I think this should be a one-line code change.

Looking in the file: Exceptionless-master\source\app\Views\Shared\_AppLayout.cshtml

At the following line (line 98 in the copy of the file that I downloaded, which may not be the latest version):

  <img src="@GravatarHelper.CreateGravatarUrl(@ViewBag.User.EmailAddress, 55, "identicon", GravatarRating.PG, false, false)" alt="@ViewBag.User.EmailAddress" class="thumbnail" />

If you change "identicon" to "mm" (in the line above), that should result in it loading the Gravatar "mystery-man" (mm) icon if the user does not have a Gravatar account/image. Or, am I looking in the wrong place in the code?

**Comment by PhilipDn** [comment]
The previous comment interpreted the line of HTML and displayed the result. Line 98 (without the angle brackets) is:

img src="@GravatarHelper.CreateGravatarUrl(@ViewBag.User.EmailAddress, 55, "identicon", GravatarRating.PG, false, false)" alt="@ViewBag.User.EmailAddress" class="thumbnail"

**Comment by niemyjski** [comment]
I think you are looking at the 1.x source code.. All of our ui code is at a different repo: https://github.com/exceptionless/Exceptionless.ui

**Comment by niemyjski** [comment]
Hello,

I fixed this in the following commit: https://github.com/exceptionless/Exceptionless.UI/commit/fe8994150196595d864e329fe45febd3643e3b26. This will be live the next time we deploy.

**Comment by PhilipDn** [comment]
Sorry I was looking at old source code. I downloaded the latest source and started to look through it.

Thanks very much for making this change.
