### ISSUE TITLE
docker :  cannot be writen to the error message

### ISSUE THREAD

**Issue by Xm-Soft** [exceptionless/Exceptionless#741]
Environment : Win 10 + Docker  , Exceptionless 6.0.0
 Exceptionless Api and UI can run normally, but cannot be writen to the error message . 
 In Setting -> Project Manager , the Events have error number 。 I dotnot konw why not data in the error message.

please reply 

thanks

**Comment by niemyjski** [comment]
Hello,

I'm really not sure what error you are running into with the limited context given. Can you ensure you are running the latest version of Docker as well as upgrade to 7.0.3 of exceptionless. If you could attach the docker logs with the error that would be great.

**Comment by Xm-Soft** [comment]
Hi

I try to install it many times , still not show error message , I dotnot know where can look for docker logs .  

thanks 

![QQ截图20201013165418](https://user-images.githubusercontent.com/50651147/95839775-fd7b8f00-0d75-11eb-96bb-f34023063b18.png)
![QQ截图20201013165451](https://user-images.githubusercontent.com/50651147/95839787-00767f80-0d76-11eb-8565-502f27d2a992.png)
![QQ截图20201013170134](https://user-images.githubusercontent.com/50651147/95839791-01a7ac80-0d76-11eb-97c8-4549fd9a9b69.png)
![QQ截图20201013170206](https://user-images.githubusercontent.com/50651147/95839793-01a7ac80-0d76-11eb-8847-18aa4e3e88f2.png)
![QQ截图20201013170235](https://user-images.githubusercontent.com/50651147/95839796-02404300-0d76-11eb-9a69-8b02160add85.png)

**Comment by Xm-Soft** [comment]
Hi

I try to install it many times , still not show error message , I dotnot know where can look for docker logs .

thanks

![20201013165418](https://user-images.githubusercontent.com/50651147/95840141-6236e980-0d76-11eb-8d2a-0b40d9cec38d.png)
![20201013165451](https://user-images.githubusercontent.com/50651147/95840151-6400ad00-0d76-11eb-8b82-78bfe296336b.png)
![20201013170134](https://user-images.githubusercontent.com/50651147/95840153-64994380-0d76-11eb-93f0-f76ca43150e2.png)
![20201013170206](https://user-images.githubusercontent.com/50651147/95840158-6531da00-0d76-11eb-8a5f-f8eb72c3db75.png)
![20201013170235](https://user-images.githubusercontent.com/50651147/95840159-65ca7080-0d76-11eb-819d-35cd9e55055b.png)

**Comment by Xm-Soft** [comment]
thanks your relpy  ,i  had put the pictures , please check , thx

[cid:d3070583-6e8d-4aa1-864a-35f5848a29a6][cid:b096e489-9f14-4156-8d2b-8a16f3a168de][cid:52434c73-d1af-490c-a1b2-60d1316d8cde][cid:decc09c9-dae0-40fa-992f-5ceef7369803][cid:9aab7ff8-84ec-43c2-8ec8-d52156fb7329]
________________________________
发件人: Blake Niemyjski <notifications@github.com>
发送时间: 2020年10月12日 22:14
收件人: exceptionless/Exceptionless <Exceptionless@noreply.github.com>
抄送: XmSoft <Xm-Soft@outlook.com>; Author <author@noreply.github.com>
主题: Re: [exceptionless/Exceptionless] docker : cannot be writen to the error message (#741)


Hello,

I'm really not sure what error you are running into with the limited context given. Can you ensure you are running the latest version of Docker as well as upgrade to 7.0.3 of exceptionless. If you could attach the docker logs with the error that would be great.

―

**Comment by niemyjski** [comment]
Hello,

It looks like the reason you are not seeing any events in your dashboards is due to the time range filter you have in the ui. Click that and change the dropdown to All. If this doesn't fix the issue please let us know and we will reopen this issue, but from what I can see everything is running normally.

**Comment by Xm-Soft** [comment]
hello

check all time , still not data

![Uploading 20201013202105.png…]()

**Comment by niemyjski** [comment]
Did you change this filter? 
![image](https://user-images.githubusercontent.com/1020579/95871748-a3f27080-0d33-11eb-90a5-139956e44f10.png)

**Comment by niemyjski** [comment]
I'd recommend taking a look at the http request you are making and see if any additional filter criteria is being specified. If it is, try removing it or put a `*` into the search box. Does this make a difference?

**Comment by Xm-Soft** [comment]
hello 

put a  * into the search box ,  can show error message .  why ? how to do it ?
![20201014170358](https://user-images.githubusercontent.com/50651147/95967960-785cac80-0e3f-11eb-87e9-55ee9154cc1f.png)

**Comment by niemyjski** [comment]
Look at the stacks, since they are showing up with the `*` it means they were marked as fixed, discarded, etc... We only show open or regressed events on the dashboards.

**Comment by Xm-Soft** [comment]
hello , thanks 

where can set open or regressed events in project ?  

thx

**Comment by niemyjski** [comment]
The default status of events is open. They are only changed if you change the status via bulk actions in the grids or on the stack page.

**Comment by niemyjski** [comment]
v7.0.4 has now been released https://github.com/exceptionless/Exceptionless/releases/tag/v7.0.4
