### ISSUE TITLE
I can not search logs 

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#748]
when  I search 【getGotoAiitLoginUrlV2】,it shows nothing. but it real there.
![图片](https://user-images.githubusercontent.com/30283517/96398159-c259df80-11fd-11eb-836b-7563b48aa9de.png)
when i search by Chinese words 【获取跳转到】，it shows search result
![图片](https://user-images.githubusercontent.com/30283517/96398230-eae1d980-11fd-11eb-8b62-f63fac4f25a0.png)

thank you very much .

**Comment by XLJ-CN** [comment]
![图片](https://user-images.githubusercontent.com/30283517/96398376-4c09ad00-11fe-11eb-8d99-bb7dc549d0ec.png)
this is the logs without search condition

**Comment by niemyjski** [comment]
Can you try sending in a single log message with just that namespace and then try. My guess is the whole event message is being ignored because it's so long (We skip indexing messages that are extremely long). Can you try this.

**Comment by XLJ-CN** [comment]
Yes, sure

**Comment by XLJ-CN** [comment]
sorry， i am  late
i make a demo and recheck it
it still there
![图片](https://user-images.githubusercontent.com/30283517/97145172-bbecda00-17a0-11eb-9561-707bd6dbe6b3.png)
search words is  "getGotoAiitLoginUrlV2"
![图片](https://user-images.githubusercontent.com/30283517/97145172-bbecda00-17a0-11eb-9561-707bd6dbe6b3.png)
 when  i  search chinese words "版本",it  seems work
![图片](https://user-images.githubusercontent.com/30283517/97145287-ef2f6900-17a0-11eb-987e-70969bad512d.png)

**Comment by niemyjski** [comment]
It could be something with the phrase `getGotoAiitLoginUrlV2` is contained within.  That is not getting split with the standard tokenizer. If you could create a unit test for this that would be greatly appreciated.

**Comment by XLJ-CN** [comment]
Sorry sir ,  I'm not very good at it.
And i   found another problem：when i am searching by chinese words ， the result is 【Fuzzy matching】。
for example：when i serach 【你好】，the result may contains【很好】 and 【你们】。
But when i search by number， the result is 【Exact matching】。（I don't know if my expression is correct）
thank you sir ,I will actively cooperate with you in finding this problem

**Comment by niemyjski** [comment]
If you could add some unit tests (with comments on the translations of each word or see if you can get it to happen in English first in the test) for this to our search (https://github.com/exceptionless/Exceptionless/blob/master/tests/Exceptionless.Tests/Search/EventIndexTests.cs) in a pr that would be greatly appreciated.

**Comment by niemyjski** [comment]
This has been fixed in the 7.0.9 release
