### ISSUE TITLE
Request for documentation for logging ASP.NET Trace calls

### ISSUE THREAD

**Issue by PhilipDn** [exceptionless/Exceptionless#75]
I have the impression that it's possible to configure the Exceptionless client to log recent .NET "Trace" calls/output when an error/exception is logged. If this is not correct, please let me know.

However, if it is possible to log Trace output, can you please provide some documentation on how to do this.

I did find this article: https://gist.github.com/niemyjski/469ccce03dc5b753d522 

In my C# code, I have some "Trace.Write" lines before the line that either submits an event or causes an error that will be logged.

From the above article, if I try the first block of code I don't encounter any errors but I can't find any indication of trace output that was logged with the exception. If I try adding either section to web.config, I get some errors about not being able to find a type for ExceptionlessTraceListener.

If it is possible to log Trace output, can you please provide some additional documentation on how to do this?

**Comment by niemyjski** [comment]
Are you wanting to log trace messages as actual log messages in exceptionless? I think that we need to add a trace log listener that just logs trace / debug messages to exceptionless. What are your thoughts on this?

**Comment by PhilipDn** [comment]
If you don't already have a trace log listener, you don't need to create one for this request. It might be occasionally useful, but I don't have an urgent need for it.

I opened this topic because it seemed that there might already be a trace log listener in Exceptionless, based on the "gist.github.com" article linked above and on the "TraceLogLimit" parameter available in the "exceptionless" tag in web.config.

If there is no current trace log listener and you don't have plans in the near future to add one, you can close this issue.

**Comment by niemyjski** [comment]
We do have one and it's documented here (http://docs.exceptionless.com/contents/configuration/). However, it won't send each trace message as a log message, it just appends them to existing events coming in. Will this work or are you looking to send them in log format?

Do you think we can improve this documentation any?

**Comment by PhilipDn** [comment]
The trace messages don't need to be separate; appending them to the event is fine. [I should have mentioned that this is a minor. low-priority issue for me.]

I have added the "TraceLogLimit" setting in web.config as documented in your linked page, and tried triggering an error on a page that has a couple of Trace.Write lines just before where the error is triggered; and I don't see the trace messages logged with the event/error. Where would they be shown?

Is there some other setting that I also need to enable to have the trace messages logged?

**Comment by niemyjski** [comment]
@PhilipDn were you able to get this working as expected? I'm closing this issue as the preferred way to log is not through a TraceLogLimit. With this said were you able to create a trace log listener that submitted new log messages? If so would you mind creating a new issue with the source / pr. I think it might be useful to include that in the extra's project.
