### ISSUE TITLE
[Selhosted] Exceptionless sending mail to fictive mail

### ISSUE THREAD

**Issue by Nonobis** [exceptionless/Exceptionless#750]
Hello,

Every night exceptionless send report mail for fictive project to fictive address. I receive bad sending report from google.

- It's marked as free plan with random project
- Target : free@test.com, test@test.com

Environnement :
i am on docker, EX_AppMode is on Production, mail settings are configured by EX_ConnectionStrings__Email

=> Email are defined in SampleDataService

Thanks

**Comment by niemyjski** [comment]
We're really sorry about that. I'm not sure we considered this happening as we thought it would just be dev mode and not promoted to production mode. If production mode is specified we won't create sample data which will have the test user. You could log in as the test and free  users and delete them in the mean time. I'm going to mark that email address as not verified so a user will have to verify it to get emails sent.

**Comment by niemyjski** [comment]
I didn't add a migration for this to find them and mark them as unverified but we'd accept a pr for this if you'd like to submit one.

**Comment by Nonobis** [comment]
@niemyjski Thanks, i will see if i got time to make a PR. Because i receive many mail.... ^^

**Comment by niemyjski** [comment]
You could log in and delete those accounts or just remove them via elastic
