### ISSUE TITLE
server cannot receive log message

### ISSUE THREAD

**Issue by a121984376** [exceptionless/Exceptionless#753]
hi
I  deployed the server and webUI. on docker.
the server version is 7.0.0

create project and orgs is scuccesed by webUI.

but client submit Log and Exception, the server cannot receive.

How can i check?

**Comment by niemyjski** [comment]
Are you running the jobs out of process or in process? Are there any docker log messages for jobs running?

**Comment by a121984376** [comment]
> Are you running the jobs out of process or in process? Are there any docker log messages for jobs running?

![微信图片_20201023135533](https://user-images.githubusercontent.com/15758574/96961580-8c876480-1537-11eb-82d6-19770da39634.png)

this is spent a night.
it seems not logs..

**Comment by niemyjski** [comment]
Yeah, it doesn't look like jobs are running out of process. If you scroll up a bit higher in that window the first few lines (which I can't see) state if jobs are running in our out of process. If you are using this (https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml) than they will run out of process and you can grab the logs by doing `docker-compose logs jobs`

**Comment by a121984376** [comment]
![Dingtalk_20201026174431](https://user-images.githubusercontent.com/15758574/97157383-fc555380-17b2-11eb-89ca-40f4f56e6d5d.jpg)

**Comment by niemyjski** [comment]
What do the jobs logs say?

**Comment by a121984376** [comment]
missd RunJobsInProcess: true
thanks
