### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by wongchance** [exceptionless/Exceptionless#754]
`version: '3.7'

services:
  api:
    depends_on:
      - elasticsearch
      - redis
    build:
      context: .
      target: api
    image: exceptionless/api:latest
    restart: on-failure
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://192.168.31.185:5100 #URL to UI
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80 # This can be commented out if using reverse proxy.
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    build:
      context: .
      target: job
    image: exceptionless/job:latest
    restart: on-failure
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://192.168.0.201:5100
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://192.168.0.201:5000
      #EX_Html5Mode: 'false'
      #EX_EnableSsl: 'false'
      #EX_EnableAccountCreation: 'false'
    ports:
      - 5100:80 # This can be commented out if using reverse proxy.

  elasticsearch:
    image: exceptionless/elasticsearch:7.9.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata7:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local
`

****
Step 8/30 : RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done
 ---> Using cache
 ---> d9ff08492c13
Step 9/30 : COPY tests/*/*.csproj ./
 ---> Using cache
 ---> 58c1987b18d8
Step 10/30 : RUN for file in $(ls *.csproj); do mkdir -p tests/${file%.*}/ && mv $file tests/${file%.*}/; done
 ---> Using cache
 ---> 9f9dfd87401d
Step 11/30 : RUN dotnet restore
 ---> Running in 2f9dcedf3058
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/microsoft.extensions.diagnostics.healthchecks/index.json'.
  The HTTP request to 'GET https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/microsoft.extensions.diagnostics.healthchecks/index.json' has timed out after 100000ms.
  Failed to download package 'Foundatio.AWS.10.0.0' from 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/foundatio.aws/10.0.0/foundatio.aws.10.0.0.nupkg'.
  The download of 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/foundatio.aws/10.0.0/foundatio.aws.10.0.0.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Failed to download package 'Foundatio.JsonNet.10.0.0' from 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/foundatio.jsonnet/10.0.0/foundatio.jsonnet.10.0.0.nupkg'.
  The download of 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/foundatio.jsonnet/10.0.0/foundatio.jsonnet.10.0.0.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Failed to download package 'Foundatio.Repositories.Elasticsearch.7.9.2' from 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/foundatio.repositories.elasticsearch/7.9.2/foundatio.repositories.elasticsearch.7.9.2.nupkg'.
  The download of 'https://f.feedz.io/foundatio/foundatio/nuget/v3/packages/foundatio.repositories.elasticsearch/7.9.2/foundatio.repositories.elasticsearch.7.9.2.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.

is this a network problem?

**Comment by niemyjski** [comment]
Thanks for reaching out. Yeah, sounds like it failed due to some kind of timeout. Grab the docker-compose file from the samples folder which will use the prebuilt images and you won't need to resolve/build any dependencies. Please let us know how that works out.

**Comment by niemyjski** [comment]
Were you able to resolve this using our docker-compose file?

**Comment by wongchance** [comment]
@niemyjski  thanks for focusing



i fix the orgin code as

`version: '3.7'

services:
  app:
    depends_on:
      - elasticsearch
      - redis
    image: exceptionless/app:latest
    environment:
      EX_AppMode: Production
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5001
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      EX_RunJobsInProcess: 'false'
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - appdata:/app/storage
      - ssldata:/https

  jobs:
    depends_on:
      - app
    image: exceptionless/job:latest
    environment:
      EX_AppMode: Production
      EX_BaseURL: http://192.168.0.201:5000
      EX_ConnectionStrings__Cache: provider=redis
      EX_ConnectionStrings__Elasticsearch: server=http://elasticsearch:9200
      #EX_ConnectionStrings__Email: smtps://user:password@smtp.host.com:587
      EX_ConnectionStrings__MessageBus: provider=redis
      #EX_ConnectionStrings__Metrics: provider=statsd;server=statsd;
      EX_ConnectionStrings__Queue: provider=redis
      EX_ConnectionStrings__Redis: server=redis,abortConnect=false
      EX_ConnectionStrings__Storage: provider=folder;path=/app/storage
    volumes:
      - appdata:/app/storage

  elasticsearch:
    image: exceptionless/elasticsearch:7.9.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata7:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

volumes:
  esdata7:
    driver: local
  appdata:
    driver: local
  ssldata:
    driver: local`


which just remove the 'ui' part and set the 'job' part's '**EX_BaseURL**': to the same as 'app''s port

**Comment by niemyjski** [comment]
Awesome! I just noticed the following line was missing in our samples and added it (https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml#L17) which you may also want to add to yours. We also updated the elasticsearch images too. Thanks for letting us know it's all working!
