### ISSUE TITLE
The dashboard does not display exception

### ISSUE THREAD

**Issue by lxz-lxz** [exceptionless/Exceptionless#755]
helllo,I saw the exception message through the email，But I can't see it through the dashboard.
![image](https://user-images.githubusercontent.com/24243415/96997501-793ebe00-1564-11eb-9f7f-c0668d5fc506.png)
![image](https://user-images.githubusercontent.com/24243415/96997686-d0dd2980-1564-11eb-9fee-a371b34e36b7.png)
![image](https://user-images.githubusercontent.com/24243415/96997623-b1de9780-1564-11eb-9007-627d991e170d.png)

**Comment by niemyjski** [comment]
You might be filtered or a stack might be marked as not open or regressed. Ensure your date filter is set to all and if you don't see it put a `*` in the search box. Do you see it then?

**Comment by lxz-lxz** [comment]
I saw it when I put a *,But why?There seems to be no problem with my application configuration information.
![image](https://user-images.githubusercontent.com/24243415/97130128-779b1300-177b-11eb-98d3-37114e7ddff8.png)

**Comment by lxz-lxz** [comment]
I've solved it.The reason for this problem is that the pull from the docker-compose.yml file is the latest version image of the api, job, and ui.But my self-hosting exceptionless  version is 6.0.The current 7.0 version is not compatible with the older version.

**Comment by niemyjski** [comment]
Thanks for the update. We recommend running the latest version of Exceptionless as it contains many improvements and bug fixes.
