### ISSUE TITLE
Can I search logs by Regular Expression  ？

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#756]
it seams like not working.

![图片](https://user-images.githubusercontent.com/30283517/97146713-4a625b00-17a3-11eb-8ddd-709d85513d8b.png)

Regular is very important for me 
thank you sir

**Comment by niemyjski** [comment]
Are you trying to search with a regex? We don't support Regex queries (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) as they require a special query syntax.

**Comment by niemyjski** [comment]
We don't yet support searching by regex. I'm going to close this for now but if there are more requests for this via this issue we'll reopen it. Also feel free to submit a pr for this as we would be more than happy to review it.
