### ISSUE TITLE
May I ask if the jump address of the menu on the left of exceptionless can be modified?

### ISSUE THREAD

**Issue by SupremeDevil** [exceptionless/Exceptionless#759]
I visited exceptionless by domain name + service name. I found that the page to jump to by clicking the menu on the left is not consistent with the expectation. After checking the source code of the webpage, I found that the jump address of this menu is missing the service name. How to set the jump address of this menu

**Comment by niemyjski** [comment]
I'm not sure what you are asking are you referring to the top logo click in the upper left?

**Comment by niemyjski** [comment]
I'm not sure what you are asking are you referring to the top logo click in the upper left?

**Comment by ejsmith** [comment]
I just verified that the logo in the top left isn't using a fully qualified URL. So not sure what this is referring to. Can you ellaborate @SupremeDevil ?

**Comment by niemyjski** [comment]
I'm going to close this until more information is sent back. Can you please give us more information @SupremeDevil
