### ISSUE TITLE
Conditional alerts

### ISSUE THREAD

**Issue by Webcoda** [exceptionless/Exceptionless#76]
Would be good to have more control over the alert messages.
For example being able to set up alert routes based on error information such type, tags, etc.
The alert target should not need to be user with access to the portal.

Thanks,
Oleg

**Comment by niemyjski** [comment]
Where do you see the notifications being configured, per project or per org?  Any email address that you choose for notifications would need to verified and currently all that code is tied to a user of the system.

**Comment by niemyjski** [comment]
Currently you could use a webhook or zapier to notify you of changes but the conditional logic would have to go someplace externally. Do you have any ideas on what the UI would look like for this?

**Comment by niemyjski** [comment]
I'm closing this as it's now merged into 177.
