### ISSUE TITLE
Resetting Project Data doesn't Remove Session Report Data

### ISSUE THREAD

**Issue by wingers999** [exceptionless/Exceptionless#767]
I wanted to clear all my previous log data from testing so I had fresh interface for testing more features – so I assumed Settings > Project > Reset Project Data > and click the big red button would do this?  

This successfully cleared everything in Exceptions, Log Messages, Features etc

But still showing all my previous session information under Reports > Sessions 

It seemed to clear the old content when I then next sent a exception as only 1 item appeared in list

**BUT if you then do Reset Project Data again ALL the previous data comes back to Report > Sessions !!!**

**Comment by niemyjski** [comment]
Thanks for reporting this issue, I've been able to verify it as well and we'll get this fixed shortly.

**Comment by wingers999** [comment]
Related issue

After doing Settings > Project > Reset Project Data  for a project - you can still see a count of stacks / events in My Projects - but if you have "reset project data" then I assume this should now show 0 / 0 

![image](https://user-images.githubusercontent.com/10872799/99881420-b48ae600-2c11-11eb-9a3b-63c1b9a55ac6.png)

**Comment by niemyjski** [comment]
Thanks for letting us know about this. I was able to reproduce in a test. We also committed a fix last night but haven't deployed it for this issue.

**Comment by niemyjski** [comment]
This has been fixed and deployed
