### ISSUE TITLE
Improve self hosted setup.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#77]
We would love feedback and your comments below on how we can improve the self hosted experience. Below is a *live list* on ways we intend to improve the self hosted setup experience.

1. Improve setup documentation
2. ~~Create a release package that has both UI and Server Content and make it clear that there are two websites that require configuration.~~
3. ~~Remove the Web.Config rewrite and redirect rules, ssl redirect from the UI projects web.config.~~
4. ~~Add existing setting `EnableAccountCreation` to Server Web.Config to disable signups.~~
5. ~~Remove MongoDB Dependency~~
6. ~~Redis is no longer needed but recommend (required for load balanced installs)~~

Future goals for improvement:
1. Docker images
2. Cross platform support (vnext)

**Comment by kellyelton** [comment]
It seems like setting up mongo redis and elastic search wasn't so bad
the parts that threw me for a loop was
* I assumed the Exceptionless repo was the only front facing piece, didn't realize until later that Exceptionless.UI was the interface. The backends 'Login' link linked to your guyses hosted service, so I assumed after that that the front end was hosted and somehow did api calls back to my back end. This one really did a huge number on me honestly
* SSL requirements(UI forces ssl for example)
* the usage of BASE_URL being ambiguous

I also think that in the client docs there are certain places (I wish I could quote off the top of my head here) where there was no mention of how you configure it for hosted, which was slightly different
As well as no possible idea(outside of being lucky that I saw it in gitter chat) how authentication worked and how to set it up.I wouldn't have had a clue had I not lucked out and saw someone in here(gitter) explain it (the authentication bit)

on a side note, it would be nice to have an option to restrict sign ups in certain ways...I'm sure I'm not the only one to mention this...but like even by domain name on email accounts.

Oh and another feature request(if you want I can turn these into tickets) would be that if you specify a blank client id for OAuth providers, it doesn't show their icon on the login screen
and maybe even the ability to only use an oauthprovider(like we use google apps for buisness here, would be nice to restrict by our domain name, and only let people auth using google)

**Comment by niemyjski** [comment]
Can you log the Oauth request here: https://github.com/exceptionless/Exceptionless.ui

**Comment by niemyjski** [comment]
I just made the oauth login buttons only show up when they are configured. This should make it much easier to setup and configure as it's one less step (you have to buy into it for it to show up).

**Comment by Phyxion** [comment]
Just my two cents:
- Less dependencies. MongoDB, ElasticSearch, Java, Redis, it's a lot.
- Mention on the hosting options than a UI is still required to be installed.
- Add an option to disable registration of accounts. We currently have an url rewrite rule for this but it's a workaround that shouldn't be necessary. With this, maybe also think of a rescue mode / super user account or something that you can use to sign in locally.
- Auto upgrade from 1.x to 2.x.
- Mention on the UI page that you can just use the release files and that grunt / bower etc is not needed.
- More (smaller) releases? The last release is now almost a month ago, I'm seeing lots of (useful) changes.

**Comment by niemyjski** [comment]
@Phyxion thanks for your feedback. 

1. If you are running a single node api install and are running the jobs in process then you do not need to install redis. The default of box experience uses in memory implementations unless you set a redis connecting string. 

We will be ditching MongoDB in a future version. We just wanted to play it safe and not put all our eggs into one basket.. Right now our elasticsearch cluster could die in a fire and we would be okay. Users would lose access to their events for a while but they are all queued into to geo redundant blob storage when you post an event. We would just have to call an admin controller action to requeue all of events and they would all be replayed :) (minus any deleted stacks or events would show up again). But we couldn't do this for all other data that we currently host in mongo right now.

2.  We are working on moving this into a single release zip (api + ui). We also have pre built zips via github releases that contain the official releases that we actually push to production.

3. You can currently disable registration of accounts right now. Just set https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Web.config#L29 to false.

4. To be honest we will help users upgrade hosted installs from v1 to v2 but it's not something we want to stick our resources into writing automated scripts, we have a set of jobs that need to be run in order to do the migration. (we need to pick the things we work on that benefits everyone going forward as we don't have a huge team). Going forward, we will make it easy to auto upgrade/upgrade to major versions. Please contact us via email / github / gitter and we can help guide you through the upgrade process. If you want to document this for others that would be greatly appreciated.

5. I added **Getting Started (Development)** to each section. I'm not sure how to make this any clearer.. Ideas??

6. We will be doing a release soon. We've been fighting many small issues since deploying 2.0. We think we have it **really** stable now (just deployed a new build on friday and it's been running really strong). I want it to bake a little bit more and then we'll push a new release out..

7. Thank you for giving us your feedback, we really appreciate it and it really helps us.. We are here to help you all first and foremost (and to hopefully eat in the process).

**Comment by Phyxion** [comment]
I understand about the migration. We've tried it two times now and both times it ended up without any data besides the project names. I think we'll just ignore the existing data and have it refill. Can the 1.x clients connect to the 2.x server if we modify the api key to the old ones? 

The registration disable is not yet in 2.0.0 (from releases) I think?

To make it a bit more clearer, I think you could do with some renaming (also on the other projects like Exceptionless.UI), like:
Getting Started (Development) -> Building / Building Exceptionless.
Hosting Options -> Hosting / Hosting Exceptionless.
Mention in Hosting (maybe also Building) that you can also grab a prebuilt version from 'releases'.

Mention at Hosting Options that Redis is optional. Was this always the case? I do not remember reading this anywhere.

Maybe also add some information about which versions of MongoDB / ElasticSearc / Redis are supported. 

Maybe change the order of the sections a bit, like:
Exceptionless (the description)
Building (Exceptionless)
Hosting (Exceptionless)
Using (Exceptionless)
Roadmap
Contributing
Thanks
License

**Comment by niemyjski** [comment]
1. Yes, we've designed the api to auto upgrade any event from any version. 
2. Yes, the registration code should be available in 2.0 (Please try `EnableAccountCreation` to `false` in the web.config)
3. Thanks, we recommend using redis because if your app dies so will any queued data. Also it scales much better. The latest versions of elastic, mongo and redis is what we use. Do you think we should add a section? or just assume you're not going to go to the mongo site and download a 2 year old version.

**Comment by Phyxion** [comment]
Well, there is Mongo 3.x and 2.x (both have releases not older than a month). Might be worth mentioning what is supported.

**Comment by niemyjski** [comment]
You can use either, We are still running 2.6.8 in production as we use a managed service for mongo and they haven't upgraded. However, we use 3.0 in development.

**Comment by Phyxion** [comment]
I tried EnableAccountCreation = false with the build from 'releases' but I can still create a new account.

**Comment by niemyjski** [comment]
Yes, I show that it existed in 2.0 (https://github.com/exceptionless/Exceptionless/blob/v2.0.0/Source/Core/Settings.cs#L74). It needs to be an setting defined in appSettings like this this:https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Web.config#L29 

After setting this are you still able to create an account?

**Comment by Phyxion** [comment]
Yes, I have set it like that (I copied it from that file in fact). I can still create an account, even after I restarted the server. I'm not sure what is supposed to happen but sign up button still works (and so is #/signup).

**Comment by niemyjski** [comment]
The signup page will still work but when you press the signup button it should return an error toast saying signup is disabled.  It should return a bad request server side: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/AuthController.cs#L118-L119 Can you please debug this and let me know if you are seeing this.

**Comment by Phyxion** [comment]
It seems the config wasn't reloaded. I stopped the application pool and restarted it (instead of the regular restart) and it works now. Not sure why the regular restart didn't work as it normally does work but it's OK now.

Still might be nice to hide the sign up button as well (which makes a bit more sense as well).

**Comment by niemyjski** [comment]
That's very odd, it should reload anytime the web.config is changed.  Yeah, I agree, would you mind logging a feature request / pull request for this in the ui project (https://github.com/exceptionless/Exceptionless.UI/issues/new)

**Comment by Phyxion** [comment]
Done.

You mentioned that 1.x clients should work on 2.x as well. With the 1.x client we run (I think it was 1.5.xxx, latest from NuGet) we cannot see any event we throw in the 2.x version. It's not that useful as we cannot modify the api keys, but as the 1.x clients are actually compatible with .NET 4.0 we thought about keeping the old client version for the time being. Is there some magic tape required to get this to work?

**Comment by niemyjski** [comment]
Yes, they will work with 2.0 with no issues. We've done a TON of testing. If you take a look at the code ( https://github.com/exceptionless/Exceptionless/tree/master/Source/Core/Plugins/EventUpgrader ) you can see that we have a plugin that handles upgrading all versions of events.

You can't see any event that's thrown in the 2.x version? Is there any chance you can jump on gitter and I can take a look with you: https://gitter.im/exceptionless/Discuss

**Comment by niemyjski** [comment]
@Phyxion, I've created a 2.0.1 release for both the api and ui

**Comment by Phyxion** [comment]
Thanks, I'll check it out soon!

**Comment by greg-williams-tcg** [comment]
Also, probably worth noting I did encounter an error whereby CORS was preventing the UI from contacting the API site from a separate subdomain under IIS8.

For these I had to add the following web config:
`<system.webServer>`
`    <handlers>`
`          <remove name="OPTIONS"/>`
`          <remove name="WebDAV" />`
`          <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />`
`          <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />`

This is under IIS8, particularly if web-dav installed (previously worked with `<remove name="OPTIONSVerbHandler" />`)

**Comment by Phyxion** [comment]
Thanks for the info greg, I'll see if that works with the CORS problems I've been having (also IIS8).

**Comment by niemyjski** [comment]
@Phyxion please let me know if this works for you. I wonder if we should be removing both of those exceptionlessUrlHandlers.. I guess it can't hurt (thoughts?). I'm not sure why they would have renamed the options and webDav handlers.

**Comment by Phyxion** [comment]
Sure, I'll post it here! 
I don't think I have time for it this week, I might be able to squeeze it in but otherwise it'll be next week.

**Comment by greg-williams-tcg** [comment]
Are there any plans to be package the API and UI as NuGet/Chocolatey packages?

**Comment by niemyjski** [comment]
@greg-williams-tcg, As of this time no, unless more people request it. We do have nuget packages that can be pulled from our ci [https://ci.appveyor.com/project/Exceptionless/exceptionless/build/artifacts](https://ci.appveyor.com/project/Exceptionless/exceptionless/build/artifacts).

How would chocolatey packages work for setting up the sites?

**Comment by greg-williams-tcg** [comment]
I was thinking it may provide an easier way to deploy straight from a NuGet feed (AppVeyor) to the targeted (self hosted) server. 

Otherwise, could one use OctopusDeploy to access AppVeyor NuGet feed to deploy package from?

**Comment by niemyjski** [comment]
We are thinking of having a build branch where our ci puts all the builds. Then we can use GitHub deploy in azure and place everything in a slot. Exceptionless is already setup to use environment variables. 

We currently have our build create a release in octopus deploy. You should be able to use our NuGet feed.

**Comment by greg-williams-tcg** [comment]
Thanks @niemyjski , I ha a dig around and managed to find the artifacts from AppVeyor, but not the NuGet feed (https://ci.appveyor.com/nuget/exceptionless?? Is it private or enabled? Do I need to have a key?). 

I then went to the OctopusDeploy (at https://deploy.codesmithtools.com) site it mentions in the build script (https://github.com/exceptionless/Exceptionless/blob/master/appveyor.yml) but again it appears this requires credentials.

Is there no public NuGet feed?

**Comment by niemyjski** [comment]
It appears that our [NuGet feed](https://ci.appveyor.com/nuget/exceptionless-fh3g7460x0ha) is public as it should be. However packages are not listed in it... Here is what the docs say:

** Project feed contains all NuGet packages pushed to artifacts during the build process. Project feed is read-only. Publish your custom packages to the account feed.**

We are publishing artifacts that are NuGet packages so I'm not sure why they are not showing up. Any ideas? If not, I'll try opening a support ticket with appveyor.

Yes, that is our private site that we use for deployment.

**Comment by Phyxion** [comment]
So, about the CORS, all that was required here was adding:
   <remove name="OPTIONS" />

All the other changes weren't required. Please add this to the web.config so it works by default on IIS 8 as well.

I also updated to the 2.0.1 release (I was still running that other build you've sent me) and that's working as well (or at least appears to be, still need to test client integration). Now I'll continue with the .NET 4.0 client.

**Comment by niemyjski** [comment]
@Phyxion  I've made those changes as well as added one for WebDav just to make sure.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless/issues/93

**Comment by niemyjski** [comment]
@all, I've been actively working on this and were going to release a 3.0 soon that just focuses solely on making hosting/development easier. Here are the notable changes so far.

* Removed Mongo (This requires you to run a migration job).
* Made changes to the config based on your feedback so far.
* Redis isn't required but recommended. It's not required to run in development and is not enabled by default. Do you all think we should remove it from the readme?
* Updates for webdav.

Currently I'm working on improving the build process. We are going to get rid of octopus deploy and deploy an artifacts repo which will allow us and others to do git deployment :). After this is done, I'll be working on creating a script to automatically merge the latest UI release into the server builds. This will allow you to just grab a github release and get running.

**Comment by niemyjski** [comment]
If you think I'm missing anything, please chime in as now is the time to do so :).

**Comment by Phyxion** [comment]
Yes, please explain step-by-step on how to run that "migration job" as last time I never got it to work (1.x to 2.x).

**Comment by niemyjski** [comment]
@Phyxion currently we have this: https://gist.github.com/niemyjski/bb4eb5a3bc9466638882 which will be making it's way to our new github wiki

**Comment by Phyxion** [comment]
The Job.exe.config, can it just be copied from the regular Exceptionless installation? I remember doing something like that the last time (or maybe it was something else, I don't recall). It would be nice if it used that config anyway, or that the jobs can be launched through Exceptionless (or even better: automatically).

**Comment by niemyjski** [comment]
Yes, but all these files will exist in the release zip, you just need to edit them.

All our jobs will run automatically in process if they are configured to do so. But the upgrade jobs will never automatically get run because they should only be ran once. Going forward, I don't see us having any upgrade jobs after v3.

**Comment by Phyxion** [comment]
What about the config file (i.e, can you copy it from normal config) for Job.exe?

**Comment by niemyjski** [comment]
What do you mean? The Job.exe.config has the same app settings and connection strings that can be applied but it has different assembly bindings defined.

**Comment by Phyxion** [comment]
If it's possible to use the config file from Exceptionless instead, but if it the majority can be copied it's OK.

**Comment by niemyjski** [comment]
It's not possible because of the way .net reads config files. I guess we may be able to get it to be read if we did a config source and told it where to read settings from.

**Comment by Phyxion** [comment]
Yes, I know, but I meant if it's possible to copy its content. As long as the names match it should be easy to copy the few changed settings I assume :)

**Comment by ejsmith** [comment]
We are making progress on simplifying things even more.  The goal is for people to be able to download a github release and run a script.  The script will download and start ElasticSearch.  The release will include both the Server and UI in a single site and will not require any configuration to run it on localhost.  When you want to take that and run it in IIS for real, you will just need to set a couple environment variables and you will be done.

**Comment by niemyjski** [comment]
We are making great progress on this :).

**Comment by Phyxion** [comment]
Sounds great!

**Comment by niemyjski** [comment]
What do you guys think of our new readme and self hosting guide: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting

Eventually I want to take our private docs for setting up elasticsearch on linux and put it in there... But that's a task for another day.

**Comment by Phyxion** [comment]
I think you should mention that the base url should include /# at the end for *Exceptionless* and /api/v2 for the *UI*. I would also rename Evaluation to Test(ing) as I got the impression that it's some sort of trial version.

The ElasticSearch link is referencing to the wrong version (1.6). You might want to change this to 1.7 or just use https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html.

**Comment by niemyjski** [comment]
Good points. I'll update this shortly. You no longer need /api/v2 for the ui asI've updated the ui to make these in sync.

**Comment by niemyjski** [comment]
I just added an upgrade section as well :) https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting

**Comment by Phyxion** [comment]
The documentation is very clear now, thanks!
