### ISSUE TITLE
Health check StackStatus completed after 0.3504ms with status Unhealthy and description

### ISSUE THREAD

**Issue by yuefengkai** [exceptionless/Exceptionless#779]
Kubernetes Self Hosting But Not Helm

exceptionless/api:7.0.7 scale  2 pod
exceptionless/job:7.0.7 scale  4 pod
exceptionless/ui:3.0.7 scale 2 pod

Cache = Standard Edition aliyun redis
Storage = aliyun oss

The query log can be written normally but there is an exception, not sure if it affects

![image](https://user-images.githubusercontent.com/2100585/99362916-0f110300-28ef-11eb-9508-3afecb1b5874.png)
![image](https://user-images.githubusercontent.com/2100585/99363326-8e9ed200-28ef-11eb-8759-c4e616010c49.png)

**Comment by yuefengkai** [comment]
I have tried reinstalling, switching versions, will have this problem

**Comment by niemyjski** [comment]
I believe I've resolved both of these issue in my latest commits. I'm going to be pushing a version shortly with some critical query fixes, could you please check either the nightly ci or the release that will be going out shortly.

**Comment by yuefengkai** [comment]
Now
exceptionless/api:7.0.8 scale 2 pod
exceptionless/job:7.0.8 scale 4 pod
exceptionless/ui:3.0.7 scale 2 pod

![image](https://user-images.githubusercontent.com/2100585/99496406-2d3e3800-29af-11eb-890a-b70294daa261.png)

but job auto reboot. one night restart Over fifty, Every one has restart
restart reason healthcheck statusCode 503
livenessProbe
![image](https://user-images.githubusercontent.com/2100585/99496825-e997fe00-29af-11eb-849b-6ba3faa32808.png)

**Comment by niemyjski** [comment]
What kind of stats of your nodes and k8s version? Some of these take out locks and should be run as singleton instances and that could be why you are seeing these messages. How many instances of each of these jobs are you running and I'll verify against our prod configuration.

**Comment by yuefengkai** [comment]
api 2 pods
job 4 pods
ui 2 pods

one project 




    


On 11/18/2020 22:29, Blake Niemyjski wrote: 
What kind of stats of your nodes and k8s version? Some of these take out locks and should be run as singleton instances and that could be why you are seeing these messages. How many instances of each of these jobs are you running and I'll verify against our prod configuration.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/exceptionless/Exceptionless/issues/779#issuecomment-729715425",
"url": "https://github.com/exceptionless/Exceptionless/issues/779#issuecomment-729715425",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by niemyjski** [comment]
That doesn't really give me much information. What are the node sizes/specs, what job pods are you running and what arguments are defined for to each job pod. What version of k8s are you running.

**Comment by yuefengkai** [comment]
k8s Worker 7
16 vCPU 32 GiB
docker://18.9.2

![image](https://user-images.githubusercontent.com/2100585/99611955-937a9780-2a4f-11eb-87fe-92e68313ddbd.png)

job ENV
![image](https://user-images.githubusercontent.com/2100585/99612076-dc325080-2a4f-11eb-91e1-fb76099f82b3.png)

api ENV
![image](https://user-images.githubusercontent.com/2100585/99612228-24ea0980-2a50-11eb-89fb-380f4ac6a93f.png)

This is all the configuration for now ，if you need Ymal, please let me know

**Comment by niemyjski** [comment]
Thanks for that information. I was curious how are these broken down: `exceptionless/job:7.0.8 scale 4 pod` Is each pod running all the jobs or are they running specific jobs? I'm assuming you are not using our helm templates since we have a massive number of pods (one or more pods per job type) https://github.com/exceptionless/Exceptionless/tree/master/k8s

**Comment by yuefengkai** [comment]
We did not use helm templates because the network problem is not smooth
![image](https://user-images.githubusercontent.com/2100585/99748954-82498d80-2b18-11eb-9c5a-b9d31fdc480f.png)
We have an old Exceptionless in the production environment. The current daily data is 5 million, but the version is relatively old (4.1.2861), and the stand-alone IIS deployment will cause data congestion under high concurrency.
So we have to redeploy a set of the latest version, because the self-host document is too little, I have to move the local test docker-compose to the production environment.
Did not use helm templates because of network problems.
Regarding the configuration of jobs, I did not find the corresponding configuration and documentation.
Deploy 4 pods, because I saw https://github.com/exceptionless/Exceptionless/issues/690, I thought that deploying multiple jobs pods can increase the processing speed.
If the jobs in docker-cpmpose are to run all jobs, then we should be using 4 pods to run all jobs.

very sorry. My English is very bad. This article uses google translate. understanding

**Comment by yuefengkai** [comment]
We deployed all jobs with reference to jobs.yaml, but lack of StackStatus is missing or not needed ?

Up to now, the non helm templates version of exceptionless has been deployed. We will test it for about a week and then switch the old version of exceptionless project to the new version. 

Thank you very much for your help!!!

**Comment by niemyjski** [comment]
You're getting these errors because some jobs are meant to only have one instance and they are taking out distributed locks so only one runs. When this happens those that aren't running will fail health checks. If you are going to fire up more jobs make sure you are only scaling the event posts job by passing a single argument of `EventPosts`. You can do this by modifying your extra jobs and add command to the `docker-compose.yml`

```
    image: exceptionless/job:latest
    command: "EventPosts"
```

Getting running up and resolving any network issues with k8s is definitely going to give you the most optimization and scaling of resources. I'm going to close this issue as I believe it's resolved but let me know if it's not and we'll reopen it. Please let us know if you have any questions or feedback.
