### ISSUE TITLE
Job run EventPostsJob failed: Unable to retrieve payload 'archive/20/11/19/08/34/5fb4e43f1fc1160001a68c9b/ac0261773db44e93b5f275871f5c7f29.payload'.

### ISSUE THREAD

**Issue by knowyi** [exceptionless/Exceptionless#781]
![image](https://user-images.githubusercontent.com/7392434/99642175-27ffec80-2a86-11eb-822b-aa5cf113f626.png)
![image](https://user-images.githubusercontent.com/7392434/99642218-351cdb80-2a86-11eb-812d-9f803cf8e800.png)
![image](https://user-images.githubusercontent.com/7392434/99642248-3e0dad00-2a86-11eb-938a-b0f352081038.png)

Job run EventPostsJob failed: Unable to retrieve payload 'q\a4c\a4c5fca52ae8468e814224b1c2ecfbde.payload'

**Comment by knowyi** [comment]
Please Help mapper-size is already installed
![image](https://user-images.githubusercontent.com/7392434/99642968-1834d800-2a87-11eb-9b80-fd1da1a0825e.png)

**Comment by niemyjski** [comment]
You need to use a federated storage implementation that all of your nodes can talk to to store event data and to get it. You can defined a storage provider like this: https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml#L17 and here are the storage providers we support out of the box: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Insulation/Bootstrapper.cs#L240-L277

Please let us know if you have any questions.
