### ISSUE TITLE
 An error occurred while attempting to establish an SSL or TLS connection.

### ISSUE THREAD

**Issue by knowyi** [exceptionless/Exceptionless#783]
![image](https://user-images.githubusercontent.com/7392434/99942252-50e7f080-2daa-11eb-953e-73eb4c57fb08.png)
![image](https://user-images.githubusercontent.com/7392434/99942281-5fcea300-2daa-11eb-8b1b-14eb359250a5.png)
Please Help

**Comment by niemyjski** [comment]
Thanks for reaching out to us. Is the certificate valid for your email server? Does it support wildcards? It says that the ssl certificate issued doesn't match the host name you are using.

**Comment by jbulowski** [comment]
Hi, @knowyi little off topic, but could you share your docker composer YML file?
Thanks in advance!

**Comment by jbulowski** [comment]
Hi @knowyi,

did you find the solution to your problem?
I'm getting the same error.

Thanks

**Comment by niemyjski** [comment]
I'd check your ssl certificates. You could also take our code and step through it to see if you can get more information / try different things.

**Comment by knowyi** [comment]
@niemyjski  It's settled. Thank you
