### ISSUE TITLE
How to upgrade with the old key (using the key but upgrade to 7.0.9)?

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#794]
sir， I find you fix some problems in v7.0.9(docker image).
Now my running version is 6.1.3 ,i really want to try it ,but  i get  something trouble
![图片](https://user-images.githubusercontent.com/30283517/100974974-3b2bb580-3578-11eb-9386-a8d7a829e3af.png)

My project have 40 ApiKeys，how can i upgrade to 7.0.9 whitout change my apikeys？and without change project settings ?
I try to follow the docs but, sorry  i can`t got it.
think you ， and hope reply me
-----------------------------------------------------------------
兄弟,我发现你在7.0.9版本修复了一个让我们非常头疼的bug
我现在在用的版本是6.1.3版本，我现在想升级到你发的船新版本，但是有一个头疼的事
如图是我现在运行的版本
我的项目里面有配置超过40个key，我不想从头开始运行7.0.9版本然后一个个配置key啊，能不能我只升级到最新版然后还能用原有的key，原有的项目也不需要额外配置呢？
我尝试看了下你写的文档，里面的升级写的我完全摸不着头脑。
非常感谢  期待回复

**Comment by niemyjski** [comment]
Hello,

I'd recommend backing up your elasticsearch data which is outside the scope of this project. You need to run the migrations as stated in the migration guide. You can do this easily with docker by passing the Migration argument to it like this `docker run exceptionless/job:latest Migration`.

**Comment by niemyjski** [comment]
I've updated the self hosting guide, please let us know if you have any questions.
