### ISSUE TITLE
API Limit on POST requests?

### ISSUE THREAD

**Issue by Edreih** [exceptionless/Exceptionless#800]
Hi,
Is there a limit on POST requests and if so, any idea on how to overcome it?

I was doing some load testing against Exceptionless by sending JSON events. I found that at around 3,500 POST requests, all subsequent requests would fail with "409 Conflict" errors. 
In further testing, I also set a delay between post requests of 0.5 up to 2 seconds, but found the same behavior. 

Any ideas appreciated! 😄 

Jmeter
![image](https://user-images.githubusercontent.com/11253613/101798072-4f1f6c00-3ad0-11eb-9764-5739787c1f66.png)

Postman Runner
![image](https://user-images.githubusercontent.com/11253613/101798306-8ee65380-3ad0-11eb-87ba-d79dd24d6732.png)

**Comment by niemyjski** [comment]
Yes, there is an [ApiThrottleLimit](https://github.com/exceptionless/Exceptionless/search?q=ApiThrottleLimit) setting that you can configure. Please let us know how perf testing goes.
