### ISSUE TITLE
what is wrong with it?

### ISSUE THREAD

**Issue by maobiwen** [exceptionless/Exceptionless#813]
when I set RunJobsInProcess: true ,it works fine ,but when I set RunJobsInProcess: false ,I run Job process, it give me error such as :
[13:30:00 ERR] Job run EventPostsJob failed: Unable to retrieve payload 'archive\21\01\11\05\27\5ff96798417d9d3eb028a052\84de8f299fc0455291abfe4681e40a12.payload'.

why? please help

![image](https://user-images.githubusercontent.com/11902441/104149532-7b047900-5411-11eb-8223-f844a3513af4.png)

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us. You'll need to map the storage directory volume to this docker container so both the api and the jobs are pointing to the same volume as shown here: https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml#L46 . Once this is done the two different containers can read/write to the same storage folder. Please let us know if you have any questions.

**Comment by maobiwen** [comment]
> Hello,
> 
> Thanks for reaching out to us. You'll need to map the storage directory volume to this docker container so both the api and the jobs are pointing to the same volume as shown here: https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml#L46 . Once this is done the two different containers can read/write to the same storage folder. Please let us know if you have any questions.

thank you .I had solved it
