### ISSUE TITLE
A few product demand.Export Logs and Custom ApiKey!

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#814]
First! Thanks you for you software! This has helped me a lot ！
But ，when i am using it in the production environment ，i find that has a lot of logs 。
I can not search it with [regular expression ]（you has responsed me last year , it seems   difficult）,so i can not search the logs with variable witch i set it in, and also i can not search logs with statistics。
So I think   can  you add a function -----Export Logs (file format: *****.txt)。
time、product 、filtering as the condition
![图片](https://user-images.githubusercontent.com/30283517/104161029-10f9cd00-542d-11eb-9328-554fe5ff7170.png)
The second demand you have replied to before, but I think it still needs to be raised。
CustomApiKey! it is so  important！
Last time, I upgraded to version 7.0.9. Because I was not familiar with how to migrate, I had to abandon the original version, rerun the container, and then reconfigure my project (create a new project on the UI and modify the key in the source code).
Sometimes I need to sell a piece of source code software to different customers, and then I need to reconfigure the key, which is very bad for management。If  i can customize the key, I think the upgrade will be very convenient。 
1：Export Logs！
2：Custom ApiKey！
Thanks a lot !
========================================
兄弟,非常感谢你这个软件，对我们非常有用。
但是我在生产环境使用时会产生超大量的日志。
我不能使用正则表达式搜索(你去年回答过我这个问题，好像实现起来很复杂)，所以我不能搜索到带有变量的日志，也就是说一些统计性的数据我是没法得出的。
所以我提出一个产品需求---增加导出功能（文件格式是.txt）。
以时间 项目 过滤词为条件进行导出
第二个需求是你之前回复过了 ，但是我觉得还是有必要再次提出来。
是关于自定义apikey的，这个在我实际使用过程中太重要了。
上次，我升级到7.0.9版本。因为不知道怎么迁移，我直接放弃了老版本，重新开一个容器，然后重新配置项目（在管理器上创建项目、key ,在源代码上修改key。有时候，交付性项目需要给不同客户部署，这时候我就需要对源代码更改，这对源代码管理来说太不友好了。如果你能够支持自定义key,这对我们项目性质的软件就太方便了。
1：导出日志！
2：自定义ApiKey！
如果能实现真的是太好了！！！

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us. 

1. We don't support searching by regex currently. If you can send us a sample event and what you'd like to search by (or submit a pr with a new search test case to our existing tests), we can see what we can do to modify our search indexes.

2. We have no plans at this time to allow users to manually enter in api keys via the ui or api. We have to ensure keys are unique and not guessable and follow a pattern. You could however, manually patch tokens via elasticsearch and clear the cache. This would give you exactly what you are looking for. We recommend taking backups before all upgrades so you can always restore.

In the future if you could open an issue for each question or feedback that would be greatly appreciated. I'll close this but feel free to open a new issue or respond to this one with the search case you'd like to search by or feel free to open a pr.

**Comment by XLJ-CN** [comment]
thank you sir.
You are right in no.2 , i did not think about security problems.you are right.
About No.1, i use it in this way.
My log format like this 【***actionname,exe time=555.88ms,res=*******】
When i want to search the action witch is more than 100ms ， i use regex 【time=\d{3,}\..*】
![图片](https://user-images.githubusercontent.com/30283517/104256877-0edc5080-54b7-11eb-9ce5-b0b43dc3b2d5.png)

**Comment by niemyjski** [comment]
Feature References #756
