### ISSUE TITLE
How to access the logs?

### ISSUE THREAD

**Issue by strombringer** [exceptionless/Exceptionless#82]
I'm trying to use a self-hosted instance of the Exceptionless API and am getting Http 500 errors when using the API directly and also when using it with the client from a console app ("DefaultEventQueue: An error occurred while submitting events").

From the configuration I assume that the logs are written to Elasticsearch. How can I access them?
(I also set up Kibana but am not sure if that is the right approach because I don't even know which index pattern to use)

**Comment by niemyjski** [comment]
Are you using the nightly builds from our repo or are you using the release zip? To get the logging to log to elastic search (logstash collection) you'd need to update the following `nlog.config` to:

```xml
  <rules>
    <logger name="EventPostsJob" minlevel="Warn" writeTo="exceptionless" final="true" />
    <logger name="*" minlevel="Info" writeTo="exceptionless" />
  </rules>
```

TO

```xml
  <rules>
    <logger name="*" minlevel="Trace" writeTo="elastic" />
  </rules>
```

I'd be more than happy to debug this with you as I'd like to know why you are seeing errors.

**Comment by strombringer** [comment]
I'm using the release zip. With your logging rule change I got the error log and the reason for my problem: System.UnauthorizedAccessException "...App_Data\storage\q"
For some reason the write access to the storage folder was removed on the system again and that's why it failed.

With the proper access setting I can send errors throug the API and the console app. Thanks for your help!

**Comment by niemyjski** [comment]
I wonder what we can do to make this easier to debug. Any ideas? Our latest nightly build checks the storage and returns a status code for it. But this isn't in the 2.0 release.

**Comment by strombringer** [comment]
I'm not sure what you want to improve. I think the error messages are clear enough, it was just a case of not knowing how to get to them.

**Comment by niemyjski** [comment]
I'm starting to wonder if we need a github wiki and we could put this how to in the wiki, we have a docs site but it's more for the clients.

**Comment by strombringer** [comment]
Ah yes, a wiki would be great. I spent a bit of time checking the existing issues for solutions to my problems (e.g. I also had the "missing /# in the UI Base Url" problem). A wiki would make that easier.
