### ISSUE TITLE
@ not allowed in username in EX_ConnectionStrings__Email

### ISSUE THREAD

**Issue by jbulowski** [exceptionless/Exceptionless#820]
Hello,

I'm having trouble setting up Exceptionless with SMTP.

I run following command and exceptionless doesn't start up at all.

```
docker run --rm -it -p 7000:80 `
-e EX_ConnectionStrings__Email=smtps://user@domain.com:password@smtp.server.com:25 `
-v esdata:/usr/share/elasticsearch/data `
exceptionless/exceptionless:latest
```

I suppose that the bit that is failing is the @ in my username. Is there another way of setting up the SMTP connection?

Thanks in advance!

**Comment by ejsmith** [comment]
You probably need to URL escape the @ sign with `%40` like `smtps://user%40domain.com:password@smtp.server.com:25`

**Comment by niemyjski** [comment]
Eric is correct, you need to escape it. Please let us know if you have any questions or feedback.
