### ISSUE TITLE
Got an error when put to ES

### ISSUE THREAD

**Issue by xdqa01** [exceptionless/Exceptionless#828]
Error message:
`
[16:39:14 ERR] Error processing EventPost 682e851ecdab4bfa9185a5cbe3a1684f q\221\2213ce771e414a2290c00373e4e251ed.payload: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /dev-events-2021.01.28/_doc/60127829d59dbf0cc4d1e904?pretty=true&error_trace=true&op_type=create&pipeline=events-pipeline&refresh=false. ServerError: Type: mapper_parsing_exception Reason: "failed to parse field [data.@level] of type [text] in document with id '60127829d59dbf0cc4d1e904'. Preview of field's value: '{name=Info, ordinal=2}'" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a START_OBJECT at 1:62""
Server: (400) Type: mapper_parsing_exception Reason: "failed to parse field [data.@level] of type [text] in document with id '60127829d59dbf0cc4d1e904'. Preview of field's value: '{name=Info, ordinal=2}'" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a START_OBJECT at 1:62""

System.ApplicationException: Original: (400 - ElasticsearchClientException) Request failed to execute. Call: Status code 400 from: PUT /dev-events-2021.01.28/_doc/60127829d59dbf0cc4d1e904?pretty=true&error_trace=true&op_type=create&pipeline=events-pipeline&refresh=false. ServerError: Type: mapper_parsing_exception Reason: "failed to parse field [data.@level] of type [text] in document with id '60127829d59dbf0cc4d1e904'. Preview of field's value: '{name=Info, ordinal=2}'" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a START_OBJECT at 1:62""
Server: (400) Type: mapper_parsing_exception Reason: "failed to parse field [data.@level] of type [text] in document with id '60127829d59dbf0cc4d1e904'. Preview of field's value: '{name=Info, ordinal=2}'" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a START_OBJECT at 1:62""

 ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /dev-events-2021.01.28/_doc/60127829d59dbf0cc4d1e904?pretty=true&error_trace=true&op_type=create&pipeline=events-pipeline&refresh=false. ServerError: Type: mapper_parsing_exception Reason: "failed to parse field [data.@level] of type [text] in document with id '60127829d59dbf0cc4d1e904'. Preview of field's value: '{name=Info, ordinal=2}'" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a START_OBJECT at 1:62""
   --- End of inner exception stack trace ---
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.IndexDocumentsAsync(IReadOnlyCollection`1 documents, Boolean isCreateOperation, ICommandOptions options)
   at Foundatio.Repositories.Elasticsearch.ElasticRepositoryBase`1.AddAsync(IEnumerable`1 documents, ICommandOptions options)
   at Exceptionless.Core.Pipeline.SaveEventAction.ProcessBatchAsync(ICollection`1 contexts) in E:\CodeSource\Exceptionless\src\Exceptionless.Core\Pipeline\040_SaveEventAction.cs:line 23
`

SourceCode : master / submition a6aa1da0 / label v7.0.9
ElasticSearch: 
`
{
  "name" : "DESKTOP-T51UA1T",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "7jf1tev7SnaKBhW2sRUzSA",
  "version" : {
    "number" : "7.10.1",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "1c34507e66d7db1211f66f3513706fdf548736aa",
    "build_date" : "2020-12-05T01:00:33.671820Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
`
Setting: All be default

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us, can you please also attach the raw log event you are trying to submit.

**Comment by niemyjski** [comment]
Can you let us know what the issue was in case someone else runs into this?

**Comment by xdqa01** [comment]
> Can you let us know what the issue was in case someone else runs into this?

Sorry.The problem cannot be reproduced,yet!After restart my windows 10 computer.

**Comment by xdqa01** [comment]
> Hello,
> 
> Thanks for reaching out to us. Can you please also attach the log event JSON you are trying to submit.

```text
[{"Id":"601b4d5e16210306eefe39ee","OrganizationId":"601a3f68795b7a0dca0c8a0a","ProjectId":"601a3f68795b7a0dca0c8a0b","StackId":"601b4d5e16210306eefe39e9","IsFirstOccurrence":false,"CreatedUtc":"2021-02-04T01:26:55.4639293Z","Idx":{},"Type":"log","Source":"Microsoft.AspNetCore.Builder.RequestLocalizationOptions","Date":"2021-02-04T09:26:54.0254085+08:00","Tags":["Info"],"Message":"Supported Request Localization Cultures: zh-Hans,de,nl,en,en-GB,es-MX,es,fr,it,pt-BR,ru,vi,tr,ar,th","Geo":null,"Value":null,"Count":null,"Data":{"@level":{"name":"Info","ordinal":2},"@version":"10.0.0","@environment":{"ProcessorCount":16,"TotalPhysicalMemory":0,"AvailablePhysicalMemory":0,"CommandLine":"*\\bin\\Debug\\net5.0\\SomeProject.dll","ProcessName":"SomeProject","ProcessId":"13744","ProcessMemorySize":302120960,"ThreadName":null,"ThreadId":"1","Architecture":"X64","OSName":"Microsoft Windows 10","OSVersion":"10.0.18363","IpAddress":"27.38.37.66","MachineName":"DESKTOP-T51UA1T","InstallId":"60dbe4a9fa3142c8924004cb056cfe2c","RuntimeVersion":"5.0","Data":{"FrameworkDescription":".NET 5.0.2","ProcessArchitecture":"X64","ApplicationBasePath":"*\\bin\\Debug\\net5.0\\","ApplicationName":"SomeProject","RuntimeFramework":".NETCoreApp,Version=v5.0"},"@submission_client":{"IpAddress":"27.38.37.66","UserAgent":"exceptionless","Version":"1.0.0.0"}},"ReferenceId":"601b4d5e16210306eefe39eb"}]
```

It happened again.I use 'using Newtonsoft.Json;' to make json,and ,the json always lost some token.
`
namespace Exceptionless.Core.Pipeline {
    [Priority(40)]
    public class SaveEventAction : EventPipelineActionBase {
        private readonly IEventRepository _eventRepository;

        public SaveEventAction(IEventRepository eventRepository, AppOptions options, ILoggerFactory loggerFactory = null) : base(options, loggerFactory) {
            _eventRepository = eventRepository;
        }

        protected override bool IsCritical => true;

        public override async Task ProcessBatchAsync(ICollection<EventContext> contexts) {
            List<Models.PersistentEvent> list;
            try {
                list = contexts.Select(c => c.Event).ToList();
            }
            catch (Exception) {
                _logger.LogWarning("Hehe,even a list!");
                return;
            }
            try {
                await _eventRepository.AddAsync(list).AnyContext();
            }
            catch (Exception ex) {
                _logger.LogWarning(ex, JsonConvert.SerializeObject(list));
                foreach (var context in contexts) {
                    bool cont = false;
                    try {
                        cont = HandleError(ex, context);
                    }
                    catch { }

                    if (!cont)
                        context.SetError(ex.Message, ex);
                }
            }
        }

        public override Task ProcessAsync(EventContext ctx) {
            return Task.CompletedTask;
        }
    }
}
`

**Comment by niemyjski** [comment]
What are you using for a client and how are you specifying the log level?

**Comment by xdqa01** [comment]
> What are you using for a client and how are you specifying the log level? The log level should be a string and not an object

Client:Asp.NetCore WebApi  / dotnet core 5
```text
//auditInfo is Abp.Auditing.AuditInfo
var client = ExceptionlessClient.Default;
string content = JsonConvert.SerializeObject(auditInfo);
builder = client.CreateLog(content, Exceptionless.Logging.LogLevel.Info);
builder.AddTags(nameof(Exceptionless.Logging.LogLevel.Info));
builder.SetValue(auditInfo.ExecutionDuration);
builder.AddTags(nameof(Auditing));
builder.SetSource(nameof(Auditing));
builder?.Submit();
```
Settings:
```text
"Exceptionless": {
    "ApiKey": "*",//Hidden
    "IncludeIpAddress": true,
    "IncludeMachineName": true,
    "IncludeUserName": true,
    "IncludeQueryString": true,
    "Enabled": true,
    "ServerUrl": "*",//Hidden
    "Settings": {
      "@@log-*": "Info",
      "@@log-Auditing": "Info",
      "MinLogLevel": "Info",
      "ConsoleLogLevel": "Info"
    }
  }
```

**Comment by niemyjski** [comment]
Hello,

I'm not seeing any of the submission errors you are reporting but I'm seeing the client have a default log level of warn which I'll look at. I do noticed because of this your event isn't logged. The reason behind this is your log level settings format is incorrect. If you change it to this it will work:

```cs
var client = ExceptionlessClient.Default;
string content = JsonConvert.SerializeObject(auditInfo);
var builder = client.CreateLog(nameof(Auditing), content,  Exceptionless.Logging.LogLevel.Info);
builder.AddTags(nameof(Exceptionless.Logging.LogLevel.Info));
builder.SetValue(auditInfo.ExecutionDuration);
builder.AddTags(nameof(Auditing));
builder.Submit();
```

```json
"Exceptionless": {
    "ApiKey": "*",//Hidden
    "ServerUrl": "*",//Hidden
    "IncludePrivateInformation": true,
    "Settings": {
      "@@log:*": "Info",
      "@@log:Auditing": "Info"
    }
  }
```

I've removed the config settings we do not support out of the box.
