### ISSUE TITLE
Restrict sign ups by domain name

### ISSUE THREAD

**Issue by kellyelton** [exceptionless/Exceptionless#83]
I would like the ability to specify that you must have a specific domain on your email account to create an account.

For example, if I have the company Doppleganger, then I could say, only people with their email @Doppleganger.com could sign up for accounts.

**Comment by niemyjski** [comment]
Would you mind submitting a pull request for this? We have a mail setting that's close to this: AllowedOutboundAddresses. I wonder if this could be reused.

**Comment by niemyjski** [comment]
@kellyelton would you mind submitting a pull request for this.

**Comment by kellyelton** [comment]
It looks pretty straight forward I probably could. Would probably just need to add an AppConfig setting and then add a check in the AuthController. I'll see if I can find some time.

**Comment by niemyjski** [comment]
Sounds good, you'd want to take a look at our Settings class in core. It's pretty straight forward across the board.

**Comment by kellyelton** [comment]
Alright I'll do that.

**Comment by niemyjski** [comment]
@kellyelton did you have any luck with this?

**Comment by kellyelton** [comment]
Sorry I have this on my todo list I've just been really busy.

**Comment by niemyjski** [comment]
I'm closing this for the time being. We'd be more than happy accept a pull request for this behavior.

**Comment by kellyelton** [comment]
Alright. Yeah I'm actually not currently working for the company I implemented Exceptionless for(where this feature would have been useful), for the time being, so it became less of a priority. I still use it on another project of mine, but I use it hosted by you and I don't need any domain restrictions.
