### ISSUE TITLE
"User Name" uses identity instead of name from SetUserIdentity

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#84]
According to the intellisense the parameters on ToExceptionless().SetUserIdentity() should be identity first, and then name, but when looking at the event on exceptionless.io it is the value of the identity parameter that is shown under User Name.

**Comment by niemyjski** [comment]
Yes, The first parameter can be any unique identifier (email address, user id in your system etc..) the second parameter is a friendly name that describes the user (Full Name, System A User)...  I don't think we are showing the friendly name in the UI are we?

**Comment by KasperLK** [comment]
Yes, but the label in the UI says User Name.
![username](https://cloud.githubusercontent.com/assets/11861088/7083797/475ff9f6-df66-11e4-98ca-fb26d7506932.png)

**Comment by niemyjski** [comment]
What do you think it should say?

**Comment by KasperLK** [comment]
User Identity

**Comment by niemyjski** [comment]
Yeah I agree. Is there any chance you can do a pull request for this ( https://github.com/exceptionless/Exceptionless.UI/blob/master/src/app/event/tabs/overview.tpl.html#L86-L89 ) as well as add a check to see if friendly name is specified and show that as well?

**Comment by KasperLK** [comment]
I will give it a go, if I can get a local instance of Exceptionless running.

**Comment by KasperLK** [comment]
I tried to follow the Getting Started guide for the Exceptionless solution, but when I start the Exceptionless.Api project I get this exception in the console.
![mongodb](https://cloud.githubusercontent.com/assets/11861088/7100682/f623dbaa-e02f-11e4-8f65-67f79fcce8df.png)

**Comment by niemyjski** [comment]
Nice find can you please create a new issue for that. It's because  we assume 7zip is installed. As a temp workaround can you install 7zip.

**Comment by KasperLK** [comment]
I had 7-Zip installed but my installation did not set the PATH Enviromental variable.
I got it working, but I think the Getting Started guide should be a little more specific, and maby a note about when the backend servers are running. At first I thought it was running when I say the "Reading web response" overlay.

Requirements:
- Java
- 7-Zip
- Set JAVA_HOME variable
  ex: https://confluence.atlassian.com/display/DOC/Setting+the+JAVA_HOME+Variable+in+Windows
- Set 7-Zip PATH Environmental variable
  ex: http://www.pythoncentral.io/add-python-to-path-python-is-not-recognized-as-an-internal-or-external-command/

**Comment by KasperLK** [comment]
Hmm... I just watched the video in the Getting Started guide. I only get the Mongo cmd window.

**Comment by KasperLK** [comment]
I'm having problems with the Exceptionless.UI.
I got Node.js installed, and figured out that the npm commands should be run from the Exceptionless.UI\src folder in the Node.js command prompt, and that Git seems to be required to run the npm install command, but I still get this error.
![npm](https://cloud.githubusercontent.com/assets/11861088/7101517/40498a68-e05d-11e4-89c8-90de88bba059.png)

I installed Git with the "Use Git from the Windows command prompt" option.

**Comment by KasperLK** [comment]
I have tried to fix this, but I have not been able to get the Exceptionless.UI project running, so I'm not sure if it works.

**Comment by niemyjski** [comment]
Thanks for posting the screenshots. I have some work to do on the setup docs and will create a new virtual machine to see the exact steps and prereqs needed. You shouldn't need git for any of this (I thought npm just used http).

Where you able to get this working? As far as setup docs go.. I think our powershell scripts for start db servers should use built in windows decompression and set the java home for you (I think when you do it in powershell it sets it only for the current session. Thoughts?

**Comment by KasperLK** [comment]
No. I'm still stuck at this step.
If you could drop the dependence on Java to, that would be great. Good I hate to have Java installed on my machine :)

**Comment by KasperLK** [comment]
I also tried using "Node.js Tools for Visual Studio" but ran into some problem with path that were over 260 character long (Visual Studio can't handle that), so that didn't work either.

What editor do you use for the UI project? The editing experience of node in Visual Studio is awful, compared to what I'm used to in Visual Studio.

**Comment by niemyjski** [comment]
As much as I hate java (and have two years of java experience) we won't be getting rid of it because elasticsearch is built on top of it :(. 

[I agree with you](http://blakeniemyjski.com/programming/the-best-javascript-ide/), that's why we use [WebStorm](https://www.jetbrains.com/webstorm/) but you could use any text editor like atom. 

I created a new issue here: https://github.com/exceptionless/Exceptionless.UI/issues/23 for getting started issues. I'd like to meet up with you and get these issues resolved. Also, I've merged your pull request :).

**Comment by niemyjski** [comment]
We will be deploying the fix later today along with another bug fix.

**Comment by niemyjski** [comment]
This fix has been deployed.
