### ISSUE TITLE
"Extended Data" capital splitting from AddObject

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#85]
A properti named OrderID is split into Order_i_d on the Extended Data page. Should be Order_id, or not split at all.
OrderId is split correct into Order_id.

**Comment by niemyjski** [comment]
I'm closing this issue as it's a duplicate here: https://github.com/exceptionless/Exceptionless.Net/issues/2 There currently is a pull request with tests out there that needs testing.
