### ISSUE TITLE
can't get real clinet ip

### ISSUE THREAD

**Issue by NPUlrk** [exceptionless/Exceptionless#850]
I set ServerUrl to the IP address of the application load balancer. However, the IP address obtained on the exceptionless UI is the IP address of the load balancer instead of the actual client IP address. What can I do?

**Comment by NPUlrk** [comment]
![image](https://user-images.githubusercontent.com/21106497/108318526-eef92480-71fa-11eb-895a-42a6a6726656.png)

**Comment by niemyjski** [comment]
Are you running the latest version of the server and client and ensure the x-forward-for headers are configured properly on your lb?

**Comment by NPUlrk** [comment]
> Are you running the latest version of the server and client and ensure the x-forward-for headers are configured properly on your lb?

I use latest version of the server and client. The x-real-ip header instead of X-Forwarded-For header is added to the backend load balancer.

**Comment by ejsmith** [comment]
@NPUlrk I've never heard of the ` x-real-ip` header. I don't believe it is commonly used and I know that the middleware we are using from ASP.NET Core does not support that header.

**Comment by NPUlrk** [comment]
> @NPUlrk I've never heard of the ` x-real-ip` header. I don't believe it is commonly used and I know that the middleware we are using from ASP.NET Core does not support that header.

After log the LB request header info, I find that load balancer owner's feedback is incorrect. The request header contains the X-Forwarded-For information, but it is strange that the second IP address rather than the first IP address is obtained.

![image](https://user-images.githubusercontent.com/21106497/108453487-8a46d400-72a5-11eb-95ae-7168af6ffa4d.png)

**Comment by NPUlrk** [comment]
Refer to [other answers](https://www.cnblogs.com/xuhongfei/p/13533062.html), I added a middleware to obtain the real IP address, It works.
```csharp
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.Net;
namespace Exceptionless.Web.Utility.Handlers {
    public class RealIpMiddleware {
        private readonly RequestDelegate _next;

        public RealIpMiddleware(RequestDelegate next) {
            _next = next;
        }

        public Task Invoke(HttpContext context) {
            var headers = context.Request.Headers;
            if (headers.ContainsKey("X-Forwarded-For")) {
                context.Connection.RemoteIpAddress = IPAddress.Parse(headers["X-Forwarded-For"].ToString().Split(',', StringSplitOptions.RemoveEmptyEntries)[0]);
            }
            if (headers.ContainsKey("X-Real-IP")) {
                context.Connection.RemoteIpAddress = IPAddress.Parse(headers["X-Real-IP"].ToString());
            }
            return _next(context);
        }
    }
}
```
