### ISSUE TITLE
Email Notification Issue for Stacks marked as fixed

### ISSUE THREAD

**Issue by StefanKoell** [exceptionless/Exceptionless#852]
Running docker images to 7.0.9 / 3.0.12:

When I mark a stack "Future occurrences are critical" and also mark it as fixed, I still get emails notifications

It used to behave differently: I didn't get any emails until a regression occurs.

Regards,
Stefan

**Comment by niemyjski** [comment]
@ejsmith is there any reason why fixed wasn't put in here: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Models/Stack.cs#L118
