### ISSUE TITLE
/api/v2/auth/signup，login or sign up,post 405

### ISSUE THREAD

**Issue by wangkunGitHub** [exceptionless/Exceptionless#855]
best regards

**Comment by wangkunGitHub** [comment]
centos7.4 ,  docker, exceptionless7.10.0

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us, were going to need way more information than just this. What do the logs say,?Are the health and ready endpoints returning success? What is the full response look like.

**Comment by samchenws** [comment]
I have had this problem, too
![image](https://user-images.githubusercontent.com/37535153/117534544-6f723900-b024-11eb-8915-c1ec444e01f7.png)

**Comment by niemyjski** [comment]
Can you please show off the response content?

**Comment by samchenws** [comment]
> 你能炫耀回答内容吗？
![image](https://user-images.githubusercontent.com/37535153/117592094-d9482b00-b169-11eb-83fd-22bc833e36cb.png)

![image](https://user-images.githubusercontent.com/37535153/117592085-cafa0f00-b169-11eb-864f-ebf671110596.png)
no response

**Comment by niemyjski** [comment]
It looks like there is a CORS issue with your browser. Are they on the same domain?

**Comment by niemyjski** [comment]
It looks like there is a CORS issue with your browser. Are they on the same domain?
