### ISSUE TITLE
Azure Exceptionless error

### ISSUE THREAD

**Issue by liguob666** [exceptionless/Exceptionless#859]
我对docker和Linux都不是非常熟悉，但是我想在Azure中通过ubuntu的 docker部署exceptionless, 我找到了如下的教程文档： https://exceptionless.com/news/2020/2020-11-11-self-hosted-error-monitoring-on-azure/

但是最后始终报错，无法正常运行起来，有人可以帮我吗？报错好像就是elasticsearch 的错误，elasticsearch的状态始终是不健康的，后面把界面UI折腾出来了，可以访问，可以注册，可以登陆，界面都一切正常，就是无法通过提供的api采集到日志，日志无法写入，应该是elasticsearch 有问题。 我的步骤都是按照文档来的，最后就是无法成功！另外我看很多人使用的是中文的界面，怎么设置界面中文呢

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us, can you please translate your message into English using Google Translate so we can help you better?

**Comment by liguob666** [comment]
> Hello,
> 
> Thanks for reaching out to us, can you please translate your message into English using Google Translate so we can help you better?


Hello!  Thank you reply，

I read your document。
https://exceptionless.com/news/2020/2020-11-11-self-hosted-error-monitoring-on-azure/

I followed the steps in the documentation, but it didn’t run successfully。
The error is shown in the attached screenshot。
![微信截图_20210317174132](https://user-images.githubusercontent.com/47095363/111448021-ff90b200-8748-11eb-8ed5-fe40a4b80d0c.png)

This error indicates insufficient permissions. I resolved the permission error in the test 2 days ago.

Finally, it can even be up and running, can access the interface, log in, register, etc. normally, but cannot collect logs. This error indicates that Elasticsearch is unhealthy. Do I need to install Elasticsearch separately first?
I have seen some people in mainland China use Chinese interface, how to set the language?

**Comment by liguob666** [comment]
I completed the deployment again, the address is:
http://13.76.196.81:5000/

http://13.76.196.81:9200/

This time I completed the separate installation of Elasticsearch,

But my Exceptionless still cannot collect logs normally
@jaddington

**Comment by niemyjski** [comment]
Hello,

How did you fix the permissions issue? Looks like we have an issue with our docker container and the front end config not being found. For Elasticsearch can you exec in and `curl -X GET "localhost:9200/_cluster/health?pretty"`

**Comment by liguob666** [comment]
Hello,

http://13.76.196.81:5000/type/log/frequent

http://13.76.196.81:9200/


Currently, both can be accessed normally, but logs cannot be collected successfully


I don’t know enough about Docker, I will continue to learn about Docker, and then learn Exceptionless

**Comment by niemyjski** [comment]
Please make sure you secure your Elasticsearch instance so it's not publicly accessible. I just noticed that our docs doesn't have this wiki content can you try enabling debug logging and look at the logs https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting

**Comment by liguob666** [comment]
Hello there!
I can successfully deploy through docker-compose, but I cannot access the API, nor can I register and log in. Is the api description missing in the docker-compnse.yml file?

![微信图片_20210413185148](https://user-images.githubusercontent.com/47095363/114541524-68f0db80-9c89-11eb-8c78-5f69d3e72763.png)

I deployed on this IP address:
http://52.139.231.233:5100/signup

http://52.139.231.233:5601/

Other services seem to be running normally, but it seems that port 5000 cannot be accessed because there is no "application".
Please help me to see!

**Comment by liguob666** [comment]
I downloaded the latest version directly on github, the address:
https://github.com/exceptionless/Exceptionless/archive/refs/tags/v7.0.9.tar.gz

**Comment by niemyjski** [comment]
Hello,

You are missing the docker-compose section for the api and jobs. **Also as stated numerous times before: please secure your elastic instance it should not be publicly accessible.**

**Comment by liguob666** [comment]
Hello,

Can I get the complete configuration there? Where can I get a complete docker-compose.yml

**Comment by niemyjski** [comment]
This is our recommended way to host with docker: https://exceptionless.com/docs/self-hosting/docker/ Here is our samples configs with a docker-compose example: https://github.com/exceptionless/Exceptionless/tree/master/samples

**Comment by liguob666** [comment]
I deployed successfully, everything can run, this project is very good, very good, can solve many, many problems. But I cannot change the language. I want to change Chinese. I found that there is too little documentation on Self Hosting.
I don't know the administrator account. I don't know where my data is stored, how to backup or migrate it. I also need to learn more about Exceptionless.

**Comment by niemyjski** [comment]
Awesome! There is no language support for the backend and the front end will automatically change the language if it detects `zh-cn` as the local: https://github.com/exceptionless/Exceptionless.UI/blob/master/src/app.js#L70-L81 How would you suggest we improve the self hosting documentation?

**Comment by niemyjski** [comment]
Is it also safe to close this issue?
