### ISSUE TITLE
Clean up expired logs

### ISSUE THREAD

**Issue by knowyi** [exceptionless/Exceptionless#860]
I want to keep the log for a while. For example, logs are kept for 30 days. I don't know if this setting is currently supported

**Comment by niemyjski** [comment]
Thanks for reaching out to us. What do you mean by logs? Do you mean log events? You can configure index retention via EX_MaximumRetentionDays setting which will cause data to be cleaned up and indexes to be dropped after XX days. 

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/AppOptions.cs#L55

**Comment by niemyjski** [comment]
Please let us know if setting this setting doesn't work for you and we can reopen and dig into this further.
