### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#87]
It would be great to have the ability to send information to a Slack channel when an event occurs.
It should be configure on project level, like the Web Hook integration.

The picture is from the Bugsnag configuration in Slack. Looks like they just uses the Slack Webhook.

![untitled](https://cloud.githubusercontent.com/assets/11861088/7061148/14f468cc-de8e-11e4-9c7d-3dc642bfc800.jpg)

This is the Slack setup instructions for a Webhook.
![setup1](https://cloud.githubusercontent.com/assets/11861088/7061205/eb99f5fe-de8e-11e4-8180-f6869b35ce42.jpg)
![setup2](https://cloud.githubusercontent.com/assets/11861088/7061209/ee193218-de8e-11e4-9d16-3e2ac59ff850.jpg)
![setup3](https://cloud.githubusercontent.com/assets/11861088/7061224/0d0ee17c-de8f-11e4-8598-994727371105.jpg)
![setup4](https://cloud.githubusercontent.com/assets/11861088/7061235/467634ba-de8f-11e4-91fb-13f021e1145e.jpg)
![setup5](https://cloud.githubusercontent.com/assets/11861088/7061253/7459e5de-de8f-11e4-81bb-4f30b26c53dc.jpg)

**Comment by niemyjski** [comment]
+1

**Comment by KasperLK** [comment]
Setup an Incoming WebHook in Slack.
Use the Webhook URL from Slack in the web.config

https://gist.github.com/a045a02611900f4db7d3.git

![image](https://cloud.githubusercontent.com/assets/11861088/8777513/ad9f3560-2ef8-11e5-8bd0-72011eb52827.png)

**Comment by niemyjski** [comment]
I'm closing this as it's now merged into 177.
