### ISSUE TITLE
How to add additional data in ExceptionLess

### ISSUE THREAD

**Issue by landonzeng** [exceptionless/Exceptionless#870]
How to add additional data in the Event of exceptionLess, for example: UserId: 123456, so that we can troubleshoot errors faster,Thanks!

**Comment by niemyjski** [comment]
Here's how you set default data and tags for every event: https://exceptionless.com/docs/clients/dotnet/settings/#adding-static-extended-data-values-with-every-report

**If you are using a non web app (single tenancy) keep reading:**

If you want to set the default user for all events:
```cs
ExceptionlessClient.Default.Configuration.SetUserIdentity(identity, name)
```

If you want to take user tracking further and get session stats (e.g., how long they used a feature) you could call:
```cs
ExceptionlessClient.Default.Configuration.UseSessions(); // call before calling startup/register
ExceptionlessClient.Default.Startup(); // if using the core client or call Register() for WinForms/WPF as described in the readme
```

**Comment by niemyjski** [comment]
Please let us know if you have any questions.
