### ISSUE TITLE
I can't run the project

### ISSUE THREAD

**Issue by liguob666** [exceptionless/Exceptionless#878]
https://github.com/exceptionless/Exceptionless

I can’t run the project, I pulled the master branch, I installed VS2017 and .net 5.0 locally, as well as the latest version of .net core
I cannot load Exceptionless.Job
Exceptionless.Tests
Exceptionless.Web
These three projects cannot be loaded, I want to run the project;

I don’t know what components are missing. Do I have to install redis and elasticsearch to run?

**Comment by niemyjski** [comment]
Are there any errors in the Visual Studio output window when you try and load the projects?

**Comment by liguob666** [comment]
No valid prompt is given, but the project cannot be loaded, and no specific reason is given

**Comment by ejsmith** [comment]
You probably need a newer version of Visual Studio than VS2017. Try downloading from here: https://visualstudio.microsoft.com/downloads/

**Comment by liguob666** [comment]
I have checked the documentation, and according to the documentation, errors always occur, and in the end there is no way to start deploying with docker-compose.
I would like to ask, are user data and logs collected by the system stored in ES? I have been using sql srver before, I think there should be a user table, such as userTable, I want to find user information

**Comment by liguob666** [comment]
No, I downloaded vs2019, still the same problem, the following is my screenshot

**Comment by niemyjski** [comment]
@liguob666 do you get a specific error when you try to open the solution? Can you check your VS Output window?

Yes data is stored in ES. You can find it by looking in Kibana Dev Tools and run `GET users-v1/_search`.

**Comment by niemyjski** [comment]
I'm closing this but let me know if this is still an issue and we can reopen if needed.
