### ISSUE TITLE
Dynamic log levels controlled via client configuration

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#88]
Option to use "Client Configuration" value in NLog.config file.
Could be used for "minlevel" on the logger rule.

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
Issue moved to [exceptionless/Exceptionless.Net #84](https://github.com/exceptionless/Exceptionless.Net/issues/84) via [**ZenHub.io**](https://www.zenhub.io/)
