### ISSUE TITLE
Recover projects and elasticseach data

### ISSUE THREAD

**Issue by rushfrisby** [exceptionless/Exceptionless#887]
I am self hosting and had something go wrong with elasticsearch. I had to run `service remove` and `service install` to get it working again but now when I open exceptionless it shows nothing. Is there a way to recover the projects and data?

**Comment by niemyjski** [comment]
What version of Exceptionless are you using and how did you install? You'd need to restore from an Elasticsearch snapshot: https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html Does this help?

**Comment by rushfrisby** [comment]
I think the data is there it's just timing out or something. I know for a fact there should be stuff show here...

![image](https://user-images.githubusercontent.com/574729/116583235-23b4e680-a8e4-11eb-8d16-50186395bcad.png)

I am running version  2.4.836. Is there a way I can clean out old data to speed things up possibly?

**Comment by niemyjski** [comment]
I'd dig into the data with kibana and from there you could see how much data you have and remove old indices that way as well. You could also set the MaximumRetentionDays setting and let it get cleaned up when the Cleanup job runs:  https://github.com/exceptionless/Exceptionless/blob/0237d99184fbcc3b2b339a17cc9b471ea689f560/src/Exceptionless.Core/Jobs/CleanupDataJob.cs#L180

**Comment by niemyjski** [comment]
Did setting the `MaximumRetentionDays` resolve this for you? I'm closing this but let me know if this is still an issue and we can reopen if needed
