### ISSUE TITLE
Promote to Visual Studio Online

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#89]
Setup options:
- Select VSO Project to promote to

Promote options:
- Create new work item
- Link to existing work item (enter work item ID in textbox)

A link to the new VSO work item, somewhere in the UI would be great.
The new VSO work item should include a link to the Exceptionless event in the description.

**Comment by KasperLK** [comment]
Setup options:
- Select VSO Project to promote to

Promote options:
- Create new work item
- Link to existing work item (enter work item ID in textbox)

**Comment by niemyjski** [comment]
This would be a really nice first class feature. However, you should be able to do all of this today using zapier ( https://zapier.com/zapbook/visual-studio-online/ ).

**Comment by niemyjski** [comment]
Do you have any code for this that you may have implemented?

**Comment by adamzolotarev** [comment]
It would be great if you had built-in integration with TFS (not just Visual Studio Online). My company doesn't want to use VSO, but we want an integration with our TFS.
Say, if there is a certain number of exceptions, then create a TFS work item automatically. If the exceptions stop happening, then cancel it. Something along these lines. 
Or, maybe a button to create/cancel a WI in TFS from Exceptionless UI.
Thanks!

**Comment by KasperLK** [comment]
I only have for VSO, and it is still work in progress.

**Comment by niemyjski** [comment]
We need to think of a good way to update the notifications / actions dialogs for choosing what happens when an event comes in or something gets promoted.

I guess when something gets promoted you'd do the web hooks and the tfs/vso config too. But where would this be defined that makes sense? Under the integrations tab?

**Comment by niemyjski** [comment]
@adamzolotarev @KasperLK do you think zapier integration is a workable solution? Were you able to create a webhook that did this? Would you mind sharing this code?

**Comment by adamzolotarev** [comment]
I just used a webhook and wrote my own code to connect to tfs server, create a work item, and then post that tfs work item url link back to Exceptionless. 

So, you could use a web api to accept a post from Exceptionless on new stack created; create tfs work item, and post it back. Here's a template:

 ```cs
[AcceptVerbs("POST")]		
		public async Task<IHttpActionResult> Tfs(StackViewModel stackViewModel)
		{
			var workItemId = CreateTfsWorkItem(stackViewModel);
			var tfsUrl = "link to tfs work item" + workItemId;
			UpdateStackReferenceLink(stackViewModel, tfsUrl);
			
			return Ok();
		}
	
		private int CreateTfsWorkItem(StackViewModel model)
		{
			var projectCollection = new TfsTeamProjectCollection(new Uri("your tfs url"));
			var workItemStore = projectCollection.GetService<WorkItemStore>();
			var teamProject = workItemStore.Projects["your project"];
			var workItemType = teamProject.WorkItemTypes["Work Item"];

			var userStory = new WorkItem(workItemType)
			{
				Title = "Title",
				Description = "Descriptiohn"				
			};
			
			userStory.Save();

			return userStory.Id;
		}
		
		private void UpdateStackReferenceLink(StackViewModel model, string tfsLink)
		{
			var exceptionlessPostUrl = "url to exceptionless to add a link";
			var httpWebRequest = (HttpWebRequest) WebRequest.Create(url);
			httpWebRequest.ContentType = "text/json";
			httpWebRequest.Method = method;

			using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
			{
				streamWriter.Write(tfsLink);
				streamWriter.Flush();
				streamWriter.Close();
			}

			var httpResponse = (HttpWebResponse) httpWebRequest.GetResponse();
			using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
			{
				return streamReader.ReadToEnd();
			}
		}
 ```

**Comment by niemyjski** [comment]
Thanks for that

**Comment by niemyjski** [comment]
I'm going to close this for the time being, it would be nice to support this first class and if anyone wants to submit a pr we would be willing to accept it. I also think you can do this today with a Zapier integration.
