### ISSUE TITLE
Mention need to escape SMTP password in documentation

### ISSUE THREAD

**Issue by matthias-schuchardt** [exceptionless/Exceptionless#893]
When self-hosting Exceptionless, one needs to use [percent-encode](https://en.wikipedia.org/wiki/Percent-encoding) the SMTP-password. Since this is not obvious at the first glance, would you mind adding a short note to the [setup documentation](https://exceptionless.com/docs/self-hosting/docker/#simple-setup-wssl-support-and-smtp)? This might save your users a few hours and you guys a [few tickets](https://github.com/exceptionless/Exceptionless/issues/820).

**Comment by ejsmith** [comment]
@matthias-schuchardt thank you for pointing this out. Any chance you can submit a PR for this change?

https://github.com/exceptionless/Website/tree/master/content/docs/self-hosting

It would be greatly appreciated.

**Comment by matthias-schuchardt** [comment]
I just realized that your website is also hosted on GitHub and opened an [issue for the website](https://github.com/exceptionless/Website/issues/28) instead. Sorry for the spam.

**Comment by matthias-schuchardt** [comment]
> @matthias-schuchardt thank you for pointing this out. Any chance you can submit a PR for this change?
> 
> https://github.com/exceptionless/Website/tree/master/content/docs/self-hosting
> 
> It would be greatly appreciated.

Can do :)
