### ISSUE TITLE
Send mail error

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#894]
error: Job run MailMessageJob failed: mail from address must be same as authorization user 
The configuration is as follows:
  Email: 'smtps://xxxx%40qq.com:pwd@smtp.exmail.qq.com:465'

**Comment by ysq5202121** [comment]
The same user name and password login third software can send mail

**Comment by niemyjski** [comment]
Sounds like you also need to change the `SmtpFrom` to match your user: https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/EmailOptions.cs#L53 Please let us know if you have any questions.
