### ISSUE TITLE
How to release the throttling control of API request?

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#895]
![企业微信截图_20210522111019](https://user-images.githubusercontent.com/8586973/119212976-87e75680-baee-11eb-98fd-1c5d5ed186a5.png)
![image](https://user-images.githubusercontent.com/8586973/119213535-4fe21280-baf2-11eb-8756-f97036e2f970.png)

System prompt: the current system controls the throttling of API requests for these organizations
How to remove the throttling control of API request? Thank you very much.

**Comment by ysq5202121** [comment]
ApiThrottleLimit: '30000000' #'最大APi事件数量'
MaximumRetentionDays: '30' #30天清理日志

**Comment by ysq5202121** [comment]
ApiThrottleLimit  Is it the sum of a day or a month？

**Comment by niemyjski** [comment]
Hello,

It's for a 15 minute period: https://github.com/exceptionless/Exceptionless/blob/07be79eb9f15b65b1ea512e0a0971d994f595b70/src/Exceptionless.Web/Startup.cs#L137-L138 You can remove throttling by setting it to -1.
