### ISSUE TITLE
如何解决查询慢的问题

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#896]
![image](https://user-images.githubusercontent.com/8586973/119291462-0bd14800-bc81-11eb-97c1-9467859df69a.png)
The above statistics need 5-10 seconds to come out, how to optimize, thank you

**Comment by niemyjski** [comment]
I'd start by looking at how long your elasticsearch queries are taking, and the overall usage of your elasticsearch cluster. Also, are you running the latest version?

**Comment by ysq5202121** [comment]
![image](https://user-images.githubusercontent.com/8586973/119430178-e3118700-bd42-11eb-8744-fb1e298e155e.png)
![image](https://user-images.githubusercontent.com/8586973/119430399-4bf8ff00-bd43-11eb-9f77-c58ef1d89be6.png)

Due to the limitation of conditions, SSD cannot be used

**Comment by ysq5202121** [comment]
Using the latest version of the program

**Comment by niemyjski** [comment]
You are logging millions of events and Elasticsearch will have read across many indices and will be limited by disk IO. You could try reducing your date range filter to a day or two and select a specific event type (e.g., logs or errors) that you are viewing to reduce the large amount indices... but it's still a large amount of IO. We highly recommend using NVME or SSD backed storage.

**Comment by ysq5202121** [comment]
Is there no other way?

**Comment by niemyjski** [comment]
What are your machine specs for each of your nodes? How are you hosting Exceptionless?

**Comment by ysq5202121** [comment]
Hello, so far it is just a node with a data volume of several hundred million. It is found that the query speed is very slow, but it is a pity that SSD cannot be applied

**Comment by niemyjski** [comment]
:\, I'm going to close this as I don't think there is very much we can do in this scenario as we recommend multiple nodes running NVME/SSD's / lots of memory as elastic is very IO Intensive. The only other thing would be to limit your queries by date range so there is less disk reads but it's still going to be slow.
