### ISSUE TITLE
Add XML comments to the most importent methods

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#90]

**Comment by niemyjski** [comment]
What methods need xml comments? They should be on most of them? Would you mind submitting a pull request for these here: https://github.com/exceptionless/Exceptionless.net ?

**Comment by KasperLK** [comment]
Weird. I have not seen it on any method yet.
![xmlcomment](https://cloud.githubusercontent.com/assets/11861088/7067868/aa109300-dece-11e4-9cc8-20b18da4c49a.png)

I'm a GitHub noob. What does a pull request do?

**Comment by niemyjski** [comment]
There is xml documentation for that ( https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/ExceptionlessClient.cs#L48-L55 ). I wonder why it's not showing. What package are you using? Can you right click on the reference in solution explorer and navigate to assemblies folder. Is there an xml document for the assembly?

A [pull request](https://github.com/exceptionless/Exceptionless/blob/master/CONTRIBUTING.md) is another way of saying a patch. You create a fork (personally copy of the repo), download it with the client, then make the changes to the source, commit and sync the changes, then click create pull request and then we can accept your changes.

**Comment by KasperLK** [comment]
There is an xml fil efor Exceptionless, but it has no documentation.

<?xml version="1.0"?>
<doc>
    <assembly>
        <name>Exceptionless</name>
    </assembly>
    <members>
    </members>
</doc>

The Exceptionless.Extras.xml hase some documentation.
I'm using version 3.0.1300 from NuGet.


I will take a look at the pull thing later.

**Comment by KasperLK** [comment]
About the pull request. What is it that you want me to change?
To me it looks like the xml files in the latest NuGet package is missing the comments.
Expressionles.NLog.xml is also empty.

**Comment by niemyjski** [comment]
I'll take a look. I was just asking about a pull request for any missing documentation (methods / properties) that were missing. But this sounds like an issue with our package.

**Comment by niemyjski** [comment]
I've fixed this in the following build: https://github.com/exceptionless/Exceptionless.Net/commit/10daec14cad63a1ecc7be2b191ed01af2c20036c It will be fixed the next time we deploy.

**Comment by niemyjski** [comment]
I was going to deploy this fix but it appears that symbol source is down so I'm going to wait until it is up and running. https://ci.appveyor.com/project/Exceptionless/exceptionless-net/deployment/77574

I'm going to close this issue. Please let us know if you have any questions or need any help figuring out the api.

**Comment by niemyjski** [comment]
It's backup, these changes will be deployed shortly.
