### ISSUE TITLE
Add Visual Studio SmartTag support

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#91]
Visual Studio SmartTag support for using directive for missing namespace would be great.

**Comment by KasperLK** [comment]
Looks like it was only on an extension method it didn't work.

**Comment by niemyjski** [comment]
What do you mean by smart tags?

**Comment by KasperLK** [comment]
I believe that MS calls this a SmartTag.

![smarttag](https://cloud.githubusercontent.com/assets/11861088/7067746/0763d522-dece-11e4-80d9-0c14db48f104.jpg)

**Comment by niemyjski** [comment]
I've always called them / heard them called namespace imports, which are also required for extension methods.

**Comment by KasperLK** [comment]
Okay.
I can't get them working on the Critical extension to NLogs Exception method.

**Comment by niemyjski** [comment]
Are you seeing an error? Do you have the Exceptionless.NLog namespace imported?

**Comment by KasperLK** [comment]
It works fine if i manually type in the namespace. I would bust like it to work with the "SmartTag", but I don't think extension methods can do that.

Sent from my Windows Phone
________________________________

**Comment by niemyjski** [comment]
Resharper will automatically ask you to import the namespace for extension methods.
