### ISSUE TITLE
How to clean up the expired data of ES database regularly？

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#919]
Hello, does the program come with cleaning up expired data?

**Comment by niemyjski** [comment]
This is a duplicate of https://github.com/exceptionless/Exceptionless/issues/592#issuecomment-619183269 

You can configure Exceptionless to remove old event indices by setting an environment variable `EX_MaximumRetentionDays` to `7`. 

https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/AppOptions.cs#L53

Please let us know if you have any questions.
