### ISSUE TITLE
Why limit message size

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#927]
![image](https://user-images.githubusercontent.com/8586973/126030998-692c5a70-338b-4c81-9934-f71471e02fd1.png)
More than 2000 cannot be displayed

**Comment by ejsmith** [comment]
I think it probably had to do with massive messages coming in and breaking the site.

**Comment by niemyjski** [comment]
Thanks for reaching out to us. We limit message size for several reasons:

1. It's much harder to display really long messages in emails, email subjects and in the app. 
2. We index the message for search and don't want thousands of tokens created and super long fields (yes, we can limit this amount in index settings).
3. Super long content belongs in extended data where it can be rendered fully. Just call SetProperty(name, value) with the content.

**Comment by ysq5202121** [comment]
tks
