### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#935]
![image](https://user-images.githubusercontent.com/8586973/127833596-50252a60-2f18-4a3e-9bd8-58826e62d03b.png)
error

**Comment by niemyjski** [comment]
What does the response message say? It's a 400 so it should have a message. Also the API container logs should show additional information.

**Comment by ysq5202121** [comment]
> 响应消息消息？这是一条 400 所以它应该有一条消息。此外，API 容器日志应显示其他信息。

![image](https://user-images.githubusercontent.com/8586973/127946540-cb8e1b5e-0a6b-447d-bb21-d1ac5cc8fd6a.png)

**Comment by niemyjski** [comment]
I'm unable to read your question, can you please post in English if possible. Looking at the stack trace this can happen if there a massive amount of resolved stacks for the current filter like you are looking at all events across all projects which appears to be the case. How many stack documents do you have?

**Comment by ysq5202121** [comment]
Very few

**Comment by niemyjski** [comment]
Can you tell me how many stack documents you have in your Elasticsearch index?

**Comment by ysq5202121** [comment]
![image](https://user-images.githubusercontent.com/8586973/128116478-1bce6649-127e-4b45-bc8a-6d231a11c70f.png)

**Comment by ysq5202121** [comment]
![image](https://user-images.githubusercontent.com/8586973/128116520-befbbf8a-8e02-4e2c-90d1-9a94c349652a.png)

**Comment by ysq5202121** [comment]
I reinitialized the data. It seems normal, but I don't know why it was like this before

**Comment by CoderRiker** [comment]
> > 响应消息消息？这是一条 400 所以它应该有一条消息。此外，API 容器日志应显示其他信息。
> 
> ![image](https://user-images.githubusercontent.com/8586973/127946540-cb8e1b5e-0a6b-447d-bb21-d1ac5cc8fd6a.png)

好家伙，终于看到国人了。哈哈，这玩意国内教程少得可怜。。

**Comment by niemyjski** [comment]
Can you please post all replies in English or use a translator. From your stack trace, we are working on improving the search experience in the latest nightly builds.

**Comment by niemyjski** [comment]
Please try out the 7.1.0 release and leave a comment with your findings and also make sure you run the CleanupData job :).
