### ISSUE TITLE
Getting Started Issues

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#94]
List out the requirements for doing local dev:

* Install Node JS

We should also run through the setup on a fresh vm and check for issues as [one user ran into the following issue](https://github.com/exceptionless/Exceptionless/issues/84): 
![image](https://cloud.githubusercontent.com/assets/1020579/7120905/4671b382-e1d6-11e4-8c9e-acd11fb08b39.png). We may want to specify that if you are on windows, than you should be putting it at the root of the drive because of the file path limitation.

**Comment by KasperLK** [comment]
I'm not sure if it's problem in Windows. But when I tried using "Node.js Tools for Visual Studio" I got a warning about the 260 character path from Visual Studio.
I tried moving the Exceptionless.UI to the root, and I even tried renaming Exceptionless.UI to E, but Visual Studio still complained.
