### ISSUE TITLE
What is the format of this email sending configuration? has any qqemail example?

### ISSUE THREAD

**Issue by CoderRiker** [exceptionless/Exceptionless#944]
![d5c3101949b507df9fa2917dd2889f7](https://user-images.githubusercontent.com/88869889/129339470-2dc168ba-f659-46c1-bc06-3a8abd6c0c86.png)

**Comment by CoderRiker** [comment]
![image](https://user-images.githubusercontent.com/88869889/129339597-2999b427-17dd-4b64-8143-c449f3783fe7.png)
that's my configurations

**Comment by CoderRiker** [comment]
![a8347e1766dc805932b9b632fa6dbb8](https://user-images.githubusercontent.com/88869889/129339964-37b47e6f-b45a-4bbd-ba80-9f4ae96a569d.png)
That's my configuration

**Comment by niemyjski** [comment]
That looks right to me for the email configuration, the error message says it's failing because the mail address must match the authorized user. I think you also need to be setting the `SmtpFrom` configuration setting.

**Comment by CoderRiker** [comment]
Thank you very much. I can send and receive emails, but there is still a problem. After I click the verify button, I will be redirected to the api page, but nothing is reflected. I used postman to request this path, and it shows 200 ok, but this api page is returned, and there is no change in the account status

**Comment by CoderRiker** [comment]
![(B7)Y~_N8X)R 0EQA_FJEAR](https://user-images.githubusercontent.com/88869889/129366661-ace9dbb4-f5c6-4813-b327-668f7e90823a.png)

**Comment by niemyjski** [comment]
As stated in the documentation you'll need to set the `BaseURL` to to the url of the front end.

**Comment by CoderRiker** [comment]
Thank you very much, my problem has been solved

**Comment by shamork** [comment]
@CoderRiker 
To helper others, can you write an example for setting SmtpFrom/BaseUrl?

**Comment by CoderRiker** [comment]
> @CoderRiker
> To helper others, can you write an example for setting SmtpFrom/BaseUrl?

![image](https://user-images.githubusercontent.com/88869889/130039737-636470e6-cc68-42e4-afc4-551c6e6ee9e5.png)

**Comment by CoderRiker** [comment]
> @CoderRiker
> To helper others, can you write an example for setting SmtpFrom/BaseUrl?

![image](https://user-images.githubusercontent.com/88869889/130040268-b720b744-caac-4dcf-9e0c-243844a887ed.png)

you can change default option about SmtpFrom configuration

**Comment by CoderRiker** [comment]
> @CoderRiker
> To helper others, can you write an example for setting SmtpFrom/BaseUrl?

![image](https://user-images.githubusercontent.com/88869889/130040591-b1218993-5312-490c-89ea-51bd346813b5.png)
you can change default SmtpFrom configuration

**Comment by niemyjski** [comment]
We'll also be updating our documentation and requiring setting SmtpFrom going forward.
