### ISSUE TITLE
Edit api key for project

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless#95]
This doesn't seem possible as adding a new key automatically generates a new one. It would be very useful if you could also edit the api key (for example, from a previous installation).

**Comment by niemyjski** [comment]
This is by design as keys are immutable. We don't allow api keys to be edited for many reasons

1. They are the uniquely indexed (think pk).
2. The tokens are used for general auth as well.
3. It can't be editable, because you might insert a duplicate / cause issues with auth (security).

**Comment by niemyjski** [comment]
This is why we prompt you with a modal when you are about to remove a key, because it cannot be undone. Did you remove an api key of a currently running project?

**Comment by Phyxion** [comment]
I understand, I asked because we wanted to migrate the 1.x clients to the new server. We'll just update everything, it doesn't matter much.

**Comment by niemyjski** [comment]
What I would do is not change anything on your mongo 1.x database (except back it up). When the 2.0 app runs it will upgrade it and migrate the api keys to the tokens controller. This way you will be able to keep your old api keys.

**Comment by Phyxion** [comment]
We couldn't get that to work with the previous build from 2.x. We have it working now so we'll just start from scratch. We already backed up some important exceptions, the rest will fill later.

**Comment by niemyjski** [comment]
Okay, If you ever want to meet up I could help you upgrade your 1.x site. However, it sounds like you are up and running!

**Comment by Phyxion** [comment]
Yeah, 2.x seems to work fine with the build you've sent over. I'm not using it at the moment as I'm waiting for the new release (hopefully with a release that also includes the UI so it's easier to manage).

**Comment by niemyjski** [comment]
If you want you can use any release from our build server. All builds are stable currently unless the build failed. We just deployed a build over the weekend with more bug fixes. I'm torn between doing a new github release right now (with all the fixes and improvements) and waiting until we have the self hosted install stuff done. Thoughts?

**Comment by Phyxion** [comment]
If you mean the points from https://github.com/exceptionless/Exceptionless/issues/77:
-1 can be added after a new release.
-2 yes please, I'm really looking forward to this. Probably not *that* much work? 
-3 not that much work as well I think and can probably be done simulateously with -2.

Why I would like -2 added is because if of all the Cross-Origin Request Blocked you get otherwise. I tried doing the usual 'fixes' for this but I still get these from time to time when I visit the UI.

All in all some more releases in between are absolutely welcome (last release is 1.5 month ago already).

**Comment by niemyjski** [comment]
I'm not sure about 2. I don't think it would, you'd just need to copy the files to the root of the website. You shouldn't get any cors errors because we are making cor requests from the ui. If we did interim releases would you do like a 2.0.1?

**Comment by Phyxion** [comment]
I already tried copying the files to the root a while ago and the UI didn't load. I also tried a subfolder with the same results. Maybe I did something wrong, I don't know.

I do get cors errors in the browser console, even with the usual fixes. I haven't had much time yet to look into this.

A few more releases would be very welcome, yes. Not like once a day of course but more than this :+1:

**Comment by niemyjski** [comment]
Okay :)

**Comment by niemyjski** [comment]
If you could comment on 77, if you get it working that would be great. We'll need to figure this out too.

**Comment by Phyxion** [comment]
I just copied everything (except from the web.config) to the root and it works. It does not work if you create a subfolder for the ui (it's just an empty page) as the index.html (and js files too) use src="/.." instead of src=".." so it tries to get the content from the root domain.

**Comment by niemyjski** [comment]
You shouldn't need anything in the web.config. It's just there for backwards compat (really old emails or  existing bookmarks)

**Comment by Phyxion** [comment]
Thanks. Does that include AngularJS rule?

**Comment by niemyjski** [comment]
Yes, you only need that if you want clean urls without the hashbang.

**Comment by Phyxion** [comment]
Great :+1:
