### ISSUE TITLE
Can you add more detailed (client) release notes?

### ISSUE THREAD

**Issue by PhilipDn** [exceptionless/Exceptionless#97]
This isn't a code issue, but i wasn't sure where to submit this request.

At the NuGet site, and also in the NuGet Package Manager in Visual Studio, there is a link for "release notes" for Exceptionless:
 http://exceptionless.io/category/versions/ 

However, this link is for more general release news and for major version information. Can you please consider providing some more detailed release notes describing the changes for each release (such as 3.0.1319, 3.0.1318, 3.0.1300, 2.0.1288, etc.)? This would be helpful when deciding whether to upgrade the client in several .NET projects to the latest version.

**Comment by niemyjski** [comment]
We should probably be linking to the github releases page instead. We've always done release notes for major and minor versions ( https://github.com/exceptionless/Exceptionless.Net/releases ) but I don't see us doing it for incremental builds because you can look at the github history. Does this work?

**Comment by niemyjski** [comment]
We try not to push revision builds unless it fixes a small bug or is an improvement. Like the last push was for an added extension method and documentation improvements.

**Comment by PhilipDn** [comment]
Sorry for not replying sooner. The link to the "releases" URL at github is definitely a better option than the current link to the "versions" category.

It would also be helpful, in addition, if the "releases" page included (even a very brief) description of released minor revision builds such as from 3.0.1318 to 3.0.,1319. Yes, I understand that I can navigate my way through all the github history in all the various Exceptionless projects to attempt to learn what has changed, but as an end-user I would just like a quick idea of whether a release fixes a security issue, adds a new feature, corrects a bug in a specific item, etc. I mainly want to be able to decide whether I need to immediately install a minor revision across all my projects, or whether I can skip this revision and wait for a future revision.
