### ISSUE TITLE
Is there a detailed description of the following configuration

### ISSUE THREAD

**Issue by ysq5202121** [exceptionless/Exceptionless#970]
ConnectionStrings:
  Elasticsearch: server=http://localhost:9200
  Cache: provider=redis;server="localhost,abortConnect=false"
  MessageBus: provider=redis;server="localhost,abortConnect=false"
  Metrics: provider=statsd;server=10.0.0.5;
  Queue: provider=redis;server="localhost,abortConnect=false"
  Storage: provider=folder;path=..\storage

I haven't seen any mention in the documentation. I still don't understand the usefulness of these configurations, whether they affect each other, and whether enabling them will have an explanatory effect

**Comment by ysq5202121** [comment]
【Storage】 will this storage never be deleted in the local path

**Comment by niemyjski** [comment]
They just control what implementations to use per specific entry (with the default being in memory implementations). Changing them only effects what you have to setup and manage and how the system scales out.

I'm not sure what you mean will this storage never be deleted in the local path?

**Comment by ejsmith** [comment]
He’s talking about the event archive folder that builds up forever. We just recently turned the archive feature off by default in the docker images. @ysq5202121 the folder can safely be deleted. We are just keeping the event archive as a form of backup for submitted events and allowing us to replay events if we need to.

**Comment by niemyjski** [comment]
We do not clean up the archive folder. We have however recently turned this off and that will go out in the next release. You can turn it off by setting `EX_EnableArchive` to false. Please let us know if you have any questions.
