### ISSUE TITLE
Show Tags in dashboard overview

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#98]
When I create a log message, I have the option to set a 'log level'. That 'log level' is shown like a tag in the dashboard overview.
I would like an option on tags to indicate whether that tag should be shown in the dahsboard overview, like the 'log level' is shown today.

![logs](https://cloud.githubusercontent.com/assets/11861088/7228958/ab68c086-e75e-11e4-9487-49d96d532b21.jpg)

**Comment by niemyjski** [comment]
What do you do if you have a lot of tags? Also, when you are on mobile layout what do you show? Currently on the stack page we show the first character with a title that has the full description. However, this doesn't work if you have multiple tags that start with the same character.

**Comment by KasperLK** [comment]
Maby it should only be possible to show one tag, or maby it should be something new, instead of an option on tags.
Color would also be a nice option.

**Comment by niemyjski** [comment]
But how do you choose to show that one tag? I think it's all or nothing and you can have an endless number of tags.

**Comment by strombringer** [comment]
A few suggestions:
- You could show the first 2-3 tags, and in case there are more, show "..." which expands the remaining tags
- Color code the tags automatically based on their full name. Maybe get the tag's name's hashcode and use that to compute RGB values for the color. Then you can show only the first n characters and the tags would still be differentiated by their color
- Provide an option to mark tags as "priority", or something like that, which makes them show up on the dashboard. Then the user can choose at what point he/she thinks the dashboard becomes too cluttered :-)

**Comment by niemyjski** [comment]
Is there any chance you can do a mockup of this so we can chat about it more? You'd just need to edit the html on the site in the dev tools.  

* I don't know how feasible it is to show an ... to expand but it's worth considering. 
* I do like using the hash for the rgb value. 
* It would be a lot of overhead to mark a tag as priority. You'd have to do a request per project / per organization. I don't see us doing this as it would really slow down the page and add a lot of overhead for little value.

**Comment by strombringer** [comment]
I'll try to make a mockup but am not sure how soon that'll be done :-).

Regarding hash as rgb value, maybe this is useful for you: I needed it for a project of mine and used the code from here: http://www.splinter.com.au/converting-hsv-to-rgb-colour-using-c/

And the conversion itself:
var name = "my tag";
int r = 255; int g = 255; int b = 255;
var hueValue = name.GetHashCode() % 300;
ColorHelper.HsvToRgb(hueValue, 0.5, 0.95, out r, out g, out b);

**Comment by KasperLK** [comment]
How about just implementing it like 'log level' is done?

**Comment by niemyjski** [comment]
@KasperLK  Log level is only ever one tag (part of extended data) and we enforce it.

**Comment by KasperLK** [comment]
One tag is enough for what I was planning to use this for.

**Comment by niemyjski** [comment]
I'll play around with this after we get the javascript client released.

**Comment by niemyjski** [comment]
@ejsmith how do you feel about this?

**Comment by ejsmith** [comment]
I think it would be nice, but it could also really clutter up the UI if there are a lot of tags. Also, if there is an unknown number of tags we would have to show them on the right side so that we don't end up with a jagged list of events on the left side.

**Comment by niemyjski** [comment]
Issue moved to [exceptionless/Exceptionless.UI #83](https://github.com/exceptionless/Exceptionless.UI/issues/83) via [**ZenHub.io**](https://www.zenhub.io/)
