### ISSUE TITLE
My local exceptionless dashboard not information 

### ISSUE THREAD

**Issue by enshishi** [exceptionless/Exceptionless#992]
I use  docker deploy exceptionless,but it dashboard not information.

**Comment by niemyjski** [comment]
Hello,

What docker image are you deploying?

**Comment by enshishi** [comment]
Yes,I Use doker to deploy。
![image](https://user-images.githubusercontent.com/3347995/140850866-3ce59ab2-4aec-4d28-9953-ef215fb6a993.png)

**Comment by niemyjski** [comment]
I'd check the network requests and see what the response says. Are they failing? What are the response messages?

**Comment by enshishi** [comment]
This is my ApiKey
![image](https://user-images.githubusercontent.com/3347995/141067859-b5bb7213-cb97-4b65-bb11-e45191b9ec7e.png)
My Code：
![image](https://user-images.githubusercontent.com/3347995/141068007-2a20f2d8-bc82-44f1-9e63-dc7f58888df6.png)
Exceptionless dashboard 
![image](https://user-images.githubusercontent.com/3347995/141068150-64ff9521-85c8-412a-b3fd-d1d137f3ef8c.png)

**Comment by niemyjski** [comment]
That information doesn't help: I'd check the network requests in your browser and see what the response says. Are they failing? What are the response messages?

**Comment by DUWENINK** [comment]
not your mistake ,it is because   1. if you use the docker image above 7.1.1  but you use the lastest netcore nuget package  you will find this question   2.if you use the docker image such as 7.2.0  you will find nothing include this UI page because this ui doesn't work on the version of 7.2.0

**Comment by DUWENINK** [comment]
> This is my ApiKey ![image](https://user-images.githubusercontent.com/3347995/141067859-b5bb7213-cb97-4b65-bb11-e45191b9ec7e.png) My Code： ![image](https://user-images.githubusercontent.com/3347995/141068007-2a20f2d8-bc82-44f1-9e63-dc7f58888df6.png) Exceptionless dashboard ![image](https://user-images.githubusercontent.com/3347995/141068150-64ff9521-85c8-412a-b3fd-d1d137f3ef8c.png)


老哥 我遇到同样的问题 发现他们给的最新的无法使用 于是我用7.1.1版本的docker镜像无济于事,

**Comment by DUWENINK** [comment]
> This is my ApiKey ![image](https://user-images.githubusercontent.com/3347995/141067859-b5bb7213-cb97-4b65-bb11-e45191b9ec7e.png) My Code： ![image](https://user-images.githubusercontent.com/3347995/141068007-2a20f2d8-bc82-44f1-9e63-dc7f58888df6.png) Exceptionless dashboard ![image](https://user-images.githubusercontent.com/3347995/141068150-64ff9521-85c8-412a-b3fd-d1d137f3ef8c.png)

这个问题主要是因为7.1.1版本的 和nuget 最新的包不匹配导致的 需要等待他们更新他们的docker 镜像问题

**Comment by niemyjski** [comment]
Can you please try 7.2.1, also if you can capture the logs form the docker container and actual network request from the browser to the server using the browsers network tab that would be a huge help.

**Comment by enshishi** [comment]
I use 7.2.1,still no information.
![image](https://user-images.githubusercontent.com/3347995/141887577-a079f608-0fc5-4a15-b53c-ab6344c3e230.png)
![image](https://user-images.githubusercontent.com/3347995/141887632-77872117-8f4d-4da4-adcf-e532e25208e0.png)
![image](https://user-images.githubusercontent.com/3347995/141887723-21509cf9-6e1e-4da7-85f4-088f11f6f669.png)

**Comment by enshishi** [comment]
> > This is my ApiKey ![image](https://user-images.githubusercontent.com/3347995/141067859-b5bb7213-cb97-4b65-bb11-e45191b9ec7e.png) My Code： ![image](https://user-images.githubusercontent.com/3347995/141068007-2a20f2d8-bc82-44f1-9e63-dc7f58888df6.png) Exceptionless dashboard ![image](https://user-images.githubusercontent.com/3347995/141068150-64ff9521-85c8-412a-b3fd-d1d137f3ef8c.png)
> 
> 这个问题主要是因为7.1.1版本的 和nuget 最新的包不匹配导致的 需要等待他们更新他们的docker 镜像问题

你用一下他们最新的7.2.1,能行吗

**Comment by niemyjski** [comment]
Nothing is being sent to your api server from the client. Make sure you can view the server url you configured:. I'd recommend looking at the about route <http://localhost:5000/api/v2/about> in your browser. If it doesn't resolve the host or port is incorrect.

**Comment by enshishi** [comment]
![微信图片_20211117103717](https://user-images.githubusercontent.com/3347995/142117765-ea0f1f3b-8faa-4dbf-b82d-8933a511d43f.png)

**Comment by enshishi** [comment]
![image](https://user-images.githubusercontent.com/3347995/142118308-e358b1a7-23b7-4269-b836-da430a507e2b.png)

**Comment by niemyjski** [comment]
I just fired up the latest docker version via the command line just to ensure I got an informational version and that was working. I was also able to go to configure project page and submit an event via the command line. 

What docker container version are you running. It should be `"informational_version": "7.2.1+2dc655fa93cffa85f587787f66e012358606fa41",` Did you build the container from source locally?

Can you try submitting an event from the command line, just go to manage project page and click on the configure project icon towards the bottom of the page or the route is `/project/yourprojectid/configure`

**Comment by enshishi** [comment]
I use docker-compose.dev.yml under this folder to deploy to docker
![image](https://user-images.githubusercontent.com/3347995/142371876-0675488f-fe8b-4953-8e4e-abf478883828.png)
![image](https://user-images.githubusercontent.com/3347995/142372359-9fdbee31-1fc9-4ec4-a413-1c1a4a2b59d9.png)

This my docker images
![image](https://user-images.githubusercontent.com/3347995/142372057-f8aa36b0-e8a9-4886-bd19-2d974e5398c1.png)
This my docker container
![image](https://user-images.githubusercontent.com/3347995/142372222-83b6af86-be98-4fa6-b4c0-29f226e07f5a.png)
![image](https://user-images.githubusercontent.com/3347995/142372583-e462359e-1e49-4c7e-89f7-8af40a9d18e0.png)
Is it the wrong way I deploy to docker??

**Comment by niemyjski** [comment]
That is for development and will build the containers from code. We recommend hosting one of the following ways which is using our production docker images: https://exceptionless.com/docs/self-hosting/
